// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hall/update.proto

package pbhall

import (
	common "cy/game/pb/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 更新用户绑定的手机 c -> s
type UpdateBindMobileReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Mobile               string          `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Captcha              string          `protobuf:"bytes,3,opt,name=Captcha,proto3" json:"Captcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateBindMobileReq) Reset()         { *m = UpdateBindMobileReq{} }
func (m *UpdateBindMobileReq) String() string { return proto.CompactTextString(m) }
func (*UpdateBindMobileReq) ProtoMessage()    {}
func (*UpdateBindMobileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_619c93b66f095325, []int{0}
}

func (m *UpdateBindMobileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBindMobileReq.Unmarshal(m, b)
}
func (m *UpdateBindMobileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBindMobileReq.Marshal(b, m, deterministic)
}
func (m *UpdateBindMobileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBindMobileReq.Merge(m, src)
}
func (m *UpdateBindMobileReq) XXX_Size() int {
	return xxx_messageInfo_UpdateBindMobileReq.Size(m)
}
func (m *UpdateBindMobileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBindMobileReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBindMobileReq proto.InternalMessageInfo

func (m *UpdateBindMobileReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *UpdateBindMobileReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UpdateBindMobileReq) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

type UpdateBindMobileRsp struct {
	Head *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	// 1 成功 2 验证码或者手机不匹配 3 内部服务错误
	Code                 uint32           `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Info                 *common.UserInfo `protobuf:"bytes,3,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateBindMobileRsp) Reset()         { *m = UpdateBindMobileRsp{} }
func (m *UpdateBindMobileRsp) String() string { return proto.CompactTextString(m) }
func (*UpdateBindMobileRsp) ProtoMessage()    {}
func (*UpdateBindMobileRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_619c93b66f095325, []int{1}
}

func (m *UpdateBindMobileRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBindMobileRsp.Unmarshal(m, b)
}
func (m *UpdateBindMobileRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBindMobileRsp.Marshal(b, m, deterministic)
}
func (m *UpdateBindMobileRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBindMobileRsp.Merge(m, src)
}
func (m *UpdateBindMobileRsp) XXX_Size() int {
	return xxx_messageInfo_UpdateBindMobileRsp.Size(m)
}
func (m *UpdateBindMobileRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBindMobileRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBindMobileRsp proto.InternalMessageInfo

func (m *UpdateBindMobileRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *UpdateBindMobileRsp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateBindMobileRsp) GetInfo() *common.UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateBindMobileReq)(nil), "pbhall.UpdateBindMobileReq")
	proto.RegisterType((*UpdateBindMobileRsp)(nil), "pbhall.UpdateBindMobileRsp")
}

func init() { proto.RegisterFile("hall/update.proto", fileDescriptor_619c93b66f095325) }

var fileDescriptor_619c93b66f095325 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x48, 0xcc, 0xc9,
	0xd1, 0x2f, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b,
	0x48, 0x02, 0x09, 0x4a, 0xc9, 0x24, 0x57, 0xea, 0xa7, 0x27, 0xe6, 0xa6, 0xea, 0x17, 0x24, 0xe9,
	0x27, 0xe7, 0xe7, 0xe6, 0xe6, 0xe7, 0xe9, 0x67, 0xa4, 0x26, 0xa6, 0x40, 0x54, 0x49, 0xc9, 0x61,
	0xca, 0x42, 0x28, 0x88, 0xbc, 0x52, 0x1e, 0x97, 0x70, 0x28, 0xd8, 0x54, 0xa7, 0xcc, 0xbc, 0x14,
	0xdf, 0xfc, 0xa4, 0xcc, 0x9c, 0xd4, 0xa0, 0xd4, 0x42, 0x21, 0x55, 0x2e, 0x16, 0x8f, 0xd4, 0xc4,
	0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x41, 0xbd, 0x82, 0x24, 0xa8, 0xae, 0xa0, 0xd4,
	0x42, 0x90, 0x44, 0x10, 0x58, 0x5a, 0x48, 0x8c, 0x8b, 0x0d, 0xa2, 0x47, 0x82, 0x49, 0x81, 0x51,
	0x83, 0x33, 0x08, 0xca, 0x13, 0x92, 0xe0, 0x62, 0x77, 0x4e, 0x2c, 0x28, 0x49, 0xce, 0x48, 0x94,
	0x60, 0x06, 0x4b, 0xc0, 0xb8, 0x4a, 0x15, 0x58, 0xec, 0x2b, 0x2e, 0xc0, 0x63, 0x5f, 0x71, 0x01,
	0x92, 0x7d, 0x42, 0x5c, 0x2c, 0xce, 0xf9, 0x29, 0x10, 0xdb, 0x78, 0x83, 0xc0, 0x6c, 0x21, 0x35,
	0x2e, 0x16, 0xcf, 0xbc, 0xb4, 0x7c, 0xb0, 0x45, 0xdc, 0x46, 0x42, 0x08, 0xad, 0xa1, 0xc5, 0xa9,
	0x45, 0x20, 0x99, 0x20, 0xb0, 0x7c, 0x12, 0x1b, 0xd8, 0xc3, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x42, 0x70, 0xa8, 0xc9, 0x4b, 0x01, 0x00, 0x00,
}
