# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/RussellLuo/timingwheel"

[[constraint]]
  branch = "master"
  name = "github.com/aperdana/batcher"

[[constraint]]
  branch = "develop"
  name = "github.com/astaxie/beego"

[[constraint]]
  branch = "master"
  name = "github.com/dropbox/godropbox"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"

[[constraint]]
  branch = "master"
  name = "github.com/go-sql-driver/mysql"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/gomodule/redigo"

[[constraint]]
  branch = "master"
  name = "github.com/google/uuid"

[[constraint]]
  branch = "master"
  name = "github.com/looplab/fsm"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  branch = "master"
  name = "github.com/rcrowley/go-metrics"

[[constraint]]
  branch = "master"
  name = "github.com/sirupsen/logrus"

[[constraint]]
  branch = "master"
  name = "github.com/smallnest/rpcx"

[[constraint]]
  branch = "master"
  name = "github.com/Abramovic/logrus_influxdb"

[prune]
  go-tests = true
  unused-packages = true
