// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package pbcommon

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserStatus int32

const (
	UserStatus_NotLogin   UserStatus = 0
	UserStatus_InHall     UserStatus = 1
	UserStatus_InMatching UserStatus = 2
	UserStatus_InGameing  UserStatus = 3
)

var UserStatus_name = map[int32]string{
	0: "NotLogin",
	1: "InHall",
	2: "InMatching",
	3: "InGameing",
}

var UserStatus_value = map[string]int32{
	"NotLogin":   0,
	"InHall":     1,
	"InMatching": 2,
	"InGameing":  3,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}

func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

// 断开提示 s -> c
type BrokenTip struct {
	Msg string `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	// 异地登陆 1 其他*
	Code                 uint32   `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrokenTip) Reset()         { *m = BrokenTip{} }
func (m *BrokenTip) String() string { return proto.CompactTextString(m) }
func (*BrokenTip) ProtoMessage()    {}
func (*BrokenTip) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

func (m *BrokenTip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokenTip.Unmarshal(m, b)
}
func (m *BrokenTip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokenTip.Marshal(b, m, deterministic)
}
func (m *BrokenTip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokenTip.Merge(m, src)
}
func (m *BrokenTip) XXX_Size() int {
	return xxx_messageInfo_BrokenTip.Size(m)
}
func (m *BrokenTip) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokenTip.DiscardUnknown(m)
}

var xxx_messageInfo_BrokenTip proto.InternalMessageInfo

func (m *BrokenTip) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *BrokenTip) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// 错误提示 s -> c
type ErrorTip struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorTip) Reset()         { *m = ErrorTip{} }
func (m *ErrorTip) String() string { return proto.CompactTextString(m) }
func (*ErrorTip) ProtoMessage()    {}
func (*ErrorTip) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{1}
}

func (m *ErrorTip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorTip.Unmarshal(m, b)
}
func (m *ErrorTip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorTip.Marshal(b, m, deterministic)
}
func (m *ErrorTip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorTip.Merge(m, src)
}
func (m *ErrorTip) XXX_Size() int {
	return xxx_messageInfo_ErrorTip.Size(m)
}
func (m *ErrorTip) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorTip.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorTip proto.InternalMessageInfo

func (m *ErrorTip) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 桌子信息
type DeskInfo struct {
	Uuid                 uint64   `protobuf:"varint,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	ID                   uint64   `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	CreateUserID         uint64   `protobuf:"varint,3,opt,name=CreateUserID,proto3" json:"CreateUserID,omitempty"`
	CreateTime           int64    `protobuf:"varint,4,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	CreateArgs           string   `protobuf:"bytes,5,opt,name=CreateArgs,proto3" json:"CreateArgs,omitempty"`
	CreateUserName       string   `protobuf:"bytes,6,opt,name=CreateUserName,proto3" json:"CreateUserName,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=Status,proto3" json:"Status,omitempty"`
	GameName             string   `protobuf:"bytes,8,opt,name=GameName,proto3" json:"GameName,omitempty"`
	GameID               string   `protobuf:"bytes,9,opt,name=GameID,proto3" json:"GameID,omitempty"`
	ClubID               int64    `protobuf:"varint,11,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	Kind                 int32    `protobuf:"varint,12,opt,name=Kind,proto3" json:"Kind,omitempty"`
	UserIDs              []uint64 `protobuf:"varint,10,rep,packed,name=UserIDs,proto3" json:"UserIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeskInfo) Reset()         { *m = DeskInfo{} }
func (m *DeskInfo) String() string { return proto.CompactTextString(m) }
func (*DeskInfo) ProtoMessage()    {}
func (*DeskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{2}
}

func (m *DeskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeskInfo.Unmarshal(m, b)
}
func (m *DeskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeskInfo.Marshal(b, m, deterministic)
}
func (m *DeskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeskInfo.Merge(m, src)
}
func (m *DeskInfo) XXX_Size() int {
	return xxx_messageInfo_DeskInfo.Size(m)
}
func (m *DeskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeskInfo proto.InternalMessageInfo

func (m *DeskInfo) GetUuid() uint64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *DeskInfo) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DeskInfo) GetCreateUserID() uint64 {
	if m != nil {
		return m.CreateUserID
	}
	return 0
}

func (m *DeskInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *DeskInfo) GetCreateArgs() string {
	if m != nil {
		return m.CreateArgs
	}
	return ""
}

func (m *DeskInfo) GetCreateUserName() string {
	if m != nil {
		return m.CreateUserName
	}
	return ""
}

func (m *DeskInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DeskInfo) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *DeskInfo) GetGameID() string {
	if m != nil {
		return m.GameID
	}
	return ""
}

func (m *DeskInfo) GetClubID() int64 {
	if m != nil {
		return m.ClubID
	}
	return 0
}

func (m *DeskInfo) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *DeskInfo) GetUserIDs() []uint64 {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

// 会话信息
type SessionInfo struct {
	Uuid                 uint64     `protobuf:"varint,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	UserID               uint64     `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	SessionID            string     `protobuf:"bytes,3,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Status               UserStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=pbcommon.UserStatus" json:"Status,omitempty"`
	AtDeskID             uint64     `protobuf:"varint,5,opt,name=AtDeskID,proto3" json:"AtDeskID,omitempty"`
	GameName             string     `protobuf:"bytes,6,opt,name=GameName,proto3" json:"GameName,omitempty"`
	GameID               string     `protobuf:"bytes,7,opt,name=GameID,proto3" json:"GameID,omitempty"`
	LastActiveTime       int64      `protobuf:"varint,8,opt,name=LastActiveTime,proto3" json:"LastActiveTime,omitempty"`
	RoomID               uint32     `protobuf:"varint,9,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SessionInfo) Reset()         { *m = SessionInfo{} }
func (m *SessionInfo) String() string { return proto.CompactTextString(m) }
func (*SessionInfo) ProtoMessage()    {}
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{3}
}

func (m *SessionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionInfo.Unmarshal(m, b)
}
func (m *SessionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionInfo.Marshal(b, m, deterministic)
}
func (m *SessionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionInfo.Merge(m, src)
}
func (m *SessionInfo) XXX_Size() int {
	return xxx_messageInfo_SessionInfo.Size(m)
}
func (m *SessionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SessionInfo proto.InternalMessageInfo

func (m *SessionInfo) GetUuid() uint64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *SessionInfo) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *SessionInfo) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *SessionInfo) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_NotLogin
}

func (m *SessionInfo) GetAtDeskID() uint64 {
	if m != nil {
		return m.AtDeskID
	}
	return 0
}

func (m *SessionInfo) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *SessionInfo) GetGameID() string {
	if m != nil {
		return m.GameID
	}
	return ""
}

func (m *SessionInfo) GetLastActiveTime() int64 {
	if m != nil {
		return m.LastActiveTime
	}
	return 0
}

func (m *SessionInfo) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

// 用户信息
type UserInfo struct {
	UserID               uint64   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	SessionID            string   `protobuf:"bytes,2,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	WxID                 string   `protobuf:"bytes,3,opt,name=WxID,proto3" json:"WxID,omitempty"`
	Longitude            float64  `protobuf:"fixed64,4,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,5,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty"`
	Sex                  string   `protobuf:"bytes,7,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Profile              string   `protobuf:"bytes,8,opt,name=Profile,proto3" json:"Profile,omitempty"`
	Mobile               string   `protobuf:"bytes,9,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Gold                 uint64   `protobuf:"varint,10,opt,name=Gold,proto3" json:"Gold,omitempty"`
	Masonry              uint64   `protobuf:"varint,11,opt,name=Masonry,proto3" json:"Masonry,omitempty"`
	GoldPre              uint64   `protobuf:"varint,12,opt,name=GoldPre,proto3" json:"GoldPre,omitempty"`
	MasonryPre           uint64   `protobuf:"varint,13,opt,name=MasonryPre,proto3" json:"MasonryPre,omitempty"`
	Agent                string   `protobuf:"bytes,14,opt,name=Agent,proto3" json:"Agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{4}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserInfo) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *UserInfo) GetWxID() string {
	if m != nil {
		return m.WxID
	}
	return ""
}

func (m *UserInfo) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *UserInfo) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *UserInfo) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *UserInfo) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserInfo) GetGold() uint64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *UserInfo) GetMasonry() uint64 {
	if m != nil {
		return m.Masonry
	}
	return 0
}

func (m *UserInfo) GetGoldPre() uint64 {
	if m != nil {
		return m.GoldPre
	}
	return 0
}

func (m *UserInfo) GetMasonryPre() uint64 {
	if m != nil {
		return m.MasonryPre
	}
	return 0
}

func (m *UserInfo) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func init() {
	proto.RegisterEnum("pbcommon.UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterType((*BrokenTip)(nil), "pbcommon.BrokenTip")
	proto.RegisterType((*ErrorTip)(nil), "pbcommon.ErrorTip")
	proto.RegisterType((*DeskInfo)(nil), "pbcommon.DeskInfo")
	proto.RegisterType((*SessionInfo)(nil), "pbcommon.SessionInfo")
	proto.RegisterType((*UserInfo)(nil), "pbcommon.UserInfo")
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor_8f954d82c0b891f6) }

var fileDescriptor_8f954d82c0b891f6 = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0x51, 0x6a, 0xdb, 0x40,
	0x10, 0x86, 0x2b, 0x59, 0x56, 0xa4, 0x49, 0x2c, 0xcc, 0x36, 0x84, 0xa5, 0x84, 0x62, 0xf4, 0x10,
	0x4c, 0x29, 0x29, 0x6d, 0x4f, 0xe0, 0x46, 0x21, 0x15, 0xb5, 0x43, 0xd8, 0x24, 0xf4, 0x59, 0x8e,
	0x37, 0xaa, 0x88, 0xb5, 0x1b, 0xa4, 0x75, 0x49, 0x0f, 0xd2, 0x5b, 0xf5, 0x18, 0x3d, 0x48, 0x99,
	0x59, 0xc9, 0xb2, 0x4d, 0xfd, 0xe4, 0xf9, 0xe7, 0xdf, 0x59, 0x6b, 0xbe, 0x19, 0x09, 0x5e, 0x3f,
	0xe8, 0xb2, 0xd4, 0xea, 0x83, 0xfd, 0x39, 0x7f, 0xae, 0xb4, 0xd1, 0x2c, 0x78, 0x9e, 0x5b, 0x1d,
	0x7f, 0x84, 0xf0, 0x4b, 0xa5, 0x9f, 0xa4, 0xba, 0x2b, 0x9e, 0xd9, 0x10, 0x7a, 0xb3, 0x3a, 0xe7,
	0xce, 0xc8, 0x19, 0x87, 0x02, 0x43, 0xc6, 0xc0, 0xbb, 0xd0, 0x0b, 0xc9, 0xdd, 0x91, 0x33, 0x1e,
	0x08, 0x8a, 0xe3, 0x53, 0x08, 0x2e, 0xab, 0x4a, 0x57, 0xff, 0xad, 0x88, 0xff, 0xb8, 0x10, 0x24,
	0xb2, 0x7e, 0x4a, 0xd5, 0xa3, 0xc6, 0xf2, 0xfb, 0x55, 0xb1, 0x20, 0xdf, 0x13, 0x14, 0xb3, 0x08,
	0xdc, 0x34, 0xa1, 0x0b, 0x3d, 0xe1, 0xa6, 0x09, 0x8b, 0xe1, 0xe8, 0xa2, 0x92, 0x99, 0x91, 0xf7,
	0xb5, 0xac, 0xd2, 0x84, 0xf7, 0xc8, 0xd9, 0xca, 0xb1, 0xb7, 0x00, 0x56, 0xdf, 0x15, 0xa5, 0xe4,
	0xde, 0xc8, 0x19, 0xf7, 0xc4, 0x46, 0xa6, 0xf3, 0x27, 0x55, 0x5e, 0xf3, 0x3e, 0x3d, 0xcd, 0x46,
	0x86, 0x9d, 0x41, 0xd4, 0xdd, 0x77, 0x9d, 0x95, 0x92, 0xfb, 0x74, 0x66, 0x27, 0xcb, 0x4e, 0xc0,
	0xbf, 0x35, 0x99, 0x59, 0xd5, 0xfc, 0x80, 0xfc, 0x46, 0xb1, 0x37, 0x10, 0x5c, 0x65, 0xa5, 0xa4,
	0xca, 0x80, 0x9c, 0xb5, 0xc6, 0x1a, 0x8c, 0xd3, 0x84, 0x87, 0xb6, 0xc6, 0x2a, 0xcc, 0x5f, 0x2c,
	0x57, 0xf3, 0x34, 0xe1, 0x87, 0xf4, 0xbc, 0x8d, 0x42, 0x26, 0xdf, 0x0a, 0xb5, 0xe0, 0x47, 0x23,
	0x67, 0xdc, 0x17, 0x14, 0x33, 0x0e, 0x07, 0xb6, 0xd3, 0x9a, 0xc3, 0xa8, 0x37, 0xf6, 0x44, 0x2b,
	0xe3, 0xdf, 0x2e, 0x1c, 0xde, 0xca, 0xba, 0x2e, 0xb4, 0xda, 0x4b, 0xf4, 0x04, 0xfc, 0x86, 0x9d,
	0xa5, 0xda, 0x28, 0x76, 0x0a, 0x61, 0x5b, 0x6a, 0xb1, 0x86, 0xa2, 0x4b, 0xb0, 0xf7, 0xeb, 0x5e,
	0x91, 0x67, 0xf4, 0xe9, 0xf8, 0xbc, 0x5d, 0x8a, 0x73, 0xac, 0xb7, 0xde, 0x26, 0x81, 0x89, 0xa1,
	0xb9, 0x26, 0xc4, 0xd7, 0x13, 0x6b, 0xbd, 0x45, 0xc7, 0xdf, 0x4b, 0xe7, 0x60, 0x8b, 0xce, 0x19,
	0x44, 0xd3, 0xac, 0x36, 0x93, 0x07, 0x53, 0xfc, 0xb4, 0x53, 0x0d, 0x88, 0xd2, 0x4e, 0x16, 0xeb,
	0x85, 0xd6, 0x65, 0x43, 0x77, 0x20, 0x1a, 0x15, 0xff, 0x75, 0x21, 0xa0, 0x36, 0x11, 0x4a, 0x07,
	0xc0, 0xd9, 0x0f, 0xc0, 0xdd, 0x05, 0xc0, 0xc0, 0xfb, 0xfe, 0xb2, 0x26, 0x43, 0x31, 0x56, 0x4c,
	0xb5, 0xca, 0x0b, 0xb3, 0x5a, 0xd8, 0x3d, 0x73, 0x44, 0x97, 0xc0, 0x46, 0xa7, 0x99, 0xb1, 0x66,
	0x9f, 0xcc, 0xb5, 0xc6, 0xdb, 0x36, 0x00, 0x50, 0x8c, 0x6f, 0xc7, 0xad, 0x7c, 0x69, 0x3a, 0xc7,
	0x10, 0x07, 0x7d, 0x53, 0xe9, 0xc7, 0x62, 0xd9, 0xee, 0x51, 0x2b, 0xb1, 0x87, 0x99, 0x9e, 0xa3,
	0xd1, 0xac, 0x91, 0x55, 0x78, 0xef, 0x95, 0x5e, 0x2e, 0x38, 0xd8, 0x81, 0x63, 0x8c, 0xb7, 0xcc,
	0xb2, 0x5a, 0xab, 0xea, 0x17, 0xed, 0x96, 0x27, 0x5a, 0x89, 0x0e, 0x9e, 0xb8, 0xa9, 0x24, 0xed,
	0x97, 0x27, 0x5a, 0x89, 0xaf, 0x48, 0x73, 0x08, 0xcd, 0x01, 0x99, 0x1b, 0x19, 0x76, 0x0c, 0xfd,
	0x49, 0x2e, 0x95, 0xe1, 0x11, 0xfd, 0xbd, 0x15, 0xef, 0x2e, 0x01, 0xba, 0x65, 0x60, 0x47, 0x10,
	0x5c, 0x6b, 0x33, 0xd5, 0x79, 0xa1, 0x86, 0xaf, 0x18, 0x80, 0x9f, 0xaa, 0xaf, 0xd9, 0x72, 0x39,
	0x74, 0x58, 0x04, 0x90, 0xaa, 0x59, 0x66, 0x1e, 0x7e, 0x14, 0x2a, 0x1f, 0xba, 0x6c, 0x00, 0x61,
	0xaa, 0x70, 0xd4, 0x28, 0x7b, 0x73, 0x9f, 0x3e, 0x3b, 0x9f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xd1, 0xa3, 0x61, 0xf7, 0x8d, 0x04, 0x00, 0x00,
}
