# 发件服务器地址
alarm_host="smtp.exmail.qq.com"
# 发件服务器端口
alarm_port=465
# 报警发送邮件地址
alarm_email="xxooxxoo"
# 报警发送邮箱密码
alarm_password="xxooxxoo"
# 报警对象
alarm_address_list="xxooxxoo;xxooxxoo;"
# 邮件来源from
alarm_from="slb-monitor"
# 邮件subject
alarm_subject="游戏服SLB报警"
