// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClubDonateDiamondsRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsClubDonateDiamondsRequest(buf []byte, offset flatbuffers.UOffsetT) *ClubDonateDiamondsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClubDonateDiamondsRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ClubDonateDiamondsRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClubDonateDiamondsRequest) UserId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClubDonateDiamondsRequest) MutateUserId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *ClubDonateDiamondsRequest) ClubId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClubDonateDiamondsRequest) MutateClubId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *ClubDonateDiamondsRequest) ConfigId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClubDonateDiamondsRequest) MutateConfigId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func ClubDonateDiamondsRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ClubDonateDiamondsRequestAddUserId(builder *flatbuffers.Builder, userId uint32) {
	builder.PrependUint32Slot(0, userId, 0)
}
func ClubDonateDiamondsRequestAddClubId(builder *flatbuffers.Builder, clubId uint32) {
	builder.PrependUint32Slot(1, clubId, 0)
}
func ClubDonateDiamondsRequestAddConfigId(builder *flatbuffers.Builder, configId uint32) {
	builder.PrependUint32Slot(2, configId, 0)
}
func ClubDonateDiamondsRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
