// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClubGetMyListResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsClubGetMyListResponse(buf []byte, offset flatbuffers.UOffsetT) *ClubGetMyListResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClubGetMyListResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ClubGetMyListResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClubGetMyListResponse) Result(obj *CommonResult) *CommonResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CommonResult)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClubGetMyListResponse) TotalPage() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClubGetMyListResponse) MutateTotalPage(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *ClubGetMyListResponse) Data(obj *ClubInfo, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(ClubInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ClubGetMyListResponse) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ClubGetMyListResponse) IsCollect() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClubGetMyListResponse) MutateIsCollect(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func ClubGetMyListResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ClubGetMyListResponseAddResult(builder *flatbuffers.Builder, result flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(result), 0)
}
func ClubGetMyListResponseAddTotalPage(builder *flatbuffers.Builder, totalPage uint32) {
	builder.PrependUint32Slot(1, totalPage, 0)
}
func ClubGetMyListResponseAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(data), 0)
}
func ClubGetMyListResponseStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ClubGetMyListResponseAddIsCollect(builder *flatbuffers.Builder, isCollect uint32) {
	builder.PrependUint32Slot(3, isCollect, 0)
}
func ClubGetMyListResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
