// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClubKickUserResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsClubKickUserResponse(buf []byte, offset flatbuffers.UOffsetT) *ClubKickUserResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClubKickUserResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ClubKickUserResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClubKickUserResponse) Result(obj *CommonResult) *CommonResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CommonResult)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ClubKickUserResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ClubKickUserResponseAddResult(builder *flatbuffers.Builder, result flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(result), 0)
}
func ClubKickUserResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
