// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClubMasterCollectRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsClubMasterCollectRequest(buf []byte, offset flatbuffers.UOffsetT) *ClubMasterCollectRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClubMasterCollectRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ClubMasterCollectRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClubMasterCollectRequest) MasterName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClubMasterCollectRequest) Mobile() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClubMasterCollectRequest) Code() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ClubMasterCollectRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ClubMasterCollectRequestAddMasterName(builder *flatbuffers.Builder, masterName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(masterName), 0)
}
func ClubMasterCollectRequestAddMobile(builder *flatbuffers.Builder, mobile flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(mobile), 0)
}
func ClubMasterCollectRequestAddCode(builder *flatbuffers.Builder, code flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(code), 0)
}
func ClubMasterCollectRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
