// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EnterFreeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsEnterFreeRequest(buf []byte, offset flatbuffers.UOffsetT) *EnterFreeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EnterFreeRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *EnterFreeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EnterFreeRequest) UserId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EnterFreeRequest) MutateUserId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func EnterFreeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func EnterFreeRequestAddUserId(builder *flatbuffers.Builder, userId uint32) {
	builder.PrependUint32Slot(0, userId, 0)
}
func EnterFreeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
