// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetGameResultResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsGetGameResultResponse(buf []byte, offset flatbuffers.UOffsetT) *GetGameResultResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetGameResultResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GetGameResultResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetGameResultResponse) Result(obj *CommonResult) *CommonResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CommonResult)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *GetGameResultResponse) GameResult() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GetGameResultResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GetGameResultResponseAddResult(builder *flatbuffers.Builder, result flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(result), 0)
}
func GetGameResultResponseAddGameResult(builder *flatbuffers.Builder, gameResult flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(gameResult), 0)
}
func GetGameResultResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
