// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KingMyRank struct {
	_tab flatbuffers.Table
}

func GetRootAsKingMyRank(buf []byte, offset flatbuffers.UOffsetT) *KingMyRank {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KingMyRank{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *KingMyRank) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KingMyRank) Position() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KingMyRank) MutatePosition(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *KingMyRank) RankInfo() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KingMyRank) MutateRankInfo(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func KingMyRankStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func KingMyRankAddPosition(builder *flatbuffers.Builder, position int32) {
	builder.PrependInt32Slot(0, position, 0)
}
func KingMyRankAddRankInfo(builder *flatbuffers.Builder, rankInfo int32) {
	builder.PrependInt32Slot(1, rankInfo, 0)
}
func KingMyRankEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
