// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/game.proto

package pbgame

import (
	common "cy/game/pb/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 玩家在桌子中状态
type UserDeskStatus int32

const (
	UserDeskStatus_UDSNone    UserDeskStatus = 0
	UserDeskStatus_UDSLook    UserDeskStatus = 1
	UserDeskStatus_UDSSitDown UserDeskStatus = 2
	UserDeskStatus_UDSPlaying UserDeskStatus = 3
	UserDeskStatus_UDSGameEnd UserDeskStatus = 4
)

var UserDeskStatus_name = map[int32]string{
	0: "UDSNone",
	1: "UDSLook",
	2: "UDSSitDown",
	3: "UDSPlaying",
	4: "UDSGameEnd",
}

var UserDeskStatus_value = map[string]int32{
	"UDSNone":    0,
	"UDSLook":    1,
	"UDSSitDown": 2,
	"UDSPlaying": 3,
	"UDSGameEnd": 4,
}

func (x UserDeskStatus) String() string {
	return proto.EnumName(UserDeskStatus_name, int32(x))
}

func (UserDeskStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{0}
}

// 扣费类型
type FeeType int32

const (
	FeeType_FTNone    FeeType = 0
	FeeType_FTGold    FeeType = 1
	FeeType_FTMasonry FeeType = 2
)

var FeeType_name = map[int32]string{
	0: "FTNone",
	1: "FTGold",
	2: "FTMasonry",
}

var FeeType_value = map[string]int32{
	"FTNone":    0,
	"FTGold":    1,
	"FTMasonry": 2,
}

func (x FeeType) String() string {
	return proto.EnumName(FeeType_name, int32(x))
}

func (FeeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{1}
}

// 创建桌子code
type MakeDeskRspCode int32

const (
	MakeDeskRspCode_MakeDeskNotUse               MakeDeskRspCode = 0
	MakeDeskRspCode_MakeDeskSucc                 MakeDeskRspCode = 1
	MakeDeskRspCode_MakeDeskArgsErr              MakeDeskRspCode = 2
	MakeDeskRspCode_MakeDeskNotEnoughMoney       MakeDeskRspCode = 3
	MakeDeskRspCode_MakeDeskNotEnoughDesk        MakeDeskRspCode = 4
	MakeDeskRspCode_MakeDeskInternalServerError  MakeDeskRspCode = 5
	MakeDeskRspCode_MakeDeskUserStatusErr        MakeDeskRspCode = 6
	MakeDeskRspCode_MakeDeskCanNotFindClubID     MakeDeskRspCode = 7
	MakeDeskRspCode_MakeDeskLimit                MakeDeskRspCode = 8
	MakeDeskRspCode_MakeDeskAlreadyInDesk        MakeDeskRspCode = 9
	MakeDeskRspCode_MakeDeskUserNotInClub        MakeDeskRspCode = 10
	MakeDeskRspCode_MakeDeskCanNotCreateClubDesk MakeDeskRspCode = 11
)

var MakeDeskRspCode_name = map[int32]string{
	0:  "MakeDeskNotUse",
	1:  "MakeDeskSucc",
	2:  "MakeDeskArgsErr",
	3:  "MakeDeskNotEnoughMoney",
	4:  "MakeDeskNotEnoughDesk",
	5:  "MakeDeskInternalServerError",
	6:  "MakeDeskUserStatusErr",
	7:  "MakeDeskCanNotFindClubID",
	8:  "MakeDeskLimit",
	9:  "MakeDeskAlreadyInDesk",
	10: "MakeDeskUserNotInClub",
	11: "MakeDeskCanNotCreateClubDesk",
}

var MakeDeskRspCode_value = map[string]int32{
	"MakeDeskNotUse":               0,
	"MakeDeskSucc":                 1,
	"MakeDeskArgsErr":              2,
	"MakeDeskNotEnoughMoney":       3,
	"MakeDeskNotEnoughDesk":        4,
	"MakeDeskInternalServerError":  5,
	"MakeDeskUserStatusErr":        6,
	"MakeDeskCanNotFindClubID":     7,
	"MakeDeskLimit":                8,
	"MakeDeskAlreadyInDesk":        9,
	"MakeDeskUserNotInClub":        10,
	"MakeDeskCanNotCreateClubDesk": 11,
}

func (x MakeDeskRspCode) String() string {
	return proto.EnumName(MakeDeskRspCode_name, int32(x))
}

func (MakeDeskRspCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{2}
}

// 加入桌子code
type JoinDeskRspCode int32

const (
	JoinDeskRspCode_JoinDeskNotUse              JoinDeskRspCode = 0
	JoinDeskRspCode_JoinDeskSucc                JoinDeskRspCode = 1
	JoinDeskRspCode_JoinDeskNotExist            JoinDeskRspCode = 2
	JoinDeskRspCode_JoinDeskDeskFull            JoinDeskRspCode = 3
	JoinDeskRspCode_JoinDeskInternalServerError JoinDeskRspCode = 4
	JoinDeskRspCode_JoinDeskUserStatusErr       JoinDeskRspCode = 5
	JoinDeskRspCode_JoinDeskAlreadyInDesk       JoinDeskRspCode = 6
)

var JoinDeskRspCode_name = map[int32]string{
	0: "JoinDeskNotUse",
	1: "JoinDeskSucc",
	2: "JoinDeskNotExist",
	3: "JoinDeskDeskFull",
	4: "JoinDeskInternalServerError",
	5: "JoinDeskUserStatusErr",
	6: "JoinDeskAlreadyInDesk",
}

var JoinDeskRspCode_value = map[string]int32{
	"JoinDeskNotUse":              0,
	"JoinDeskSucc":                1,
	"JoinDeskNotExist":            2,
	"JoinDeskDeskFull":            3,
	"JoinDeskInternalServerError": 4,
	"JoinDeskUserStatusErr":       5,
	"JoinDeskAlreadyInDesk":       6,
}

func (x JoinDeskRspCode) String() string {
	return proto.EnumName(JoinDeskRspCode_name, int32(x))
}

func (JoinDeskRspCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{3}
}

// 坐下准备code
type SitDownRspCode int32

const (
	SitDownRspCode_SitDownNone              SitDownRspCode = 0
	SitDownRspCode_SitDownSucc              SitDownRspCode = 1
	SitDownRspCode_SitDownNotInDesk         SitDownRspCode = 2
	SitDownRspCode_SitDownNotEmpty          SitDownRspCode = 3
	SitDownRspCode_SitDownDistanceSoClose   SitDownRspCode = 4
	SitDownRspCode_SitDownGameStatusErr     SitDownRspCode = 5
	SitDownRspCode_SitDownNotEnoughMoney    SitDownRspCode = 6
	SitDownRspCode_SitDownClubNotExist      SitDownRspCode = 7
	SitDownRspCode_SitDownNotInClub         SitDownRspCode = 8
	SitDownRspCode_SitDownCanNotSitClubDesk SitDownRspCode = 9
	SitDownRspCode_SitDownClubHaveReleation SitDownRspCode = 10
	SitDownRspCode_SitDownIPLimit           SitDownRspCode = 11
)

var SitDownRspCode_name = map[int32]string{
	0:  "SitDownNone",
	1:  "SitDownSucc",
	2:  "SitDownNotInDesk",
	3:  "SitDownNotEmpty",
	4:  "SitDownDistanceSoClose",
	5:  "SitDownGameStatusErr",
	6:  "SitDownNotEnoughMoney",
	7:  "SitDownClubNotExist",
	8:  "SitDownNotInClub",
	9:  "SitDownCanNotSitClubDesk",
	10: "SitDownClubHaveReleation",
	11: "SitDownIPLimit",
}

var SitDownRspCode_value = map[string]int32{
	"SitDownNone":              0,
	"SitDownSucc":              1,
	"SitDownNotInDesk":         2,
	"SitDownNotEmpty":          3,
	"SitDownDistanceSoClose":   4,
	"SitDownGameStatusErr":     5,
	"SitDownNotEnoughMoney":    6,
	"SitDownClubNotExist":      7,
	"SitDownNotInClub":         8,
	"SitDownCanNotSitClubDesk": 9,
	"SitDownClubHaveReleation": 10,
	"SitDownIPLimit":           11,
}

func (x SitDownRspCode) String() string {
	return proto.EnumName(SitDownRspCode_name, int32(x))
}

func (SitDownRspCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{4}
}

// 离开桌子code
type ExitDeskRspCode int32

const (
	ExitDeskRspCode_ExitDeskNone                ExitDeskRspCode = 0
	ExitDeskRspCode_ExitDeskSucc                ExitDeskRspCode = 1
	ExitDeskRspCode_ExitDeskNotInDesk           ExitDeskRspCode = 2
	ExitDeskRspCode_ExitDeskPlaying             ExitDeskRspCode = 3
	ExitDeskRspCode_ExitDeskInternalServerError ExitDeskRspCode = 4
)

var ExitDeskRspCode_name = map[int32]string{
	0: "ExitDeskNone",
	1: "ExitDeskSucc",
	2: "ExitDeskNotInDesk",
	3: "ExitDeskPlaying",
	4: "ExitDeskInternalServerError",
}

var ExitDeskRspCode_value = map[string]int32{
	"ExitDeskNone":                0,
	"ExitDeskSucc":                1,
	"ExitDeskNotInDesk":           2,
	"ExitDeskPlaying":             3,
	"ExitDeskInternalServerError": 4,
}

func (x ExitDeskRspCode) String() string {
	return proto.EnumName(ExitDeskRspCode_name, int32(x))
}

func (ExitDeskRspCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{5}
}

// 点击解散按钮方式
type DestroyDeskType int32

const (
	DestroyDeskType_DestroyTypeGame    DestroyDeskType = 0
	DestroyDeskType_DestroyTypeClub    DestroyDeskType = 1
	DestroyDeskType_DestroyTypeDebug   DestroyDeskType = 2
	DestroyDeskType_DestroyTypeGameEnd DestroyDeskType = 3
	DestroyDeskType_DestroyTypeTimeOut DestroyDeskType = 4
)

var DestroyDeskType_name = map[int32]string{
	0: "DestroyTypeGame",
	1: "DestroyTypeClub",
	2: "DestroyTypeDebug",
	3: "DestroyTypeGameEnd",
	4: "DestroyTypeTimeOut",
}

var DestroyDeskType_value = map[string]int32{
	"DestroyTypeGame":    0,
	"DestroyTypeClub":    1,
	"DestroyTypeDebug":   2,
	"DestroyTypeGameEnd": 3,
	"DestroyTypeTimeOut": 4,
}

func (x DestroyDeskType) String() string {
	return proto.EnumName(DestroyDeskType_name, int32(x))
}

func (DestroyDeskType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{6}
}

// 申请解散回应code
type DestroyDeskRspCode int32

const (
	DestroyDeskRspCode_DestroyDeskNone      DestroyDeskRspCode = 0
	DestroyDeskRspCode_DestroyDeskSucc      DestroyDeskRspCode = 1
	DestroyDeskRspCode_DestroyDeskPlaying   DestroyDeskRspCode = 2
	DestroyDeskRspCode_DestroyDeskNotMaster DestroyDeskRspCode = 3
	DestroyDeskRspCode_DestroyDeskFrequent  DestroyDeskRspCode = 4
	DestroyDeskRspCode_DestroyDeskNotExist  DestroyDeskRspCode = 5
	DestroyDeskRspCode_DestroyDeskNotInDesk DestroyDeskRspCode = 6
	DestroyDeskRspCode_DestroyDeskRepeated  DestroyDeskRspCode = 7
)

var DestroyDeskRspCode_name = map[int32]string{
	0: "DestroyDeskNone",
	1: "DestroyDeskSucc",
	2: "DestroyDeskPlaying",
	3: "DestroyDeskNotMaster",
	4: "DestroyDeskFrequent",
	5: "DestroyDeskNotExist",
	6: "DestroyDeskNotInDesk",
	7: "DestroyDeskRepeated",
}

var DestroyDeskRspCode_value = map[string]int32{
	"DestroyDeskNone":      0,
	"DestroyDeskSucc":      1,
	"DestroyDeskPlaying":   2,
	"DestroyDeskNotMaster": 3,
	"DestroyDeskFrequent":  4,
	"DestroyDeskNotExist":  5,
	"DestroyDeskNotInDesk": 6,
	"DestroyDeskRepeated":  7,
}

func (x DestroyDeskRspCode) String() string {
	return proto.EnumName(DestroyDeskRspCode_name, int32(x))
}

func (DestroyDeskRspCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{7}
}

type VoteOption int32

const (
	VoteOption_VoteOptionNone   VoteOption = 0
	VoteOption_VoteOptionAgree  VoteOption = 1
	VoteOption_VoteOptionReject VoteOption = 2
)

var VoteOption_name = map[int32]string{
	0: "VoteOptionNone",
	1: "VoteOptionAgree",
	2: "VoteOptionReject",
}

var VoteOption_value = map[string]int32{
	"VoteOptionNone":   0,
	"VoteOptionAgree":  1,
	"VoteOptionReject": 2,
}

func (x VoteOption) String() string {
	return proto.EnumName(VoteOption_name, int32(x))
}

func (VoteOption) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{8}
}

type CmdType int32

const (
	CmdType_CmdNone      CmdType = 0
	CmdType_CmdEmoji     CmdType = 1
	CmdType_CmdDebugCard CmdType = 2
	CmdType_CmdProps     CmdType = 3
	CmdType_CmdPhrase    CmdType = 4
)

var CmdType_name = map[int32]string{
	0: "CmdNone",
	1: "CmdEmoji",
	2: "CmdDebugCard",
	3: "CmdProps",
	4: "CmdPhrase",
}

var CmdType_value = map[string]int32{
	"CmdNone":      0,
	"CmdEmoji":     1,
	"CmdDebugCard": 2,
	"CmdProps":     3,
	"CmdPhrase":    4,
}

func (x CmdType) String() string {
	return proto.EnumName(CmdType_name, int32(x))
}

func (CmdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{9}
}

// 查询游戏配置 c -> s
type QueryGameConfigReq struct {
	Head     *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	GameName string          `protobuf:"bytes,2,opt,name=GameName,proto3" json:"GameName,omitempty"`
	// 1匹配 2好友 3比赛
	Type                 common.DeskType `protobuf:"varint,3,opt,name=Type,proto3,enum=pbcommon.DeskType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryGameConfigReq) Reset()         { *m = QueryGameConfigReq{} }
func (m *QueryGameConfigReq) String() string { return proto.CompactTextString(m) }
func (*QueryGameConfigReq) ProtoMessage()    {}
func (*QueryGameConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{0}
}

func (m *QueryGameConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGameConfigReq.Unmarshal(m, b)
}
func (m *QueryGameConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGameConfigReq.Marshal(b, m, deterministic)
}
func (m *QueryGameConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGameConfigReq.Merge(m, src)
}
func (m *QueryGameConfigReq) XXX_Size() int {
	return xxx_messageInfo_QueryGameConfigReq.Size(m)
}
func (m *QueryGameConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGameConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGameConfigReq proto.InternalMessageInfo

func (m *QueryGameConfigReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryGameConfigReq) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *QueryGameConfigReq) GetType() common.DeskType {
	if m != nil {
		return m.Type
	}
	return common.DeskType_DTNone
}

type QueryGameConfigRsp struct {
	Head    *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	CfgName string          `protobuf:"bytes,2,opt,name=CfgName,proto3" json:"CfgName,omitempty"`
	// pbgame_ddz.FriendsConfigTpl
	CfgValue             []byte   `protobuf:"bytes,3,opt,name=CfgValue,proto3" json:"CfgValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGameConfigRsp) Reset()         { *m = QueryGameConfigRsp{} }
func (m *QueryGameConfigRsp) String() string { return proto.CompactTextString(m) }
func (*QueryGameConfigRsp) ProtoMessage()    {}
func (*QueryGameConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{1}
}

func (m *QueryGameConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGameConfigRsp.Unmarshal(m, b)
}
func (m *QueryGameConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGameConfigRsp.Marshal(b, m, deterministic)
}
func (m *QueryGameConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGameConfigRsp.Merge(m, src)
}
func (m *QueryGameConfigRsp) XXX_Size() int {
	return xxx_messageInfo_QueryGameConfigRsp.Size(m)
}
func (m *QueryGameConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGameConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGameConfigRsp proto.InternalMessageInfo

func (m *QueryGameConfigRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryGameConfigRsp) GetCfgName() string {
	if m != nil {
		return m.CfgName
	}
	return ""
}

func (m *QueryGameConfigRsp) GetCfgValue() []byte {
	if m != nil {
		return m.CfgValue
	}
	return nil
}

// 查询桌子信息 c -> s
type QueryDeskInfoReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	DeskID               uint64          `protobuf:"varint,2,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryDeskInfoReq) Reset()         { *m = QueryDeskInfoReq{} }
func (m *QueryDeskInfoReq) String() string { return proto.CompactTextString(m) }
func (*QueryDeskInfoReq) ProtoMessage()    {}
func (*QueryDeskInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{2}
}

func (m *QueryDeskInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeskInfoReq.Unmarshal(m, b)
}
func (m *QueryDeskInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeskInfoReq.Marshal(b, m, deterministic)
}
func (m *QueryDeskInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeskInfoReq.Merge(m, src)
}
func (m *QueryDeskInfoReq) XXX_Size() int {
	return xxx_messageInfo_QueryDeskInfoReq.Size(m)
}
func (m *QueryDeskInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeskInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeskInfoReq proto.InternalMessageInfo

func (m *QueryDeskInfoReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryDeskInfoReq) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

type QueryDeskInfoRsp struct {
	Head *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	// 1 成功 2 不存在
	Code                 uint32           `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Info                 *common.DeskInfo `protobuf:"bytes,3,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueryDeskInfoRsp) Reset()         { *m = QueryDeskInfoRsp{} }
func (m *QueryDeskInfoRsp) String() string { return proto.CompactTextString(m) }
func (*QueryDeskInfoRsp) ProtoMessage()    {}
func (*QueryDeskInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{3}
}

func (m *QueryDeskInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeskInfoRsp.Unmarshal(m, b)
}
func (m *QueryDeskInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeskInfoRsp.Marshal(b, m, deterministic)
}
func (m *QueryDeskInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeskInfoRsp.Merge(m, src)
}
func (m *QueryDeskInfoRsp) XXX_Size() int {
	return xxx_messageInfo_QueryDeskInfoRsp.Size(m)
}
func (m *QueryDeskInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeskInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeskInfoRsp proto.InternalMessageInfo

func (m *QueryDeskInfoRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryDeskInfoRsp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryDeskInfoRsp) GetInfo() *common.DeskInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 新建桌子 c -> s
type MakeDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	GameName             string          `protobuf:"bytes,2,opt,name=GameName,proto3" json:"GameName,omitempty"`
	GameArgMsgName       string          `protobuf:"bytes,3,opt,name=GameArgMsgName,proto3" json:"GameArgMsgName,omitempty"`
	GameArgMsgValue      []byte          `protobuf:"bytes,4,opt,name=GameArgMsgValue,proto3" json:"GameArgMsgValue,omitempty"`
	ClubID               int64           `protobuf:"varint,5,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MakeDeskReq) Reset()         { *m = MakeDeskReq{} }
func (m *MakeDeskReq) String() string { return proto.CompactTextString(m) }
func (*MakeDeskReq) ProtoMessage()    {}
func (*MakeDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{4}
}

func (m *MakeDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeDeskReq.Unmarshal(m, b)
}
func (m *MakeDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeDeskReq.Marshal(b, m, deterministic)
}
func (m *MakeDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeDeskReq.Merge(m, src)
}
func (m *MakeDeskReq) XXX_Size() int {
	return xxx_messageInfo_MakeDeskReq.Size(m)
}
func (m *MakeDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_MakeDeskReq proto.InternalMessageInfo

func (m *MakeDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MakeDeskReq) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *MakeDeskReq) GetGameArgMsgName() string {
	if m != nil {
		return m.GameArgMsgName
	}
	return ""
}

func (m *MakeDeskReq) GetGameArgMsgValue() []byte {
	if m != nil {
		return m.GameArgMsgValue
	}
	return nil
}

func (m *MakeDeskReq) GetClubID() int64 {
	if m != nil {
		return m.ClubID
	}
	return 0
}

type MakeDeskRsp struct {
	Head                 *common.RspHead  `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Code                 MakeDeskRspCode  `protobuf:"varint,2,opt,name=Code,proto3,enum=pbgame.MakeDeskRspCode" json:"Code,omitempty"`
	StrCode              string           `protobuf:"bytes,3,opt,name=StrCode,proto3" json:"StrCode,omitempty"`
	Info                 *common.DeskInfo `protobuf:"bytes,4,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MakeDeskRsp) Reset()         { *m = MakeDeskRsp{} }
func (m *MakeDeskRsp) String() string { return proto.CompactTextString(m) }
func (*MakeDeskRsp) ProtoMessage()    {}
func (*MakeDeskRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{5}
}

func (m *MakeDeskRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeDeskRsp.Unmarshal(m, b)
}
func (m *MakeDeskRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeDeskRsp.Marshal(b, m, deterministic)
}
func (m *MakeDeskRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeDeskRsp.Merge(m, src)
}
func (m *MakeDeskRsp) XXX_Size() int {
	return xxx_messageInfo_MakeDeskRsp.Size(m)
}
func (m *MakeDeskRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeDeskRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MakeDeskRsp proto.InternalMessageInfo

func (m *MakeDeskRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MakeDeskRsp) GetCode() MakeDeskRspCode {
	if m != nil {
		return m.Code
	}
	return MakeDeskRspCode_MakeDeskNotUse
}

func (m *MakeDeskRsp) GetStrCode() string {
	if m != nil {
		return m.StrCode
	}
	return ""
}

func (m *MakeDeskRsp) GetInfo() *common.DeskInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 加入桌子 c -> s
type JoinDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	DeskID               uint64          `protobuf:"varint,2,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *JoinDeskReq) Reset()         { *m = JoinDeskReq{} }
func (m *JoinDeskReq) String() string { return proto.CompactTextString(m) }
func (*JoinDeskReq) ProtoMessage()    {}
func (*JoinDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{6}
}

func (m *JoinDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinDeskReq.Unmarshal(m, b)
}
func (m *JoinDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinDeskReq.Marshal(b, m, deterministic)
}
func (m *JoinDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinDeskReq.Merge(m, src)
}
func (m *JoinDeskReq) XXX_Size() int {
	return xxx_messageInfo_JoinDeskReq.Size(m)
}
func (m *JoinDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinDeskReq proto.InternalMessageInfo

func (m *JoinDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *JoinDeskReq) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

// 加入桌子 s -> c
type JoinDeskRsp struct {
	Head                 *common.RspHead  `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Code                 JoinDeskRspCode  `protobuf:"varint,2,opt,name=Code,proto3,enum=pbgame.JoinDeskRspCode" json:"Code,omitempty"`
	ErrMsg               string           `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Info                 *common.DeskInfo `protobuf:"bytes,4,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *JoinDeskRsp) Reset()         { *m = JoinDeskRsp{} }
func (m *JoinDeskRsp) String() string { return proto.CompactTextString(m) }
func (*JoinDeskRsp) ProtoMessage()    {}
func (*JoinDeskRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{7}
}

func (m *JoinDeskRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinDeskRsp.Unmarshal(m, b)
}
func (m *JoinDeskRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinDeskRsp.Marshal(b, m, deterministic)
}
func (m *JoinDeskRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinDeskRsp.Merge(m, src)
}
func (m *JoinDeskRsp) XXX_Size() int {
	return xxx_messageInfo_JoinDeskRsp.Size(m)
}
func (m *JoinDeskRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinDeskRsp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinDeskRsp proto.InternalMessageInfo

func (m *JoinDeskRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *JoinDeskRsp) GetCode() JoinDeskRspCode {
	if m != nil {
		return m.Code
	}
	return JoinDeskRspCode_JoinDeskNotUse
}

func (m *JoinDeskRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *JoinDeskRsp) GetInfo() *common.DeskInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 坐下准备 c -> s
type SitDownReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	ChairId              int32           `protobuf:"varint,2,opt,name=chair_id,json=chairId,proto3" json:"chair_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SitDownReq) Reset()         { *m = SitDownReq{} }
func (m *SitDownReq) String() string { return proto.CompactTextString(m) }
func (*SitDownReq) ProtoMessage()    {}
func (*SitDownReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{8}
}

func (m *SitDownReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitDownReq.Unmarshal(m, b)
}
func (m *SitDownReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitDownReq.Marshal(b, m, deterministic)
}
func (m *SitDownReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitDownReq.Merge(m, src)
}
func (m *SitDownReq) XXX_Size() int {
	return xxx_messageInfo_SitDownReq.Size(m)
}
func (m *SitDownReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SitDownReq.DiscardUnknown(m)
}

var xxx_messageInfo_SitDownReq proto.InternalMessageInfo

func (m *SitDownReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *SitDownReq) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

// 坐下准备 s -> c
type SitDownRsp struct {
	Head                 *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Code                 SitDownRspCode  `protobuf:"varint,2,opt,name=Code,proto3,enum=pbgame.SitDownRspCode" json:"Code,omitempty"`
	ErrMsg               string          `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SitDownRsp) Reset()         { *m = SitDownRsp{} }
func (m *SitDownRsp) String() string { return proto.CompactTextString(m) }
func (*SitDownRsp) ProtoMessage()    {}
func (*SitDownRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{9}
}

func (m *SitDownRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitDownRsp.Unmarshal(m, b)
}
func (m *SitDownRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitDownRsp.Marshal(b, m, deterministic)
}
func (m *SitDownRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitDownRsp.Merge(m, src)
}
func (m *SitDownRsp) XXX_Size() int {
	return xxx_messageInfo_SitDownRsp.Size(m)
}
func (m *SitDownRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SitDownRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SitDownRsp proto.InternalMessageInfo

func (m *SitDownRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *SitDownRsp) GetCode() SitDownRspCode {
	if m != nil {
		return m.Code
	}
	return SitDownRspCode_SitDownNone
}

func (m *SitDownRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 离开桌子 c -> s
type ExitDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ExitDeskReq) Reset()         { *m = ExitDeskReq{} }
func (m *ExitDeskReq) String() string { return proto.CompactTextString(m) }
func (*ExitDeskReq) ProtoMessage()    {}
func (*ExitDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{10}
}

func (m *ExitDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitDeskReq.Unmarshal(m, b)
}
func (m *ExitDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitDeskReq.Marshal(b, m, deterministic)
}
func (m *ExitDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitDeskReq.Merge(m, src)
}
func (m *ExitDeskReq) XXX_Size() int {
	return xxx_messageInfo_ExitDeskReq.Size(m)
}
func (m *ExitDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExitDeskReq proto.InternalMessageInfo

func (m *ExitDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

type ExitDeskRsp struct {
	Head                 *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Code                 ExitDeskRspCode `protobuf:"varint,2,opt,name=Code,proto3,enum=pbgame.ExitDeskRspCode" json:"Code,omitempty"`
	ErrMsg               string          `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ExitDeskRsp) Reset()         { *m = ExitDeskRsp{} }
func (m *ExitDeskRsp) String() string { return proto.CompactTextString(m) }
func (*ExitDeskRsp) ProtoMessage()    {}
func (*ExitDeskRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{11}
}

func (m *ExitDeskRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitDeskRsp.Unmarshal(m, b)
}
func (m *ExitDeskRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitDeskRsp.Marshal(b, m, deterministic)
}
func (m *ExitDeskRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitDeskRsp.Merge(m, src)
}
func (m *ExitDeskRsp) XXX_Size() int {
	return xxx_messageInfo_ExitDeskRsp.Size(m)
}
func (m *ExitDeskRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitDeskRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ExitDeskRsp proto.InternalMessageInfo

func (m *ExitDeskRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *ExitDeskRsp) GetCode() ExitDeskRspCode {
	if m != nil {
		return m.Code
	}
	return ExitDeskRspCode_ExitDeskNone
}

func (m *ExitDeskRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 申请解散 c -> s (包括游戏开始前房主解散和游戏中投票解散)
type DestroyDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	DeskID               uint64          `protobuf:"varint,2,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	Type                 DestroyDeskType `protobuf:"varint,3,opt,name=Type,proto3,enum=pbgame.DestroyDeskType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DestroyDeskReq) Reset()         { *m = DestroyDeskReq{} }
func (m *DestroyDeskReq) String() string { return proto.CompactTextString(m) }
func (*DestroyDeskReq) ProtoMessage()    {}
func (*DestroyDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{12}
}

func (m *DestroyDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyDeskReq.Unmarshal(m, b)
}
func (m *DestroyDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyDeskReq.Marshal(b, m, deterministic)
}
func (m *DestroyDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyDeskReq.Merge(m, src)
}
func (m *DestroyDeskReq) XXX_Size() int {
	return xxx_messageInfo_DestroyDeskReq.Size(m)
}
func (m *DestroyDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyDeskReq proto.InternalMessageInfo

func (m *DestroyDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *DestroyDeskReq) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

func (m *DestroyDeskReq) GetType() DestroyDeskType {
	if m != nil {
		return m.Type
	}
	return DestroyDeskType_DestroyTypeGame
}

// 申请解散回应
type DestroyDeskRsp struct {
	Head                 *common.RspHead    `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Code                 DestroyDeskRspCode `protobuf:"varint,2,opt,name=Code,proto3,enum=pbgame.DestroyDeskRspCode" json:"Code,omitempty"`
	Type                 DestroyDeskType    `protobuf:"varint,3,opt,name=Type,proto3,enum=pbgame.DestroyDeskType" json:"Type,omitempty"`
	ErrMsg               string             `protobuf:"bytes,4,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DestroyDeskRsp) Reset()         { *m = DestroyDeskRsp{} }
func (m *DestroyDeskRsp) String() string { return proto.CompactTextString(m) }
func (*DestroyDeskRsp) ProtoMessage()    {}
func (*DestroyDeskRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{13}
}

func (m *DestroyDeskRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyDeskRsp.Unmarshal(m, b)
}
func (m *DestroyDeskRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyDeskRsp.Marshal(b, m, deterministic)
}
func (m *DestroyDeskRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyDeskRsp.Merge(m, src)
}
func (m *DestroyDeskRsp) XXX_Size() int {
	return xxx_messageInfo_DestroyDeskRsp.Size(m)
}
func (m *DestroyDeskRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyDeskRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyDeskRsp proto.InternalMessageInfo

func (m *DestroyDeskRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *DestroyDeskRsp) GetCode() DestroyDeskRspCode {
	if m != nil {
		return m.Code
	}
	return DestroyDeskRspCode_DestroyDeskNone
}

func (m *DestroyDeskRsp) GetType() DestroyDeskType {
	if m != nil {
		return m.Type
	}
	return DestroyDeskType_DestroyTypeGame
}

func (m *DestroyDeskRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 房间解散结果通知
type DestroyDeskResultNotif struct {
	DeskID               uint64          `protobuf:"varint,1,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	Result               int32           `protobuf:"varint,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Type                 DestroyDeskType `protobuf:"varint,3,opt,name=Type,proto3,enum=pbgame.DestroyDeskType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DestroyDeskResultNotif) Reset()         { *m = DestroyDeskResultNotif{} }
func (m *DestroyDeskResultNotif) String() string { return proto.CompactTextString(m) }
func (*DestroyDeskResultNotif) ProtoMessage()    {}
func (*DestroyDeskResultNotif) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{14}
}

func (m *DestroyDeskResultNotif) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyDeskResultNotif.Unmarshal(m, b)
}
func (m *DestroyDeskResultNotif) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyDeskResultNotif.Marshal(b, m, deterministic)
}
func (m *DestroyDeskResultNotif) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyDeskResultNotif.Merge(m, src)
}
func (m *DestroyDeskResultNotif) XXX_Size() int {
	return xxx_messageInfo_DestroyDeskResultNotif.Size(m)
}
func (m *DestroyDeskResultNotif) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyDeskResultNotif.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyDeskResultNotif proto.InternalMessageInfo

func (m *DestroyDeskResultNotif) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

func (m *DestroyDeskResultNotif) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *DestroyDeskResultNotif) GetType() DestroyDeskType {
	if m != nil {
		return m.Type
	}
	return DestroyDeskType_DestroyTypeGame
}

// c -> s 玩家选择解散请求
type VoteDestroyDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Option               VoteOption      `protobuf:"varint,3,opt,name=Option,proto3,enum=pbgame.VoteOption" json:"Option,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *VoteDestroyDeskReq) Reset()         { *m = VoteDestroyDeskReq{} }
func (m *VoteDestroyDeskReq) String() string { return proto.CompactTextString(m) }
func (*VoteDestroyDeskReq) ProtoMessage()    {}
func (*VoteDestroyDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{15}
}

func (m *VoteDestroyDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteDestroyDeskReq.Unmarshal(m, b)
}
func (m *VoteDestroyDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteDestroyDeskReq.Marshal(b, m, deterministic)
}
func (m *VoteDestroyDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteDestroyDeskReq.Merge(m, src)
}
func (m *VoteDestroyDeskReq) XXX_Size() int {
	return xxx_messageInfo_VoteDestroyDeskReq.Size(m)
}
func (m *VoteDestroyDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteDestroyDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_VoteDestroyDeskReq proto.InternalMessageInfo

func (m *VoteDestroyDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *VoteDestroyDeskReq) GetOption() VoteOption {
	if m != nil {
		return m.Option
	}
	return VoteOption_VoteOptionNone
}

// 投票解散信息
type VoteDestroyDeskInfo struct {
	UserID               uint64     `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Option               VoteOption `protobuf:"varint,2,opt,name=Option,proto3,enum=pbgame.VoteOption" json:"Option,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VoteDestroyDeskInfo) Reset()         { *m = VoteDestroyDeskInfo{} }
func (m *VoteDestroyDeskInfo) String() string { return proto.CompactTextString(m) }
func (*VoteDestroyDeskInfo) ProtoMessage()    {}
func (*VoteDestroyDeskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{16}
}

func (m *VoteDestroyDeskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteDestroyDeskInfo.Unmarshal(m, b)
}
func (m *VoteDestroyDeskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteDestroyDeskInfo.Marshal(b, m, deterministic)
}
func (m *VoteDestroyDeskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteDestroyDeskInfo.Merge(m, src)
}
func (m *VoteDestroyDeskInfo) XXX_Size() int {
	return xxx_messageInfo_VoteDestroyDeskInfo.Size(m)
}
func (m *VoteDestroyDeskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteDestroyDeskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VoteDestroyDeskInfo proto.InternalMessageInfo

func (m *VoteDestroyDeskInfo) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *VoteDestroyDeskInfo) GetOption() VoteOption {
	if m != nil {
		return m.Option
	}
	return VoteOption_VoteOptionNone
}

// 玩家选择解散请求广播
type VoteDestroyDeskNotif struct {
	DeskID               uint64                 `protobuf:"varint,1,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	VoteUser             uint64                 `protobuf:"varint,2,opt,name=VoteUser,proto3" json:"VoteUser,omitempty"`
	LeftTime             int32                  `protobuf:"varint,3,opt,name=LeftTime,proto3" json:"LeftTime,omitempty"`
	VoteResult           []*VoteDestroyDeskInfo `protobuf:"bytes,4,rep,name=VoteResult,proto3" json:"VoteResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *VoteDestroyDeskNotif) Reset()         { *m = VoteDestroyDeskNotif{} }
func (m *VoteDestroyDeskNotif) String() string { return proto.CompactTextString(m) }
func (*VoteDestroyDeskNotif) ProtoMessage()    {}
func (*VoteDestroyDeskNotif) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{17}
}

func (m *VoteDestroyDeskNotif) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteDestroyDeskNotif.Unmarshal(m, b)
}
func (m *VoteDestroyDeskNotif) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteDestroyDeskNotif.Marshal(b, m, deterministic)
}
func (m *VoteDestroyDeskNotif) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteDestroyDeskNotif.Merge(m, src)
}
func (m *VoteDestroyDeskNotif) XXX_Size() int {
	return xxx_messageInfo_VoteDestroyDeskNotif.Size(m)
}
func (m *VoteDestroyDeskNotif) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteDestroyDeskNotif.DiscardUnknown(m)
}

var xxx_messageInfo_VoteDestroyDeskNotif proto.InternalMessageInfo

func (m *VoteDestroyDeskNotif) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

func (m *VoteDestroyDeskNotif) GetVoteUser() uint64 {
	if m != nil {
		return m.VoteUser
	}
	return 0
}

func (m *VoteDestroyDeskNotif) GetLeftTime() int32 {
	if m != nil {
		return m.LeftTime
	}
	return 0
}

func (m *VoteDestroyDeskNotif) GetVoteResult() []*VoteDestroyDeskInfo {
	if m != nil {
		return m.VoteResult
	}
	return nil
}

// 游戏动作 c -> s
type GameAction struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	ActionName           string          `protobuf:"bytes,2,opt,name=ActionName,proto3" json:"ActionName,omitempty"`
	ActionValue          []byte          `protobuf:"bytes,3,opt,name=ActionValue,proto3" json:"ActionValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GameAction) Reset()         { *m = GameAction{} }
func (m *GameAction) String() string { return proto.CompactTextString(m) }
func (*GameAction) ProtoMessage()    {}
func (*GameAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{18}
}

func (m *GameAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameAction.Unmarshal(m, b)
}
func (m *GameAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameAction.Marshal(b, m, deterministic)
}
func (m *GameAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameAction.Merge(m, src)
}
func (m *GameAction) XXX_Size() int {
	return xxx_messageInfo_GameAction.Size(m)
}
func (m *GameAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GameAction.DiscardUnknown(m)
}

var xxx_messageInfo_GameAction proto.InternalMessageInfo

func (m *GameAction) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *GameAction) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *GameAction) GetActionValue() []byte {
	if m != nil {
		return m.ActionValue
	}
	return nil
}

// 服务器主动通知 s -> c
type GameNotif struct {
	NotifName            string   `protobuf:"bytes,1,opt,name=NotifName,proto3" json:"NotifName,omitempty"`
	NotifValue           []byte   `protobuf:"bytes,2,opt,name=NotifValue,proto3" json:"NotifValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameNotif) Reset()         { *m = GameNotif{} }
func (m *GameNotif) String() string { return proto.CompactTextString(m) }
func (*GameNotif) ProtoMessage()    {}
func (*GameNotif) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{19}
}

func (m *GameNotif) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameNotif.Unmarshal(m, b)
}
func (m *GameNotif) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameNotif.Marshal(b, m, deterministic)
}
func (m *GameNotif) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameNotif.Merge(m, src)
}
func (m *GameNotif) XXX_Size() int {
	return xxx_messageInfo_GameNotif.Size(m)
}
func (m *GameNotif) XXX_DiscardUnknown() {
	xxx_messageInfo_GameNotif.DiscardUnknown(m)
}

var xxx_messageInfo_GameNotif proto.InternalMessageInfo

func (m *GameNotif) GetNotifName() string {
	if m != nil {
		return m.NotifName
	}
	return ""
}

func (m *GameNotif) GetNotifValue() []byte {
	if m != nil {
		return m.NotifValue
	}
	return nil
}

// 发送游戏指令 c -> s
type GameCommandReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	CmdType              CmdType         `protobuf:"varint,2,opt,name=CmdType,proto3,enum=pbgame.CmdType" json:"CmdType,omitempty"`
	CmdInfo              string          `protobuf:"bytes,3,opt,name=CmdInfo,proto3" json:"CmdInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GameCommandReq) Reset()         { *m = GameCommandReq{} }
func (m *GameCommandReq) String() string { return proto.CompactTextString(m) }
func (*GameCommandReq) ProtoMessage()    {}
func (*GameCommandReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{20}
}

func (m *GameCommandReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameCommandReq.Unmarshal(m, b)
}
func (m *GameCommandReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameCommandReq.Marshal(b, m, deterministic)
}
func (m *GameCommandReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameCommandReq.Merge(m, src)
}
func (m *GameCommandReq) XXX_Size() int {
	return xxx_messageInfo_GameCommandReq.Size(m)
}
func (m *GameCommandReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GameCommandReq.DiscardUnknown(m)
}

var xxx_messageInfo_GameCommandReq proto.InternalMessageInfo

func (m *GameCommandReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *GameCommandReq) GetCmdType() CmdType {
	if m != nil {
		return m.CmdType
	}
	return CmdType_CmdNone
}

func (m *GameCommandReq) GetCmdInfo() string {
	if m != nil {
		return m.CmdInfo
	}
	return ""
}

// 发送游戏指令 s -> c
type GameCommandRsp struct {
	Head                 *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	CmdType              CmdType         `protobuf:"varint,2,opt,name=CmdType,proto3,enum=pbgame.CmdType" json:"CmdType,omitempty"`
	Code                 int32           `protobuf:"varint,3,opt,name=Code,proto3" json:"Code,omitempty"`
	ErrMsg               string          `protobuf:"bytes,4,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GameCommandRsp) Reset()         { *m = GameCommandRsp{} }
func (m *GameCommandRsp) String() string { return proto.CompactTextString(m) }
func (*GameCommandRsp) ProtoMessage()    {}
func (*GameCommandRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{21}
}

func (m *GameCommandRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameCommandRsp.Unmarshal(m, b)
}
func (m *GameCommandRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameCommandRsp.Marshal(b, m, deterministic)
}
func (m *GameCommandRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameCommandRsp.Merge(m, src)
}
func (m *GameCommandRsp) XXX_Size() int {
	return xxx_messageInfo_GameCommandRsp.Size(m)
}
func (m *GameCommandRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GameCommandRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GameCommandRsp proto.InternalMessageInfo

func (m *GameCommandRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *GameCommandRsp) GetCmdType() CmdType {
	if m != nil {
		return m.CmdType
	}
	return CmdType_CmdNone
}

func (m *GameCommandRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GameCommandRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 游戏指令通知,发送给1个或者多个人
type GameCommandNotif struct {
	UserID               uint64   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	CmdType              CmdType  `protobuf:"varint,2,opt,name=CmdType,proto3,enum=pbgame.CmdType" json:"CmdType,omitempty"`
	CmdInfo              string   `protobuf:"bytes,3,opt,name=CmdInfo,proto3" json:"CmdInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameCommandNotif) Reset()         { *m = GameCommandNotif{} }
func (m *GameCommandNotif) String() string { return proto.CompactTextString(m) }
func (*GameCommandNotif) ProtoMessage()    {}
func (*GameCommandNotif) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{22}
}

func (m *GameCommandNotif) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameCommandNotif.Unmarshal(m, b)
}
func (m *GameCommandNotif) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameCommandNotif.Marshal(b, m, deterministic)
}
func (m *GameCommandNotif) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameCommandNotif.Merge(m, src)
}
func (m *GameCommandNotif) XXX_Size() int {
	return xxx_messageInfo_GameCommandNotif.Size(m)
}
func (m *GameCommandNotif) XXX_DiscardUnknown() {
	xxx_messageInfo_GameCommandNotif.DiscardUnknown(m)
}

var xxx_messageInfo_GameCommandNotif proto.InternalMessageInfo

func (m *GameCommandNotif) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GameCommandNotif) GetCmdType() CmdType {
	if m != nil {
		return m.CmdType
	}
	return CmdType_CmdNone
}

func (m *GameCommandNotif) GetCmdInfo() string {
	if m != nil {
		return m.CmdInfo
	}
	return ""
}

func init() {
	proto.RegisterEnum("pbgame.UserDeskStatus", UserDeskStatus_name, UserDeskStatus_value)
	proto.RegisterEnum("pbgame.FeeType", FeeType_name, FeeType_value)
	proto.RegisterEnum("pbgame.MakeDeskRspCode", MakeDeskRspCode_name, MakeDeskRspCode_value)
	proto.RegisterEnum("pbgame.JoinDeskRspCode", JoinDeskRspCode_name, JoinDeskRspCode_value)
	proto.RegisterEnum("pbgame.SitDownRspCode", SitDownRspCode_name, SitDownRspCode_value)
	proto.RegisterEnum("pbgame.ExitDeskRspCode", ExitDeskRspCode_name, ExitDeskRspCode_value)
	proto.RegisterEnum("pbgame.DestroyDeskType", DestroyDeskType_name, DestroyDeskType_value)
	proto.RegisterEnum("pbgame.DestroyDeskRspCode", DestroyDeskRspCode_name, DestroyDeskRspCode_value)
	proto.RegisterEnum("pbgame.VoteOption", VoteOption_name, VoteOption_value)
	proto.RegisterEnum("pbgame.CmdType", CmdType_name, CmdType_value)
	proto.RegisterType((*QueryGameConfigReq)(nil), "pbgame.QueryGameConfigReq")
	proto.RegisterType((*QueryGameConfigRsp)(nil), "pbgame.QueryGameConfigRsp")
	proto.RegisterType((*QueryDeskInfoReq)(nil), "pbgame.QueryDeskInfoReq")
	proto.RegisterType((*QueryDeskInfoRsp)(nil), "pbgame.QueryDeskInfoRsp")
	proto.RegisterType((*MakeDeskReq)(nil), "pbgame.MakeDeskReq")
	proto.RegisterType((*MakeDeskRsp)(nil), "pbgame.MakeDeskRsp")
	proto.RegisterType((*JoinDeskReq)(nil), "pbgame.JoinDeskReq")
	proto.RegisterType((*JoinDeskRsp)(nil), "pbgame.JoinDeskRsp")
	proto.RegisterType((*SitDownReq)(nil), "pbgame.SitDownReq")
	proto.RegisterType((*SitDownRsp)(nil), "pbgame.SitDownRsp")
	proto.RegisterType((*ExitDeskReq)(nil), "pbgame.ExitDeskReq")
	proto.RegisterType((*ExitDeskRsp)(nil), "pbgame.ExitDeskRsp")
	proto.RegisterType((*DestroyDeskReq)(nil), "pbgame.DestroyDeskReq")
	proto.RegisterType((*DestroyDeskRsp)(nil), "pbgame.DestroyDeskRsp")
	proto.RegisterType((*DestroyDeskResultNotif)(nil), "pbgame.DestroyDeskResultNotif")
	proto.RegisterType((*VoteDestroyDeskReq)(nil), "pbgame.VoteDestroyDeskReq")
	proto.RegisterType((*VoteDestroyDeskInfo)(nil), "pbgame.VoteDestroyDeskInfo")
	proto.RegisterType((*VoteDestroyDeskNotif)(nil), "pbgame.VoteDestroyDeskNotif")
	proto.RegisterType((*GameAction)(nil), "pbgame.GameAction")
	proto.RegisterType((*GameNotif)(nil), "pbgame.GameNotif")
	proto.RegisterType((*GameCommandReq)(nil), "pbgame.GameCommandReq")
	proto.RegisterType((*GameCommandRsp)(nil), "pbgame.GameCommandRsp")
	proto.RegisterType((*GameCommandNotif)(nil), "pbgame.GameCommandNotif")
}

func init() { proto.RegisterFile("game/game.proto", fileDescriptor_2a9278d664c0c01e) }

var fileDescriptor_2a9278d664c0c01e = []byte{
	// 1404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xdd, 0x6e, 0xdb, 0xc6,
	0x12, 0x0e, 0x29, 0x5a, 0xb2, 0x47, 0x89, 0xb4, 0x59, 0x27, 0x8a, 0xa2, 0x18, 0x89, 0x20, 0xe0,
	0x1c, 0xf8, 0xe8, 0x00, 0x76, 0xe1, 0xf6, 0xae, 0x57, 0x86, 0x24, 0x27, 0x6a, 0x6d, 0x25, 0xa1,
	0xec, 0x00, 0xed, 0x4d, 0x41, 0x89, 0x6b, 0x99, 0x89, 0xc8, 0x95, 0xf9, 0x93, 0x44, 0x40, 0x81,
	0xa2, 0x7d, 0x80, 0xbe, 0x43, 0x91, 0xdb, 0xf6, 0x05, 0xf2, 0x04, 0x7d, 0x81, 0xbe, 0x4f, 0x31,
	0xcb, 0x25, 0xb9, 0xa4, 0xdd, 0x44, 0x6a, 0x72, 0x61, 0x9b, 0xf3, 0xcd, 0xee, 0xfc, 0x7c, 0x33,
	0xbb, 0x3b, 0x30, 0xd4, 0x67, 0x96, 0xcb, 0xf6, 0xf1, 0xd7, 0xde, 0xc2, 0xe7, 0x21, 0xa7, 0xe5,
	0xc5, 0x04, 0xa5, 0xd6, 0xce, 0x74, 0x29, 0xe0, 0xfd, 0xc5, 0x64, 0x7f, 0xca, 0x5d, 0x97, 0x7b,
	0xfb, 0x17, 0xcc, 0xb2, 0xe3, 0x55, 0xad, 0x87, 0x57, 0xb5, 0xf1, 0x9f, 0x58, 0xdf, 0xf9, 0x09,
	0xe8, 0xf3, 0x88, 0xf9, 0xcb, 0xc7, 0x96, 0xcb, 0x7a, 0xdc, 0x3b, 0x77, 0x66, 0x26, 0xbb, 0xa4,
	0xff, 0x01, 0xe3, 0x09, 0xb3, 0xec, 0xa6, 0xd6, 0xd6, 0x76, 0xab, 0x07, 0xb7, 0xf7, 0x16, 0x13,
	0xb9, 0xc9, 0x64, 0x97, 0xa8, 0x30, 0x85, 0x9a, 0xb6, 0x60, 0x13, 0xf7, 0x8d, 0x2c, 0x97, 0x35,
	0xf5, 0xb6, 0xb6, 0xbb, 0x65, 0xa6, 0x32, 0xfd, 0x2f, 0x18, 0xa7, 0xcb, 0x05, 0x6b, 0x96, 0xda,
	0xda, 0x6e, 0xed, 0x80, 0x66, 0x26, 0xfa, 0x2c, 0x78, 0x85, 0x1a, 0x53, 0xe8, 0x3b, 0x97, 0x57,
	0x03, 0x08, 0x16, 0x1f, 0x08, 0x20, 0x58, 0x28, 0x01, 0x34, 0xa1, 0xd2, 0x3b, 0x9f, 0x29, 0xfe,
	0x13, 0x11, 0x43, 0xeb, 0x9d, 0xcf, 0x5e, 0x58, 0xf3, 0x28, 0x0e, 0xe1, 0xa6, 0x99, 0xca, 0x9d,
	0xe7, 0x40, 0x84, 0x4b, 0x8c, 0x64, 0xe8, 0x9d, 0xf3, 0x35, 0x32, 0x6e, 0x40, 0x59, 0xec, 0xea,
	0x0b, 0x7f, 0x86, 0x29, 0xa5, 0x4e, 0x54, 0x34, 0xb9, 0x7a, 0x0e, 0x14, 0x8c, 0x1e, 0xb7, 0xe3,
	0x04, 0x6e, 0x99, 0xe2, 0x1b, 0xc9, 0x43, 0x2b, 0x22, 0xf2, 0x6a, 0x91, 0x3c, 0x61, 0x5f, 0xe8,
	0x3b, 0xef, 0x35, 0xa8, 0x9e, 0x58, 0xaf, 0x18, 0xc2, 0x9f, 0xad, 0x6e, 0x35, 0xfc, 0x3e, 0xf4,
	0x67, 0x27, 0x41, 0xcc, 0x6c, 0x49, 0xac, 0x28, 0xa0, 0x74, 0x17, 0xea, 0x19, 0x12, 0xf3, 0x6c,
	0x08, 0x9e, 0x8b, 0x30, 0x72, 0xd6, 0x9b, 0x47, 0x93, 0x61, 0xbf, 0xb9, 0xd1, 0xd6, 0x76, 0x4b,
	0xa6, 0x94, 0x3a, 0xef, 0xd4, 0xe0, 0x57, 0xe7, 0xeb, 0xff, 0x0a, 0x5f, 0xb5, 0x83, 0x7b, 0x7b,
	0xf1, 0x31, 0xd8, 0x53, 0x2c, 0xa1, 0x5a, 0x12, 0xd9, 0x84, 0xca, 0x38, 0xf4, 0xc5, 0xfa, 0x38,
	0x8d, 0x44, 0x4c, 0x29, 0x36, 0x3e, 0x42, 0xf1, 0x31, 0x54, 0xbf, 0xe1, 0x8e, 0xb7, 0x26, 0xc3,
	0xff, 0xd4, 0x27, 0xbf, 0x69, 0x8a, 0xb9, 0x4f, 0xce, 0x59, 0xb1, 0xa4, 0xe4, 0xdc, 0x80, 0xf2,
	0xc0, 0xf7, 0x4f, 0x82, 0x99, 0x4c, 0x59, 0x4a, 0x2b, 0x67, 0x3c, 0x02, 0x18, 0x3b, 0x61, 0x9f,
	0xbf, 0xf1, 0xd6, 0x48, 0xf8, 0x3e, 0x6c, 0x4e, 0x2f, 0x2c, 0xc7, 0xff, 0xc1, 0xb1, 0x45, 0x94,
	0x1b, 0x66, 0x45, 0xc8, 0x43, 0xbb, 0xf3, 0x26, 0xb3, 0xb7, 0x7a, 0xc6, 0xdd, 0x5c, 0xc6, 0x8d,
	0x24, 0xe3, 0xcc, 0xd0, 0xc7, 0x13, 0xee, 0x7c, 0x05, 0xd5, 0xc1, 0x5b, 0x27, 0x5c, 0xaf, 0x74,
	0x9d, 0xa5, 0xb2, 0xeb, 0x93, 0x2b, 0xa4, 0x58, 0x5a, 0x21, 0xe0, 0x1f, 0xa1, 0xd6, 0x67, 0x41,
	0xe8, 0xf3, 0xe5, 0xe7, 0x69, 0x37, 0x8c, 0x4a, 0xb9, 0x84, 0xd3, 0xa8, 0x14, 0x27, 0xca, 0x4d,
	0xfc, 0xbb, 0x96, 0x77, 0xbf, 0x7a, 0xf2, 0x7b, 0xb9, 0xe4, 0x5b, 0xd7, 0xb8, 0xc9, 0xe7, 0xbf,
	0x4e, 0x58, 0x0a, 0x59, 0x46, 0x8e, 0xac, 0x08, 0x1a, 0x39, 0xb2, 0x82, 0x68, 0x1e, 0x8e, 0x78,
	0xe8, 0x9c, 0x2b, 0x6c, 0x68, 0x39, 0x36, 0x1a, 0x50, 0x8e, 0x97, 0xc9, 0x0e, 0x95, 0xd2, 0x7a,
	0x2c, 0xcd, 0x80, 0xbe, 0xe0, 0x21, 0xfb, 0x77, 0x75, 0xea, 0x42, 0xf9, 0xe9, 0x22, 0x74, 0xb8,
	0xa7, 0x3c, 0x8b, 0xc2, 0x17, 0x9a, 0x8c, 0x35, 0xa6, 0x5c, 0xd1, 0xf9, 0x0e, 0xb6, 0x0b, 0x8e,
	0xf0, 0x74, 0x62, 0x12, 0x67, 0x01, 0xf3, 0xb3, 0xe4, 0x62, 0x49, 0x31, 0xad, 0x7f, 0xd4, 0xf4,
	0x3b, 0x0d, 0xee, 0x14, 0x6c, 0x7f, 0x98, 0xb9, 0x16, 0x6c, 0xe2, 0x7a, 0x74, 0x25, 0x3b, 0x2c,
	0x95, 0x51, 0x77, 0xcc, 0xce, 0xc3, 0x53, 0x47, 0x3e, 0x15, 0x1b, 0x66, 0x2a, 0xd3, 0xaf, 0x01,
	0x70, 0x9d, 0x64, 0xdd, 0x68, 0x97, 0x76, 0xab, 0x07, 0x0f, 0xd4, 0xc0, 0x0a, 0xd9, 0x99, 0xca,
	0xf2, 0x4e, 0x04, 0x20, 0x9e, 0x92, 0x29, 0xc6, 0xbc, 0x2a, 0xc3, 0x0f, 0x01, 0xe2, 0x0d, 0xca,
	0xe3, 0xa6, 0x20, 0xb4, 0x0d, 0xd5, 0x58, 0x52, 0x47, 0x03, 0x15, 0xea, 0x0c, 0x61, 0x4b, 0x3c,
	0x86, 0x82, 0x90, 0x1d, 0xd8, 0x12, 0x1f, 0xc2, 0x9a, 0x26, 0xac, 0x65, 0x00, 0x3a, 0x13, 0x42,
	0x6c, 0x4b, 0x17, 0xb6, 0x14, 0x04, 0xcf, 0x73, 0x3c, 0xd6, 0xb8, 0xae, 0xe5, 0xd9, 0x6b, 0xf4,
	0xc9, 0xff, 0xa0, 0xd2, 0x73, 0x6d, 0xd1, 0x94, 0x71, 0x35, 0xeb, 0x09, 0x69, 0x12, 0x36, 0x13,
	0xbd, 0x18, 0x81, 0x5c, 0x3b, 0x9d, 0x16, 0xb6, 0xcc, 0x44, 0xec, 0xfc, 0xaa, 0xe5, 0xdd, 0xaf,
	0x7e, 0x9e, 0xd7, 0x70, 0x9f, 0x4c, 0x2f, 0x71, 0xe5, 0x8b, 0xd7, 0x5b, 0xfe, 0xc4, 0x72, 0x20,
	0x4a, 0x3c, 0x69, 0xc7, 0x5d, 0xdb, 0xce, 0x9f, 0x83, 0x81, 0xee, 0xf7, 0x50, 0x43, 0x73, 0xd8,
	0x5d, 0xe3, 0xd0, 0x0a, 0xa3, 0x80, 0x56, 0xa1, 0x72, 0xd6, 0x1f, 0x8f, 0xb8, 0xc7, 0xc8, 0x0d,
	0x29, 0x1c, 0x73, 0xfe, 0x8a, 0x68, 0xb4, 0x06, 0x70, 0xd6, 0x1f, 0xcb, 0xf7, 0x85, 0xe8, 0x52,
	0x7e, 0x36, 0xb7, 0x96, 0x8e, 0x37, 0x23, 0x25, 0x29, 0x63, 0xfc, 0x03, 0xcf, 0x26, 0x46, 0xf7,
	0x0b, 0xa8, 0x1c, 0x31, 0x26, 0x02, 0x00, 0x28, 0x1f, 0x9d, 0x4a, 0x9b, 0xe2, 0xfb, 0x31, 0x9f,
	0xdb, 0x44, 0xa3, 0xb7, 0x60, 0xeb, 0xe8, 0xf4, 0xc4, 0x0a, 0xb8, 0xe7, 0x2f, 0x89, 0xde, 0xfd,
	0x53, 0x87, 0x7a, 0x61, 0x4a, 0xa1, 0x14, 0x6a, 0x09, 0x34, 0xe2, 0xe1, 0x59, 0x80, 0x26, 0x08,
	0xdc, 0x4c, 0xb0, 0x71, 0x34, 0x9d, 0x12, 0x8d, 0x6e, 0x67, 0x1b, 0x0f, 0xfd, 0x59, 0x30, 0xf0,
	0x7d, 0xa2, 0xd3, 0x16, 0x34, 0x94, 0xad, 0x03, 0x8f, 0x47, 0xb3, 0x8b, 0x13, 0xee, 0xb1, 0x25,
	0x29, 0xd1, 0xfb, 0x70, 0xf7, 0x8a, 0x0e, 0x05, 0x62, 0xd0, 0x47, 0xf0, 0x20, 0x51, 0x0d, 0xbd,
	0x90, 0xf9, 0x9e, 0x35, 0x1f, 0x33, 0xff, 0x35, 0xf3, 0x07, 0xbe, 0xcf, 0x7d, 0xb2, 0xa1, 0xee,
	0x45, 0xf2, 0x62, 0xe2, 0xd0, 0x65, 0x99, 0xee, 0x40, 0x33, 0x51, 0xf5, 0x2c, 0x6f, 0xc4, 0xc3,
	0x23, 0xc7, 0xb3, 0xe3, 0x69, 0x8e, 0x54, 0xe8, 0x6d, 0xb8, 0x95, 0x68, 0x8f, 0x1d, 0xd7, 0x09,
	0xc9, 0xa6, 0x6a, 0xeb, 0x70, 0xee, 0x33, 0xcb, 0x5e, 0x0e, 0xc5, 0xc0, 0x42, 0xb6, 0x8a, 0x6e,
	0x46, 0x3c, 0x1c, 0x7a, 0x68, 0x8a, 0x00, 0x6d, 0xc3, 0x4e, 0xde, 0x4d, 0xcf, 0x67, 0x56, 0xc8,
	0x50, 0x2b, 0x36, 0x57, 0xbb, 0xef, 0x35, 0xa8, 0x17, 0x86, 0x1f, 0xa4, 0x32, 0x81, 0x54, 0x2a,
	0x13, 0x4c, 0x52, 0x79, 0x07, 0x88, 0xb2, 0x6a, 0xf0, 0xd6, 0x09, 0x42, 0xa2, 0xab, 0x28, 0xfe,
	0x1c, 0x45, 0xf3, 0x39, 0x29, 0x21, 0x55, 0x09, 0x7a, 0x1d, 0x55, 0x06, 0xe6, 0x90, 0x2c, 0xc8,
	0x53, 0xb5, 0xa1, 0xaa, 0xf2, 0x99, 0x97, 0xbb, 0x7f, 0xe8, 0x50, 0xcb, 0xcf, 0x31, 0xb4, 0x0e,
	0x55, 0x89, 0xc8, 0x36, 0xca, 0x80, 0x2c, 0xee, 0x74, 0x45, 0x28, 0x4d, 0xe9, 0xd8, 0x18, 0x19,
	0x3a, 0x70, 0x17, 0x21, 0x16, 0xbf, 0x05, 0x0d, 0x09, 0xf6, 0x9d, 0x20, 0xb4, 0xbc, 0x29, 0x1b,
	0xf3, 0xde, 0x9c, 0x07, 0x8c, 0x18, 0xb4, 0x09, 0x77, 0xa4, 0x0e, 0x3b, 0xb9, 0x10, 0xb0, 0x62,
	0x4a, 0xe9, 0xa6, 0x32, 0xbd, 0x07, 0xdb, 0x52, 0x85, 0x25, 0x48, 0x69, 0xab, 0x14, 0x83, 0x12,
	0xe5, 0xdb, 0xc4, 0x2e, 0x49, 0x96, 0x8b, 0xea, 0x8d, 0x9d, 0x30, 0x2d, 0xdd, 0x96, 0xaa, 0x9d,
	0x47, 0x93, 0x27, 0xd6, 0x6b, 0x66, 0xb2, 0x39, 0xb3, 0xf0, 0xfe, 0x25, 0x80, 0x45, 0x94, 0xda,
	0xe1, 0xb3, 0xb8, 0x89, 0xaa, 0xdd, 0x5f, 0x34, 0xa8, 0x17, 0xe6, 0x28, 0x2c, 0x6c, 0x02, 0x49,
	0xc6, 0x14, 0x44, 0x52, 0x76, 0x17, 0x6e, 0x67, 0x6b, 0x72, 0x9c, 0x25, 0x70, 0x76, 0xba, 0x1f,
	0xc1, 0x83, 0x04, 0xbc, 0xb6, 0xd4, 0xdd, 0x9f, 0x35, 0xa8, 0x17, 0x06, 0x02, 0xb4, 0x24, 0x21,
	0x14, 0x91, 0x50, 0x72, 0xa3, 0x00, 0x0a, 0x4a, 0x44, 0xf5, 0x14, 0xb0, 0xcf, 0x26, 0xd1, 0x8c,
	0xe8, 0xb4, 0x01, 0xb4, 0xb0, 0x1f, 0xaf, 0x96, 0x52, 0x01, 0xc7, 0x87, 0xf4, 0x69, 0x14, 0x12,
	0xa3, 0xfb, 0x97, 0x96, 0x2a, 0x54, 0x2e, 0xb6, 0x73, 0x91, 0x49, 0x3a, 0xf2, 0xa0, 0x64, 0xa4,
	0x91, 0xdb, 0x9f, 0x64, 0xaf, 0x63, 0x57, 0xe4, 0x47, 0x81, 0x13, 0x2b, 0x08, 0x99, 0x4f, 0x4a,
	0x58, 0x7a, 0x45, 0x73, 0xe4, 0xb3, 0xcb, 0x88, 0x79, 0x21, 0x31, 0x0a, 0x8a, 0xb4, 0x27, 0x36,
	0xae, 0xda, 0x4a, 0xfa, 0xbe, 0xb0, 0xc5, 0x64, 0x0b, 0x3c, 0xd4, 0x36, 0xa9, 0x74, 0xbf, 0x8d,
	0xa7, 0x84, 0x78, 0x38, 0xc1, 0x16, 0xc8, 0xa4, 0x2c, 0x9b, 0x0c, 0x3b, 0x9c, 0xf9, 0x8c, 0xc5,
	0xa4, 0x2a, 0xb3, 0x0d, 0x7b, 0xc9, 0xa6, 0x21, 0xd1, 0xbb, 0xe3, 0xf4, 0xe1, 0xc0, 0xfb, 0xbd,
	0xe7, 0xda, 0xd2, 0xc4, 0x4d, 0xd8, 0xec, 0xb9, 0xf6, 0xc0, 0xe5, 0x2f, 0x1d, 0xa2, 0x61, 0xb7,
	0xf4, 0x5c, 0x5b, 0x14, 0xa2, 0x67, 0xf9, 0x36, 0xd1, 0xa5, 0xfe, 0x99, 0xcf, 0x17, 0x01, 0x29,
	0xe1, 0xd5, 0x8d, 0xd2, 0x85, 0x6f, 0xe1, 0xb1, 0x99, 0x94, 0xc5, 0x3f, 0x4b, 0xbe, 0xfc, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0xe1, 0x02, 0x00, 0xc2, 0x85, 0x11, 0x00, 0x00,
}
