// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/game.proto

package pbgame

import (
	common "cy/game/pb/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MakeDeskRspCode int32

const (
	MakeDeskRspCode_MakeDeskNotUse              MakeDeskRspCode = 0
	MakeDeskRspCode_MakeDeskSucc                MakeDeskRspCode = 1
	MakeDeskRspCode_MakeDeskArgsErr             MakeDeskRspCode = 2
	MakeDeskRspCode_MakeDeskNotEnoughMoney      MakeDeskRspCode = 3
	MakeDeskRspCode_MakeDeskNotEnoughDesk       MakeDeskRspCode = 4
	MakeDeskRspCode_MakeDeskInternalServerError MakeDeskRspCode = 5
	MakeDeskRspCode_MakeDeskUserStatusErr       MakeDeskRspCode = 6
	MakeDeskRspCode_MakeDeskCanNotFindClubID    MakeDeskRspCode = 7
	MakeDeskRspCode_MakeDeskLimit               MakeDeskRspCode = 8
)

var MakeDeskRspCode_name = map[int32]string{
	0: "MakeDeskNotUse",
	1: "MakeDeskSucc",
	2: "MakeDeskArgsErr",
	3: "MakeDeskNotEnoughMoney",
	4: "MakeDeskNotEnoughDesk",
	5: "MakeDeskInternalServerError",
	6: "MakeDeskUserStatusErr",
	7: "MakeDeskCanNotFindClubID",
	8: "MakeDeskLimit",
}

var MakeDeskRspCode_value = map[string]int32{
	"MakeDeskNotUse":              0,
	"MakeDeskSucc":                1,
	"MakeDeskArgsErr":             2,
	"MakeDeskNotEnoughMoney":      3,
	"MakeDeskNotEnoughDesk":       4,
	"MakeDeskInternalServerError": 5,
	"MakeDeskUserStatusErr":       6,
	"MakeDeskCanNotFindClubID":    7,
	"MakeDeskLimit":               8,
}

func (x MakeDeskRspCode) String() string {
	return proto.EnumName(MakeDeskRspCode_name, int32(x))
}

func (MakeDeskRspCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{0}
}

type JoinDeskRspCode int32

const (
	JoinDeskRspCode_JoinDeskNotUse              JoinDeskRspCode = 0
	JoinDeskRspCode_JoinDeskSucc                JoinDeskRspCode = 1
	JoinDeskRspCode_JoinDeskNotExist            JoinDeskRspCode = 2
	JoinDeskRspCode_JoinDeskDeskFull            JoinDeskRspCode = 3
	JoinDeskRspCode_JoinDeskInternalServerError JoinDeskRspCode = 4
	JoinDeskRspCode_JoinDeskUserStatusErr       JoinDeskRspCode = 5
	JoinDeskRspCode_JoinDeskAlreadyInDesk       JoinDeskRspCode = 6
)

var JoinDeskRspCode_name = map[int32]string{
	0: "JoinDeskNotUse",
	1: "JoinDeskSucc",
	2: "JoinDeskNotExist",
	3: "JoinDeskDeskFull",
	4: "JoinDeskInternalServerError",
	5: "JoinDeskUserStatusErr",
	6: "JoinDeskAlreadyInDesk",
}

var JoinDeskRspCode_value = map[string]int32{
	"JoinDeskNotUse":              0,
	"JoinDeskSucc":                1,
	"JoinDeskNotExist":            2,
	"JoinDeskDeskFull":            3,
	"JoinDeskInternalServerError": 4,
	"JoinDeskUserStatusErr":       5,
	"JoinDeskAlreadyInDesk":       6,
}

func (x JoinDeskRspCode) String() string {
	return proto.EnumName(JoinDeskRspCode_name, int32(x))
}

func (JoinDeskRspCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{1}
}

type SitDownRspCode int32

const (
	SitDownRspCode_SitDownNone            SitDownRspCode = 0
	SitDownRspCode_SitDownSucc            SitDownRspCode = 1
	SitDownRspCode_SitDownNotInDesk       SitDownRspCode = 2
	SitDownRspCode_SitDownFull            SitDownRspCode = 3
	SitDownRspCode_SitDownDistanceSoClose SitDownRspCode = 4
	SitDownRspCode_SitDownGameStatusErr   SitDownRspCode = 5
)

var SitDownRspCode_name = map[int32]string{
	0: "SitDownNone",
	1: "SitDownSucc",
	2: "SitDownNotInDesk",
	3: "SitDownFull",
	4: "SitDownDistanceSoClose",
	5: "SitDownGameStatusErr",
}

var SitDownRspCode_value = map[string]int32{
	"SitDownNone":            0,
	"SitDownSucc":            1,
	"SitDownNotInDesk":       2,
	"SitDownFull":            3,
	"SitDownDistanceSoClose": 4,
	"SitDownGameStatusErr":   5,
}

func (x SitDownRspCode) String() string {
	return proto.EnumName(SitDownRspCode_name, int32(x))
}

func (SitDownRspCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{2}
}

// 查询游戏配置 c -> s
type QueryGameConfigReq struct {
	Head     *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	GameName string          `protobuf:"bytes,2,opt,name=GameName,proto3" json:"GameName,omitempty"`
	// 1匹配 2好友 3比赛
	Type                 int32    `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGameConfigReq) Reset()         { *m = QueryGameConfigReq{} }
func (m *QueryGameConfigReq) String() string { return proto.CompactTextString(m) }
func (*QueryGameConfigReq) ProtoMessage()    {}
func (*QueryGameConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{0}
}

func (m *QueryGameConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGameConfigReq.Unmarshal(m, b)
}
func (m *QueryGameConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGameConfigReq.Marshal(b, m, deterministic)
}
func (m *QueryGameConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGameConfigReq.Merge(m, src)
}
func (m *QueryGameConfigReq) XXX_Size() int {
	return xxx_messageInfo_QueryGameConfigReq.Size(m)
}
func (m *QueryGameConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGameConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGameConfigReq proto.InternalMessageInfo

func (m *QueryGameConfigReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryGameConfigReq) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *QueryGameConfigReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type QueryGameConfigRsp struct {
	Head                 *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	CfgName              string          `protobuf:"bytes,2,opt,name=CfgName,proto3" json:"CfgName,omitempty"`
	CfgValue             []byte          `protobuf:"bytes,3,opt,name=CfgValue,proto3" json:"CfgValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryGameConfigRsp) Reset()         { *m = QueryGameConfigRsp{} }
func (m *QueryGameConfigRsp) String() string { return proto.CompactTextString(m) }
func (*QueryGameConfigRsp) ProtoMessage()    {}
func (*QueryGameConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{1}
}

func (m *QueryGameConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGameConfigRsp.Unmarshal(m, b)
}
func (m *QueryGameConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGameConfigRsp.Marshal(b, m, deterministic)
}
func (m *QueryGameConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGameConfigRsp.Merge(m, src)
}
func (m *QueryGameConfigRsp) XXX_Size() int {
	return xxx_messageInfo_QueryGameConfigRsp.Size(m)
}
func (m *QueryGameConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGameConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGameConfigRsp proto.InternalMessageInfo

func (m *QueryGameConfigRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryGameConfigRsp) GetCfgName() string {
	if m != nil {
		return m.CfgName
	}
	return ""
}

func (m *QueryGameConfigRsp) GetCfgValue() []byte {
	if m != nil {
		return m.CfgValue
	}
	return nil
}

// 查询桌子信息 c -> s
type QueryDeskInfoReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	DeskID               uint64          `protobuf:"varint,2,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryDeskInfoReq) Reset()         { *m = QueryDeskInfoReq{} }
func (m *QueryDeskInfoReq) String() string { return proto.CompactTextString(m) }
func (*QueryDeskInfoReq) ProtoMessage()    {}
func (*QueryDeskInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{2}
}

func (m *QueryDeskInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeskInfoReq.Unmarshal(m, b)
}
func (m *QueryDeskInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeskInfoReq.Marshal(b, m, deterministic)
}
func (m *QueryDeskInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeskInfoReq.Merge(m, src)
}
func (m *QueryDeskInfoReq) XXX_Size() int {
	return xxx_messageInfo_QueryDeskInfoReq.Size(m)
}
func (m *QueryDeskInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeskInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeskInfoReq proto.InternalMessageInfo

func (m *QueryDeskInfoReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryDeskInfoReq) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

type QueryDeskInfoRsp struct {
	Head *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	// 1 成功 2 不存在
	Code                 uint32           `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Info                 *common.DeskInfo `protobuf:"bytes,3,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueryDeskInfoRsp) Reset()         { *m = QueryDeskInfoRsp{} }
func (m *QueryDeskInfoRsp) String() string { return proto.CompactTextString(m) }
func (*QueryDeskInfoRsp) ProtoMessage()    {}
func (*QueryDeskInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{3}
}

func (m *QueryDeskInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeskInfoRsp.Unmarshal(m, b)
}
func (m *QueryDeskInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeskInfoRsp.Marshal(b, m, deterministic)
}
func (m *QueryDeskInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeskInfoRsp.Merge(m, src)
}
func (m *QueryDeskInfoRsp) XXX_Size() int {
	return xxx_messageInfo_QueryDeskInfoRsp.Size(m)
}
func (m *QueryDeskInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeskInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeskInfoRsp proto.InternalMessageInfo

func (m *QueryDeskInfoRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryDeskInfoRsp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryDeskInfoRsp) GetInfo() *common.DeskInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 新建桌子 c -> s
type MakeDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	GameName             string          `protobuf:"bytes,2,opt,name=GameName,proto3" json:"GameName,omitempty"`
	GameArgMsgName       string          `protobuf:"bytes,3,opt,name=GameArgMsgName,proto3" json:"GameArgMsgName,omitempty"`
	GameArgMsgValue      []byte          `protobuf:"bytes,4,opt,name=GameArgMsgValue,proto3" json:"GameArgMsgValue,omitempty"`
	ClubID               int64           `protobuf:"varint,5,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MakeDeskReq) Reset()         { *m = MakeDeskReq{} }
func (m *MakeDeskReq) String() string { return proto.CompactTextString(m) }
func (*MakeDeskReq) ProtoMessage()    {}
func (*MakeDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{4}
}

func (m *MakeDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeDeskReq.Unmarshal(m, b)
}
func (m *MakeDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeDeskReq.Marshal(b, m, deterministic)
}
func (m *MakeDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeDeskReq.Merge(m, src)
}
func (m *MakeDeskReq) XXX_Size() int {
	return xxx_messageInfo_MakeDeskReq.Size(m)
}
func (m *MakeDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_MakeDeskReq proto.InternalMessageInfo

func (m *MakeDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MakeDeskReq) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *MakeDeskReq) GetGameArgMsgName() string {
	if m != nil {
		return m.GameArgMsgName
	}
	return ""
}

func (m *MakeDeskReq) GetGameArgMsgValue() []byte {
	if m != nil {
		return m.GameArgMsgValue
	}
	return nil
}

func (m *MakeDeskReq) GetClubID() int64 {
	if m != nil {
		return m.ClubID
	}
	return 0
}

type MakeDeskRsp struct {
	Head                 *common.RspHead  `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Code                 MakeDeskRspCode  `protobuf:"varint,2,opt,name=Code,proto3,enum=pbgame.MakeDeskRspCode" json:"Code,omitempty"`
	StrCode              string           `protobuf:"bytes,3,opt,name=StrCode,proto3" json:"StrCode,omitempty"`
	Info                 *common.DeskInfo `protobuf:"bytes,4,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MakeDeskRsp) Reset()         { *m = MakeDeskRsp{} }
func (m *MakeDeskRsp) String() string { return proto.CompactTextString(m) }
func (*MakeDeskRsp) ProtoMessage()    {}
func (*MakeDeskRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{5}
}

func (m *MakeDeskRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeDeskRsp.Unmarshal(m, b)
}
func (m *MakeDeskRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeDeskRsp.Marshal(b, m, deterministic)
}
func (m *MakeDeskRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeDeskRsp.Merge(m, src)
}
func (m *MakeDeskRsp) XXX_Size() int {
	return xxx_messageInfo_MakeDeskRsp.Size(m)
}
func (m *MakeDeskRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeDeskRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MakeDeskRsp proto.InternalMessageInfo

func (m *MakeDeskRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MakeDeskRsp) GetCode() MakeDeskRspCode {
	if m != nil {
		return m.Code
	}
	return MakeDeskRspCode_MakeDeskNotUse
}

func (m *MakeDeskRsp) GetStrCode() string {
	if m != nil {
		return m.StrCode
	}
	return ""
}

func (m *MakeDeskRsp) GetInfo() *common.DeskInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 销毁桌子 c -> s
type DestroyDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	DeskID               uint64          `protobuf:"varint,2,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DestroyDeskReq) Reset()         { *m = DestroyDeskReq{} }
func (m *DestroyDeskReq) String() string { return proto.CompactTextString(m) }
func (*DestroyDeskReq) ProtoMessage()    {}
func (*DestroyDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{6}
}

func (m *DestroyDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyDeskReq.Unmarshal(m, b)
}
func (m *DestroyDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyDeskReq.Marshal(b, m, deterministic)
}
func (m *DestroyDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyDeskReq.Merge(m, src)
}
func (m *DestroyDeskReq) XXX_Size() int {
	return xxx_messageInfo_DestroyDeskReq.Size(m)
}
func (m *DestroyDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyDeskReq proto.InternalMessageInfo

func (m *DestroyDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *DestroyDeskReq) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

type DestroyDeskRsp struct {
	Head *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	// 1成功 2失败-已经开始 3失败-必须为房主
	Code                 uint32   `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	StrCode              string   `protobuf:"bytes,3,opt,name=StrCode,proto3" json:"StrCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyDeskRsp) Reset()         { *m = DestroyDeskRsp{} }
func (m *DestroyDeskRsp) String() string { return proto.CompactTextString(m) }
func (*DestroyDeskRsp) ProtoMessage()    {}
func (*DestroyDeskRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{7}
}

func (m *DestroyDeskRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyDeskRsp.Unmarshal(m, b)
}
func (m *DestroyDeskRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyDeskRsp.Marshal(b, m, deterministic)
}
func (m *DestroyDeskRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyDeskRsp.Merge(m, src)
}
func (m *DestroyDeskRsp) XXX_Size() int {
	return xxx_messageInfo_DestroyDeskRsp.Size(m)
}
func (m *DestroyDeskRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyDeskRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyDeskRsp proto.InternalMessageInfo

func (m *DestroyDeskRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *DestroyDeskRsp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DestroyDeskRsp) GetStrCode() string {
	if m != nil {
		return m.StrCode
	}
	return ""
}

// s -> c 通知桌子被销毁
type DestroyDeskNotif struct {
	DeskID               uint64   `protobuf:"varint,1,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyDeskNotif) Reset()         { *m = DestroyDeskNotif{} }
func (m *DestroyDeskNotif) String() string { return proto.CompactTextString(m) }
func (*DestroyDeskNotif) ProtoMessage()    {}
func (*DestroyDeskNotif) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{8}
}

func (m *DestroyDeskNotif) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyDeskNotif.Unmarshal(m, b)
}
func (m *DestroyDeskNotif) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyDeskNotif.Marshal(b, m, deterministic)
}
func (m *DestroyDeskNotif) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyDeskNotif.Merge(m, src)
}
func (m *DestroyDeskNotif) XXX_Size() int {
	return xxx_messageInfo_DestroyDeskNotif.Size(m)
}
func (m *DestroyDeskNotif) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyDeskNotif.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyDeskNotif proto.InternalMessageInfo

func (m *DestroyDeskNotif) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

// 加入桌子 c -> s
type JoinDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	DeskID               uint64          `protobuf:"varint,2,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *JoinDeskReq) Reset()         { *m = JoinDeskReq{} }
func (m *JoinDeskReq) String() string { return proto.CompactTextString(m) }
func (*JoinDeskReq) ProtoMessage()    {}
func (*JoinDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{9}
}

func (m *JoinDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinDeskReq.Unmarshal(m, b)
}
func (m *JoinDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinDeskReq.Marshal(b, m, deterministic)
}
func (m *JoinDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinDeskReq.Merge(m, src)
}
func (m *JoinDeskReq) XXX_Size() int {
	return xxx_messageInfo_JoinDeskReq.Size(m)
}
func (m *JoinDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinDeskReq proto.InternalMessageInfo

func (m *JoinDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *JoinDeskReq) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

type JoinDeskRsp struct {
	Head                 *common.RspHead  `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Code                 JoinDeskRspCode  `protobuf:"varint,2,opt,name=Code,proto3,enum=pbgame.JoinDeskRspCode" json:"Code,omitempty"`
	ErrMsg               string           `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Info                 *common.DeskInfo `protobuf:"bytes,4,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *JoinDeskRsp) Reset()         { *m = JoinDeskRsp{} }
func (m *JoinDeskRsp) String() string { return proto.CompactTextString(m) }
func (*JoinDeskRsp) ProtoMessage()    {}
func (*JoinDeskRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{10}
}

func (m *JoinDeskRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinDeskRsp.Unmarshal(m, b)
}
func (m *JoinDeskRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinDeskRsp.Marshal(b, m, deterministic)
}
func (m *JoinDeskRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinDeskRsp.Merge(m, src)
}
func (m *JoinDeskRsp) XXX_Size() int {
	return xxx_messageInfo_JoinDeskRsp.Size(m)
}
func (m *JoinDeskRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinDeskRsp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinDeskRsp proto.InternalMessageInfo

func (m *JoinDeskRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *JoinDeskRsp) GetCode() JoinDeskRspCode {
	if m != nil {
		return m.Code
	}
	return JoinDeskRspCode_JoinDeskNotUse
}

func (m *JoinDeskRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *JoinDeskRsp) GetInfo() *common.DeskInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 坐下准备 c -> s
type SitDownReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SitDownReq) Reset()         { *m = SitDownReq{} }
func (m *SitDownReq) String() string { return proto.CompactTextString(m) }
func (*SitDownReq) ProtoMessage()    {}
func (*SitDownReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{11}
}

func (m *SitDownReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitDownReq.Unmarshal(m, b)
}
func (m *SitDownReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitDownReq.Marshal(b, m, deterministic)
}
func (m *SitDownReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitDownReq.Merge(m, src)
}
func (m *SitDownReq) XXX_Size() int {
	return xxx_messageInfo_SitDownReq.Size(m)
}
func (m *SitDownReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SitDownReq.DiscardUnknown(m)
}

var xxx_messageInfo_SitDownReq proto.InternalMessageInfo

func (m *SitDownReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

type SitDownRsp struct {
	Head                 *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Code                 SitDownRspCode  `protobuf:"varint,2,opt,name=Code,proto3,enum=pbgame.SitDownRspCode" json:"Code,omitempty"`
	ErrMsg               string          `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	ChairId              int32           `protobuf:"varint,4,opt,name=ChairId,proto3" json:"ChairId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SitDownRsp) Reset()         { *m = SitDownRsp{} }
func (m *SitDownRsp) String() string { return proto.CompactTextString(m) }
func (*SitDownRsp) ProtoMessage()    {}
func (*SitDownRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{12}
}

func (m *SitDownRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitDownRsp.Unmarshal(m, b)
}
func (m *SitDownRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitDownRsp.Marshal(b, m, deterministic)
}
func (m *SitDownRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitDownRsp.Merge(m, src)
}
func (m *SitDownRsp) XXX_Size() int {
	return xxx_messageInfo_SitDownRsp.Size(m)
}
func (m *SitDownRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SitDownRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SitDownRsp proto.InternalMessageInfo

func (m *SitDownRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *SitDownRsp) GetCode() SitDownRspCode {
	if m != nil {
		return m.Code
	}
	return SitDownRspCode_SitDownNone
}

func (m *SitDownRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *SitDownRsp) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

// 离开桌子 c -> s
type ExitDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ExitDeskReq) Reset()         { *m = ExitDeskReq{} }
func (m *ExitDeskReq) String() string { return proto.CompactTextString(m) }
func (*ExitDeskReq) ProtoMessage()    {}
func (*ExitDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{13}
}

func (m *ExitDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitDeskReq.Unmarshal(m, b)
}
func (m *ExitDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitDeskReq.Marshal(b, m, deterministic)
}
func (m *ExitDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitDeskReq.Merge(m, src)
}
func (m *ExitDeskReq) XXX_Size() int {
	return xxx_messageInfo_ExitDeskReq.Size(m)
}
func (m *ExitDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExitDeskReq proto.InternalMessageInfo

func (m *ExitDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

type ExitDeskRsp struct {
	Head *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	// 1 成功 2 失败-游戏开始
	Code                 uint32   `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitDeskRsp) Reset()         { *m = ExitDeskRsp{} }
func (m *ExitDeskRsp) String() string { return proto.CompactTextString(m) }
func (*ExitDeskRsp) ProtoMessage()    {}
func (*ExitDeskRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{14}
}

func (m *ExitDeskRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitDeskRsp.Unmarshal(m, b)
}
func (m *ExitDeskRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitDeskRsp.Marshal(b, m, deterministic)
}
func (m *ExitDeskRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitDeskRsp.Merge(m, src)
}
func (m *ExitDeskRsp) XXX_Size() int {
	return xxx_messageInfo_ExitDeskRsp.Size(m)
}
func (m *ExitDeskRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitDeskRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ExitDeskRsp proto.InternalMessageInfo

func (m *ExitDeskRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *ExitDeskRsp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ExitDeskRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 游戏动作 c -> s
type GameAction struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	ActionName           string          `protobuf:"bytes,2,opt,name=ActionName,proto3" json:"ActionName,omitempty"`
	ActionValue          []byte          `protobuf:"bytes,3,opt,name=ActionValue,proto3" json:"ActionValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GameAction) Reset()         { *m = GameAction{} }
func (m *GameAction) String() string { return proto.CompactTextString(m) }
func (*GameAction) ProtoMessage()    {}
func (*GameAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{15}
}

func (m *GameAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameAction.Unmarshal(m, b)
}
func (m *GameAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameAction.Marshal(b, m, deterministic)
}
func (m *GameAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameAction.Merge(m, src)
}
func (m *GameAction) XXX_Size() int {
	return xxx_messageInfo_GameAction.Size(m)
}
func (m *GameAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GameAction.DiscardUnknown(m)
}

var xxx_messageInfo_GameAction proto.InternalMessageInfo

func (m *GameAction) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *GameAction) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *GameAction) GetActionValue() []byte {
	if m != nil {
		return m.ActionValue
	}
	return nil
}

// 服务器主动通知 s -> c
type GameNotif struct {
	NotifName            string   `protobuf:"bytes,1,opt,name=NotifName,proto3" json:"NotifName,omitempty"`
	NotifValue           []byte   `protobuf:"bytes,2,opt,name=NotifValue,proto3" json:"NotifValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameNotif) Reset()         { *m = GameNotif{} }
func (m *GameNotif) String() string { return proto.CompactTextString(m) }
func (*GameNotif) ProtoMessage()    {}
func (*GameNotif) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9278d664c0c01e, []int{16}
}

func (m *GameNotif) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameNotif.Unmarshal(m, b)
}
func (m *GameNotif) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameNotif.Marshal(b, m, deterministic)
}
func (m *GameNotif) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameNotif.Merge(m, src)
}
func (m *GameNotif) XXX_Size() int {
	return xxx_messageInfo_GameNotif.Size(m)
}
func (m *GameNotif) XXX_DiscardUnknown() {
	xxx_messageInfo_GameNotif.DiscardUnknown(m)
}

var xxx_messageInfo_GameNotif proto.InternalMessageInfo

func (m *GameNotif) GetNotifName() string {
	if m != nil {
		return m.NotifName
	}
	return ""
}

func (m *GameNotif) GetNotifValue() []byte {
	if m != nil {
		return m.NotifValue
	}
	return nil
}

func init() {
	proto.RegisterEnum("pbgame.MakeDeskRspCode", MakeDeskRspCode_name, MakeDeskRspCode_value)
	proto.RegisterEnum("pbgame.JoinDeskRspCode", JoinDeskRspCode_name, JoinDeskRspCode_value)
	proto.RegisterEnum("pbgame.SitDownRspCode", SitDownRspCode_name, SitDownRspCode_value)
	proto.RegisterType((*QueryGameConfigReq)(nil), "pbgame.QueryGameConfigReq")
	proto.RegisterType((*QueryGameConfigRsp)(nil), "pbgame.QueryGameConfigRsp")
	proto.RegisterType((*QueryDeskInfoReq)(nil), "pbgame.QueryDeskInfoReq")
	proto.RegisterType((*QueryDeskInfoRsp)(nil), "pbgame.QueryDeskInfoRsp")
	proto.RegisterType((*MakeDeskReq)(nil), "pbgame.MakeDeskReq")
	proto.RegisterType((*MakeDeskRsp)(nil), "pbgame.MakeDeskRsp")
	proto.RegisterType((*DestroyDeskReq)(nil), "pbgame.DestroyDeskReq")
	proto.RegisterType((*DestroyDeskRsp)(nil), "pbgame.DestroyDeskRsp")
	proto.RegisterType((*DestroyDeskNotif)(nil), "pbgame.DestroyDeskNotif")
	proto.RegisterType((*JoinDeskReq)(nil), "pbgame.JoinDeskReq")
	proto.RegisterType((*JoinDeskRsp)(nil), "pbgame.JoinDeskRsp")
	proto.RegisterType((*SitDownReq)(nil), "pbgame.SitDownReq")
	proto.RegisterType((*SitDownRsp)(nil), "pbgame.SitDownRsp")
	proto.RegisterType((*ExitDeskReq)(nil), "pbgame.ExitDeskReq")
	proto.RegisterType((*ExitDeskRsp)(nil), "pbgame.ExitDeskRsp")
	proto.RegisterType((*GameAction)(nil), "pbgame.GameAction")
	proto.RegisterType((*GameNotif)(nil), "pbgame.GameNotif")
}

func init() { proto.RegisterFile("game/game.proto", fileDescriptor_2a9278d664c0c01e) }

var fileDescriptor_2a9278d664c0c01e = []byte{
	// 793 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x61, 0x6e, 0xda, 0x4a,
	0x10, 0x7e, 0x06, 0x43, 0x92, 0x21, 0x81, 0xcd, 0xbe, 0x3c, 0x9e, 0x4b, 0xa3, 0x14, 0x59, 0x6a,
	0x84, 0xa8, 0x04, 0x52, 0xd2, 0x0b, 0x44, 0x40, 0x5a, 0xaa, 0x40, 0x15, 0xd3, 0xf4, 0x77, 0x0d,
	0x2c, 0x8e, 0x15, 0xf0, 0x92, 0xf5, 0xba, 0x0d, 0xa7, 0xa8, 0x7a, 0x84, 0xaa, 0xb7, 0xc8, 0xa9,
	0x7a, 0x84, 0x6a, 0xd7, 0x36, 0x5e, 0x48, 0xd3, 0x3a, 0x4a, 0x7e, 0x24, 0xd9, 0xf9, 0x66, 0xe7,
	0x9b, 0xf9, 0x66, 0xc7, 0xa3, 0x40, 0xc9, 0xb1, 0x67, 0xa4, 0x29, 0x7e, 0x35, 0xe6, 0x8c, 0x72,
	0x8a, 0xf3, 0xf3, 0xa1, 0xb0, 0x2a, 0xfb, 0xa3, 0x85, 0x84, 0x9b, 0xf3, 0x61, 0x73, 0x44, 0x67,
	0x33, 0xea, 0x35, 0x2f, 0x89, 0x3d, 0x0e, 0x6f, 0x55, 0x0e, 0xee, 0x7a, 0xc3, 0x3f, 0xa1, 0xdf,
	0xbc, 0x02, 0x7c, 0x1e, 0x10, 0xb6, 0x78, 0x63, 0xcf, 0x48, 0x8b, 0x7a, 0x13, 0xd7, 0xb1, 0xc8,
	0x35, 0x7e, 0x09, 0xfa, 0x5b, 0x62, 0x8f, 0x0d, 0xad, 0xaa, 0xd5, 0x0a, 0x47, 0xbb, 0x8d, 0xf9,
	0x30, 0x0a, 0xb2, 0xc8, 0xb5, 0x70, 0x58, 0xd2, 0x8d, 0x2b, 0xb0, 0x29, 0xe2, 0xfa, 0xf6, 0x8c,
	0x18, 0x99, 0xaa, 0x56, 0xdb, 0xb2, 0x96, 0x36, 0xc6, 0xa0, 0x7f, 0x58, 0xcc, 0x89, 0x91, 0xad,
	0x6a, 0xb5, 0x9c, 0x25, 0xcf, 0xe6, 0xf5, 0xdd, 0x64, 0xfe, 0xfc, 0x0f, 0xc9, 0xfc, 0xb9, 0x92,
	0xcc, 0x80, 0x8d, 0xd6, 0xc4, 0x51, 0x72, 0xc5, 0xa6, 0x28, 0xa3, 0x35, 0x71, 0x3e, 0xda, 0xd3,
	0x20, 0x4c, 0xb7, 0x6d, 0x2d, 0x6d, 0xf3, 0x1c, 0x90, 0x4c, 0xd9, 0x26, 0xfe, 0x55, 0xd7, 0x9b,
	0xd0, 0x07, 0xa8, 0x2b, 0x43, 0x5e, 0x46, 0xb5, 0x65, 0x3e, 0xdd, 0x8a, 0x2c, 0x33, 0x58, 0xa7,
	0x4c, 0xaf, 0x01, 0x83, 0xde, 0xa2, 0xe3, 0x50, 0xc0, 0x8e, 0x25, 0xcf, 0xf8, 0x10, 0x74, 0xc1,
	0x22, 0x2b, 0x2f, 0x1c, 0xe1, 0x24, 0x74, 0xc9, 0x2f, 0xfd, 0xe6, 0xad, 0x06, 0x85, 0x9e, 0x7d,
	0x45, 0x04, 0xfc, 0x44, 0x6f, 0x74, 0x08, 0x45, 0x71, 0x3e, 0x61, 0x4e, 0xcf, 0x0f, 0x3b, 0x9b,
	0x95, 0x37, 0xd6, 0x50, 0x5c, 0x83, 0x52, 0x82, 0x84, 0x7d, 0xd6, 0x65, 0x9f, 0xd7, 0x61, 0xd1,
	0xb3, 0xd6, 0x34, 0x18, 0x76, 0xdb, 0x46, 0xae, 0xaa, 0xd5, 0xb2, 0x56, 0x64, 0x99, 0x3f, 0xd4,
	0xe2, 0xd3, 0xf7, 0xeb, 0x95, 0xd2, 0xaf, 0xe2, 0xd1, 0xff, 0x8d, 0x70, 0xe4, 0x1b, 0x0a, 0x93,
	0x70, 0x47, 0x8d, 0x34, 0x60, 0x63, 0xc0, 0x99, 0xbc, 0x1f, 0xca, 0x88, 0xcd, 0x65, 0x8b, 0xf5,
	0xbf, 0xb4, 0xf8, 0x3d, 0x14, 0xdb, 0xc4, 0xe7, 0x8c, 0x2e, 0x1e, 0xd8, 0xe4, 0xfb, 0x46, 0x85,
	0xac, 0x12, 0x3e, 0x6e, 0x50, 0xee, 0xd5, 0x67, 0xd6, 0x01, 0x29, 0x69, 0xfa, 0x94, 0xbb, 0x13,
	0xa5, 0x24, 0x6d, 0xa5, 0xa4, 0x33, 0x28, 0xbc, 0xa3, 0xae, 0xf7, 0x44, 0x02, 0xbf, 0x6b, 0x0a,
	0xdd, 0xa3, 0xdf, 0x55, 0x61, 0x52, 0xde, 0xb5, 0x0c, 0xf9, 0x0e, 0x63, 0x3d, 0xdf, 0x89, 0x64,
	0x47, 0x56, 0xea, 0x57, 0x3d, 0x06, 0x18, 0xb8, 0xbc, 0x4d, 0xbf, 0x78, 0xe9, 0x05, 0x9b, 0xdf,
	0xb4, 0x24, 0x2a, 0xbd, 0xae, 0xfa, 0x8a, 0xae, 0x72, 0xac, 0x2b, 0x21, 0x4a, 0x21, 0x4b, 0xec,
	0xb9, 0x4b, 0xdb, 0x65, 0xdd, 0xb1, 0x54, 0x96, 0xb3, 0x62, 0xd3, 0x7c, 0x0d, 0x85, 0xce, 0x8d,
	0xcb, 0x1f, 0xf6, 0x74, 0xe6, 0x27, 0x25, 0xea, 0x71, 0x03, 0x78, 0x4f, 0xc5, 0x66, 0x00, 0x20,
	0xf7, 0xc0, 0x88, 0xbb, 0xd4, 0x4b, 0x3b, 0x51, 0x07, 0x00, 0x61, 0x80, 0xb2, 0x99, 0x14, 0x04,
	0x57, 0xa1, 0x10, 0x5a, 0xea, 0x5e, 0x57, 0x21, 0xb3, 0x0b, 0x5b, 0x72, 0x93, 0xc9, 0x71, 0xdf,
	0x87, 0x2d, 0x79, 0x90, 0x6c, 0x9a, 0x64, 0x4b, 0x00, 0x91, 0x4c, 0x1a, 0x21, 0x57, 0x46, 0x72,
	0x29, 0x48, 0xfd, 0xa7, 0x06, 0xa5, 0xb5, 0xa5, 0x82, 0x31, 0x14, 0x63, 0xa8, 0x4f, 0xf9, 0x85,
	0x4f, 0xd0, 0x3f, 0x18, 0xc1, 0x76, 0x8c, 0x0d, 0x82, 0xd1, 0x08, 0x69, 0xf8, 0xdf, 0x24, 0xf0,
	0x84, 0x39, 0x7e, 0x87, 0x31, 0x94, 0xc1, 0x15, 0x28, 0x2b, 0xa1, 0x1d, 0x8f, 0x06, 0xce, 0x65,
	0x8f, 0x7a, 0x64, 0x81, 0xb2, 0xf8, 0x19, 0xfc, 0x77, 0xc7, 0x27, 0x0c, 0xa4, 0xe3, 0x17, 0xf0,
	0x3c, 0x76, 0x75, 0x3d, 0x4e, 0x98, 0x67, 0x4f, 0x07, 0x84, 0x7d, 0x26, 0xac, 0xc3, 0x18, 0x65,
	0x28, 0xa7, 0xc6, 0x5e, 0xf8, 0x84, 0x0d, 0xb8, 0xcd, 0x03, 0x99, 0x32, 0x8f, 0xf7, 0xc1, 0x88,
	0x5d, 0x2d, 0xdb, 0xeb, 0x53, 0x7e, 0xea, 0x7a, 0xe3, 0x70, 0xf9, 0xa2, 0x0d, 0xbc, 0x0b, 0x3b,
	0xb1, 0xf7, 0xcc, 0x9d, 0xb9, 0x1c, 0x6d, 0xd6, 0x6f, 0x35, 0x28, 0xad, 0x7d, 0x6f, 0x42, 0x72,
	0x0c, 0xa9, 0x92, 0x63, 0x2c, 0x92, 0xbc, 0x07, 0x48, 0xb9, 0xd5, 0xb9, 0x71, 0x7d, 0x8e, 0x32,
	0x2a, 0x2a, 0x7e, 0x4e, 0x83, 0xe9, 0x14, 0x65, 0x85, 0xa4, 0x18, 0xfd, 0x9d, 0x24, 0x5d, 0x48,
	0x8a, 0x2f, 0xac, 0x4a, 0xca, 0xa9, 0xae, 0x93, 0x29, 0x23, 0xf6, 0x78, 0xd1, 0x95, 0x06, 0xca,
	0xd7, 0xbf, 0x6a, 0x50, 0x5c, 0xfd, 0xa8, 0x70, 0x09, 0x0a, 0x11, 0xd2, 0xa7, 0x9e, 0x28, 0x3c,
	0x01, 0x92, 0xba, 0x97, 0x37, 0x78, 0x44, 0x95, 0x51, 0xae, 0x45, 0x25, 0x57, 0xa0, 0x1c, 0x01,
	0x6d, 0xd7, 0xe7, 0xb6, 0x37, 0x22, 0x03, 0xda, 0x9a, 0x52, 0x9f, 0x20, 0x1d, 0x1b, 0xb0, 0x17,
	0xf9, 0xc4, 0xe4, 0x29, 0xc5, 0x0e, 0xf3, 0xf2, 0xdf, 0xa9, 0xe3, 0x5f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x75, 0x03, 0x93, 0x63, 0xa7, 0x09, 0x00, 0x00,
}
