// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/game.proto

package pbgame

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "cy/game/pb/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 玩家在桌子中状态
type UserDeskStatus int32

const (
	UserDeskStatus_UDSNone    UserDeskStatus = 0
	UserDeskStatus_UDSLook    UserDeskStatus = 1
	UserDeskStatus_UDSSitDown UserDeskStatus = 2
	UserDeskStatus_UDSPlaying UserDeskStatus = 3
)

var UserDeskStatus_name = map[int32]string{
	0: "UDSNone",
	1: "UDSLook",
	2: "UDSSitDown",
	3: "UDSPlaying",
}
var UserDeskStatus_value = map[string]int32{
	"UDSNone":    0,
	"UDSLook":    1,
	"UDSSitDown": 2,
	"UDSPlaying": 3,
}

func (x UserDeskStatus) String() string {
	return proto.EnumName(UserDeskStatus_name, int32(x))
}
func (UserDeskStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{0}
}

// 扣费类型
type FeeType int32

const (
	FeeType_FTNone    FeeType = 0
	FeeType_FTGold    FeeType = 1
	FeeType_FTMasonry FeeType = 2
)

var FeeType_name = map[int32]string{
	0: "FTNone",
	1: "FTGold",
	2: "FTMasonry",
}
var FeeType_value = map[string]int32{
	"FTNone":    0,
	"FTGold":    1,
	"FTMasonry": 2,
}

func (x FeeType) String() string {
	return proto.EnumName(FeeType_name, int32(x))
}
func (FeeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{1}
}

// 创建桌子code
type MakeDeskRspCode int32

const (
	MakeDeskRspCode_MakeDeskNotUse              MakeDeskRspCode = 0
	MakeDeskRspCode_MakeDeskSucc                MakeDeskRspCode = 1
	MakeDeskRspCode_MakeDeskArgsErr             MakeDeskRspCode = 2
	MakeDeskRspCode_MakeDeskNotEnoughMoney      MakeDeskRspCode = 3
	MakeDeskRspCode_MakeDeskNotEnoughDesk       MakeDeskRspCode = 4
	MakeDeskRspCode_MakeDeskInternalServerError MakeDeskRspCode = 5
	MakeDeskRspCode_MakeDeskUserStatusErr       MakeDeskRspCode = 6
	MakeDeskRspCode_MakeDeskCanNotFindClubID    MakeDeskRspCode = 7
	MakeDeskRspCode_MakeDeskLimit               MakeDeskRspCode = 8
	MakeDeskRspCode_MakeDeskAlreadyInDesk       MakeDeskRspCode = 9
)

var MakeDeskRspCode_name = map[int32]string{
	0: "MakeDeskNotUse",
	1: "MakeDeskSucc",
	2: "MakeDeskArgsErr",
	3: "MakeDeskNotEnoughMoney",
	4: "MakeDeskNotEnoughDesk",
	5: "MakeDeskInternalServerError",
	6: "MakeDeskUserStatusErr",
	7: "MakeDeskCanNotFindClubID",
	8: "MakeDeskLimit",
	9: "MakeDeskAlreadyInDesk",
}
var MakeDeskRspCode_value = map[string]int32{
	"MakeDeskNotUse":              0,
	"MakeDeskSucc":                1,
	"MakeDeskArgsErr":             2,
	"MakeDeskNotEnoughMoney":      3,
	"MakeDeskNotEnoughDesk":       4,
	"MakeDeskInternalServerError": 5,
	"MakeDeskUserStatusErr":       6,
	"MakeDeskCanNotFindClubID":    7,
	"MakeDeskLimit":               8,
	"MakeDeskAlreadyInDesk":       9,
}

func (x MakeDeskRspCode) String() string {
	return proto.EnumName(MakeDeskRspCode_name, int32(x))
}
func (MakeDeskRspCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{2}
}

// 加入桌子code
type JoinDeskRspCode int32

const (
	JoinDeskRspCode_JoinDeskNotUse              JoinDeskRspCode = 0
	JoinDeskRspCode_JoinDeskSucc                JoinDeskRspCode = 1
	JoinDeskRspCode_JoinDeskNotExist            JoinDeskRspCode = 2
	JoinDeskRspCode_JoinDeskDeskFull            JoinDeskRspCode = 3
	JoinDeskRspCode_JoinDeskInternalServerError JoinDeskRspCode = 4
	JoinDeskRspCode_JoinDeskUserStatusErr       JoinDeskRspCode = 5
	JoinDeskRspCode_JoinDeskAlreadyInDesk       JoinDeskRspCode = 6
)

var JoinDeskRspCode_name = map[int32]string{
	0: "JoinDeskNotUse",
	1: "JoinDeskSucc",
	2: "JoinDeskNotExist",
	3: "JoinDeskDeskFull",
	4: "JoinDeskInternalServerError",
	5: "JoinDeskUserStatusErr",
	6: "JoinDeskAlreadyInDesk",
}
var JoinDeskRspCode_value = map[string]int32{
	"JoinDeskNotUse":              0,
	"JoinDeskSucc":                1,
	"JoinDeskNotExist":            2,
	"JoinDeskDeskFull":            3,
	"JoinDeskInternalServerError": 4,
	"JoinDeskUserStatusErr":       5,
	"JoinDeskAlreadyInDesk":       6,
}

func (x JoinDeskRspCode) String() string {
	return proto.EnumName(JoinDeskRspCode_name, int32(x))
}
func (JoinDeskRspCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{3}
}

// 坐下准备code
type SitDownRspCode int32

const (
	SitDownRspCode_SitDownNone            SitDownRspCode = 0
	SitDownRspCode_SitDownSucc            SitDownRspCode = 1
	SitDownRspCode_SitDownNotInDesk       SitDownRspCode = 2
	SitDownRspCode_SitDownNotEmpty        SitDownRspCode = 3
	SitDownRspCode_SitDownDistanceSoClose SitDownRspCode = 4
	SitDownRspCode_SitDownGameStatusErr   SitDownRspCode = 5
	SitDownRspCode_SitDownNotEnoughMoney  SitDownRspCode = 6
)

var SitDownRspCode_name = map[int32]string{
	0: "SitDownNone",
	1: "SitDownSucc",
	2: "SitDownNotInDesk",
	3: "SitDownNotEmpty",
	4: "SitDownDistanceSoClose",
	5: "SitDownGameStatusErr",
	6: "SitDownNotEnoughMoney",
}
var SitDownRspCode_value = map[string]int32{
	"SitDownNone":            0,
	"SitDownSucc":            1,
	"SitDownNotInDesk":       2,
	"SitDownNotEmpty":        3,
	"SitDownDistanceSoClose": 4,
	"SitDownGameStatusErr":   5,
	"SitDownNotEnoughMoney":  6,
}

func (x SitDownRspCode) String() string {
	return proto.EnumName(SitDownRspCode_name, int32(x))
}
func (SitDownRspCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{4}
}

// 离开桌子code
type ExitDeskRspCode int32

const (
	ExitDeskRspCode_ExitDeskNone                ExitDeskRspCode = 0
	ExitDeskRspCode_ExitDeskSucc                ExitDeskRspCode = 1
	ExitDeskRspCode_ExitDeskNotInDesk           ExitDeskRspCode = 2
	ExitDeskRspCode_ExitDeskPlaying             ExitDeskRspCode = 3
	ExitDeskRspCode_ExitDeskInternalServerError ExitDeskRspCode = 4
)

var ExitDeskRspCode_name = map[int32]string{
	0: "ExitDeskNone",
	1: "ExitDeskSucc",
	2: "ExitDeskNotInDesk",
	3: "ExitDeskPlaying",
	4: "ExitDeskInternalServerError",
}
var ExitDeskRspCode_value = map[string]int32{
	"ExitDeskNone":                0,
	"ExitDeskSucc":                1,
	"ExitDeskNotInDesk":           2,
	"ExitDeskPlaying":             3,
	"ExitDeskInternalServerError": 4,
}

func (x ExitDeskRspCode) String() string {
	return proto.EnumName(ExitDeskRspCode_name, int32(x))
}
func (ExitDeskRspCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{5}
}

// 申请解散回应code
type DestroyDeskRspCode int32

const (
	DestroyDeskRspCode_DestroyDeskNone      DestroyDeskRspCode = 0
	DestroyDeskRspCode_DestroyDeskSucc      DestroyDeskRspCode = 1
	DestroyDeskRspCode_DestroyDeskPlaying   DestroyDeskRspCode = 2
	DestroyDeskRspCode_DestroyDeskNotMaster DestroyDeskRspCode = 3
	DestroyDeskRspCode_DestroyDeskFrequent  DestroyDeskRspCode = 4
	DestroyDeskRspCode_DestroyDeskNotExist  DestroyDeskRspCode = 5
	DestroyDeskRspCode_DestroyDeskNotInDesk DestroyDeskRspCode = 6
	DestroyDeskRspCode_DestroyDeskRepeated  DestroyDeskRspCode = 7
)

var DestroyDeskRspCode_name = map[int32]string{
	0: "DestroyDeskNone",
	1: "DestroyDeskSucc",
	2: "DestroyDeskPlaying",
	3: "DestroyDeskNotMaster",
	4: "DestroyDeskFrequent",
	5: "DestroyDeskNotExist",
	6: "DestroyDeskNotInDesk",
	7: "DestroyDeskRepeated",
}
var DestroyDeskRspCode_value = map[string]int32{
	"DestroyDeskNone":      0,
	"DestroyDeskSucc":      1,
	"DestroyDeskPlaying":   2,
	"DestroyDeskNotMaster": 3,
	"DestroyDeskFrequent":  4,
	"DestroyDeskNotExist":  5,
	"DestroyDeskNotInDesk": 6,
	"DestroyDeskRepeated":  7,
}

func (x DestroyDeskRspCode) String() string {
	return proto.EnumName(DestroyDeskRspCode_name, int32(x))
}
func (DestroyDeskRspCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{6}
}

type VoteOption int32

const (
	VoteOption_VoteOptionNone   VoteOption = 0
	VoteOption_VoteOptionAgree  VoteOption = 1
	VoteOption_VoteOptionReject VoteOption = 2
)

var VoteOption_name = map[int32]string{
	0: "VoteOptionNone",
	1: "VoteOptionAgree",
	2: "VoteOptionReject",
}
var VoteOption_value = map[string]int32{
	"VoteOptionNone":   0,
	"VoteOptionAgree":  1,
	"VoteOptionReject": 2,
}

func (x VoteOption) String() string {
	return proto.EnumName(VoteOption_name, int32(x))
}
func (VoteOption) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{7}
}

// 查询游戏配置 c -> s
type QueryGameConfigReq struct {
	Head     *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	GameName string          `protobuf:"bytes,2,opt,name=GameName,proto3" json:"GameName,omitempty"`
	// 1匹配 2好友 3比赛
	Type                 common.DeskType `protobuf:"varint,3,opt,name=Type,proto3,enum=pbcommon.DeskType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryGameConfigReq) Reset()         { *m = QueryGameConfigReq{} }
func (m *QueryGameConfigReq) String() string { return proto.CompactTextString(m) }
func (*QueryGameConfigReq) ProtoMessage()    {}
func (*QueryGameConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{0}
}
func (m *QueryGameConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGameConfigReq.Unmarshal(m, b)
}
func (m *QueryGameConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGameConfigReq.Marshal(b, m, deterministic)
}
func (dst *QueryGameConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGameConfigReq.Merge(dst, src)
}
func (m *QueryGameConfigReq) XXX_Size() int {
	return xxx_messageInfo_QueryGameConfigReq.Size(m)
}
func (m *QueryGameConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGameConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGameConfigReq proto.InternalMessageInfo

func (m *QueryGameConfigReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryGameConfigReq) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *QueryGameConfigReq) GetType() common.DeskType {
	if m != nil {
		return m.Type
	}
	return common.DeskType_DTNone
}

type QueryGameConfigRsp struct {
	Head    *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	CfgName string          `protobuf:"bytes,2,opt,name=CfgName,proto3" json:"CfgName,omitempty"`
	// pbgame_ddz.FriendsConfigTpl
	CfgValue             []byte   `protobuf:"bytes,3,opt,name=CfgValue,proto3" json:"CfgValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGameConfigRsp) Reset()         { *m = QueryGameConfigRsp{} }
func (m *QueryGameConfigRsp) String() string { return proto.CompactTextString(m) }
func (*QueryGameConfigRsp) ProtoMessage()    {}
func (*QueryGameConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{1}
}
func (m *QueryGameConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGameConfigRsp.Unmarshal(m, b)
}
func (m *QueryGameConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGameConfigRsp.Marshal(b, m, deterministic)
}
func (dst *QueryGameConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGameConfigRsp.Merge(dst, src)
}
func (m *QueryGameConfigRsp) XXX_Size() int {
	return xxx_messageInfo_QueryGameConfigRsp.Size(m)
}
func (m *QueryGameConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGameConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGameConfigRsp proto.InternalMessageInfo

func (m *QueryGameConfigRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryGameConfigRsp) GetCfgName() string {
	if m != nil {
		return m.CfgName
	}
	return ""
}

func (m *QueryGameConfigRsp) GetCfgValue() []byte {
	if m != nil {
		return m.CfgValue
	}
	return nil
}

// 查询桌子信息 c -> s
type QueryDeskInfoReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	DeskID               uint64          `protobuf:"varint,2,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryDeskInfoReq) Reset()         { *m = QueryDeskInfoReq{} }
func (m *QueryDeskInfoReq) String() string { return proto.CompactTextString(m) }
func (*QueryDeskInfoReq) ProtoMessage()    {}
func (*QueryDeskInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{2}
}
func (m *QueryDeskInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeskInfoReq.Unmarshal(m, b)
}
func (m *QueryDeskInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeskInfoReq.Marshal(b, m, deterministic)
}
func (dst *QueryDeskInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeskInfoReq.Merge(dst, src)
}
func (m *QueryDeskInfoReq) XXX_Size() int {
	return xxx_messageInfo_QueryDeskInfoReq.Size(m)
}
func (m *QueryDeskInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeskInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeskInfoReq proto.InternalMessageInfo

func (m *QueryDeskInfoReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryDeskInfoReq) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

type QueryDeskInfoRsp struct {
	Head *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	// 1 成功 2 不存在
	Code                 uint32           `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Info                 *common.DeskInfo `protobuf:"bytes,3,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueryDeskInfoRsp) Reset()         { *m = QueryDeskInfoRsp{} }
func (m *QueryDeskInfoRsp) String() string { return proto.CompactTextString(m) }
func (*QueryDeskInfoRsp) ProtoMessage()    {}
func (*QueryDeskInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{3}
}
func (m *QueryDeskInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeskInfoRsp.Unmarshal(m, b)
}
func (m *QueryDeskInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeskInfoRsp.Marshal(b, m, deterministic)
}
func (dst *QueryDeskInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeskInfoRsp.Merge(dst, src)
}
func (m *QueryDeskInfoRsp) XXX_Size() int {
	return xxx_messageInfo_QueryDeskInfoRsp.Size(m)
}
func (m *QueryDeskInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeskInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeskInfoRsp proto.InternalMessageInfo

func (m *QueryDeskInfoRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryDeskInfoRsp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryDeskInfoRsp) GetInfo() *common.DeskInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 新建桌子 c -> s
type MakeDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	GameName             string          `protobuf:"bytes,2,opt,name=GameName,proto3" json:"GameName,omitempty"`
	GameArgMsgName       string          `protobuf:"bytes,3,opt,name=GameArgMsgName,proto3" json:"GameArgMsgName,omitempty"`
	GameArgMsgValue      []byte          `protobuf:"bytes,4,opt,name=GameArgMsgValue,proto3" json:"GameArgMsgValue,omitempty"`
	ClubID               int64           `protobuf:"varint,5,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MakeDeskReq) Reset()         { *m = MakeDeskReq{} }
func (m *MakeDeskReq) String() string { return proto.CompactTextString(m) }
func (*MakeDeskReq) ProtoMessage()    {}
func (*MakeDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{4}
}
func (m *MakeDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeDeskReq.Unmarshal(m, b)
}
func (m *MakeDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeDeskReq.Marshal(b, m, deterministic)
}
func (dst *MakeDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeDeskReq.Merge(dst, src)
}
func (m *MakeDeskReq) XXX_Size() int {
	return xxx_messageInfo_MakeDeskReq.Size(m)
}
func (m *MakeDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_MakeDeskReq proto.InternalMessageInfo

func (m *MakeDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MakeDeskReq) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *MakeDeskReq) GetGameArgMsgName() string {
	if m != nil {
		return m.GameArgMsgName
	}
	return ""
}

func (m *MakeDeskReq) GetGameArgMsgValue() []byte {
	if m != nil {
		return m.GameArgMsgValue
	}
	return nil
}

func (m *MakeDeskReq) GetClubID() int64 {
	if m != nil {
		return m.ClubID
	}
	return 0
}

type MakeDeskRsp struct {
	Head                 *common.RspHead  `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Code                 MakeDeskRspCode  `protobuf:"varint,2,opt,name=Code,proto3,enum=pbgame.MakeDeskRspCode" json:"Code,omitempty"`
	StrCode              string           `protobuf:"bytes,3,opt,name=StrCode,proto3" json:"StrCode,omitempty"`
	Info                 *common.DeskInfo `protobuf:"bytes,4,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MakeDeskRsp) Reset()         { *m = MakeDeskRsp{} }
func (m *MakeDeskRsp) String() string { return proto.CompactTextString(m) }
func (*MakeDeskRsp) ProtoMessage()    {}
func (*MakeDeskRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{5}
}
func (m *MakeDeskRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeDeskRsp.Unmarshal(m, b)
}
func (m *MakeDeskRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeDeskRsp.Marshal(b, m, deterministic)
}
func (dst *MakeDeskRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeDeskRsp.Merge(dst, src)
}
func (m *MakeDeskRsp) XXX_Size() int {
	return xxx_messageInfo_MakeDeskRsp.Size(m)
}
func (m *MakeDeskRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeDeskRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MakeDeskRsp proto.InternalMessageInfo

func (m *MakeDeskRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MakeDeskRsp) GetCode() MakeDeskRspCode {
	if m != nil {
		return m.Code
	}
	return MakeDeskRspCode_MakeDeskNotUse
}

func (m *MakeDeskRsp) GetStrCode() string {
	if m != nil {
		return m.StrCode
	}
	return ""
}

func (m *MakeDeskRsp) GetInfo() *common.DeskInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 加入桌子 c -> s
type JoinDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	DeskID               uint64          `protobuf:"varint,2,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *JoinDeskReq) Reset()         { *m = JoinDeskReq{} }
func (m *JoinDeskReq) String() string { return proto.CompactTextString(m) }
func (*JoinDeskReq) ProtoMessage()    {}
func (*JoinDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{6}
}
func (m *JoinDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinDeskReq.Unmarshal(m, b)
}
func (m *JoinDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinDeskReq.Marshal(b, m, deterministic)
}
func (dst *JoinDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinDeskReq.Merge(dst, src)
}
func (m *JoinDeskReq) XXX_Size() int {
	return xxx_messageInfo_JoinDeskReq.Size(m)
}
func (m *JoinDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinDeskReq proto.InternalMessageInfo

func (m *JoinDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *JoinDeskReq) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

// 加入桌子 s -> c
type JoinDeskRsp struct {
	Head                 *common.RspHead  `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Code                 JoinDeskRspCode  `protobuf:"varint,2,opt,name=Code,proto3,enum=pbgame.JoinDeskRspCode" json:"Code,omitempty"`
	ErrMsg               string           `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Info                 *common.DeskInfo `protobuf:"bytes,4,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *JoinDeskRsp) Reset()         { *m = JoinDeskRsp{} }
func (m *JoinDeskRsp) String() string { return proto.CompactTextString(m) }
func (*JoinDeskRsp) ProtoMessage()    {}
func (*JoinDeskRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{7}
}
func (m *JoinDeskRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinDeskRsp.Unmarshal(m, b)
}
func (m *JoinDeskRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinDeskRsp.Marshal(b, m, deterministic)
}
func (dst *JoinDeskRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinDeskRsp.Merge(dst, src)
}
func (m *JoinDeskRsp) XXX_Size() int {
	return xxx_messageInfo_JoinDeskRsp.Size(m)
}
func (m *JoinDeskRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinDeskRsp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinDeskRsp proto.InternalMessageInfo

func (m *JoinDeskRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *JoinDeskRsp) GetCode() JoinDeskRspCode {
	if m != nil {
		return m.Code
	}
	return JoinDeskRspCode_JoinDeskNotUse
}

func (m *JoinDeskRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *JoinDeskRsp) GetInfo() *common.DeskInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 坐下准备 c -> s
type SitDownReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	ChairId              int32           `protobuf:"varint,2,opt,name=chair_id,json=chairId,proto3" json:"chair_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SitDownReq) Reset()         { *m = SitDownReq{} }
func (m *SitDownReq) String() string { return proto.CompactTextString(m) }
func (*SitDownReq) ProtoMessage()    {}
func (*SitDownReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{8}
}
func (m *SitDownReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitDownReq.Unmarshal(m, b)
}
func (m *SitDownReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitDownReq.Marshal(b, m, deterministic)
}
func (dst *SitDownReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitDownReq.Merge(dst, src)
}
func (m *SitDownReq) XXX_Size() int {
	return xxx_messageInfo_SitDownReq.Size(m)
}
func (m *SitDownReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SitDownReq.DiscardUnknown(m)
}

var xxx_messageInfo_SitDownReq proto.InternalMessageInfo

func (m *SitDownReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *SitDownReq) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

// 坐下准备 s -> c
type SitDownRsp struct {
	Head                 *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Code                 SitDownRspCode  `protobuf:"varint,2,opt,name=Code,proto3,enum=pbgame.SitDownRspCode" json:"Code,omitempty"`
	ErrMsg               string          `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SitDownRsp) Reset()         { *m = SitDownRsp{} }
func (m *SitDownRsp) String() string { return proto.CompactTextString(m) }
func (*SitDownRsp) ProtoMessage()    {}
func (*SitDownRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{9}
}
func (m *SitDownRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitDownRsp.Unmarshal(m, b)
}
func (m *SitDownRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitDownRsp.Marshal(b, m, deterministic)
}
func (dst *SitDownRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitDownRsp.Merge(dst, src)
}
func (m *SitDownRsp) XXX_Size() int {
	return xxx_messageInfo_SitDownRsp.Size(m)
}
func (m *SitDownRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SitDownRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SitDownRsp proto.InternalMessageInfo

func (m *SitDownRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *SitDownRsp) GetCode() SitDownRspCode {
	if m != nil {
		return m.Code
	}
	return SitDownRspCode_SitDownNone
}

func (m *SitDownRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 离开桌子 c -> s
type ExitDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ExitDeskReq) Reset()         { *m = ExitDeskReq{} }
func (m *ExitDeskReq) String() string { return proto.CompactTextString(m) }
func (*ExitDeskReq) ProtoMessage()    {}
func (*ExitDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{10}
}
func (m *ExitDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitDeskReq.Unmarshal(m, b)
}
func (m *ExitDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitDeskReq.Marshal(b, m, deterministic)
}
func (dst *ExitDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitDeskReq.Merge(dst, src)
}
func (m *ExitDeskReq) XXX_Size() int {
	return xxx_messageInfo_ExitDeskReq.Size(m)
}
func (m *ExitDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExitDeskReq proto.InternalMessageInfo

func (m *ExitDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

type ExitDeskRsp struct {
	Head                 *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Code                 ExitDeskRspCode `protobuf:"varint,2,opt,name=Code,proto3,enum=pbgame.ExitDeskRspCode" json:"Code,omitempty"`
	ErrMsg               string          `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ExitDeskRsp) Reset()         { *m = ExitDeskRsp{} }
func (m *ExitDeskRsp) String() string { return proto.CompactTextString(m) }
func (*ExitDeskRsp) ProtoMessage()    {}
func (*ExitDeskRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{11}
}
func (m *ExitDeskRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitDeskRsp.Unmarshal(m, b)
}
func (m *ExitDeskRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitDeskRsp.Marshal(b, m, deterministic)
}
func (dst *ExitDeskRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitDeskRsp.Merge(dst, src)
}
func (m *ExitDeskRsp) XXX_Size() int {
	return xxx_messageInfo_ExitDeskRsp.Size(m)
}
func (m *ExitDeskRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitDeskRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ExitDeskRsp proto.InternalMessageInfo

func (m *ExitDeskRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *ExitDeskRsp) GetCode() ExitDeskRspCode {
	if m != nil {
		return m.Code
	}
	return ExitDeskRspCode_ExitDeskNone
}

func (m *ExitDeskRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 申请解散 c -> s (包括游戏开始前房主解散和游戏中投票解散)
type DestroyDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	DeskID               uint64          `protobuf:"varint,2,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DestroyDeskReq) Reset()         { *m = DestroyDeskReq{} }
func (m *DestroyDeskReq) String() string { return proto.CompactTextString(m) }
func (*DestroyDeskReq) ProtoMessage()    {}
func (*DestroyDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{12}
}
func (m *DestroyDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyDeskReq.Unmarshal(m, b)
}
func (m *DestroyDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyDeskReq.Marshal(b, m, deterministic)
}
func (dst *DestroyDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyDeskReq.Merge(dst, src)
}
func (m *DestroyDeskReq) XXX_Size() int {
	return xxx_messageInfo_DestroyDeskReq.Size(m)
}
func (m *DestroyDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyDeskReq proto.InternalMessageInfo

func (m *DestroyDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *DestroyDeskReq) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

// 申请解散回应
type DestroyDeskRsp struct {
	Head                 *common.RspHead    `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Code                 DestroyDeskRspCode `protobuf:"varint,2,opt,name=Code,proto3,enum=pbgame.DestroyDeskRspCode" json:"Code,omitempty"`
	ErrMsg               string             `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DestroyDeskRsp) Reset()         { *m = DestroyDeskRsp{} }
func (m *DestroyDeskRsp) String() string { return proto.CompactTextString(m) }
func (*DestroyDeskRsp) ProtoMessage()    {}
func (*DestroyDeskRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{13}
}
func (m *DestroyDeskRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyDeskRsp.Unmarshal(m, b)
}
func (m *DestroyDeskRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyDeskRsp.Marshal(b, m, deterministic)
}
func (dst *DestroyDeskRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyDeskRsp.Merge(dst, src)
}
func (m *DestroyDeskRsp) XXX_Size() int {
	return xxx_messageInfo_DestroyDeskRsp.Size(m)
}
func (m *DestroyDeskRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyDeskRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyDeskRsp proto.InternalMessageInfo

func (m *DestroyDeskRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *DestroyDeskRsp) GetCode() DestroyDeskRspCode {
	if m != nil {
		return m.Code
	}
	return DestroyDeskRspCode_DestroyDeskNone
}

func (m *DestroyDeskRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 房间解散结果通知
type DestroyDeskResultNotif struct {
	DeskID               uint64   `protobuf:"varint,1,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	Result               int32    `protobuf:"varint,2,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyDeskResultNotif) Reset()         { *m = DestroyDeskResultNotif{} }
func (m *DestroyDeskResultNotif) String() string { return proto.CompactTextString(m) }
func (*DestroyDeskResultNotif) ProtoMessage()    {}
func (*DestroyDeskResultNotif) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{14}
}
func (m *DestroyDeskResultNotif) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyDeskResultNotif.Unmarshal(m, b)
}
func (m *DestroyDeskResultNotif) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyDeskResultNotif.Marshal(b, m, deterministic)
}
func (dst *DestroyDeskResultNotif) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyDeskResultNotif.Merge(dst, src)
}
func (m *DestroyDeskResultNotif) XXX_Size() int {
	return xxx_messageInfo_DestroyDeskResultNotif.Size(m)
}
func (m *DestroyDeskResultNotif) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyDeskResultNotif.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyDeskResultNotif proto.InternalMessageInfo

func (m *DestroyDeskResultNotif) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

func (m *DestroyDeskResultNotif) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// 投票解散开始
type VoteDestroyDeskStartNotif struct {
	DeskID               uint64   `protobuf:"varint,1,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	VoteUser             uint64   `protobuf:"varint,2,opt,name=VoteUser,proto3" json:"VoteUser,omitempty"`
	LeftTime             int32    `protobuf:"varint,3,opt,name=LeftTime,proto3" json:"LeftTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteDestroyDeskStartNotif) Reset()         { *m = VoteDestroyDeskStartNotif{} }
func (m *VoteDestroyDeskStartNotif) String() string { return proto.CompactTextString(m) }
func (*VoteDestroyDeskStartNotif) ProtoMessage()    {}
func (*VoteDestroyDeskStartNotif) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{15}
}
func (m *VoteDestroyDeskStartNotif) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteDestroyDeskStartNotif.Unmarshal(m, b)
}
func (m *VoteDestroyDeskStartNotif) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteDestroyDeskStartNotif.Marshal(b, m, deterministic)
}
func (dst *VoteDestroyDeskStartNotif) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteDestroyDeskStartNotif.Merge(dst, src)
}
func (m *VoteDestroyDeskStartNotif) XXX_Size() int {
	return xxx_messageInfo_VoteDestroyDeskStartNotif.Size(m)
}
func (m *VoteDestroyDeskStartNotif) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteDestroyDeskStartNotif.DiscardUnknown(m)
}

var xxx_messageInfo_VoteDestroyDeskStartNotif proto.InternalMessageInfo

func (m *VoteDestroyDeskStartNotif) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

func (m *VoteDestroyDeskStartNotif) GetVoteUser() uint64 {
	if m != nil {
		return m.VoteUser
	}
	return 0
}

func (m *VoteDestroyDeskStartNotif) GetLeftTime() int32 {
	if m != nil {
		return m.LeftTime
	}
	return 0
}

// c -> s 玩家选择解散请求
type VoteDestroyDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Option               VoteOption      `protobuf:"varint,3,opt,name=Option,proto3,enum=pbgame.VoteOption" json:"Option,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *VoteDestroyDeskReq) Reset()         { *m = VoteDestroyDeskReq{} }
func (m *VoteDestroyDeskReq) String() string { return proto.CompactTextString(m) }
func (*VoteDestroyDeskReq) ProtoMessage()    {}
func (*VoteDestroyDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{16}
}
func (m *VoteDestroyDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteDestroyDeskReq.Unmarshal(m, b)
}
func (m *VoteDestroyDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteDestroyDeskReq.Marshal(b, m, deterministic)
}
func (dst *VoteDestroyDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteDestroyDeskReq.Merge(dst, src)
}
func (m *VoteDestroyDeskReq) XXX_Size() int {
	return xxx_messageInfo_VoteDestroyDeskReq.Size(m)
}
func (m *VoteDestroyDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteDestroyDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_VoteDestroyDeskReq proto.InternalMessageInfo

func (m *VoteDestroyDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *VoteDestroyDeskReq) GetOption() VoteOption {
	if m != nil {
		return m.Option
	}
	return VoteOption_VoteOptionNone
}

// 玩家选择解散请求广播
type VoteDestroyDeskNotif struct {
	DeskID               uint64     `protobuf:"varint,1,opt,name=DeskID,proto3" json:"DeskID,omitempty"`
	UserID               uint64     `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Option               VoteOption `protobuf:"varint,3,opt,name=Option,proto3,enum=pbgame.VoteOption" json:"Option,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VoteDestroyDeskNotif) Reset()         { *m = VoteDestroyDeskNotif{} }
func (m *VoteDestroyDeskNotif) String() string { return proto.CompactTextString(m) }
func (*VoteDestroyDeskNotif) ProtoMessage()    {}
func (*VoteDestroyDeskNotif) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{17}
}
func (m *VoteDestroyDeskNotif) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteDestroyDeskNotif.Unmarshal(m, b)
}
func (m *VoteDestroyDeskNotif) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteDestroyDeskNotif.Marshal(b, m, deterministic)
}
func (dst *VoteDestroyDeskNotif) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteDestroyDeskNotif.Merge(dst, src)
}
func (m *VoteDestroyDeskNotif) XXX_Size() int {
	return xxx_messageInfo_VoteDestroyDeskNotif.Size(m)
}
func (m *VoteDestroyDeskNotif) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteDestroyDeskNotif.DiscardUnknown(m)
}

var xxx_messageInfo_VoteDestroyDeskNotif proto.InternalMessageInfo

func (m *VoteDestroyDeskNotif) GetDeskID() uint64 {
	if m != nil {
		return m.DeskID
	}
	return 0
}

func (m *VoteDestroyDeskNotif) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *VoteDestroyDeskNotif) GetOption() VoteOption {
	if m != nil {
		return m.Option
	}
	return VoteOption_VoteOptionNone
}

// 投票解散信息(断线重连时用)
type VoteDestroyDeskInfo struct {
	UserID               uint64     `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Option               VoteOption `protobuf:"varint,2,opt,name=Option,proto3,enum=pbgame.VoteOption" json:"Option,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VoteDestroyDeskInfo) Reset()         { *m = VoteDestroyDeskInfo{} }
func (m *VoteDestroyDeskInfo) String() string { return proto.CompactTextString(m) }
func (*VoteDestroyDeskInfo) ProtoMessage()    {}
func (*VoteDestroyDeskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{18}
}
func (m *VoteDestroyDeskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteDestroyDeskInfo.Unmarshal(m, b)
}
func (m *VoteDestroyDeskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteDestroyDeskInfo.Marshal(b, m, deterministic)
}
func (dst *VoteDestroyDeskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteDestroyDeskInfo.Merge(dst, src)
}
func (m *VoteDestroyDeskInfo) XXX_Size() int {
	return xxx_messageInfo_VoteDestroyDeskInfo.Size(m)
}
func (m *VoteDestroyDeskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteDestroyDeskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VoteDestroyDeskInfo proto.InternalMessageInfo

func (m *VoteDestroyDeskInfo) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *VoteDestroyDeskInfo) GetOption() VoteOption {
	if m != nil {
		return m.Option
	}
	return VoteOption_VoteOptionNone
}

// 游戏动作 c -> s
type GameAction struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	ActionName           string          `protobuf:"bytes,2,opt,name=ActionName,proto3" json:"ActionName,omitempty"`
	ActionValue          []byte          `protobuf:"bytes,3,opt,name=ActionValue,proto3" json:"ActionValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GameAction) Reset()         { *m = GameAction{} }
func (m *GameAction) String() string { return proto.CompactTextString(m) }
func (*GameAction) ProtoMessage()    {}
func (*GameAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{19}
}
func (m *GameAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameAction.Unmarshal(m, b)
}
func (m *GameAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameAction.Marshal(b, m, deterministic)
}
func (dst *GameAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameAction.Merge(dst, src)
}
func (m *GameAction) XXX_Size() int {
	return xxx_messageInfo_GameAction.Size(m)
}
func (m *GameAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GameAction.DiscardUnknown(m)
}

var xxx_messageInfo_GameAction proto.InternalMessageInfo

func (m *GameAction) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *GameAction) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *GameAction) GetActionValue() []byte {
	if m != nil {
		return m.ActionValue
	}
	return nil
}

// 服务器主动通知 s -> c
type GameNotif struct {
	NotifName            string   `protobuf:"bytes,1,opt,name=NotifName,proto3" json:"NotifName,omitempty"`
	NotifValue           []byte   `protobuf:"bytes,2,opt,name=NotifValue,proto3" json:"NotifValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameNotif) Reset()         { *m = GameNotif{} }
func (m *GameNotif) String() string { return proto.CompactTextString(m) }
func (*GameNotif) ProtoMessage()    {}
func (*GameNotif) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_f1ee0acae25292c9, []int{20}
}
func (m *GameNotif) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameNotif.Unmarshal(m, b)
}
func (m *GameNotif) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameNotif.Marshal(b, m, deterministic)
}
func (dst *GameNotif) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameNotif.Merge(dst, src)
}
func (m *GameNotif) XXX_Size() int {
	return xxx_messageInfo_GameNotif.Size(m)
}
func (m *GameNotif) XXX_DiscardUnknown() {
	xxx_messageInfo_GameNotif.DiscardUnknown(m)
}

var xxx_messageInfo_GameNotif proto.InternalMessageInfo

func (m *GameNotif) GetNotifName() string {
	if m != nil {
		return m.NotifName
	}
	return ""
}

func (m *GameNotif) GetNotifValue() []byte {
	if m != nil {
		return m.NotifValue
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGameConfigReq)(nil), "pbgame.QueryGameConfigReq")
	proto.RegisterType((*QueryGameConfigRsp)(nil), "pbgame.QueryGameConfigRsp")
	proto.RegisterType((*QueryDeskInfoReq)(nil), "pbgame.QueryDeskInfoReq")
	proto.RegisterType((*QueryDeskInfoRsp)(nil), "pbgame.QueryDeskInfoRsp")
	proto.RegisterType((*MakeDeskReq)(nil), "pbgame.MakeDeskReq")
	proto.RegisterType((*MakeDeskRsp)(nil), "pbgame.MakeDeskRsp")
	proto.RegisterType((*JoinDeskReq)(nil), "pbgame.JoinDeskReq")
	proto.RegisterType((*JoinDeskRsp)(nil), "pbgame.JoinDeskRsp")
	proto.RegisterType((*SitDownReq)(nil), "pbgame.SitDownReq")
	proto.RegisterType((*SitDownRsp)(nil), "pbgame.SitDownRsp")
	proto.RegisterType((*ExitDeskReq)(nil), "pbgame.ExitDeskReq")
	proto.RegisterType((*ExitDeskRsp)(nil), "pbgame.ExitDeskRsp")
	proto.RegisterType((*DestroyDeskReq)(nil), "pbgame.DestroyDeskReq")
	proto.RegisterType((*DestroyDeskRsp)(nil), "pbgame.DestroyDeskRsp")
	proto.RegisterType((*DestroyDeskResultNotif)(nil), "pbgame.DestroyDeskResultNotif")
	proto.RegisterType((*VoteDestroyDeskStartNotif)(nil), "pbgame.VoteDestroyDeskStartNotif")
	proto.RegisterType((*VoteDestroyDeskReq)(nil), "pbgame.VoteDestroyDeskReq")
	proto.RegisterType((*VoteDestroyDeskNotif)(nil), "pbgame.VoteDestroyDeskNotif")
	proto.RegisterType((*VoteDestroyDeskInfo)(nil), "pbgame.VoteDestroyDeskInfo")
	proto.RegisterType((*GameAction)(nil), "pbgame.GameAction")
	proto.RegisterType((*GameNotif)(nil), "pbgame.GameNotif")
	proto.RegisterEnum("pbgame.UserDeskStatus", UserDeskStatus_name, UserDeskStatus_value)
	proto.RegisterEnum("pbgame.FeeType", FeeType_name, FeeType_value)
	proto.RegisterEnum("pbgame.MakeDeskRspCode", MakeDeskRspCode_name, MakeDeskRspCode_value)
	proto.RegisterEnum("pbgame.JoinDeskRspCode", JoinDeskRspCode_name, JoinDeskRspCode_value)
	proto.RegisterEnum("pbgame.SitDownRspCode", SitDownRspCode_name, SitDownRspCode_value)
	proto.RegisterEnum("pbgame.ExitDeskRspCode", ExitDeskRspCode_name, ExitDeskRspCode_value)
	proto.RegisterEnum("pbgame.DestroyDeskRspCode", DestroyDeskRspCode_name, DestroyDeskRspCode_value)
	proto.RegisterEnum("pbgame.VoteOption", VoteOption_name, VoteOption_value)
}

func init() { proto.RegisterFile("game/game.proto", fileDescriptor_game_f1ee0acae25292c9) }

var fileDescriptor_game_f1ee0acae25292c9 = []byte{
	// 1126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0x9e, 0xe4, 0xbf, 0xe4, 0xb8, 0xb1, 0x19, 0x26, 0x75, 0x1d, 0x2f, 0xe8, 0x02, 0x01, 0x1b,
	0x02, 0x0f, 0x48, 0x86, 0x6c, 0x2f, 0x10, 0xf8, 0xa7, 0x75, 0x17, 0xbb, 0xab, 0x9c, 0x14, 0xd8,
	0xd5, 0xa0, 0xd8, 0xb4, 0xa2, 0xc5, 0x16, 0x15, 0x8a, 0x5a, 0xeb, 0xab, 0x02, 0xbb, 0xdd, 0x53,
	0x0c, 0xbb, 0xdf, 0x03, 0xf4, 0x3d, 0xf6, 0x3e, 0x03, 0x29, 0xca, 0xa2, 0x94, 0xb6, 0xb1, 0xd1,
	0x5e, 0x24, 0xd6, 0xf9, 0x0e, 0xf9, 0xf1, 0x7c, 0x1f, 0x29, 0x1e, 0x1b, 0xea, 0xae, 0xb3, 0x20,
	0xa7, 0xe2, 0xdf, 0x49, 0xc0, 0x28, 0xa7, 0xb8, 0x1c, 0x5c, 0x8b, 0xa8, 0x75, 0x38, 0x59, 0x4a,
	0xf8, 0x34, 0xb8, 0x3e, 0x9d, 0xd0, 0xc5, 0x82, 0xfa, 0xa7, 0x37, 0xc4, 0x99, 0xc6, 0xa3, 0x5a,
	0x4f, 0xef, 0x67, 0xe3, 0x8f, 0x38, 0x6f, 0xbd, 0x03, 0xfc, 0x2a, 0x22, 0x6c, 0xf9, 0xcc, 0x59,
	0x90, 0x0e, 0xf5, 0x67, 0x9e, 0x6b, 0x93, 0x3b, 0xfc, 0x2d, 0x14, 0x9f, 0x13, 0x67, 0xda, 0x34,
	0x8e, 0x8c, 0xe3, 0xea, 0xd9, 0xee, 0x49, 0x70, 0xad, 0x26, 0xd9, 0xe4, 0x4e, 0x24, 0x6c, 0x99,
	0xc6, 0x2d, 0xd8, 0x12, 0xf3, 0x46, 0xce, 0x82, 0x34, 0xcd, 0x23, 0xe3, 0x78, 0xdb, 0x5e, 0xc5,
	0xf8, 0x3b, 0x28, 0x5e, 0x2e, 0x03, 0xd2, 0x2c, 0x1c, 0x19, 0xc7, 0xb5, 0x33, 0x9c, 0x52, 0x74,
	0x49, 0x78, 0x2b, 0x32, 0xb6, 0xcc, 0x5b, 0x77, 0xf7, 0x0b, 0x08, 0x83, 0x4f, 0x14, 0x10, 0x06,
	0x5a, 0x01, 0x4d, 0xa8, 0x74, 0x66, 0xae, 0xb6, 0x7e, 0x12, 0x8a, 0xd2, 0x3a, 0x33, 0xf7, 0xb5,
	0x33, 0x8f, 0xe2, 0x12, 0x1e, 0xd9, 0xab, 0xd8, 0x7a, 0x05, 0x48, 0x2e, 0x29, 0x2a, 0x19, 0xf8,
	0x33, 0xba, 0x81, 0xe2, 0x06, 0x94, 0xe5, 0xac, 0xae, 0x5c, 0xaf, 0x68, 0xab, 0xc8, 0x8a, 0xf2,
	0x94, 0xeb, 0x6b, 0xc0, 0x50, 0xec, 0xd0, 0x69, 0x2c, 0x60, 0xc7, 0x96, 0xcf, 0xc2, 0x3c, 0xc1,
	0x22, 0x2b, 0xaf, 0xe6, 0xcd, 0x93, 0xfc, 0x32, 0x6f, 0xbd, 0x37, 0xa0, 0x3a, 0x74, 0x6e, 0x89,
	0x80, 0xbf, 0xd8, 0xbe, 0xd5, 0xc4, 0xf3, 0x39, 0x73, 0x87, 0x61, 0xec, 0x6c, 0x41, 0x8e, 0xc8,
	0xa1, 0xf8, 0x18, 0xea, 0x29, 0x12, 0xfb, 0x5c, 0x94, 0x3e, 0xe7, 0x61, 0xe1, 0x59, 0x67, 0x1e,
	0x5d, 0x0f, 0xba, 0xcd, 0xd2, 0x91, 0x71, 0x5c, 0xb0, 0x55, 0x64, 0xfd, 0xa3, 0x17, 0xbf, 0xbe,
	0x5f, 0xdf, 0x6b, 0x7e, 0xd5, 0xce, 0x9e, 0x9c, 0xc4, 0xaf, 0xc1, 0x89, 0xc6, 0x24, 0xd2, 0xca,
	0xc8, 0x26, 0x54, 0xc6, 0x9c, 0xc9, 0xf1, 0xb1, 0x8c, 0x24, 0x5c, 0x59, 0x5c, 0x7c, 0xc0, 0xe2,
	0x0b, 0xa8, 0xbe, 0xa0, 0x9e, 0xbf, 0xa1, 0xc3, 0x1f, 0x3b, 0x27, 0x7f, 0x1b, 0x1a, 0xdd, 0x67,
	0x6b, 0xd6, 0x98, 0x34, 0xcd, 0x0d, 0x28, 0xf7, 0x18, 0x1b, 0x86, 0xae, 0x92, 0xac, 0xa2, 0xb5,
	0x15, 0x8f, 0x00, 0xc6, 0x1e, 0xef, 0xd2, 0x37, 0xfe, 0x06, 0x82, 0x0f, 0x60, 0x6b, 0x72, 0xe3,
	0x78, 0xec, 0x37, 0x6f, 0x2a, 0xab, 0x2c, 0xd9, 0x15, 0x19, 0x0f, 0xa6, 0xd6, 0x9b, 0x94, 0x6f,
	0x7d, 0xc5, 0xed, 0x8c, 0xe2, 0x46, 0xa2, 0x38, 0x25, 0x7a, 0x58, 0xb0, 0xf5, 0x13, 0x54, 0x7b,
	0x6f, 0x3d, 0xbe, 0xd9, 0xd6, 0x59, 0x4b, 0x6d, 0xd6, 0x67, 0xef, 0x90, 0xc6, 0xb4, 0x46, 0xc1,
	0x2f, 0xa1, 0xd6, 0x25, 0x21, 0x67, 0x74, 0xf9, 0x85, 0x8e, 0xdb, 0xbb, 0x2c, 0xe1, 0xfa, 0x72,
	0x4e, 0x32, 0x72, 0x5a, 0x89, 0x9c, 0x2c, 0xd9, 0x1a, 0x8a, 0x9e, 0x43, 0x23, 0xa3, 0x28, 0x8c,
	0xe6, 0x7c, 0x44, 0xb9, 0x37, 0xd3, 0x4a, 0x36, 0xf4, 0x92, 0x05, 0x1e, 0x0f, 0x53, 0xc7, 0x48,
	0x45, 0xd6, 0x2d, 0x1c, 0xbc, 0xa6, 0x9c, 0x68, 0x6c, 0x63, 0xee, 0xb0, 0x07, 0xc8, 0x5a, 0xb0,
	0x25, 0x26, 0x5d, 0x85, 0x84, 0x29, 0x67, 0x56, 0xb1, 0xc8, 0x5d, 0x90, 0x19, 0xbf, 0xf4, 0xd4,
	0x15, 0x57, 0xb2, 0x57, 0xb1, 0xe5, 0x02, 0xce, 0x2d, 0xb6, 0xc1, 0x66, 0xb4, 0xa1, 0xfc, 0x32,
	0xe0, 0x1e, 0xf5, 0xb5, 0xde, 0x27, 0xdd, 0x13, 0x94, 0x71, 0xc6, 0x56, 0x23, 0x2c, 0x06, 0xfb,
	0xb9, 0x85, 0x1e, 0x74, 0x47, 0x14, 0x9f, 0x6e, 0x74, 0x1c, 0x6d, 0xb4, 0xe6, 0xaf, 0xb0, 0x97,
	0x5b, 0x53, 0xbc, 0xf6, 0x1a, 0xb5, 0xf1, 0x11, 0x6a, 0xf3, 0x41, 0xea, 0x08, 0x40, 0xde, 0xfe,
	0x13, 0x11, 0xad, 0xeb, 0xd7, 0x53, 0x80, 0x78, 0x82, 0xd6, 0x8f, 0x34, 0x04, 0x1f, 0x41, 0x35,
	0x8e, 0xf4, 0x6e, 0xae, 0x43, 0xd6, 0x00, 0xb6, 0x65, 0xff, 0x92, 0xd6, 0x1d, 0xc2, 0xb6, 0x7c,
	0x90, 0x6c, 0x86, 0x64, 0x4b, 0x01, 0xb1, 0x98, 0x0c, 0x62, 0x2e, 0x53, 0x72, 0x69, 0x48, 0xfb,
	0x05, 0xd4, 0x84, 0x6e, 0x75, 0xbe, 0x78, 0x14, 0xe2, 0x2a, 0x54, 0xae, 0xba, 0xe3, 0x11, 0xf5,
	0x09, 0xfa, 0x4a, 0x05, 0x17, 0x94, 0xde, 0x22, 0x03, 0xd7, 0x00, 0xae, 0xba, 0x63, 0x75, 0x25,
	0x21, 0x53, 0xc5, 0xbf, 0xcc, 0x9d, 0xa5, 0xe7, 0xbb, 0xa8, 0xd0, 0xfe, 0x01, 0x2a, 0x7d, 0x42,
	0xc4, 0xb7, 0x1c, 0x0c, 0x50, 0xee, 0x5f, 0x2a, 0x0e, 0xf9, 0xfc, 0x8c, 0xce, 0xa7, 0xc8, 0xc0,
	0x3b, 0xb0, 0xdd, 0xbf, 0x1c, 0x3a, 0x21, 0xf5, 0xd9, 0x12, 0x99, 0xed, 0xbf, 0x4c, 0xa8, 0xe7,
	0x1a, 0x19, 0xc6, 0x50, 0x4b, 0xa0, 0x11, 0xe5, 0x57, 0xa1, 0xa0, 0x40, 0xf0, 0x28, 0xc1, 0xc6,
	0xd1, 0x64, 0x82, 0x0c, 0xbc, 0x97, 0x4e, 0x3c, 0x67, 0x6e, 0xd8, 0x63, 0x0c, 0x99, 0xb8, 0x05,
	0x0d, 0x6d, 0x6a, 0xcf, 0xa7, 0x91, 0x7b, 0x33, 0xa4, 0x3e, 0x59, 0xa2, 0x02, 0x3e, 0x80, 0xc7,
	0xf7, 0x72, 0x22, 0x40, 0x45, 0xfc, 0x0d, 0x7c, 0x9d, 0xa4, 0x06, 0x3e, 0x27, 0xcc, 0x77, 0xe6,
	0x63, 0xc2, 0xfe, 0x20, 0xac, 0xc7, 0x18, 0x65, 0xa8, 0xa4, 0xcf, 0x15, 0x66, 0xc5, 0x46, 0x89,
	0x25, 0xcb, 0xf8, 0x10, 0x9a, 0x49, 0xaa, 0xe3, 0xf8, 0x23, 0xca, 0xfb, 0x9e, 0x3f, 0x8d, 0x1b,
	0x3e, 0xaa, 0xe0, 0x5d, 0xd8, 0x49, 0xb2, 0x17, 0xde, 0xc2, 0xe3, 0x68, 0x4b, 0xe7, 0x3a, 0x9f,
	0x33, 0xe2, 0x4c, 0x97, 0x03, 0xd9, 0xd3, 0xd0, 0x76, 0xfb, 0xbd, 0x01, 0xf5, 0x5c, 0x8b, 0x13,
	0x6e, 0x24, 0x90, 0xee, 0x46, 0x82, 0x29, 0x37, 0xf6, 0x01, 0x69, 0xa3, 0x7a, 0x6f, 0xbd, 0x90,
	0x23, 0x53, 0x47, 0xc5, 0x5f, 0x3f, 0x9a, 0xcf, 0x51, 0x41, 0xa8, 0x4d, 0xd0, 0x0f, 0xa9, 0x2d,
	0x8a, 0x0a, 0x93, 0x01, 0x59, 0xb5, 0x25, 0x3d, 0x95, 0x2d, 0xbe, 0xdc, 0xfe, 0xd7, 0x80, 0x5a,
	0xb6, 0x5b, 0xe1, 0x3a, 0x54, 0x15, 0xa2, 0x4e, 0x42, 0x0a, 0xa4, 0x75, 0xaf, 0x46, 0x70, 0x45,
	0x65, 0x8a, 0xbd, 0x4d, 0xd1, 0xde, 0x22, 0xe0, 0x62, 0xff, 0x5a, 0xd0, 0x50, 0x60, 0xd7, 0x0b,
	0xb9, 0xe3, 0x4f, 0xc8, 0x98, 0x76, 0xe6, 0x34, 0x24, 0xa8, 0x88, 0x9b, 0xb0, 0xaf, 0x72, 0xe2,
	0xb5, 0xc8, 0x15, 0xac, 0x51, 0x69, 0x07, 0xa2, 0xdc, 0xfe, 0xd3, 0x80, 0x7a, 0xae, 0x5d, 0x09,
	0x67, 0x13, 0x48, 0x95, 0xac, 0x21, 0xaa, 0xe6, 0xc7, 0xb0, 0x9b, 0x8e, 0xc9, 0x14, 0x9d, 0xc0,
	0xab, 0x37, 0x42, 0x78, 0x9d, 0x80, 0x1f, 0xf4, 0xba, 0xfd, 0x9f, 0x01, 0xf8, 0x7e, 0x93, 0x11,
	0x64, 0x99, 0x2b, 0x52, 0x96, 0x92, 0x05, 0x55, 0x35, 0x8d, 0xcc, 0xfc, 0x64, 0x65, 0x53, 0x58,
	0x92, 0xbd, 0x64, 0x87, 0x4e, 0xc8, 0x09, 0x43, 0x05, 0xfc, 0x04, 0xf6, 0xb4, 0x4c, 0x9f, 0x91,
	0xbb, 0x88, 0xf8, 0x1c, 0x15, 0x73, 0x89, 0xd5, 0x39, 0x2a, 0xdd, 0xe7, 0x4a, 0x36, 0x3d, 0x37,
	0xc5, 0x26, 0x01, 0x71, 0x38, 0x99, 0xa2, 0x4a, 0xfb, 0x67, 0x80, 0xf4, 0xba, 0x14, 0x87, 0x38,
	0x8d, 0x52, 0x35, 0x29, 0x76, 0xee, 0x32, 0x42, 0xe2, 0xf3, 0xa0, 0xdd, 0xb2, 0xe4, 0x77, 0x32,
	0xe1, 0xc8, 0xbc, 0x2e, 0xcb, 0x9f, 0x6e, 0x3f, 0xfe, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x44, 0x7e,
	0x35, 0x46, 0x13, 0x0e, 0x00, 0x00,
}
