// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BindMobileRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsBindMobileRequest(buf []byte, offset flatbuffers.UOffsetT) *BindMobileRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BindMobileRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *BindMobileRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BindMobileRequest) Mobile() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BindMobileRequest) Code() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func BindMobileRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BindMobileRequestAddMobile(builder *flatbuffers.Builder, mobile flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(mobile), 0)
}
func BindMobileRequestAddCode(builder *flatbuffers.Builder, code flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(code), 0)
}
func BindMobileRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
