// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClubCreateRoomRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsClubCreateRoomRequest(buf []byte, offset flatbuffers.UOffsetT) *ClubCreateRoomRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClubCreateRoomRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ClubCreateRoomRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClubCreateRoomRequest) UserId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClubCreateRoomRequest) MutateUserId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *ClubCreateRoomRequest) ClubId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClubCreateRoomRequest) MutateClubId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func ClubCreateRoomRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ClubCreateRoomRequestAddUserId(builder *flatbuffers.Builder, userId uint32) {
	builder.PrependUint32Slot(0, userId, 0)
}
func ClubCreateRoomRequestAddClubId(builder *flatbuffers.Builder, clubId uint32) {
	builder.PrependUint32Slot(1, clubId, 0)
}
func ClubCreateRoomRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
