// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClubCheckApplyRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsClubCheckApplyRequest(buf []byte, offset flatbuffers.UOffsetT) *ClubCheckApplyRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClubCheckApplyRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ClubCheckApplyRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClubCheckApplyRequest) UserId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClubCheckApplyRequest) MutateUserId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *ClubCheckApplyRequest) ApplyUser() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClubCheckApplyRequest) MutateApplyUser(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *ClubCheckApplyRequest) ClubId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClubCheckApplyRequest) MutateClubId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *ClubCheckApplyRequest) CheckType() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *ClubCheckApplyRequest) MutateCheckType(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func ClubCheckApplyRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ClubCheckApplyRequestAddUserId(builder *flatbuffers.Builder, userId uint32) {
	builder.PrependUint32Slot(0, userId, 0)
}
func ClubCheckApplyRequestAddApplyUser(builder *flatbuffers.Builder, applyUser uint32) {
	builder.PrependUint32Slot(1, applyUser, 0)
}
func ClubCheckApplyRequestAddClubId(builder *flatbuffers.Builder, clubId uint32) {
	builder.PrependUint32Slot(2, clubId, 0)
}
func ClubCheckApplyRequestAddCheckType(builder *flatbuffers.Builder, checkType uint32) {
	builder.PrependUint32Slot(3, checkType, 1)
}
func ClubCheckApplyRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
