// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetCoinMatchRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGetCoinMatchRequest(buf []byte, offset flatbuffers.UOffsetT) *GetCoinMatchRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetCoinMatchRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GetCoinMatchRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetCoinMatchRequest) MahjongType() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetCoinMatchRequest) MutateMahjongType(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func GetCoinMatchRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetCoinMatchRequestAddMahjongType(builder *flatbuffers.Builder, mahjongType uint32) {
	builder.PrependUint32Slot(0, mahjongType, 0)
}
func GetCoinMatchRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
