// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RewardCoinRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsRewardCoinRequest(buf []byte, offset flatbuffers.UOffsetT) *RewardCoinRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RewardCoinRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RewardCoinRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RewardCoinRequest) UserId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RewardCoinRequest) MutateUserId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *RewardCoinRequest) MahjongType() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RewardCoinRequest) MutateMahjongType(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func RewardCoinRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RewardCoinRequestAddUserId(builder *flatbuffers.Builder, userId uint32) {
	builder.PrependUint32Slot(0, userId, 0)
}
func RewardCoinRequestAddMahjongType(builder *flatbuffers.Builder, mahjongType uint32) {
	builder.PrependUint32Slot(1, mahjongType, 0)
}
func RewardCoinRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
