// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SelectServerTerminalResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSelectServerTerminalResponse(buf []byte, offset flatbuffers.UOffsetT) *SelectServerTerminalResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SelectServerTerminalResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SelectServerTerminalResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SelectServerTerminalResponse) Result(obj *CommonResult) *CommonResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CommonResult)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SelectServerTerminalResponse) UserId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SelectServerTerminalResponse) MutateUserId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *SelectServerTerminalResponse) RoomId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SelectServerTerminalResponse) MutateRoomId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *SelectServerTerminalResponse) Ip() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SelectServerTerminalResponse) Port() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SelectServerTerminalResponse) MutatePort(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func SelectServerTerminalResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func SelectServerTerminalResponseAddResult(builder *flatbuffers.Builder, result flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(result), 0)
}
func SelectServerTerminalResponseAddUserId(builder *flatbuffers.Builder, userId uint32) {
	builder.PrependUint32Slot(1, userId, 0)
}
func SelectServerTerminalResponseAddRoomId(builder *flatbuffers.Builder, roomId uint32) {
	builder.PrependUint32Slot(2, roomId, 0)
}
func SelectServerTerminalResponseAddIp(builder *flatbuffers.Builder, ip flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(ip), 0)
}
func SelectServerTerminalResponseAddPort(builder *flatbuffers.Builder, port int32) {
	builder.PrependInt32Slot(4, port, 0)
}
func SelectServerTerminalResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
