// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SelectServerRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSelectServerRequest(buf []byte, offset flatbuffers.UOffsetT) *SelectServerRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SelectServerRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SelectServerRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SelectServerRequest) UserId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SelectServerRequest) MutateUserId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *SelectServerRequest) RoomNum() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SelectServerRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SelectServerRequestAddUserId(builder *flatbuffers.Builder, userId uint32) {
	builder.PrependUint32Slot(0, userId, 0)
}
func SelectServerRequestAddRoomNum(builder *flatbuffers.Builder, roomNum flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(roomNum), 0)
}
func SelectServerRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
