// automatically generated by the FlatBuffers compiler, do not modify

package info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WakePlayResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsWakePlayResponse(buf []byte, offset flatbuffers.UOffsetT) *WakePlayResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WakePlayResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *WakePlayResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WakePlayResponse) Result(obj *CommonResult) *CommonResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CommonResult)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *WakePlayResponse) PlayFlag() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *WakePlayResponse) ShareId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *WakePlayResponse) ShareUserId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *WakePlayResponse) MutateShareUserId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func WakePlayResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func WakePlayResponseAddResult(builder *flatbuffers.Builder, result flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(result), 0)
}
func WakePlayResponseAddPlayFlag(builder *flatbuffers.Builder, playFlag flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(playFlag), 0)
}
func WakePlayResponseAddShareId(builder *flatbuffers.Builder, shareId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(shareId), 0)
}
func WakePlayResponseAddShareUserId(builder *flatbuffers.Builder, shareUserId uint32) {
	builder.PrependUint32Slot(3, shareUserId, 0)
}
func WakePlayResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
