# 日志级别
log_level = 1
# 机器人加入保底时间 单位:秒
join_interval_base = 0
# 机器人加入随机时间 [0, v) 单位:秒
join_interval_rand = 1
# 机器人加入根据时间段偏移时间 单位:秒
join_interver_times = [1,3,5,7,9,9,7,5,3,2,2,2,2,1,1,1,2,2,1,0,0,0,0,0]
# 排位赛段位额外时间 单位:秒
join_interver_grades = [0, 0, 1, 3, 5, 8]
# 机器人准备间隔时间范围, 单位:毫秒
prepare_interval = [2000, 7000]
# 机器人胡牌间隔时间, 单位:毫秒
win_interval = 1000
# 机器人定缺间隔时间范围, 单位:毫秒
lack_interval = [1500, 7000]
# 其他决策间隔时间范围,[概率, 最短间隔, 最大间隔], 单位: 毫秒
reply_interval = [[70, 800, 1500],[25, 1500, 3000],[4, 3000, 5000],[1, 5000, 8000]]

# 机器人消息概率
chat_rate = 5
# 机器人消息发送间隔,即多长时间内，最多发送一次, 单位:秒
chat_interval = 60
# 机器人消息发送检测时间间隔, 单位:秒
chat_check_interval = 20
# 机器人消息id
chat_ids = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,28,30,107,108,109,105,106]

# 机器人“催”的概率
urge_rate = 3
# 机器人"催"时间间隔,单位:秒
urge_interval = 7
# 机器人“催”的消息id
urge_chat_id = 100

# 机器人发送网络间隔,单位:秒
network_interval = [6, 20]