// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamerecord/gamerecord.proto

package pbgamerecord

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GamePlayerInfo struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	BringinIntegral      int32    `protobuf:"varint,3,opt,name=BringinIntegral,proto3" json:"BringinIntegral,omitempty"`
	WinIntegral          int32    `protobuf:"varint,4,opt,name=WinIntegral,proto3" json:"WinIntegral,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamePlayerInfo) Reset()         { *m = GamePlayerInfo{} }
func (m *GamePlayerInfo) String() string { return proto.CompactTextString(m) }
func (*GamePlayerInfo) ProtoMessage()    {}
func (*GamePlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d42389f4cea3718, []int{0}
}

func (m *GamePlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamePlayerInfo.Unmarshal(m, b)
}
func (m *GamePlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamePlayerInfo.Marshal(b, m, deterministic)
}
func (m *GamePlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamePlayerInfo.Merge(m, src)
}
func (m *GamePlayerInfo) XXX_Size() int {
	return xxx_messageInfo_GamePlayerInfo.Size(m)
}
func (m *GamePlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GamePlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GamePlayerInfo proto.InternalMessageInfo

func (m *GamePlayerInfo) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GamePlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GamePlayerInfo) GetBringinIntegral() int32 {
	if m != nil {
		return m.BringinIntegral
	}
	return 0
}

func (m *GamePlayerInfo) GetWinIntegral() int32 {
	if m != nil {
		return m.WinIntegral
	}
	return 0
}

// games -> center
type WriteGameRecordReq struct {
	RoomRecordId         string            `protobuf:"bytes,1,opt,name=RoomRecordId,proto3" json:"RoomRecordId,omitempty"`
	GameId               string            `protobuf:"bytes,2,opt,name=GameId,proto3" json:"GameId,omitempty"`
	RoomType             int32             `protobuf:"varint,3,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	ClubId               int64             `protobuf:"varint,4,opt,name=ClubId,proto3" json:"ClubId,omitempty"`
	RoomId               uint32            `protobuf:"varint,5,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	TotalJuNun           int32             `protobuf:"varint,6,opt,name=TotalJuNun,proto3" json:"TotalJuNun,omitempty"`
	Index                int32             `protobuf:"varint,7,opt,name=Index,proto3" json:"Index,omitempty"`
	GameStartTime        int64             `protobuf:"varint,8,opt,name=GameStartTime,proto3" json:"GameStartTime,omitempty"`
	GameEndTime          int64             `protobuf:"varint,9,opt,name=GameEndTime,proto3" json:"GameEndTime,omitempty"`
	PayType              int32             `protobuf:"varint,10,opt,name=PayType,proto3" json:"PayType,omitempty"`
	PlayerInfos          []*GamePlayerInfo `protobuf:"bytes,11,rep,name=PlayerInfos,proto3" json:"PlayerInfos,omitempty"`
	RePlayData           []byte            `protobuf:"bytes,12,opt,name=RePlayData,proto3" json:"RePlayData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WriteGameRecordReq) Reset()         { *m = WriteGameRecordReq{} }
func (m *WriteGameRecordReq) String() string { return proto.CompactTextString(m) }
func (*WriteGameRecordReq) ProtoMessage()    {}
func (*WriteGameRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d42389f4cea3718, []int{1}
}

func (m *WriteGameRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteGameRecordReq.Unmarshal(m, b)
}
func (m *WriteGameRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteGameRecordReq.Marshal(b, m, deterministic)
}
func (m *WriteGameRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteGameRecordReq.Merge(m, src)
}
func (m *WriteGameRecordReq) XXX_Size() int {
	return xxx_messageInfo_WriteGameRecordReq.Size(m)
}
func (m *WriteGameRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteGameRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_WriteGameRecordReq proto.InternalMessageInfo

func (m *WriteGameRecordReq) GetRoomRecordId() string {
	if m != nil {
		return m.RoomRecordId
	}
	return ""
}

func (m *WriteGameRecordReq) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *WriteGameRecordReq) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *WriteGameRecordReq) GetClubId() int64 {
	if m != nil {
		return m.ClubId
	}
	return 0
}

func (m *WriteGameRecordReq) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *WriteGameRecordReq) GetTotalJuNun() int32 {
	if m != nil {
		return m.TotalJuNun
	}
	return 0
}

func (m *WriteGameRecordReq) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *WriteGameRecordReq) GetGameStartTime() int64 {
	if m != nil {
		return m.GameStartTime
	}
	return 0
}

func (m *WriteGameRecordReq) GetGameEndTime() int64 {
	if m != nil {
		return m.GameEndTime
	}
	return 0
}

func (m *WriteGameRecordReq) GetPayType() int32 {
	if m != nil {
		return m.PayType
	}
	return 0
}

func (m *WriteGameRecordReq) GetPlayerInfos() []*GamePlayerInfo {
	if m != nil {
		return m.PlayerInfos
	}
	return nil
}

func (m *WriteGameRecordReq) GetRePlayData() []byte {
	if m != nil {
		return m.RePlayData
	}
	return nil
}

// 查询房间游戏记录数据请求
type QueryRoomRecordReq struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	QueryType            int32    `protobuf:"varint,2,opt,name=QueryType,proto3" json:"QueryType,omitempty"`
	QueryParam           uint64   `protobuf:"varint,3,opt,name=QueryParam,proto3" json:"QueryParam,omitempty"`
	QueryStartTime       int64    `protobuf:"varint,4,opt,name=QueryStartTime,proto3" json:"QueryStartTime,omitempty"`
	QueryEndTime         int64    `protobuf:"varint,5,opt,name=QueryEndTime,proto3" json:"QueryEndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRoomRecordReq) Reset()         { *m = QueryRoomRecordReq{} }
func (m *QueryRoomRecordReq) String() string { return proto.CompactTextString(m) }
func (*QueryRoomRecordReq) ProtoMessage()    {}
func (*QueryRoomRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d42389f4cea3718, []int{2}
}

func (m *QueryRoomRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRoomRecordReq.Unmarshal(m, b)
}
func (m *QueryRoomRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRoomRecordReq.Marshal(b, m, deterministic)
}
func (m *QueryRoomRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRoomRecordReq.Merge(m, src)
}
func (m *QueryRoomRecordReq) XXX_Size() int {
	return xxx_messageInfo_QueryRoomRecordReq.Size(m)
}
func (m *QueryRoomRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRoomRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRoomRecordReq proto.InternalMessageInfo

func (m *QueryRoomRecordReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *QueryRoomRecordReq) GetQueryType() int32 {
	if m != nil {
		return m.QueryType
	}
	return 0
}

func (m *QueryRoomRecordReq) GetQueryParam() uint64 {
	if m != nil {
		return m.QueryParam
	}
	return 0
}

func (m *QueryRoomRecordReq) GetQueryStartTime() int64 {
	if m != nil {
		return m.QueryStartTime
	}
	return 0
}

func (m *QueryRoomRecordReq) GetQueryEndTime() int64 {
	if m != nil {
		return m.QueryEndTime
	}
	return 0
}

type RoomPlayerInfo struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	WinIntegral          int32    `protobuf:"varint,3,opt,name=WinIntegral,proto3" json:"WinIntegral,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomPlayerInfo) Reset()         { *m = RoomPlayerInfo{} }
func (m *RoomPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*RoomPlayerInfo) ProtoMessage()    {}
func (*RoomPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d42389f4cea3718, []int{3}
}

func (m *RoomPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomPlayerInfo.Unmarshal(m, b)
}
func (m *RoomPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomPlayerInfo.Marshal(b, m, deterministic)
}
func (m *RoomPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomPlayerInfo.Merge(m, src)
}
func (m *RoomPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_RoomPlayerInfo.Size(m)
}
func (m *RoomPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomPlayerInfo proto.InternalMessageInfo

func (m *RoomPlayerInfo) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RoomPlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoomPlayerInfo) GetWinIntegral() int32 {
	if m != nil {
		return m.WinIntegral
	}
	return 0
}

// 房间记录
type RoomRecord struct {
	RoomRecordId         string            `protobuf:"bytes,1,opt,name=RoomRecordId,proto3" json:"RoomRecordId,omitempty"`
	GameStartTime        int64             `protobuf:"varint,2,opt,name=GameStartTime,proto3" json:"GameStartTime,omitempty"`
	RoomId               uint32            `protobuf:"varint,3,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	GameId               string            `protobuf:"bytes,4,opt,name=GameId,proto3" json:"GameId,omitempty"`
	RoomType             int32             `protobuf:"varint,5,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	TotalJuNun           int32             `protobuf:"varint,6,opt,name=TotalJuNun,proto3" json:"TotalJuNun,omitempty"`
	PayType              int32             `protobuf:"varint,7,opt,name=PayType,proto3" json:"PayType,omitempty"`
	ClubId               int64             `protobuf:"varint,8,opt,name=ClubId,proto3" json:"ClubId,omitempty"`
	GamePlayers          []*RoomPlayerInfo `protobuf:"bytes,9,rep,name=GamePlayers,proto3" json:"GamePlayers,omitempty"`
	GameRecordIds        []string          `protobuf:"bytes,10,rep,name=GameRecordIds,proto3" json:"GameRecordIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RoomRecord) Reset()         { *m = RoomRecord{} }
func (m *RoomRecord) String() string { return proto.CompactTextString(m) }
func (*RoomRecord) ProtoMessage()    {}
func (*RoomRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d42389f4cea3718, []int{4}
}

func (m *RoomRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomRecord.Unmarshal(m, b)
}
func (m *RoomRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomRecord.Marshal(b, m, deterministic)
}
func (m *RoomRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomRecord.Merge(m, src)
}
func (m *RoomRecord) XXX_Size() int {
	return xxx_messageInfo_RoomRecord.Size(m)
}
func (m *RoomRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomRecord.DiscardUnknown(m)
}

var xxx_messageInfo_RoomRecord proto.InternalMessageInfo

func (m *RoomRecord) GetRoomRecordId() string {
	if m != nil {
		return m.RoomRecordId
	}
	return ""
}

func (m *RoomRecord) GetGameStartTime() int64 {
	if m != nil {
		return m.GameStartTime
	}
	return 0
}

func (m *RoomRecord) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomRecord) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *RoomRecord) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *RoomRecord) GetTotalJuNun() int32 {
	if m != nil {
		return m.TotalJuNun
	}
	return 0
}

func (m *RoomRecord) GetPayType() int32 {
	if m != nil {
		return m.PayType
	}
	return 0
}

func (m *RoomRecord) GetClubId() int64 {
	if m != nil {
		return m.ClubId
	}
	return 0
}

func (m *RoomRecord) GetGamePlayers() []*RoomPlayerInfo {
	if m != nil {
		return m.GamePlayers
	}
	return nil
}

func (m *RoomRecord) GetGameRecordIds() []string {
	if m != nil {
		return m.GameRecordIds
	}
	return nil
}

// 查询房间游戏记录数据回应
type QueryRoomRecordRsp struct {
	Error                int32         `protobuf:"varint,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Datas                []*RoomRecord `protobuf:"bytes,2,rep,name=Datas,proto3" json:"Datas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueryRoomRecordRsp) Reset()         { *m = QueryRoomRecordRsp{} }
func (m *QueryRoomRecordRsp) String() string { return proto.CompactTextString(m) }
func (*QueryRoomRecordRsp) ProtoMessage()    {}
func (*QueryRoomRecordRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d42389f4cea3718, []int{5}
}

func (m *QueryRoomRecordRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRoomRecordRsp.Unmarshal(m, b)
}
func (m *QueryRoomRecordRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRoomRecordRsp.Marshal(b, m, deterministic)
}
func (m *QueryRoomRecordRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRoomRecordRsp.Merge(m, src)
}
func (m *QueryRoomRecordRsp) XXX_Size() int {
	return xxx_messageInfo_QueryRoomRecordRsp.Size(m)
}
func (m *QueryRoomRecordRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRoomRecordRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRoomRecordRsp proto.InternalMessageInfo

func (m *QueryRoomRecordRsp) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *QueryRoomRecordRsp) GetDatas() []*RoomRecord {
	if m != nil {
		return m.Datas
	}
	return nil
}

// 查询游戏记录请求
type QueryGameRecordReq struct {
	GameRecordIds        []string `protobuf:"bytes,1,rep,name=GameRecordIds,proto3" json:"GameRecordIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGameRecordReq) Reset()         { *m = QueryGameRecordReq{} }
func (m *QueryGameRecordReq) String() string { return proto.CompactTextString(m) }
func (*QueryGameRecordReq) ProtoMessage()    {}
func (*QueryGameRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d42389f4cea3718, []int{6}
}

func (m *QueryGameRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGameRecordReq.Unmarshal(m, b)
}
func (m *QueryGameRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGameRecordReq.Marshal(b, m, deterministic)
}
func (m *QueryGameRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGameRecordReq.Merge(m, src)
}
func (m *QueryGameRecordReq) XXX_Size() int {
	return xxx_messageInfo_QueryGameRecordReq.Size(m)
}
func (m *QueryGameRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGameRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGameRecordReq proto.InternalMessageInfo

func (m *QueryGameRecordReq) GetGameRecordIds() []string {
	if m != nil {
		return m.GameRecordIds
	}
	return nil
}

// 房间记录
type GameRecord struct {
	GameRecordId         string            `protobuf:"bytes,1,opt,name=GameRecordId,proto3" json:"GameRecordId,omitempty"`
	GameId               string            `protobuf:"bytes,2,opt,name=GameId,proto3" json:"GameId,omitempty"`
	RoomType             int32             `protobuf:"varint,3,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	ClubId               int64             `protobuf:"varint,4,opt,name=ClubId,proto3" json:"ClubId,omitempty"`
	RoomId               uint32            `protobuf:"varint,5,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	Index                int32             `protobuf:"varint,6,opt,name=Index,proto3" json:"Index,omitempty"`
	GameStartTime        int64             `protobuf:"varint,7,opt,name=GameStartTime,proto3" json:"GameStartTime,omitempty"`
	GameEndTime          int64             `protobuf:"varint,8,opt,name=GameEndTime,proto3" json:"GameEndTime,omitempty"`
	GamePlayers          []*GamePlayerInfo `protobuf:"bytes,9,rep,name=GamePlayers,proto3" json:"GamePlayers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GameRecord) Reset()         { *m = GameRecord{} }
func (m *GameRecord) String() string { return proto.CompactTextString(m) }
func (*GameRecord) ProtoMessage()    {}
func (*GameRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d42389f4cea3718, []int{7}
}

func (m *GameRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameRecord.Unmarshal(m, b)
}
func (m *GameRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameRecord.Marshal(b, m, deterministic)
}
func (m *GameRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameRecord.Merge(m, src)
}
func (m *GameRecord) XXX_Size() int {
	return xxx_messageInfo_GameRecord.Size(m)
}
func (m *GameRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_GameRecord.DiscardUnknown(m)
}

var xxx_messageInfo_GameRecord proto.InternalMessageInfo

func (m *GameRecord) GetGameRecordId() string {
	if m != nil {
		return m.GameRecordId
	}
	return ""
}

func (m *GameRecord) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *GameRecord) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *GameRecord) GetClubId() int64 {
	if m != nil {
		return m.ClubId
	}
	return 0
}

func (m *GameRecord) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *GameRecord) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *GameRecord) GetGameStartTime() int64 {
	if m != nil {
		return m.GameStartTime
	}
	return 0
}

func (m *GameRecord) GetGameEndTime() int64 {
	if m != nil {
		return m.GameEndTime
	}
	return 0
}

func (m *GameRecord) GetGamePlayers() []*GamePlayerInfo {
	if m != nil {
		return m.GamePlayers
	}
	return nil
}

// 查询游戏记录请求
type QueryGameRecordRsp struct {
	Error                int32         `protobuf:"varint,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Records              []*GameRecord `protobuf:"bytes,2,rep,name=Records,proto3" json:"Records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueryGameRecordRsp) Reset()         { *m = QueryGameRecordRsp{} }
func (m *QueryGameRecordRsp) String() string { return proto.CompactTextString(m) }
func (*QueryGameRecordRsp) ProtoMessage()    {}
func (*QueryGameRecordRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d42389f4cea3718, []int{8}
}

func (m *QueryGameRecordRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGameRecordRsp.Unmarshal(m, b)
}
func (m *QueryGameRecordRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGameRecordRsp.Marshal(b, m, deterministic)
}
func (m *QueryGameRecordRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGameRecordRsp.Merge(m, src)
}
func (m *QueryGameRecordRsp) XXX_Size() int {
	return xxx_messageInfo_QueryGameRecordRsp.Size(m)
}
func (m *QueryGameRecordRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGameRecordRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGameRecordRsp proto.InternalMessageInfo

func (m *QueryGameRecordRsp) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *QueryGameRecordRsp) GetRecords() []*GameRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

// 查询游戏复盘数据请求
type QueryGameRePlaydReq struct {
	GameRecordIds        string   `protobuf:"bytes,1,opt,name=GameRecordIds,proto3" json:"GameRecordIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGameRePlaydReq) Reset()         { *m = QueryGameRePlaydReq{} }
func (m *QueryGameRePlaydReq) String() string { return proto.CompactTextString(m) }
func (*QueryGameRePlaydReq) ProtoMessage()    {}
func (*QueryGameRePlaydReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d42389f4cea3718, []int{9}
}

func (m *QueryGameRePlaydReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGameRePlaydReq.Unmarshal(m, b)
}
func (m *QueryGameRePlaydReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGameRePlaydReq.Marshal(b, m, deterministic)
}
func (m *QueryGameRePlaydReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGameRePlaydReq.Merge(m, src)
}
func (m *QueryGameRePlaydReq) XXX_Size() int {
	return xxx_messageInfo_QueryGameRePlaydReq.Size(m)
}
func (m *QueryGameRePlaydReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGameRePlaydReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGameRePlaydReq proto.InternalMessageInfo

func (m *QueryGameRePlaydReq) GetGameRecordIds() string {
	if m != nil {
		return m.GameRecordIds
	}
	return ""
}

type QueryGameRePlaydRsp struct {
	Error                int32    `protobuf:"varint,1,opt,name=Error,proto3" json:"Error,omitempty"`
	RePlayData           []byte   `protobuf:"bytes,2,opt,name=RePlayData,proto3" json:"RePlayData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGameRePlaydRsp) Reset()         { *m = QueryGameRePlaydRsp{} }
func (m *QueryGameRePlaydRsp) String() string { return proto.CompactTextString(m) }
func (*QueryGameRePlaydRsp) ProtoMessage()    {}
func (*QueryGameRePlaydRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d42389f4cea3718, []int{10}
}

func (m *QueryGameRePlaydRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGameRePlaydRsp.Unmarshal(m, b)
}
func (m *QueryGameRePlaydRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGameRePlaydRsp.Marshal(b, m, deterministic)
}
func (m *QueryGameRePlaydRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGameRePlaydRsp.Merge(m, src)
}
func (m *QueryGameRePlaydRsp) XXX_Size() int {
	return xxx_messageInfo_QueryGameRePlaydRsp.Size(m)
}
func (m *QueryGameRePlaydRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGameRePlaydRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGameRePlaydRsp proto.InternalMessageInfo

func (m *QueryGameRePlaydRsp) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *QueryGameRePlaydRsp) GetRePlayData() []byte {
	if m != nil {
		return m.RePlayData
	}
	return nil
}

// 查询俱乐部统计请求
type QueryClubStatisticsReq struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	QueryType            int32    `protobuf:"varint,2,opt,name=QueryType,proto3" json:"QueryType,omitempty"`
	QueryClubId          uint64   `protobuf:"varint,3,opt,name=QueryClubId,proto3" json:"QueryClubId,omitempty"`
	QueryStartTime       int64    `protobuf:"varint,4,opt,name=QueryStartTime,proto3" json:"QueryStartTime,omitempty"`
	QueryEndTime         int64    `protobuf:"varint,5,opt,name=QueryEndTime,proto3" json:"QueryEndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryClubStatisticsReq) Reset()         { *m = QueryClubStatisticsReq{} }
func (m *QueryClubStatisticsReq) String() string { return proto.CompactTextString(m) }
func (*QueryClubStatisticsReq) ProtoMessage()    {}
func (*QueryClubStatisticsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d42389f4cea3718, []int{11}
}

func (m *QueryClubStatisticsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClubStatisticsReq.Unmarshal(m, b)
}
func (m *QueryClubStatisticsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClubStatisticsReq.Marshal(b, m, deterministic)
}
func (m *QueryClubStatisticsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClubStatisticsReq.Merge(m, src)
}
func (m *QueryClubStatisticsReq) XXX_Size() int {
	return xxx_messageInfo_QueryClubStatisticsReq.Size(m)
}
func (m *QueryClubStatisticsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClubStatisticsReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClubStatisticsReq proto.InternalMessageInfo

func (m *QueryClubStatisticsReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *QueryClubStatisticsReq) GetQueryType() int32 {
	if m != nil {
		return m.QueryType
	}
	return 0
}

func (m *QueryClubStatisticsReq) GetQueryClubId() uint64 {
	if m != nil {
		return m.QueryClubId
	}
	return 0
}

func (m *QueryClubStatisticsReq) GetQueryStartTime() int64 {
	if m != nil {
		return m.QueryStartTime
	}
	return 0
}

func (m *QueryClubStatisticsReq) GetQueryEndTime() int64 {
	if m != nil {
		return m.QueryEndTime
	}
	return 0
}

// 统计数据
type StatisticsData struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Statistics           int64    `protobuf:"varint,3,opt,name=Statistics,proto3" json:"Statistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatisticsData) Reset()         { *m = StatisticsData{} }
func (m *StatisticsData) String() string { return proto.CompactTextString(m) }
func (*StatisticsData) ProtoMessage()    {}
func (*StatisticsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d42389f4cea3718, []int{12}
}

func (m *StatisticsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisticsData.Unmarshal(m, b)
}
func (m *StatisticsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisticsData.Marshal(b, m, deterministic)
}
func (m *StatisticsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisticsData.Merge(m, src)
}
func (m *StatisticsData) XXX_Size() int {
	return xxx_messageInfo_StatisticsData.Size(m)
}
func (m *StatisticsData) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisticsData.DiscardUnknown(m)
}

var xxx_messageInfo_StatisticsData proto.InternalMessageInfo

func (m *StatisticsData) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *StatisticsData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StatisticsData) GetStatistics() int64 {
	if m != nil {
		return m.Statistics
	}
	return 0
}

// 查询俱乐部统计回应
type QueryClubStatisticsRsp struct {
	Error                int32             `protobuf:"varint,1,opt,name=Error,proto3" json:"Error,omitempty"`
	StatisticsDatas      []*StatisticsData `protobuf:"bytes,8,rep,name=StatisticsDatas,proto3" json:"StatisticsDatas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryClubStatisticsRsp) Reset()         { *m = QueryClubStatisticsRsp{} }
func (m *QueryClubStatisticsRsp) String() string { return proto.CompactTextString(m) }
func (*QueryClubStatisticsRsp) ProtoMessage()    {}
func (*QueryClubStatisticsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d42389f4cea3718, []int{13}
}

func (m *QueryClubStatisticsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClubStatisticsRsp.Unmarshal(m, b)
}
func (m *QueryClubStatisticsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClubStatisticsRsp.Marshal(b, m, deterministic)
}
func (m *QueryClubStatisticsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClubStatisticsRsp.Merge(m, src)
}
func (m *QueryClubStatisticsRsp) XXX_Size() int {
	return xxx_messageInfo_QueryClubStatisticsRsp.Size(m)
}
func (m *QueryClubStatisticsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClubStatisticsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClubStatisticsRsp proto.InternalMessageInfo

func (m *QueryClubStatisticsRsp) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *QueryClubStatisticsRsp) GetStatisticsDatas() []*StatisticsData {
	if m != nil {
		return m.StatisticsDatas
	}
	return nil
}

func init() {
	proto.RegisterType((*GamePlayerInfo)(nil), "pbgamerecord.GamePlayerInfo")
	proto.RegisterType((*WriteGameRecordReq)(nil), "pbgamerecord.WriteGameRecordReq")
	proto.RegisterType((*QueryRoomRecordReq)(nil), "pbgamerecord.QueryRoomRecordReq")
	proto.RegisterType((*RoomPlayerInfo)(nil), "pbgamerecord.RoomPlayerInfo")
	proto.RegisterType((*RoomRecord)(nil), "pbgamerecord.RoomRecord")
	proto.RegisterType((*QueryRoomRecordRsp)(nil), "pbgamerecord.QueryRoomRecordRsp")
	proto.RegisterType((*QueryGameRecordReq)(nil), "pbgamerecord.QueryGameRecordReq")
	proto.RegisterType((*GameRecord)(nil), "pbgamerecord.GameRecord")
	proto.RegisterType((*QueryGameRecordRsp)(nil), "pbgamerecord.QueryGameRecordRsp")
	proto.RegisterType((*QueryGameRePlaydReq)(nil), "pbgamerecord.QueryGameRePlaydReq")
	proto.RegisterType((*QueryGameRePlaydRsp)(nil), "pbgamerecord.QueryGameRePlaydRsp")
	proto.RegisterType((*QueryClubStatisticsReq)(nil), "pbgamerecord.QueryClubStatisticsReq")
	proto.RegisterType((*StatisticsData)(nil), "pbgamerecord.StatisticsData")
	proto.RegisterType((*QueryClubStatisticsRsp)(nil), "pbgamerecord.QueryClubStatisticsRsp")
}

func init() { proto.RegisterFile("gamerecord/gamerecord.proto", fileDescriptor_7d42389f4cea3718) }

var fileDescriptor_7d42389f4cea3718 = []byte{
	// 691 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdf, 0x6a, 0xd4, 0x4e,
	0x14, 0x26, 0xc9, 0x66, 0xff, 0x9c, 0xdd, 0x6e, 0x61, 0x7e, 0x3f, 0xca, 0xa0, 0xa5, 0x84, 0x20,
	0x92, 0xab, 0x15, 0xea, 0x9d, 0x42, 0x2f, 0xd4, 0x2a, 0x51, 0x28, 0x75, 0x5a, 0x29, 0x88, 0x14,
	0xa6, 0xcd, 0x58, 0x16, 0x76, 0x93, 0x75, 0x92, 0x15, 0xf7, 0x0d, 0x7c, 0x00, 0x9f, 0xc4, 0x0b,
	0xaf, 0x7c, 0x12, 0x9f, 0x46, 0xe6, 0x24, 0xdb, 0x99, 0xd9, 0x24, 0x5a, 0x8b, 0x78, 0xb7, 0xe7,
	0xcb, 0x39, 0x67, 0xbe, 0x39, 0xdf, 0x37, 0x87, 0x85, 0xbb, 0x57, 0x7c, 0x2e, 0xa4, 0xb8, 0xcc,
	0x64, 0xf2, 0x40, 0xff, 0x9c, 0x2c, 0x64, 0x56, 0x64, 0x64, 0xb4, 0xb8, 0xd0, 0x58, 0xf8, 0xd9,
	0x81, 0xf1, 0x0b, 0x3e, 0x17, 0xc7, 0x33, 0xbe, 0x12, 0x32, 0x4e, 0xdf, 0x67, 0x64, 0x07, 0xba,
	0x6f, 0x72, 0x21, 0xe3, 0x84, 0x3a, 0x81, 0x13, 0x75, 0x58, 0x15, 0x11, 0x02, 0x9d, 0x23, 0x3e,
	0x17, 0xd4, 0x0d, 0x9c, 0x68, 0xc0, 0xf0, 0x37, 0x89, 0x60, 0xfb, 0x89, 0x9c, 0xa6, 0x57, 0xd3,
	0x34, 0x4e, 0x0b, 0x71, 0x25, 0xf9, 0x8c, 0x7a, 0x81, 0x13, 0xf9, 0x6c, 0x13, 0x26, 0x01, 0x0c,
	0xcf, 0x8c, 0xac, 0x0e, 0x66, 0x99, 0x50, 0xf8, 0xc5, 0x03, 0x72, 0x26, 0xa7, 0x85, 0x50, 0x7c,
	0x18, 0xd2, 0x63, 0xe2, 0x03, 0x09, 0x61, 0xc4, 0xb2, 0x6c, 0x5e, 0x02, 0x15, 0xa9, 0x01, 0xb3,
	0x30, 0x45, 0x59, 0x15, 0xc5, 0x49, 0x45, 0xae, 0x8a, 0xc8, 0x1d, 0xe8, 0xab, 0xbc, 0xd3, 0xd5,
	0x42, 0x54, 0xbc, 0xae, 0x63, 0x55, 0xf3, 0x74, 0xb6, 0xbc, 0x88, 0x13, 0xe4, 0xe2, 0xb1, 0x2a,
	0x52, 0xb8, 0xca, 0x89, 0x13, 0xea, 0x07, 0x4e, 0xb4, 0xc5, 0xaa, 0x88, 0xec, 0x01, 0x9c, 0x66,
	0x05, 0x9f, 0xbd, 0x5c, 0x1e, 0x2d, 0x53, 0xda, 0xc5, 0x6e, 0x06, 0x42, 0xfe, 0x07, 0x3f, 0x4e,
	0x13, 0xf1, 0x89, 0xf6, 0xf0, 0x53, 0x19, 0x90, 0x7b, 0xb0, 0xa5, 0xb8, 0x9c, 0x14, 0x5c, 0x16,
	0xa7, 0xd3, 0xb9, 0xa0, 0x7d, 0x3c, 0xcc, 0x06, 0xd5, 0x70, 0x14, 0x70, 0x98, 0x26, 0x98, 0x33,
	0xc0, 0x1c, 0x13, 0x22, 0x14, 0x7a, 0xc7, 0x7c, 0x85, 0x17, 0x01, 0xec, 0xbf, 0x0e, 0xc9, 0x01,
	0x0c, 0xb5, 0x78, 0x39, 0x1d, 0x06, 0x5e, 0x34, 0xdc, 0xdf, 0x9d, 0x98, 0x2a, 0x4f, 0x6c, 0x85,
	0x99, 0x59, 0xa0, 0xee, 0xc5, 0xf0, 0xe3, 0x33, 0x5e, 0x70, 0x3a, 0x0a, 0x9c, 0x68, 0xc4, 0x0c,
	0x24, 0xfc, 0xe6, 0x00, 0x79, 0xbd, 0x14, 0x72, 0xa5, 0x27, 0xae, 0x64, 0x69, 0x73, 0xc9, 0x2e,
	0x0c, 0x30, 0x1b, 0xa9, 0xba, 0x48, 0x55, 0x03, 0xea, 0x30, 0x0c, 0x8e, 0xb9, 0xe4, 0x73, 0x94,
	0xa4, 0xc3, 0x0c, 0x84, 0xdc, 0x87, 0x31, 0x46, 0x7a, 0x5e, 0xa5, 0x38, 0x1b, 0xa8, 0x32, 0x05,
	0x22, 0xeb, 0x89, 0xf9, 0x98, 0x65, 0x61, 0xe1, 0x39, 0x8c, 0x15, 0xe5, 0x5b, 0x3a, 0x7b, 0xc3,
	0xaf, 0x5e, 0xdd, 0xaf, 0x3f, 0x5c, 0x00, 0x3d, 0x93, 0x1b, 0xf9, 0xb4, 0xe6, 0x06, 0xb7, 0xc9,
	0x0d, 0xda, 0x81, 0x9e, 0xe5, 0x40, 0xed, 0xf2, 0x4e, 0xab, 0xcb, 0xfd, 0x0d, 0x97, 0xff, 0xce,
	0xb5, 0x86, 0xaf, 0x7a, 0xb6, 0xaf, 0xf4, 0xfb, 0xe8, 0x5b, 0xef, 0xe3, 0xa0, 0xf4, 0x6a, 0x39,
	0xd6, 0x9c, 0x0e, 0x9a, 0xfc, 0x66, 0xcf, 0x9d, 0x99, 0x05, 0xeb, 0x19, 0xac, 0x67, 0x92, 0x53,
	0x08, 0xbc, 0x68, 0xc0, 0x6c, 0x30, 0x7c, 0x5b, 0x37, 0x5d, 0xbe, 0x50, 0x6f, 0xec, 0x50, 0xca,
	0x4c, 0xe2, 0x70, 0x7d, 0x56, 0x06, 0x64, 0x02, 0xbe, 0x72, 0x6a, 0x4e, 0x5d, 0xe4, 0x42, 0xeb,
	0x5c, 0xaa, 0x0e, 0x65, 0x5a, 0xf8, 0xa8, 0xea, 0x6d, 0xef, 0x99, 0x1a, 0x2f, 0xa7, 0x89, 0xd7,
	0x57, 0x17, 0x40, 0x23, 0x4a, 0x74, 0xf3, 0xfb, 0x5a, 0x74, 0x13, 0xfb, 0x27, 0xcb, 0xe9, 0x7a,
	0xf9, 0x74, 0x7f, 0xb9, 0x7c, 0x7a, 0x37, 0x58, 0x3e, 0xfd, 0xfa, 0xf2, 0xb9, 0x89, 0xe4, 0x9b,
	0x2b, 0xc6, 0x28, 0x08, 0xcf, 0xeb, 0x03, 0x6f, 0x15, 0x73, 0x1f, 0x7a, 0x65, 0x4a, 0x8b, 0x9c,
	0x46, 0x8f, 0x75, 0x62, 0xf8, 0x18, 0xfe, 0x33, 0xfa, 0xab, 0x53, 0xdb, 0x14, 0x75, 0xea, 0x8a,
	0xbe, 0x6a, 0x28, 0x6e, 0x65, 0x67, 0x2f, 0x4b, 0xb7, 0xb6, 0x2c, 0xbf, 0x3b, 0xb0, 0x83, 0xdd,
	0x94, 0x5e, 0x27, 0x05, 0x2f, 0xa6, 0x79, 0x31, 0xbd, 0xcc, 0x6f, 0xbf, 0x30, 0x03, 0x18, 0x5e,
	0xf7, 0xab, 0x16, 0x42, 0x87, 0x99, 0xd0, 0x5f, 0x5d, 0x99, 0xef, 0x60, 0xac, 0x49, 0xab, 0x0b,
	0xfd, 0xd1, 0xca, 0xdc, 0x03, 0xd0, 0xd5, 0x48, 0xd5, 0x63, 0x06, 0x12, 0x7e, 0x6c, 0x9e, 0x4d,
	0xeb, 0xb0, 0x9f, 0xc3, 0xb6, 0xcd, 0x26, 0xa7, 0xfd, 0x26, 0xeb, 0xd9, 0x49, 0x6c, 0xb3, 0xe8,
	0xa2, 0x8b, 0x7f, 0x7c, 0x1e, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x22, 0x53, 0xd3, 0xc9, 0x17,
	0x09, 0x00, 0x00,
}
