package config

// ScoreTypeToFrontMap 服务端scoreType与客户端的对应关系
var ScoreTypeToFrontMap = map[int]int{
	// 积分类型
	SCORE_TYPE_KONG_EXPOSED:      FRONT_SCORE_TYPE_KONG_EXPOSED,
	-SCORE_TYPE_KONG_EXPOSED:     FRONT_SCORE_TYPE_DIAN_KONG,
	SCORE_TYPE_KONG_DARK:         FRONT_SCORE_TYPE_KONG_DARK,
	-SCORE_TYPE_KONG_DARK:        FRONT_SCORE_TYPE_KONG_DARK_LOSER,
	SCORE_TYPE_KONG_TURN:         FRONT_SCORE_TYPE_KONG_TURN,
	-SCORE_TYPE_KONG_TURN:        FRONT_SCORE_TYPE_KONG_TURN_LOSER,
	SCORE_TYPE_KONG_QIANG:        FRONT_SCORE_TYPE_QIANG,
	-SCORE_TYPE_KONG_QIANG:       FRONT_SCORE_TYPE_BEI_QIANG,
	SCORE_TYPE_TIANHU:            FRONT_SCORE_TYPE_TIANHU,
	-SCORE_TYPE_TIANHU:           FRONT_SCORE_TYPE_TIANHU_LOSER,
	SCORE_TYPE_DIHU:              FRONT_SCORE_TYPE_DIHU,
	-SCORE_TYPE_DIHU:             FRONT_SCORE_TYPE_DIHU_LOSER,
	SCORE_TYPE_BAOTING:           FRONT_SCORE_TYPE_BAOTING,
	-SCORE_TYPE_BAOTING:          FRONT_SCORE_TYPE_BAOTING_LOSER,
	SCORE_TYPE_QING:              FRONT_SCORE_TYPE_QING,
	-SCORE_TYPE_QING:             FRONT_SCORE_TYPE_QING_LOSER,
	SCORE_TYPE_FULL_CHIKEN:       FRONT_SCORE_TYPE_FULL_CHIKEN,
	-SCORE_TYPE_FULL_CHIKEN:      FRONT_SCORE_TYPE_FULL_CHIKEN_LOSER,
	SCORE_TYPE_SHUANGLONG_QIDUI:  FRONT_SCORE_TYPE_SHUANGLONGQIDUI,
	-SCORE_TYPE_SHUANGLONG_QIDUI: FRONT_SCORE_TYPE_SHUANGLONGQIDUI_LOSER,
	SCORE_TYPE_LONGQIDUI:         FRONT_SCORE_TYPE_LONGQIDUI,
	-SCORE_TYPE_LONGQIDUI:        FRONT_SCORE_TYPE_LONGQIDUI_LOSER,
	SCORE_TYPE_QIDUI:             FRONT_SCORE_TYPE_QIDUI,
	-SCORE_TYPE_QIDUI:            FRONT_SCORE_TYPE_QIDUI_LOSER,
	SCORE_TYPE_DIQIDUI:           FRONT_SCORE_TYPE_DIQIDUI,
	-SCORE_TYPE_DIQIDUI:          FRONT_SCORE_TYPE_DIQIDUI_LOSER,
	SCORE_TYPE_DANDIAO:           FRONT_SCORE_TYPE_DANDIAO,
	-SCORE_TYPE_DANDIAO:          FRONT_SCORE_TYPE_DANDIAO_LOSER,
	SCORE_TYPE_REPAO_EXPOSED:     FRONT_SCORE_TYPE_JIE_REPAO_KONG_EXPOSED,
	-SCORE_TYPE_REPAO_EXPOSED:    FRONT_SCORE_TYPE_REPAO_KONG_EXPOSED,
	SCORE_TYPE_REPAO_DARK:        FRONT_SCORE_TYPE_JIE_REPAO,
	-SCORE_TYPE_REPAO_DARK:       FRONT_SCORE_TYPE_REPAO,
	SCORE_TYPE_DADUI:             FRONT_SCORE_TYPE_DADUI,
	-SCORE_TYPE_DADUI:            FRONT_SCORE_TYPE_DADUI_LOSER,
	SCORE_TYPE_BAO_KONG:          FRONT_SCORE_TYPE_BAO_KONG_SHOURU,
	-SCORE_TYPE_BAO_KONG:         FRONT_SCORE_TYPE_BAO_KONG,
	SCORE_TYPE_BAO_QUE:           FRONT_SCORE_TYPE_CHAQUE_SHOURU,
	-SCORE_TYPE_BAO_QUE:          FRONT_SCORE_TYPE_CHAQUE,
	SCORE_TYPE_QING_EXTRA:        FRONT_SCORE_TYPE_QING_EXTRA,
	-SCORE_TYPE_QING_EXTRA:       FRONT_SCORE_TYPE_QING_EXTRA_LOSER,
	SCORE_TYPE_REPAO_TURN:        FRONT_SCORE_TYPE_JIE_REPAO,
	-SCORE_TYPE_REPAO_TURN:       FRONT_SCORE_TYPE_REPAO,
	SCORE_TYPE_HEPU_QIDUI:        FRONT_SCORE_TYPE_HEPU_QIDIU,
	-SCORE_TYPE_HEPU_QIDUI:       FRONT_SCORE_TYPE_HEPU_QIDIU_LOSER,
	SCORE_TYPE_BAO_KONG_DARK:     FRONT_SCORE_TYPE_BAO_KONG_SHOURU,
	-SCORE_TYPE_BAO_KONG_DARK:    FRONT_SCORE_TYPE_BAO_KONG,
	SCORE_TYPE_BAO_KONG_TURN:     FRONT_SCORE_TYPE_BAO_KONG_SHOURU,
	-SCORE_TYPE_BAO_KONG_TURN:    FRONT_SCORE_TYPE_BAO_KONG,
	// 杠上开花
	SCORE_TYPE_KONG_DRAW:             FRONT_SCORE_TYPE_KONG_DRAW,
	-SCORE_TYPE_KONG_DRAW:            FRONT_SCORE_TYPE_KONG_DRAW_LOSER,
	SCORE_TYPE_DAKUANZHANG:           FRONT_SCORE_TYPE_DAKUAN,
	-SCORE_TYPE_DAKUANZHANG:          FRONT_SCORE_TYPE_DAKUAN_LOSER,
	SCORE_TYPE_BIANKADIAO:            FRONT_SCORE_TYPE_BIANKADIAO,
	-SCORE_TYPE_BIANKADIAO:           FRONT_SCORE_TYPE_BIANKADIAO_LOSER,
	SCORE_TYPE_PINGHU:                FRONT_SCORE_TYPE_PINGHU,
	-SCORE_TYPE_PINGHU:               FRONT_SCORE_TYPE_PINGHU_LOSER,
	SCORE_TYPE_PINGHU_ZIMO:           FRONT_SCORE_TYPE_PINGHU_ZIMO,
	-SCORE_TYPE_PINGHU_ZIMO:          FRONT_SCORE_TYPE_PINGHU_ZIMO_LOSER,
	SCORE_TYPE_CONTINUE_DEALER:       FRONT_SCORE_TYPE_ZHUANG,
	-SCORE_TYPE_CONTINUE_DEALER:      FRONT_SCORE_TYPE_ZHUANG_CONTINUE,
	SCORE_TYPE_CONTINUE_DEALER_LOSE:  FRONT_SCORE_TYPE_ZHUANG_XIAZHUANG,
	-SCORE_TYPE_CONTINUE_DEALER_LOSE: FRONT_SCORE_TYPE_XIAZHUANG,
	SCORE_TYPE_SHABAO:                FRONT_SCORE_TYPE_SHABAO,
	-SCORE_TYPE_SHABAO:               FRONT_SCORE_TYPE_BEI_SHABAO,
	SCORE_TYPE_ZIMO:                  FRONT_SCORE_TYPE_ZIMO,
	-SCORE_TYPE_ZIMO:                 FRONT_SCORE_TYPE_ZIMO_LOSER,
	SCORE_TYPE_ZIMO_EXTRA:            FRONT_SCORE_TYPE_ZIMO_EXTRA,
	-SCORE_TYPE_ZIMO_EXTRA:           FRONT_SCORE_TYPE_ZIMO_EXTRA_LOSER,
	// 冲锋鸡
	SCORE_TYPE_CHARGE_KITCHEN:              FRONT_SCORE_TYPE_CHARGE_JI,
	-SCORE_TYPE_CHARGE_KITCHEN:             FRONT_SCORE_TYPE_CHARGE_JI_LOSER,
	SCORE_TYPE_CHARGE_JIN_KITCHEN:          FRONT_SCORE_TYPE_JIN_CHARGE_JI,
	-SCORE_TYPE_CHARGE_JIN_KITCHEN:         FRONT_SCORE_TYPE_JIN_CHARGE_JI_LOSER,
	SCORE_TYPE_CHARGE_JIN_JIN_KITCHEN:      FRONT_SCORE_TYPE_JIN_CHARGE_JI,
	-SCORE_TYPE_CHARGE_JIN_JIN_KITCHEN:     FRONT_SCORE_TYPE_JIN_CHARGE_JI_LOSER,
	SCORE_TYPE_BAO_CHARGE_KITCHEN:          FRONT_SCORE_TYPE_BAOJI_SHOURU,
	-SCORE_TYPE_BAO_CHARGE_KITCHEN:         FRONT_SCORE_TYPE_BAOJI,
	SCORE_TYPE_BAO_CHARGE_JIN_KITCHEN:      FRONT_SCORE_TYPE_BAOJI_SHOURU,
	-SCORE_TYPE_BAO_CHARGE_JIN_KITCHEN:     FRONT_SCORE_TYPE_BAOJI,
	SCORE_TYPE_BAO_CHARGE_JIN_JIN_KITCHEN:  FRONT_SCORE_TYPE_BAOJI_SHOURU,
	-SCORE_TYPE_BAO_CHARGE_JIN_JIN_KITCHEN: FRONT_SCORE_TYPE_BAOJI,
	// 责任鸡
	SCORE_TYPE_RB_KITCHEN:              FRONT_SCORE_TYPE_ZEREN_SHOURU,
	-SCORE_TYPE_RB_KITCHEN:             FRONT_SCORE_TYPE_ZEREN,
	SCORE_TYPE_RB_JIN_KITCHEN:          FRONT_SCORE_TYPE_ZEREN_SHOURU,
	-SCORE_TYPE_RB_JIN_KITCHEN:         FRONT_SCORE_TYPE_ZEREN,
	SCORE_TYPE_RB_JIN_JIN_KITCHEN:      FRONT_SCORE_TYPE_ZEREN_SHOURU,
	-SCORE_TYPE_RB_JIN_JIN_KITCHEN:     FRONT_SCORE_TYPE_ZEREN,
	SCORE_TYPE_BAO_RB_KITCHEN:          FRONT_SCORE_TYPE_ZEREN_SHOURU,
	-SCORE_TYPE_BAO_RB_KITCHEN:         FRONT_SCORE_TYPE_ZEREN,
	SCORE_TYPE_BAO_RB_JIN_KITCHEN:      FRONT_SCORE_TYPE_ZEREN_SHOURU,
	-SCORE_TYPE_BAO_RB_JIN_KITCHEN:     FRONT_SCORE_TYPE_ZEREN,
	SCORE_TYPE_BAO_RB_JIN_JIN_KITCHEN:  FRONT_SCORE_TYPE_ZEREN_SHOURU,
	-SCORE_TYPE_BAO_RB_JIN_JIN_KITCHEN: FRONT_SCORE_TYPE_ZEREN,
	// 冲锋乌骨鸡
	SCORE_TYPE_CHARGE_WUGU_KITCHEN:              FRONT_SCORE_TYPE_CHARGE_WUGU,
	-SCORE_TYPE_CHARGE_WUGU_KITCHEN:             FRONT_SCORE_TYPE_CHARGE_WUGU_LOSER,
	SCORE_TYPE_CHARGE_WUGU_JIN_KITCHEN:          FRONT_SCORE_TYPE_JIN_CHARGE_WUGU,
	-SCORE_TYPE_CHARGE_WUGU_JIN_KITCHEN:         FRONT_SCORE_TYPE_JIN_CHARGE_WUGU_LOSER,
	SCORE_TYPE_CHARGE_WUGU_JIN_JIN_KITCHEN:      FRONT_SCORE_TYPE_JIN_CHARGE_WUGU,
	-SCORE_TYPE_CHARGE_WUGU_JIN_JIN_KITCHEN:     FRONT_SCORE_TYPE_JIN_CHARGE_WUGU_LOSER,
	SCORE_TYPE_BAO_CHARGE_WUGU_KITCHEN:          FRONT_SCORE_TYPE_BAOJI_SHOURU,
	-SCORE_TYPE_BAO_CHARGE_WUGU_KITCHEN:         FRONT_SCORE_TYPE_BAOJI,
	SCORE_TYPE_BAO_CHARGE_WUGU_JIN_KITCHEN:      FRONT_SCORE_TYPE_BAOJI_SHOURU,
	-SCORE_TYPE_BAO_CHARGE_WUGU_JIN_KITCHEN:     FRONT_SCORE_TYPE_BAOJI,
	SCORE_TYPE_BAO_CHARGE_WUGU_JIN_JIN_KITCHEN:  FRONT_SCORE_TYPE_BAOJI_SHOURU,
	-SCORE_TYPE_BAO_CHARGE_WUGU_JIN_JIN_KITCHEN: FRONT_SCORE_TYPE_BAOJI,
	// 幺鸡
	SCORE_TYPE_KITCHEN:              FRONT_SCORE_TYPE_JI,
	-SCORE_TYPE_KITCHEN:             FRONT_SCORE_TYPE_JI_LOSER,
	SCORE_TYPE_JIN_KITCHEN:          FRONT_SCORE_TYPE_JIN_JI,
	-SCORE_TYPE_JIN_KITCHEN:         FRONT_SCORE_TYPE_JIN_JI_LOSER,
	SCORE_TYPE_JIN_JIN_KITCHEN:      FRONT_SCORE_TYPE_JIN_JI,
	-SCORE_TYPE_JIN_JIN_KITCHEN:     FRONT_SCORE_TYPE_JIN_JI_LOSER,
	SCORE_TYPE_BAO_KITCHEN:          FRONT_SCORE_TYPE_BAOJI_SHOURU,
	-SCORE_TYPE_BAO_KITCHEN:         FRONT_SCORE_TYPE_BAOJI,
	SCORE_TYPE_BAO_JIN_KITCHEN:      FRONT_SCORE_TYPE_BAOJI_SHOURU,
	-SCORE_TYPE_BAO_JIN_KITCHEN:     FRONT_SCORE_TYPE_BAOJI,
	SCORE_TYPE_BAO_JIN_JIN_KITCHEN:  FRONT_SCORE_TYPE_BAOJI_SHOURU,
	-SCORE_TYPE_BAO_JIN_JIN_KITCHEN: FRONT_SCORE_TYPE_BAOJI,
	// 银鸡
	SCORE_TYPE_SILVER_CHIKEN:         FRONT_SCORE_TYPE_SILVER_CHIKEN,       // 银鸡
	-SCORE_TYPE_SILVER_CHIKEN:        FRONT_SCORE_TYPE_SILVER_CHIKEN_LOSER, // 银鸡
	SCORE_TYPE_SILVER_DOUBLE_CHIKEN:  FRONT_SCORE_TYPE_SILVER_CHIKEN,       // 银鸡（双倍）
	-SCORE_TYPE_SILVER_DOUBLE_CHIKEN: FRONT_SCORE_TYPE_SILVER_CHIKEN_LOSER, // 银鸡（双倍）
	SCORE_TYPE_SILVER_TRIPLE_CHIKEN:  FRONT_SCORE_TYPE_SILVER_CHIKEN,       // 银鸡（三倍）
	-SCORE_TYPE_SILVER_TRIPLE_CHIKEN: FRONT_SCORE_TYPE_SILVER_CHIKEN_LOSER, // 银鸡（三倍）
	// 乌骨鸡
	SCORE_TYPE_WUGU_KITCHEN:              FRONT_SCORE_TYPE_WUGU,
	-SCORE_TYPE_WUGU_KITCHEN:             FRONT_SCORE_TYPE_WUGU_LOSER,
	SCORE_TYPE_WUGU_JIN_KITCHEN:          FRONT_SCORE_TYPE_JIN_WUGU,
	-SCORE_TYPE_WUGU_JIN_KITCHEN:         FRONT_SCORE_TYPE_JIN_WUGU_LOSER,
	SCORE_TYPE_WUGU_JIN_JIN_KITCHEN:      FRONT_SCORE_TYPE_JIN_WUGU,
	-SCORE_TYPE_WUGU_JIN_JIN_KITCHEN:     FRONT_SCORE_TYPE_JIN_WUGU_LOSER,
	SCORE_TYPE_BAO_WUGU_KITCHEN:          FRONT_SCORE_TYPE_BAOJI_SHOURU,
	-SCORE_TYPE_BAO_WUGU_KITCHEN:         FRONT_SCORE_TYPE_BAOJI,
	SCORE_TYPE_BAO_WUGU_JIN_KITCHEN:      FRONT_SCORE_TYPE_BAOJI_SHOURU,
	-SCORE_TYPE_BAO_WUGU_JIN_KITCHEN:     FRONT_SCORE_TYPE_BAOJI,
	SCORE_TYPE_BAO_WUGU_JIN_JIN_KITCHEN:  FRONT_SCORE_TYPE_BAOJI_SHOURU,
	-SCORE_TYPE_BAO_WUGU_JIN_JIN_KITCHEN: FRONT_SCORE_TYPE_BAOJI,
	// 钻石鸡
	SCORE_TYPE_DIAMOND_KITCHEN:         FRONT_SCORE_TYPE_DIAMOND,       // 钻石鸡
	-SCORE_TYPE_DIAMOND_KITCHEN:        FRONT_SCORE_TYPE_DIAMOND_LOSER, // 钻石鸡
	SCORE_TYPE_DIAMOND_DOUBLE_KITCHEN:  FRONT_SCORE_TYPE_DIAMOND,       // 钻石鸡（双倍）
	-SCORE_TYPE_DIAMOND_DOUBLE_KITCHEN: FRONT_SCORE_TYPE_DIAMOND_LOSER, // 钻石鸡（双倍）

	SCORE_TYPE_FB_KITCHEN:  FRONT_SCORE_TYPE_FB,           // 前后鸡
	-SCORE_TYPE_FB_KITCHEN: FRONT_SCORE_TYPE_FB_LOSER,     // 前后鸡
	SCORE_TYPE_FP_KITCHEN:  FRONT_SCORE_TYPE_FANPAI,       // 翻牌鸡
	-SCORE_TYPE_FP_KITCHEN: FRONT_SCORE_TYPE_FANPAI_LOSER, // 翻牌鸡
	SCORE_TYPE_UD_KITCHEN:  FRONT_SCORE_TYPE_UD,           // 上下鸡
	-SCORE_TYPE_UD_KITCHEN: FRONT_SCORE_TYPE_UD_LOSER,     // 上下鸡

	SCORE_TYPE_B_KITCHEN:   FRONT_SCORE_TYPE_BEN,            // 本鸡
	-SCORE_TYPE_B_KITCHEN:  FRONT_SCORE_TYPE_BEN_LOSER,      // 本鸡
	SCORE_TYPE_GT_KITCHEN:  FRONT_SCORE_TYPE_TUMBLING,       // 滚筒鸡
	-SCORE_TYPE_GT_KITCHEN: FRONT_SCORE_TYPE_TUMBLING_LOSER, // 滚筒鸡
	SCORE_TYPE_XQ_KITCHEN:  FRONT_SCORE_TYPE_XQ,             // 星期鸡
	-SCORE_TYPE_XQ_KITCHEN: FRONT_SCORE_TYPE_XQ_LOSER,       // 星期鸡

	// 站鸡
	SCORE_TYPE_STAND_KITCHEN:              FRONT_SCORE_TYPE_STAND_KITCHEN,           // 站鸡
	-SCORE_TYPE_STAND_KITCHEN:             FRONT_SCORE_TYPE_STAND_KITCHEN_LOSER,     // 站鸡
	SCORE_TYPE_STAND_JIN_KITCHEN:          FRONT_SCORE_TYPE_STAND_JIN_KITCHEN,       // 金站鸡
	-SCORE_TYPE_STAND_JIN_KITCHEN:         FRONT_SCORE_TYPE_STAND_JIN_KITCHEN_LOSER, // 金站鸡
	SCORE_TYPE_STAND_JIN_JIN_KITCHEN:      FRONT_SCORE_TYPE_STAND_JIN_KITCHEN,       // 金金站鸡
	-SCORE_TYPE_STAND_JIN_JIN_KITCHEN:     FRONT_SCORE_TYPE_STAND_JIN_KITCHEN_LOSER, // 金金站鸡
	SCORE_TYPE_BAO_STAND_KITCHEN:          FRONT_SCORE_TYPE_BAOJI_SHOURU,            // 包站鸡
	-SCORE_TYPE_BAO_STAND_KITCHEN:         FRONT_SCORE_TYPE_BAOJI,                   // 包站鸡
	SCORE_TYPE_BAO_STAND_JIN_KITCHEN:      FRONT_SCORE_TYPE_BAOJI_SHOURU,            // 包金站鸡
	-SCORE_TYPE_BAO_STAND_JIN_KITCHEN:     FRONT_SCORE_TYPE_BAOJI,                   // 包金站鸡
	SCORE_TYPE_BAO_STAND_JIN_JIN_KITCHEN:  FRONT_SCORE_TYPE_BAOJI_SHOURU,            // 包金金站鸡
	-SCORE_TYPE_BAO_STAND_JIN_JIN_KITCHEN: FRONT_SCORE_TYPE_BAOJI,                   // 包金金站鸡

	SCORE_TYPE_FIRST_CYCLE_CHARGE_KITCHEN:              FRONT_SCORE_TYPE_FIRST_CYCLE_CHARGE_KITCHEN,           // 首圈鸡
	-SCORE_TYPE_FIRST_CYCLE_CHARGE_KITCHEN:             FRONT_SCORE_TYPE_FIRST_CYCLE_CHARGE_KITCHEN_LOSER,     // 首圈鸡
	SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_KITCHEN:          FRONT_SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_KITCHEN,       // 金首圈鸡
	-SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_KITCHEN:         FRONT_SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_KITCHEN_LOSER, // 金首圈鸡
	SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_JIN_KITCHEN:      FRONT_SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_KITCHEN,       // 金金首圈鸡
	-SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_JIN_KITCHEN:     FRONT_SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_KITCHEN_LOSER, // 金金首圈鸡
	SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_KITCHEN:          FRONT_SCORE_TYPE_BAOJI_SHOURU,                         // 包首圈鸡
	-SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_KITCHEN:         FRONT_SCORE_TYPE_BAOJI,                                // 包首圈鸡
	SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_JIN_KITCHEN:      FRONT_SCORE_TYPE_BAOJI_SHOURU,                         // 包金首圈鸡
	-SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_JIN_KITCHEN:     FRONT_SCORE_TYPE_BAOJI,                                // 包金首圈鸡
	SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_JIN_JIN_KITCHEN:  FRONT_SCORE_TYPE_BAOJI_SHOURU,                         // 包金金首圈鸡
	-SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_JIN_JIN_KITCHEN: FRONT_SCORE_TYPE_BAOJI,                                // 包金金首圈鸡

	SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN:              FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN,       // 首圈责任鸡
	-SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN:             FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN_LOSER, // 首圈责任鸡
	SCORE_TYPE_RB_FIRST_CYCLE_JIN_KITCHEN:          FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN,       // 金首圈责任鸡
	-SCORE_TYPE_RB_FIRST_CYCLE_JIN_KITCHEN:         FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN_LOSER, // 金首圈责任鸡
	SCORE_TYPE_RB_FIRST_CYCLE_JIN_JIN_KITCHEN:      FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN,       // 金金首圈责任鸡
	-SCORE_TYPE_RB_FIRST_CYCLE_JIN_JIN_KITCHEN:     FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN_LOSER, // 金金首圈责任鸡
	SCORE_TYPE_BAO_RB_FIRST_CYCLE_KITCHEN:          FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN,       // 包首圈责任鸡
	-SCORE_TYPE_BAO_RB_FIRST_CYCLE_KITCHEN:         FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN_LOSER, // 包首圈责任鸡
	SCORE_TYPE_BAO_RB_FIRST_CYCLE_JIN_KITCHEN:      FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN,       // 包金首圈责任鸡
	-SCORE_TYPE_BAO_RB_FIRST_CYCLE_JIN_KITCHEN:     FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN_LOSER, // 包金首圈责任鸡
	SCORE_TYPE_BAO_RB_FIRST_CYCLE_JIN_JIN_KITCHEN:  FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN,       // 包金金首圈责任鸡
	-SCORE_TYPE_BAO_RB_FIRST_CYCLE_JIN_JIN_KITCHEN: FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN_LOSER, // 包金金首圈责任鸡

	SCORE_TYPE_TONG_SAN:  FRONT_SCORE_TYPE_TONG_SAN,       // 通三
	-SCORE_TYPE_TONG_SAN: FRONT_SCORE_TYPE_TONG_SAN_LOSER, // 通三

	SCORE_TYPE_PP_KITCHEN:  FRONT_SCORE_TYPE_PP_KITCHEN,       // 爬坡鸡
	-SCORE_TYPE_PP_KITCHEN: FRONT_SCORE_TYPE_PP_KITCHEN_LOSER, // 爬坡鸡

	SCORE_TYPE_FLOWER_RED_KITCHEN_TING:          FRONT_SCORE_TYPE_FLOWER_RED_KITCHEN,               // 补花鸡(叫牌)
	-SCORE_TYPE_FLOWER_RED_KITCHEN_TING:         FRONT_SCORE_TYPE_FLOWER_RED_KITCHEN_LOSER,         // 补花鸡(叫牌)
	SCORE_TYPE_FLOWER_RED_KITCHEN_WIN:           FRONT_SCORE_TYPE_FLOWER_RED_KITCHEN,               // 补花鸡(胡牌)
	-SCORE_TYPE_FLOWER_RED_KITCHEN_WIN:          FRONT_SCORE_TYPE_FLOWER_RED_KITCHEN_LOSER,         // 补花鸡(胡牌)
	SCORE_TYPE_FLOWER_RED_KITCHEN_TING_DIAMOND:  FRONT_SCORE_TYPE_FLOWER_RED_DIAMOND_KITCHEN,       // 补花鸡（叫牌、钻石）
	-SCORE_TYPE_FLOWER_RED_KITCHEN_TING_DIAMOND: FRONT_SCORE_TYPE_FLOWER_RED_DIAMOND_KITCHEN_LOSER, // 补花鸡（叫牌、钻石）
	SCORE_TYPE_FLOWER_RED_KITCHEN_WIN_DIAMOND:   FRONT_SCORE_TYPE_FLOWER_RED_DIAMOND_KITCHEN,       // 补花鸡（胡牌、钻石）
	-SCORE_TYPE_FLOWER_RED_KITCHEN_WIN_DIAMOND:  FRONT_SCORE_TYPE_FLOWER_RED_DIAMOND_KITCHEN_LOSER, // 补花鸡（胡牌、钻石）

	// 赢杀报牌型
	SCORE_TYPE_SHABAO_SHUANG_LONG_7DUI:      FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_SHUANG_LONG_7DUI_QING: FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_LONG_7DUI:             FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_LONG_7DUI_QING:        FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_7DUI:                  FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_7DUI_QING:             FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_DIQIDUI:               FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_DIQIDUI_QING:          FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_DANDIAO:               FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_DANDIAO_QING:          FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_DADUI:                 FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_DADUI_QING:            FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_BIANKADIAO:            FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_BIANKADIAO_QING:       FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_DAKUANZHANG:           FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_DAKUANZHANG_QING:      FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_QING:                  FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_HEPU_7DUI:             FRONT_SCORE_TYPE_SHABAO_HU_TYPE,
	SCORE_TYPE_SHABAO_HEPU_7DUI_QING:        FRONT_SCORE_TYPE_SHABAO_HU_TYPE,

	// 输杀报牌型
	-SCORE_TYPE_SHABAO_SHUANG_LONG_7DUI:      FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_SHUANG_LONG_7DUI_QING: FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_LONG_7DUI:             FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_LONG_7DUI_QING:        FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_7DUI:                  FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_7DUI_QING:             FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_DIQIDUI:               FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_DIQIDUI_QING:          FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_DANDIAO:               FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_DANDIAO_QING:          FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_DADUI:                 FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_DADUI_QING:            FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_BIANKADIAO:            FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_BIANKADIAO_QING:       FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_DAKUANZHANG:           FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_DAKUANZHANG_QING:      FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_QING:                  FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_HEPU_7DUI:             FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	-SCORE_TYPE_SHABAO_HEPU_7DUI_QING:        FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,

	// 见7挖
	SCORE_TYPE_J7W:  FRONT_SCORE_TYPE_J7W,
	-SCORE_TYPE_J7W: FRONT_SCORE_TYPE_J7W_LOSER,
	// 高挖弹
	SCORE_TYPE_GWD:  FRONT_SCORE_TYPE_GWD,
	-SCORE_TYPE_GWD: FRONT_SCORE_TYPE_GWD_LOSER,
	// 原缺
	SCORE_TYPE_INIT_LACK:  FRONT_SCORE_TYPE_INIT_LACK,
	-SCORE_TYPE_INIT_LACK: FRONT_SCORE_TYPE_INIT_LACK_LOSER,
	// 龙七对+3分
	SCORE_TYPE_LE:  FRONT_SCORE_TYPE_LE,
	-SCORE_TYPE_LE: FRONT_SCORE_TYPE_LE_LOSER,
}

// 客户端需要合并的条目组合
const MERGE_GROUP_WIN = uint16(10001)
const MERGE_GROUP_BAO_CHIKEN = uint16(10002)
const MERGE_GROUP_BAO_KONG = uint16(10003)
const MERGE_GROUP_CHA_QUE = uint16(10004)

var ScoreTypeItemMergeMap = map[int]uint16{
	FRONT_SCORE_TYPE_QIANG:                  MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_BEI_QIANG:              MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_TIANHU:                 MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_TIANHU_LOSER:           MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_DIHU:                   MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_DIHU_LOSER:             MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_BAOTING:                MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_BAOTING_LOSER:          MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_QING:                   MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_QING_LOSER:             MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_SHUANGLONGQIDUI:        MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_SHUANGLONGQIDUI_LOSER:  MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_LONGQIDUI:              MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_LONGQIDUI_LOSER:        MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_QIDUI:                  MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_QIDUI_LOSER:            MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_DIQIDUI:                MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_DIQIDUI_LOSER:          MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_DANDIAO:                MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_DANDIAO_LOSER:          MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_JIE_REPAO_KONG_EXPOSED: MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_REPAO_KONG_EXPOSED:     MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_JIE_REPAO:              MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_REPAO:                  MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_DADUI:                  MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_DADUI_LOSER:            MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_HEPU_QIDIU:             MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_HEPU_QIDIU_LOSER:       MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_KONG_DRAW:              MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_KONG_DRAW_LOSER:        MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_DAKUAN:                 MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_DAKUAN_LOSER:           MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_BIANKADIAO:             MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_BIANKADIAO_LOSER:       MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_PINGHU:                 MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_PINGHU_LOSER:           MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_PINGHU_ZIMO:            MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_PINGHU_ZIMO_LOSER:      MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_ZIMO:                   MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_ZIMO_LOSER:             MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_ZIMO_EXTRA:             MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_ZIMO_EXTRA_LOSER:       MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_DIANPAO:                MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_ZHUANG:                 MERGE_GROUP_WIN,
	FRONT_SCORE_TYPE_ZHUANG_CONTINUE:        MERGE_GROUP_WIN,

	FRONT_SCORE_TYPE_BAO_KONG_SHOURU: MERGE_GROUP_BAO_KONG,
	FRONT_SCORE_TYPE_BAO_KONG:        MERGE_GROUP_BAO_KONG,

	FRONT_SCORE_TYPE_CHAQUE_SHOURU: MERGE_GROUP_CHA_QUE,
	FRONT_SCORE_TYPE_CHAQUE:        MERGE_GROUP_CHA_QUE,

	FRONT_SCORE_TYPE_BAOJI_SHOURU: MERGE_GROUP_BAO_CHIKEN,
	FRONT_SCORE_TYPE_BAOJI:        MERGE_GROUP_BAO_CHIKEN,
}
