package config

import (
	fbsCommon "mahjong.go/fbs/Common"
)

const (
	FRONT_WINWAY_BLANK     = 0
	FRONT_WINWAY_ZIMO      = 20
	FRONT_WINWAY_DIANPAO   = 30
	FRONT_WINWAY_DIANREPAO = 31
	FRONT_WINWAY_HU        = 40
	FRONT_WINWAY_QIANG     = 50
	FRONT_WINWAY_BEI_QIANG = 60
)

const (
	FRONT_WINSTATUS_NO_TING              = 10
	FRONT_WINSTATUS_TING                 = 20
	FRONT_WINSTATUS_BAOTING              = 30
	FRONT_WINSTATUS_HU                   = 40
	FRONT_WINSTATUS_DAKUAN               = 50
	FRONT_WINSTATUS_BIANDIAO             = 60
	FRONT_WINSTATUS_QING                 = 70
	FRONT_WINSTATUS_DADUI                = 80
	FRONT_WINSTATUS_DADUI_QING           = 81
	FRONT_WINSTATUS_QIDUI                = 100
	FRONT_WINSTATUS_QIDUI_QING           = 101
	FRONT_WINSTATUS_LONGQIDUI            = 120
	FRONT_WINSTATUS_LONGQIDUI_QING       = 121
	FRONT_WINSTATUS_DIQIDUI              = 140
	FRONT_WINSTATUS_DIQIDUI_QING         = 141
	FRONT_WINSTATUS_DANDIAO              = 160
	FRONT_WINSTATUS_DANDIAO_QING         = 161
	FRONT_WINSTATUS_SHUANGLONGQIDUI      = 180
	FRONT_WINSTATUS_SHUANGLONGQIDUI_QING = 181
	FRONT_WINSTATUS_KONG_DRAW            = 190
	FRONT_WINSTATUS_HEPU_QIDUI           = 200
	FRONT_WINSTATUS_HEPU_QIDUI_QING      = 201
)

const (
	FRONT_SCORE_TYPE_ZHUANG                = 10
	FRONT_SCORE_TYPE_ZHUANG_CONTINUE       = 11
	FRONT_SCORE_TYPE_ZHUANG_XIAZHUANG      = 20
	FRONT_SCORE_TYPE_KONG_DRAW             = 30
	FRONT_SCORE_TYPE_KONG_DRAW_LOSER       = 31
	FRONT_SCORE_TYPE_TIANHU                = 40
	FRONT_SCORE_TYPE_TIANHU_LOSER          = 41
	FRONT_SCORE_TYPE_DIHU                  = 50
	FRONT_SCORE_TYPE_DIHU_LOSER            = 51
	FRONT_SCORE_TYPE_BAOTING               = 60
	FRONT_SCORE_TYPE_BAOTING_LOSER         = 61
	FRONT_SCORE_TYPE_QING                  = 70
	FRONT_SCORE_TYPE_QING_LOSER            = 71
	FRONT_SCORE_TYPE_FULL_CHIKEN           = 75
	FRONT_SCORE_TYPE_FULL_CHIKEN_LOSER     = 76
	FRONT_SCORE_TYPE_SHUANGLONGQIDUI       = 80
	FRONT_SCORE_TYPE_SHUANGLONGQIDUI_LOSER = 81
	FRONT_SCORE_TYPE_HEPU_QIDIU            = 85
	FRONT_SCORE_TYPE_HEPU_QIDIU_LOSER      = 86
	FRONT_SCORE_TYPE_LONGQIDUI             = 90
	FRONT_SCORE_TYPE_LONGQIDUI_LOSER       = 91
	FRONT_SCORE_TYPE_QIDUI                 = 100
	FRONT_SCORE_TYPE_QIDUI_LOSER           = 101
	FRONT_SCORE_TYPE_DIQIDUI               = 110
	FRONT_SCORE_TYPE_DIQIDUI_LOSER         = 111
	FRONT_SCORE_TYPE_DANDIAO               = 120
	FRONT_SCORE_TYPE_DANDIAO_LOSER         = 121
	FRONT_SCORE_TYPE_DADUI                 = 130
	FRONT_SCORE_TYPE_DADUI_LOSER           = 131
	FRONT_SCORE_TYPE_DAKUAN                = 140
	FRONT_SCORE_TYPE_DAKUAN_LOSER          = 141
	FRONT_SCORE_TYPE_BIANKADIAO            = 150
	FRONT_SCORE_TYPE_BIANKADIAO_LOSER      = 151
	FRONT_SCORE_TYPE_PINGHU                = 160
	FRONT_SCORE_TYPE_PINGHU_LOSER          = 162
	FRONT_SCORE_TYPE_PINGHU_ZIMO           = 161
	FRONT_SCORE_TYPE_PINGHU_ZIMO_LOSER     = 163
	FRONT_SCORE_TYPE_XIAZHUANG             = 170
	FRONT_SCORE_TYPE_DIANPAO               = 180

	FRONT_SCORE_TYPE_BAO_KONG        = 183
	FRONT_SCORE_TYPE_BAO_KONG_SHOURU = 184
	FRONT_SCORE_TYPE_KONG_EXPOSED    = 190
	FRONT_SCORE_TYPE_KONG_TURN       = 200
	FRONT_SCORE_TYPE_KONG_TURN_LOSER = 201
	FRONT_SCORE_TYPE_KONG_DARK       = 210
	FRONT_SCORE_TYPE_KONG_DARK_LOSER = 211
	FRONT_SCORE_TYPE_DIAN_KONG       = 220

	FRONT_SCORE_TYPE_JI                    = 230
	FRONT_SCORE_TYPE_JI_LOSER              = 231
	FRONT_SCORE_TYPE_SILVER_CHIKEN         = 235
	FRONT_SCORE_TYPE_SILVER_CHIKEN_LOSER   = 236
	FRONT_SCORE_TYPE_CHARGE_JI             = 240
	FRONT_SCORE_TYPE_CHARGE_JI_LOSER       = 241
	FRONT_SCORE_TYPE_JIN_JI                = 250
	FRONT_SCORE_TYPE_JIN_JI_LOSER          = 251
	FRONT_SCORE_TYPE_JIN_CHARGE_JI         = 260
	FRONT_SCORE_TYPE_JIN_CHARGE_JI_LOSER   = 261
	FRONT_SCORE_TYPE_WUGU                  = 270
	FRONT_SCORE_TYPE_WUGU_LOSER            = 271
	FRONT_SCORE_TYPE_CHARGE_WUGU           = 280
	FRONT_SCORE_TYPE_CHARGE_WUGU_LOSER     = 281
	FRONT_SCORE_TYPE_JIN_WUGU              = 290
	FRONT_SCORE_TYPE_JIN_WUGU_LOSER        = 291
	FRONT_SCORE_TYPE_JIN_CHARGE_WUGU       = 300
	FRONT_SCORE_TYPE_JIN_CHARGE_WUGU_LOSER = 301
	FRONT_SCORE_TYPE_FANPAI                = 310
	FRONT_SCORE_TYPE_FANPAI_LOSER          = 312
	FRONT_SCORE_TYPE_UD                    = 311
	FRONT_SCORE_TYPE_UD_LOSER              = 313
	FRONT_SCORE_TYPE_FB                    = 320
	FRONT_SCORE_TYPE_FB_LOSER              = 321
	FRONT_SCORE_TYPE_YIWAI                 = 330
	FRONT_SCORE_TYPE_XQ                    = 340
	FRONT_SCORE_TYPE_XQ_LOSER              = 341
	FRONT_SCORE_TYPE_DIAMOND               = 345
	FRONT_SCORE_TYPE_DIAMOND_LOSER         = 346
	FRONT_SCORE_TYPE_BEN                   = 350
	FRONT_SCORE_TYPE_BEN_LOSER             = 351
	FRONT_SCORE_TYPE_TUMBLING              = 355
	FRONT_SCORE_TYPE_TUMBLING_LOSER        = 356

	FRONT_SCORE_TYPE_BAOPAI                 = 360
	FRONT_SCORE_TYPE_BAOPAI_SHOURU          = 370
	FRONT_SCORE_TYPE_BAOJI                  = 380
	FRONT_SCORE_TYPE_BAOJI_SHOURU           = 390
	FRONT_SCORE_TYPE_ZEREN                  = 400
	FRONT_SCORE_TYPE_ZEREN_SHOURU           = 410
	FRONT_SCORE_TYPE_CHAQUE                 = 420
	FRONT_SCORE_TYPE_CHAQUE_SHOURU          = 430
	FRONT_SCORE_TYPE_BEI_SHABAO             = 440
	FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE     = 445
	FRONT_SCORE_TYPE_SHABAO                 = 450
	FRONT_SCORE_TYPE_SHABAO_HU_TYPE         = 455
	FRONT_SCORE_TYPE_REPAO_KONG_EXPOSED     = 460
	FRONT_SCORE_TYPE_JIE_REPAO_KONG_EXPOSED = 470
	FRONT_SCORE_TYPE_REPAO                  = 480
	FRONT_SCORE_TYPE_JIE_REPAO              = 490
	FRONT_SCORE_TYPE_QIANG                  = 500
	FRONT_SCORE_TYPE_BEI_QIANG              = 510

	FRONT_SCORE_TYPE_QING_EXTRA       = 520
	FRONT_SCORE_TYPE_QING_EXTRA_LOSER = 521

	FRONT_SCORE_TYPE_ZIMO       = 530
	FRONT_SCORE_TYPE_ZIMO_LOSER = 531

	FRONT_SCORE_TYPE_ZIMO_EXTRA       = 535
	FRONT_SCORE_TYPE_ZIMO_EXTRA_LOSER = 536

	FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN       = 540
	FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN_LOSER = 541

	FRONT_SCORE_TYPE_STAND_KITCHEN           = 550
	FRONT_SCORE_TYPE_STAND_KITCHEN_LOSER     = 551
	FRONT_SCORE_TYPE_STAND_JIN_KITCHEN       = 560
	FRONT_SCORE_TYPE_STAND_JIN_KITCHEN_LOSER = 561

	FRONT_SCORE_TYPE_FIRST_CYCLE_CHARGE_KITCHEN           = 570
	FRONT_SCORE_TYPE_FIRST_CYCLE_CHARGE_KITCHEN_LOSER     = 571
	FRONT_SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_KITCHEN       = 580
	FRONT_SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_KITCHEN_LOSER = 581

	// 通三
	FRONT_SCORE_TYPE_TONG_SAN       = 590
	FRONT_SCORE_TYPE_TONG_SAN_LOSER = 591

	// 摇摆鸡（上下鸡）
	FRONT_SCORE_TYPE_YB       = 600
	FRONT_SCORE_TYPE_YB_LOSER = 601

	// 爬坡鸡
	FRONT_SCORE_TYPE_PP_KITCHEN       = 610
	FRONT_SCORE_TYPE_PP_KITCHEN_LOSER = 611

	// 补花鸡（红中）
	FRONT_SCORE_TYPE_FLOWER_RED_KITCHEN       = 620
	FRONT_SCORE_TYPE_FLOWER_RED_KITCHEN_LOSER = 621
	// 补花钻石鸡（红中）
	FRONT_SCORE_TYPE_FLOWER_RED_DIAMOND_KITCHEN       = 625
	FRONT_SCORE_TYPE_FLOWER_RED_DIAMOND_KITCHEN_LOSER = 626

	// 见7挖
	FRONT_SCORE_TYPE_J7W       = 630
	FRONT_SCORE_TYPE_J7W_LOSER = 631

	// 高挖弹
	FRONT_SCORE_TYPE_GWD       = 640
	FRONT_SCORE_TYPE_GWD_LOSER = 641

	// 原缺
	FRONT_SCORE_TYPE_INIT_LACK       = 650
	FRONT_SCORE_TYPE_INIT_LACK_LOSER = 651

	// 龙七对+3分
	FRONT_SCORE_TYPE_LE       = 660
	FRONT_SCORE_TYPE_LE_LOSER = 661
)

// 同一个的条目，可能在客户端有不同的描述
// 为了简化客户端逻辑，在服务端做一下id的转换
// map[玩法]map[原条目id]新条目id
var (
	FrontScoreTypeTrans = map[int]map[int]int{
		fbsCommon.GameTypeMAHJONG_ZY: map[int]int{
		// FRONT_SCORE_TYPE_UD:       FRONT_SCORE_TYPE_YB,
		// FRONT_SCORE_TYPE_UD_LOSER: FRONT_SCORE_TYPE_YB_LOSER,
		},
	}
)

// 如果客户端版本低于1.9，则以下这些积分条目不显示
var FrontScoreLowVersionExclude = []int{
	FRONT_SCORE_TYPE_ZHUANG_CONTINUE,
	FRONT_SCORE_TYPE_KONG_DRAW_LOSER,
	FRONT_SCORE_TYPE_TIANHU_LOSER,
	FRONT_SCORE_TYPE_DIHU_LOSER,
	FRONT_SCORE_TYPE_BAOTING_LOSER,
	FRONT_SCORE_TYPE_QING_LOSER,
	FRONT_SCORE_TYPE_SHUANGLONGQIDUI_LOSER,
	FRONT_SCORE_TYPE_LONGQIDUI_LOSER,
	FRONT_SCORE_TYPE_QIDUI_LOSER,
	FRONT_SCORE_TYPE_DIQIDUI_LOSER,
	FRONT_SCORE_TYPE_DANDIAO_LOSER,
	FRONT_SCORE_TYPE_DADUI_LOSER,
	FRONT_SCORE_TYPE_DAKUAN_LOSER,
	FRONT_SCORE_TYPE_BIANKADIAO_LOSER,
	FRONT_SCORE_TYPE_PINGHU_LOSER,
	FRONT_SCORE_TYPE_PINGHU_ZIMO_LOSER,
	FRONT_SCORE_TYPE_KONG_TURN_LOSER,
	FRONT_SCORE_TYPE_KONG_DARK_LOSER,
	FRONT_SCORE_TYPE_JI_LOSER,
	FRONT_SCORE_TYPE_CHARGE_JI_LOSER,
	FRONT_SCORE_TYPE_JIN_JI_LOSER,
	FRONT_SCORE_TYPE_JIN_CHARGE_JI_LOSER,
	FRONT_SCORE_TYPE_WUGU_LOSER,
	FRONT_SCORE_TYPE_CHARGE_WUGU_LOSER,
	FRONT_SCORE_TYPE_JIN_WUGU_LOSER,
	FRONT_SCORE_TYPE_JIN_CHARGE_WUGU_LOSER,
	FRONT_SCORE_TYPE_FANPAI_LOSER,
	FRONT_SCORE_TYPE_UD_LOSER,
	FRONT_SCORE_TYPE_FB_LOSER,
	FRONT_SCORE_TYPE_XQ_LOSER,
	FRONT_SCORE_TYPE_BEN_LOSER,
	FRONT_SCORE_TYPE_TUMBLING_LOSER,
	FRONT_SCORE_TYPE_QING_EXTRA,
	FRONT_SCORE_TYPE_QING_EXTRA_LOSER,
	FRONT_SCORE_TYPE_ZIMO,
	FRONT_SCORE_TYPE_ZIMO_LOSER,
	FRONT_SCORE_TYPE_ZIMO_EXTRA,
	FRONT_SCORE_TYPE_ZIMO_EXTRA_LOSER,
	FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN,
	FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN_LOSER,
	FRONT_SCORE_TYPE_STAND_KITCHEN,
	FRONT_SCORE_TYPE_STAND_KITCHEN_LOSER,
	FRONT_SCORE_TYPE_STAND_JIN_KITCHEN,
	FRONT_SCORE_TYPE_STAND_JIN_KITCHEN_LOSER,
	FRONT_SCORE_TYPE_FIRST_CYCLE_CHARGE_KITCHEN,
	FRONT_SCORE_TYPE_FIRST_CYCLE_CHARGE_KITCHEN_LOSER,
	FRONT_SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_KITCHEN,
	FRONT_SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_KITCHEN_LOSER,
	FRONT_SCORE_TYPE_TONG_SAN,
	FRONT_SCORE_TYPE_TONG_SAN_LOSER,
	FRONT_SCORE_TYPE_YB,
	FRONT_SCORE_TYPE_YB_LOSER,

	FRONT_SCORE_TYPE_PP_KITCHEN,
	FRONT_SCORE_TYPE_PP_KITCHEN_LOSER,
	FRONT_SCORE_TYPE_FLOWER_RED_KITCHEN,
	FRONT_SCORE_TYPE_FLOWER_RED_KITCHEN_LOSER,
	FRONT_SCORE_TYPE_FLOWER_RED_DIAMOND_KITCHEN,
	FRONT_SCORE_TYPE_FLOWER_RED_DIAMOND_KITCHEN_LOSER,
	FRONT_SCORE_TYPE_DIAMOND,
	FRONT_SCORE_TYPE_DIAMOND_LOSER,
	FRONT_SCORE_TYPE_SILVER_CHIKEN,
	FRONT_SCORE_TYPE_SILVER_CHIKEN_LOSER,
	FRONT_SCORE_TYPE_HEPU_QIDIU,
	FRONT_SCORE_TYPE_HEPU_QIDIU_LOSER,

	FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE,
	FRONT_SCORE_TYPE_SHABAO_HU_TYPE,

	FRONT_SCORE_TYPE_J7W,
	FRONT_SCORE_TYPE_J7W_LOSER,
	FRONT_SCORE_TYPE_GWD,
	FRONT_SCORE_TYPE_GWD_LOSER,
	FRONT_SCORE_TYPE_INIT_LACK,
	FRONT_SCORE_TYPE_INIT_LACK_LOSER,
	FRONT_SCORE_TYPE_LE,
	FRONT_SCORE_TYPE_LE_LOSER,
}

// WinStatusIndex 牌型大小 key: front_winstatus, value :大小值
var WinStatusIndex = map[int]int{
	FRONT_WINSTATUS_HU:                   10,
	FRONT_WINSTATUS_BIANDIAO:             20,
	FRONT_WINSTATUS_DAKUAN:               30,
	FRONT_WINSTATUS_DADUI:                40,
	FRONT_WINSTATUS_DANDIAO:              50,
	FRONT_WINSTATUS_QIDUI:                60,
	FRONT_WINSTATUS_QING:                 70,
	FRONT_WINSTATUS_DADUI_QING:           80,
	FRONT_WINSTATUS_LONGQIDUI:            90,
	FRONT_WINSTATUS_LONGQIDUI_QING:       100,
	FRONT_WINSTATUS_HEPU_QIDUI:           110,
	FRONT_WINSTATUS_SHUANGLONGQIDUI:      120,
	FRONT_WINSTATUS_HEPU_QIDUI_QING:      130,
	FRONT_WINSTATUS_SHUANGLONGQIDUI_QING: 140,
}
