package config

const (
	// 积分类型
	SCORE_TYPE_KONG_EXPOSED     = 1
	SCORE_TYPE_KONG_DARK        = 2
	SCORE_TYPE_KONG_TURN        = 3
	SCORE_TYPE_KONG_QIANG       = 4
	SCORE_TYPE_TIANHU           = 5
	SCORE_TYPE_DIHU             = 6
	SCORE_TYPE_BAOTING          = 7
	SCORE_TYPE_QING             = 8
	SCORE_TYPE_SHUANGLONG_QIDUI = 9
	SCORE_TYPE_LONGQIDUI        = 10
	SCORE_TYPE_QIDUI            = 11
	SCORE_TYPE_DIQIDUI          = 12
	SCORE_TYPE_DANDIAO          = 13
	SCORE_TYPE_REPAO_EXPOSED    = 14
	SCORE_TYPE_REPAO_DARK       = 15
	SCORE_TYPE_DADUI            = 16
	SCORE_TYPE_BAO_KONG         = 17
	SCORE_TYPE_BAO_QUE          = 18
	SCORE_TYPE_QING_EXTRA       = 19
	SCORE_TYPE_REPAO_TURN       = 20
	SCORE_TYPE_HEPU_QIDUI       = 21
	SCORE_TYPE_BAO_KONG_DARK    = 22
	SCORE_TYPE_BAO_KONG_TURN    = 23
	SCORE_TYPE_FULL_CHIKEN      = 24

	// 杠上开花
	SCORE_TYPE_KONG_DRAW            = 50
	SCORE_TYPE_DAKUANZHANG          = 51
	SCORE_TYPE_BIANKADIAO           = 52
	SCORE_TYPE_PINGHU               = 53
	SCORE_TYPE_PINGHU_ZIMO          = 54
	SCORE_TYPE_CONTINUE_DEALER      = 55
	SCORE_TYPE_CONTINUE_DEALER_LOSE = 56
	SCORE_TYPE_SHABAO               = 57
	SCORE_TYPE_ZIMO                 = 58
	SCORE_TYPE_ZIMO_EXTRA           = 59

	SCORE_TYPE_CHARGE_KITCHEN             = 100
	SCORE_TYPE_CHARGE_JIN_KITCHEN         = 101
	SCORE_TYPE_CHARGE_JIN_JIN_KITCHEN     = 102
	SCORE_TYPE_BAO_CHARGE_KITCHEN         = 103
	SCORE_TYPE_BAO_CHARGE_JIN_KITCHEN     = 104
	SCORE_TYPE_BAO_CHARGE_JIN_JIN_KITCHEN = 105

	SCORE_TYPE_RB_KITCHEN             = 130
	SCORE_TYPE_RB_JIN_KITCHEN         = 131
	SCORE_TYPE_RB_JIN_JIN_KITCHEN     = 132
	SCORE_TYPE_BAO_RB_KITCHEN         = 133
	SCORE_TYPE_BAO_RB_JIN_KITCHEN     = 134
	SCORE_TYPE_BAO_RB_JIN_JIN_KITCHEN = 135

	SCORE_TYPE_CHARGE_WUGU_KITCHEN             = 150
	SCORE_TYPE_CHARGE_WUGU_JIN_KITCHEN         = 151
	SCORE_TYPE_CHARGE_WUGU_JIN_JIN_KITCHEN     = 152
	SCORE_TYPE_BAO_CHARGE_WUGU_KITCHEN         = 153
	SCORE_TYPE_BAO_CHARGE_WUGU_JIN_KITCHEN     = 154
	SCORE_TYPE_BAO_CHARGE_WUGU_JIN_JIN_KITCHEN = 155

	SCORE_TYPE_KITCHEN             = 170
	SCORE_TYPE_JIN_KITCHEN         = 171
	SCORE_TYPE_JIN_JIN_KITCHEN     = 172
	SCORE_TYPE_BAO_KITCHEN         = 173
	SCORE_TYPE_BAO_JIN_KITCHEN     = 174
	SCORE_TYPE_BAO_JIN_JIN_KITCHEN = 175

	SCORE_TYPE_SILVER_CHIKEN        = 180 // 银鸡
	SCORE_TYPE_SILVER_DOUBLE_CHIKEN = 181 // 银鸡（双倍）
	SCORE_TYPE_SILVER_TRIPLE_CHIKEN = 182 // 银鸡（三倍）

	SCORE_TYPE_WUGU_KITCHEN             = 200
	SCORE_TYPE_WUGU_JIN_KITCHEN         = 201
	SCORE_TYPE_WUGU_JIN_JIN_KITCHEN     = 202
	SCORE_TYPE_BAO_WUGU_KITCHEN         = 203
	SCORE_TYPE_BAO_WUGU_JIN_KITCHEN     = 204
	SCORE_TYPE_BAO_WUGU_JIN_JIN_KITCHEN = 205

	SCORE_TYPE_DIAMOND_KITCHEN        = 210 // 钻石鸡
	SCORE_TYPE_DIAMOND_DOUBLE_KITCHEN = 211 // 钻石鸡（双倍）

	SCORE_TYPE_FB_KITCHEN = 230 // 前后鸡
	SCORE_TYPE_FP_KITCHEN = 231 // 翻牌鸡
	SCORE_TYPE_UD_KITCHEN = 232 // 上下鸡

	SCORE_TYPE_B_KITCHEN  = 233 // 本鸡
	SCORE_TYPE_GT_KITCHEN = 234 // 滚筒鸡
	SCORE_TYPE_XQ_KITCHEN = 235 // 星期鸡

	SCORE_TYPE_STAND_KITCHEN             = 240 // 站鸡
	SCORE_TYPE_STAND_JIN_KITCHEN         = 241 // 金站鸡
	SCORE_TYPE_STAND_JIN_JIN_KITCHEN     = 242 // 金金站鸡
	SCORE_TYPE_BAO_STAND_KITCHEN         = 243 // 包站鸡
	SCORE_TYPE_BAO_STAND_JIN_KITCHEN     = 244 // 包金站鸡
	SCORE_TYPE_BAO_STAND_JIN_JIN_KITCHEN = 245 // 包金金站鸡

	SCORE_TYPE_FIRST_CYCLE_CHARGE_KITCHEN             = 250 // 首圈鸡
	SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_KITCHEN         = 251 // 金首圈鸡
	SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_JIN_KITCHEN     = 252 // 金金首圈鸡
	SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_KITCHEN         = 253 // 包首圈鸡
	SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_JIN_KITCHEN     = 254 // 包金首圈鸡
	SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_JIN_JIN_KITCHEN = 255 // 包金金首圈鸡

	SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN             = 260 // 首圈责任鸡
	SCORE_TYPE_RB_FIRST_CYCLE_JIN_KITCHEN         = 261 // 金首圈责任鸡
	SCORE_TYPE_RB_FIRST_CYCLE_JIN_JIN_KITCHEN     = 262 // 金金首圈责任鸡
	SCORE_TYPE_BAO_RB_FIRST_CYCLE_KITCHEN         = 263 // 包首圈责任鸡
	SCORE_TYPE_BAO_RB_FIRST_CYCLE_JIN_KITCHEN     = 264 // 包金首圈责任鸡
	SCORE_TYPE_BAO_RB_FIRST_CYCLE_JIN_JIN_KITCHEN = 265 // 包金金首圈责任鸡

	SCORE_TYPE_TONG_SAN = 270 // 通三

	SCORE_TYPE_PP_KITCHEN = 280 // 爬坡鸡

	SCORE_TYPE_FLOWER_RED_KITCHEN_TING         = 290 // 补花鸡(叫牌)
	SCORE_TYPE_FLOWER_RED_KITCHEN_WIN          = 292 // 补花鸡(胡牌)
	SCORE_TYPE_FLOWER_RED_KITCHEN_TING_DIAMOND = 294 // 补花鸡（叫牌、钻石）
	SCORE_TYPE_FLOWER_RED_KITCHEN_WIN_DIAMOND  = 296 // 补花鸡（胡牌、钻石）

	// 见7挖
	SCORE_TYPE_J7W = 300
	// 高挖弹
	SCORE_TYPE_GWD = 310
	// 原缺
	SCORE_TYPE_INIT_LACK = 320
	// 龙七对+3分
	SCORE_TYPE_LE = 330

	// 杀报牌型
	SCORE_TYPE_SHABAO_SHUANG_LONG_7DUI      = 10001
	SCORE_TYPE_SHABAO_SHUANG_LONG_7DUI_QING = 20001
	SCORE_TYPE_SHABAO_LONG_7DUI             = 10002
	SCORE_TYPE_SHABAO_LONG_7DUI_QING        = 20002
	SCORE_TYPE_SHABAO_7DUI                  = 10003
	SCORE_TYPE_SHABAO_7DUI_QING             = 20003
	SCORE_TYPE_SHABAO_DIQIDUI               = 10004
	SCORE_TYPE_SHABAO_DIQIDUI_QING          = 20004
	SCORE_TYPE_SHABAO_DANDIAO               = 10005
	SCORE_TYPE_SHABAO_DANDIAO_QING          = 20005
	SCORE_TYPE_SHABAO_DADUI                 = 10006
	SCORE_TYPE_SHABAO_DADUI_QING            = 20006
	SCORE_TYPE_SHABAO_BIANKADIAO            = 10007
	SCORE_TYPE_SHABAO_BIANKADIAO_QING       = 20007
	SCORE_TYPE_SHABAO_DAKUANZHANG           = 10008
	SCORE_TYPE_SHABAO_DAKUANZHANG_QING      = 20008
	SCORE_TYPE_SHABAO_QING                  = 20009
	SCORE_TYPE_SHABAO_HEPU_7DUI             = 10011
	SCORE_TYPE_SHABAO_HEPU_7DUI_QING        = 20011
)

// 胡牌积分, 只读变量所以是线程安全的
var (
	GY_SCORE       = map[int]int{}
	BJ_SCORE       = map[int]int{}
	SD_SCORE       = map[int]int{}
	ZY_SCORE       = map[int]int{}
	MATCH_GZ_SCORE = map[int]int{}
	AS_SCORE       = map[int]int{}
	XY_SCORE       = map[int]int{}
	LPS_SCORE      = map[int]int{}
	KL_SCORE       = map[int]int{}
	DY_SCORE       = map[int]int{}
	TR_SCORE       = map[int]int{}
	GYA_SCORE      = map[int]int{}
	QX_SCORE       = map[int]int{}
	JS_SCORE       = map[int]int{}
	RH_SCORE       = map[int]int{}
)

// 翻倍的类型
var (
	// ZM_DOUBLE_SCORE_TYPE 自摸翻倍
	ZM_DOUBLE_SCORE_TYPE = []int{
		SCORE_TYPE_QING,
		SCORE_TYPE_SHUANGLONG_QIDUI,
		SCORE_TYPE_HEPU_QIDUI,
		SCORE_TYPE_LONGQIDUI,
		SCORE_TYPE_QIDUI,
		SCORE_TYPE_DIQIDUI,
		SCORE_TYPE_DADUI,
		SCORE_TYPE_DANDIAO,
		SCORE_TYPE_PINGHU,
		SCORE_TYPE_PINGHU_ZIMO,
	}
	// DP_DOUBLE_SCORE_TYPE 大牌翻倍
	DP_DOUBLE_SCORE_TYPE = []int{
		SCORE_TYPE_QING,
		SCORE_TYPE_SHUANGLONG_QIDUI,
		SCORE_TYPE_HEPU_QIDUI,
		SCORE_TYPE_LONGQIDUI,
		SCORE_TYPE_QIDUI,
		SCORE_TYPE_DIQIDUI,
		SCORE_TYPE_DADUI,
		SCORE_TYPE_DANDIAO,

		SCORE_TYPE_SHABAO_QING,
		SCORE_TYPE_SHABAO_SHUANG_LONG_7DUI,
		SCORE_TYPE_SHABAO_SHUANG_LONG_7DUI_QING,
		SCORE_TYPE_SHABAO_HEPU_7DUI,
		SCORE_TYPE_SHABAO_HEPU_7DUI_QING,
		SCORE_TYPE_SHABAO_LONG_7DUI,
		SCORE_TYPE_SHABAO_LONG_7DUI_QING,
		SCORE_TYPE_SHABAO_7DUI,
		SCORE_TYPE_SHABAO_7DUI_QING,
		SCORE_TYPE_SHABAO_DIQIDUI,
		SCORE_TYPE_SHABAO_DIQIDUI_QING,
		SCORE_TYPE_SHABAO_DADUI,
		SCORE_TYPE_SHABAO_DADUI_QING,
		SCORE_TYPE_SHABAO_DANDIAO,
		SCORE_TYPE_SHABAO_DANDIAO_QING,
	}
	DEALER_DOUBLE_SCORE_TYPE = []int{
		SCORE_TYPE_QING,
		SCORE_TYPE_SHUANGLONG_QIDUI,
		SCORE_TYPE_HEPU_QIDUI,
		SCORE_TYPE_LONGQIDUI,
		SCORE_TYPE_QIDUI,
		SCORE_TYPE_DIQIDUI,
		SCORE_TYPE_DADUI,
		SCORE_TYPE_DANDIAO,
		SCORE_TYPE_PINGHU,
		SCORE_TYPE_PINGHU_ZIMO,
	}
)

// TS_EXTRA_SCORE 通三额外分数
// 清一色和其他牌型冲突的时候，只加3分，而不是加两个三分
var (
	TS_EXTRA_SCORE = map[int]int{
		// 牌型相关
		SCORE_TYPE_PINGHU:      2,
		SCORE_TYPE_PINGHU_ZIMO: 3,
		// 幺鸡相关
		// 冲锋鸡
		SCORE_TYPE_CHARGE_KITCHEN:             1,
		SCORE_TYPE_CHARGE_JIN_KITCHEN:         2,
		SCORE_TYPE_CHARGE_JIN_JIN_KITCHEN:     4,
		SCORE_TYPE_BAO_CHARGE_KITCHEN:         1,
		SCORE_TYPE_BAO_CHARGE_JIN_KITCHEN:     2,
		SCORE_TYPE_BAO_CHARGE_JIN_JIN_KITCHEN: 4,
		// 责任鸡
		SCORE_TYPE_RB_KITCHEN:             2,
		SCORE_TYPE_RB_JIN_KITCHEN:         4,
		SCORE_TYPE_RB_JIN_JIN_KITCHEN:     8,
		SCORE_TYPE_BAO_RB_KITCHEN:         2,
		SCORE_TYPE_BAO_RB_JIN_KITCHEN:     4,
		SCORE_TYPE_BAO_RB_JIN_JIN_KITCHEN: 8,
		// 首圈冲锋鸡
		SCORE_TYPE_FIRST_CYCLE_CHARGE_KITCHEN:             1, // 首圈鸡
		SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_KITCHEN:         2, // 金首圈鸡
		SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_JIN_KITCHEN:     4, // 金金首圈鸡
		SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_KITCHEN:         1, // 包首圈鸡
		SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_JIN_KITCHEN:     2, // 包金首圈鸡
		SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_JIN_JIN_KITCHEN: 4, // 包金金首圈鸡
		// 首圈责任鸡
		SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN:         2, // 首圈责任鸡
		SCORE_TYPE_RB_FIRST_CYCLE_JIN_KITCHEN:     4, // 金首圈责任鸡
		SCORE_TYPE_RB_FIRST_CYCLE_JIN_JIN_KITCHEN: 8, // 金金首圈责任鸡
		SCORE_TYPE_BAO_RB_FIRST_CYCLE_KITCHEN:     2, // 包首圈责任鸡
		SCORE_TYPE_BAO_RB_FIRST_CYCLE_JIN_KITCHEN: 4, // 包金首圈责任鸡
	}
	TS_WTYPE_EXTRA_SCORE = []int{
		HU_TYPE_SHUANG_LONG_7DUI,
		HU_TYPE_HEPU_7DUI,
		HU_TYPE_LONG_7DUI,
		HU_TYPE_7DUI,
		HU_TYPE_DIQIDUI,
		HU_TYPE_DANDIAO,
		HU_TYPE_DADUI,
		HU_TYPE_BIANKADIAO,
		HU_TYPE_DAKUANZHANG,
	}
)

func init() {
	// 贵阳麻将
	GY_SCORE = map[int]int{
		SCORE_TYPE_KONG_EXPOSED:     3,
		SCORE_TYPE_KONG_DARK:        3,
		SCORE_TYPE_KONG_TURN:        3,
		SCORE_TYPE_KONG_QIANG:       3,
		SCORE_TYPE_TIANHU:           20,
		SCORE_TYPE_DIHU:             10,
		SCORE_TYPE_BAOTING:          10,
		SCORE_TYPE_QING:             10,
		SCORE_TYPE_SHUANGLONG_QIDUI: 30,
		SCORE_TYPE_LONGQIDUI:        20,
		SCORE_TYPE_QIDUI:            10,
		SCORE_TYPE_DIQIDUI:          20,
		SCORE_TYPE_DANDIAO:          10,
		SCORE_TYPE_REPAO_EXPOSED:    3,
		SCORE_TYPE_REPAO_DARK:       3,
		SCORE_TYPE_REPAO_TURN:       3,
		SCORE_TYPE_DADUI:            5,
		SCORE_TYPE_DAKUANZHANG:      4,
		SCORE_TYPE_BIANKADIAO:       3,
		SCORE_TYPE_BAO_QUE:          1,
		SCORE_TYPE_QING_EXTRA:       3,
		SCORE_TYPE_HEPU_QIDUI:       20,
		SCORE_TYPE_BAO_KONG:         3,
		SCORE_TYPE_BAO_KONG_DARK:    3,
		SCORE_TYPE_BAO_KONG_TURN:    3,
		SCORE_TYPE_FULL_CHIKEN:      10,

		SCORE_TYPE_KONG_DRAW:            1,
		SCORE_TYPE_PINGHU:               1,
		SCORE_TYPE_ZIMO:                 1,
		SCORE_TYPE_ZIMO_EXTRA:           1,
		SCORE_TYPE_CONTINUE_DEALER:      1,
		SCORE_TYPE_CONTINUE_DEALER_LOSE: 1,
		SCORE_TYPE_SHABAO:               10,

		SCORE_TYPE_CHARGE_KITCHEN:             2,
		SCORE_TYPE_CHARGE_JIN_KITCHEN:         4,
		SCORE_TYPE_CHARGE_JIN_JIN_KITCHEN:     8,
		SCORE_TYPE_BAO_CHARGE_KITCHEN:         2,
		SCORE_TYPE_BAO_CHARGE_JIN_KITCHEN:     4,
		SCORE_TYPE_BAO_CHARGE_JIN_JIN_KITCHEN: 8,

		SCORE_TYPE_RB_KITCHEN:             1,
		SCORE_TYPE_RB_JIN_KITCHEN:         2,
		SCORE_TYPE_RB_JIN_JIN_KITCHEN:     4,
		SCORE_TYPE_BAO_RB_KITCHEN:         1,
		SCORE_TYPE_BAO_RB_JIN_KITCHEN:     2,
		SCORE_TYPE_BAO_RB_JIN_JIN_KITCHEN: 4,

		SCORE_TYPE_CHARGE_WUGU_KITCHEN:             4,
		SCORE_TYPE_CHARGE_WUGU_JIN_KITCHEN:         8,
		SCORE_TYPE_CHARGE_WUGU_JIN_JIN_KITCHEN:     16,
		SCORE_TYPE_BAO_CHARGE_WUGU_KITCHEN:         4,
		SCORE_TYPE_BAO_CHARGE_WUGU_JIN_KITCHEN:     8,
		SCORE_TYPE_BAO_CHARGE_WUGU_JIN_JIN_KITCHEN: 16,

		SCORE_TYPE_KITCHEN:             1,
		SCORE_TYPE_JIN_KITCHEN:         2,
		SCORE_TYPE_JIN_JIN_KITCHEN:     4,
		SCORE_TYPE_BAO_KITCHEN:         1,
		SCORE_TYPE_BAO_JIN_KITCHEN:     2,
		SCORE_TYPE_BAO_JIN_JIN_KITCHEN: 4,

		SCORE_TYPE_SILVER_CHIKEN:        2, // 银鸡
		SCORE_TYPE_SILVER_DOUBLE_CHIKEN: 4, // 银鸡（双倍）
		SCORE_TYPE_SILVER_TRIPLE_CHIKEN: 8, // 银鸡（三倍）

		SCORE_TYPE_WUGU_KITCHEN:             2,
		SCORE_TYPE_WUGU_JIN_KITCHEN:         4,
		SCORE_TYPE_WUGU_JIN_JIN_KITCHEN:     8,
		SCORE_TYPE_BAO_WUGU_KITCHEN:         2,
		SCORE_TYPE_BAO_WUGU_JIN_KITCHEN:     4,
		SCORE_TYPE_BAO_WUGU_JIN_JIN_KITCHEN: 8,

		SCORE_TYPE_DIAMOND_KITCHEN:        4, // 钻石鸡
		SCORE_TYPE_DIAMOND_DOUBLE_KITCHEN: 8, // 钻石鸡(双倍)

		// 滚筒，翻牌
		SCORE_TYPE_FB_KITCHEN: 1,
		SCORE_TYPE_FP_KITCHEN: 1,
		SCORE_TYPE_UD_KITCHEN: 1,

		SCORE_TYPE_B_KITCHEN:  1,
		SCORE_TYPE_GT_KITCHEN: 1,
		SCORE_TYPE_XQ_KITCHEN: 1,

		// 站鸡
		SCORE_TYPE_STAND_KITCHEN:             2, // 站鸡
		SCORE_TYPE_STAND_JIN_KITCHEN:         4, // 金站鸡
		SCORE_TYPE_STAND_JIN_JIN_KITCHEN:     8, // 金站鸡
		SCORE_TYPE_BAO_STAND_KITCHEN:         2, // 包站鸡
		SCORE_TYPE_BAO_STAND_JIN_KITCHEN:     4, // 包金站鸡
		SCORE_TYPE_BAO_STAND_JIN_JIN_KITCHEN: 8, // 包金站鸡

		// 首圈鸡
		SCORE_TYPE_FIRST_CYCLE_CHARGE_KITCHEN:             3,  // 首圈鸡
		SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_KITCHEN:         6,  // 金首圈鸡
		SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_JIN_KITCHEN:     12, // 金金首圈鸡
		SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_KITCHEN:         3,  // 包首圈鸡
		SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_JIN_KITCHEN:     6,  // 包金首圈鸡
		SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_JIN_JIN_KITCHEN: 12, // 包金金首圈鸡

		// 首圈责任鸡
		SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN:             3,  // 首圈责任鸡
		SCORE_TYPE_RB_FIRST_CYCLE_JIN_KITCHEN:         6,  // 金首圈责任鸡
		SCORE_TYPE_RB_FIRST_CYCLE_JIN_JIN_KITCHEN:     12, // 金金首圈责任鸡
		SCORE_TYPE_BAO_RB_FIRST_CYCLE_KITCHEN:         3,  // 包首圈责任鸡
		SCORE_TYPE_BAO_RB_FIRST_CYCLE_JIN_KITCHEN:     6,  // 包金首圈责任鸡
		SCORE_TYPE_BAO_RB_FIRST_CYCLE_JIN_JIN_KITCHEN: 12, // 包金金首圈责任鸡

		// 通三
		SCORE_TYPE_TONG_SAN: 3,

		// 爬坡鸡
		SCORE_TYPE_PP_KITCHEN: 1,

		// 补花鸡（红中）
		SCORE_TYPE_FLOWER_RED_KITCHEN_TING:         1,
		SCORE_TYPE_FLOWER_RED_KITCHEN_WIN:          2,
		SCORE_TYPE_FLOWER_RED_KITCHEN_TING_DIAMOND: 4,
		SCORE_TYPE_FLOWER_RED_KITCHEN_WIN_DIAMOND:  6,

		// 杀报牌型分
		SCORE_TYPE_SHABAO_SHUANG_LONG_7DUI:      30,
		SCORE_TYPE_SHABAO_SHUANG_LONG_7DUI_QING: 40,
		SCORE_TYPE_SHABAO_LONG_7DUI:             20,
		SCORE_TYPE_SHABAO_LONG_7DUI_QING:        30,
		SCORE_TYPE_SHABAO_7DUI:                  10,
		SCORE_TYPE_SHABAO_7DUI_QING:             20,
		SCORE_TYPE_SHABAO_DIQIDUI:               20,
		SCORE_TYPE_SHABAO_DIQIDUI_QING:          30,
		SCORE_TYPE_SHABAO_DANDIAO:               10,
		SCORE_TYPE_SHABAO_DANDIAO_QING:          20,
		SCORE_TYPE_SHABAO_DADUI:                 5,
		SCORE_TYPE_SHABAO_DADUI_QING:            15,
		SCORE_TYPE_SHABAO_BIANKADIAO:            3,
		SCORE_TYPE_SHABAO_BIANKADIAO_QING:       13,
		SCORE_TYPE_SHABAO_DAKUANZHANG:           4,
		SCORE_TYPE_SHABAO_DAKUANZHANG_QING:      14,
		SCORE_TYPE_SHABAO_QING:                  10,
		SCORE_TYPE_SHABAO_HEPU_7DUI:             20,
		SCORE_TYPE_SHABAO_HEPU_7DUI_QING:        30,

		// 见7挖
		SCORE_TYPE_J7W: 5,
		// 高挖弹
		SCORE_TYPE_GWD: 5,
		// 原缺
		SCORE_TYPE_INIT_LACK: 3,
		// 龙7对+3分
		SCORE_TYPE_LE: 3,
	}
	// 初始化
	for k, v := range GY_SCORE {
		BJ_SCORE[k] = v
		SD_SCORE[k] = v
		ZY_SCORE[k] = v
		MATCH_GZ_SCORE[k] = v
		AS_SCORE[k] = v
		XY_SCORE[k] = v
		LPS_SCORE[k] = v
		KL_SCORE[k] = v
		DY_SCORE[k] = v
		TR_SCORE[k] = v
		GYA_SCORE[k] = v
		QX_SCORE[k] = v
		JS_SCORE[k] = v
		RH_SCORE[k] = v
	}

	// 毕节麻将
	BJ_SCORE[SCORE_TYPE_DADUI] = 6                       // 大对子算6分
	BJ_SCORE[SCORE_TYPE_SHABAO_DADUI] = 6                // 杀报大对算6分
	BJ_SCORE[SCORE_TYPE_SHABAO_DADUI_QING] = 16          // 杀报清大对算16分
	BJ_SCORE[SCORE_TYPE_PINGHU_ZIMO] = 2                 // 有平胡自摸 2分
	BJ_SCORE[SCORE_TYPE_CHARGE_JIN_KITCHEN] = 6          // 冲锋金鸡6分
	BJ_SCORE[SCORE_TYPE_BAO_CHARGE_JIN_JIN_KITCHEN] = 12 // 冲锋金金鸡12分
	BJ_SCORE[SCORE_TYPE_BAO_CHARGE_JIN_KITCHEN] = 6      // 包冲锋金鸡6分
	BJ_SCORE[SCORE_TYPE_BAO_CHARGE_JIN_JIN_KITCHEN] = 12 // 包冲锋金金鸡12分
	BJ_SCORE[SCORE_TYPE_RB_JIN_KITCHEN] = 3              // 责任金鸡3分
	BJ_SCORE[SCORE_TYPE_RB_JIN_JIN_KITCHEN] = 6          // 责任金金鸡6分
	BJ_SCORE[SCORE_TYPE_BAO_RB_JIN_KITCHEN] = 3          // 包责任金鸡3分
	BJ_SCORE[SCORE_TYPE_BAO_RB_JIN_JIN_KITCHEN] = 6      // 包责任金金鸡6分
	BJ_SCORE[SCORE_TYPE_JIN_KITCHEN] = 3                 // 金鸡3分
	BJ_SCORE[SCORE_TYPE_JIN_JIN_KITCHEN] = 6             // 金金鸡6分
	BJ_SCORE[SCORE_TYPE_BAO_JIN_KITCHEN] = 3             // 包金鸡3分
	BJ_SCORE[SCORE_TYPE_BAO_JIN_JIN_KITCHEN] = 6         // 包金金鸡6分
	// 三丁拐
	// 遵义麻将
	ZY_SCORE[SCORE_TYPE_KONG_DRAW] = 11 // 杠开算11分
	// 雀王榜
	MATCH_GZ_SCORE[SCORE_TYPE_DADUI] = 6              // 大对子算6分
	MATCH_GZ_SCORE[SCORE_TYPE_SHABAO_DADUI] = 6       // 杀报大对算6分
	MATCH_GZ_SCORE[SCORE_TYPE_SHABAO_DADUI_QING] = 16 // 杀报清大对算16分
	// 安顺麻将
	// 兴义麻将
	XY_SCORE[SCORE_TYPE_QIDUI] = 8                  // 七对8分
	XY_SCORE[SCORE_TYPE_SHABAO_7DUI] = 8            // 杀报七对8分
	XY_SCORE[SCORE_TYPE_SHABAO_7DUI_QING] = 18      // 杀报清七对18分
	XY_SCORE[SCORE_TYPE_LONGQIDUI] = 10             // 龙七对10分
	XY_SCORE[SCORE_TYPE_SHABAO_LONG_7DUI] = 10      // 杀报龙七对10分
	XY_SCORE[SCORE_TYPE_SHABAO_LONG_7DUI_QING] = 20 // 杀报清龙七对20分
	// 六盘水麻将
	// 凯里麻将
	KL_SCORE[SCORE_TYPE_DADUI] = 3                  // 大对子:3分
	KL_SCORE[SCORE_TYPE_SHABAO_DADUI] = 3           // 杀报大对子:3分
	KL_SCORE[SCORE_TYPE_SHABAO_DADUI_QING] = 8      // 杀报大对子:8分
	KL_SCORE[SCORE_TYPE_QIDUI] = 3                  // 七对:3分
	KL_SCORE[SCORE_TYPE_SHABAO_7DUI] = 3            // 杀报七对:3分
	KL_SCORE[SCORE_TYPE_SHABAO_7DUI_QING] = 8       // 杀报七对:8分
	KL_SCORE[SCORE_TYPE_LONGQIDUI] = 5              // 龙七对:5分
	KL_SCORE[SCORE_TYPE_SHABAO_LONG_7DUI] = 5       // 杀报龙七对:5分
	KL_SCORE[SCORE_TYPE_SHABAO_LONG_7DUI_QING] = 10 // 杀报龙七对:10分
	KL_SCORE[SCORE_TYPE_QING] = 5                   // 清一色:5分
	KL_SCORE[SCORE_TYPE_SHABAO_QING] = 5            // 杀报清一色:5分
	KL_SCORE[SCORE_TYPE_KONG_EXPOSED] = 1           // 明杠
	KL_SCORE[SCORE_TYPE_KONG_TURN] = 1              // 转弯杠
	KL_SCORE[SCORE_TYPE_KONG_DARK] = 2              // 暗杠
	KL_SCORE[SCORE_TYPE_BAO_KONG] = 1               // 明杠
	KL_SCORE[SCORE_TYPE_BAO_KONG_TURN] = 1          // 转弯杠
	KL_SCORE[SCORE_TYPE_BAO_KONG_DARK] = 2          // 暗杠
	KL_SCORE[SCORE_TYPE_KONG_QIANG] = 1             // 抢杠
	KL_SCORE[SCORE_TYPE_REPAO_EXPOSED] = 1          // 热炮（明杠）
	KL_SCORE[SCORE_TYPE_REPAO_DARK] = 2             // 热炮（暗杠）
	KL_SCORE[SCORE_TYPE_REPAO_TURN] = 1             // 热炮（转弯杠）
	// 铜仁麻将
	TR_SCORE[SCORE_TYPE_DADUI] = 8
	TR_SCORE[SCORE_TYPE_SHABAO_DADUI] = 8
	TR_SCORE[SCORE_TYPE_SHABAO_DADUI_QING] = 20
	TR_SCORE[SCORE_TYPE_QIDUI] = 12
	TR_SCORE[SCORE_TYPE_SHABAO_7DUI] = 12
	TR_SCORE[SCORE_TYPE_SHABAO_7DUI_QING] = 24
	TR_SCORE[SCORE_TYPE_LONGQIDUI] = 24
	TR_SCORE[SCORE_TYPE_SHABAO_LONG_7DUI] = 24
	TR_SCORE[SCORE_TYPE_SHABAO_LONG_7DUI_QING] = 36
	TR_SCORE[SCORE_TYPE_QING] = 12
	TR_SCORE[SCORE_TYPE_SHABAO_QING] = 12
	TR_SCORE[SCORE_TYPE_CHARGE_KITCHEN] = 3
	TR_SCORE[SCORE_TYPE_CHARGE_JIN_KITCHEN] = 6
	TR_SCORE[SCORE_TYPE_CHARGE_JIN_JIN_KITCHEN] = 12
	TR_SCORE[SCORE_TYPE_BAO_CHARGE_KITCHEN] = 3
	TR_SCORE[SCORE_TYPE_BAO_CHARGE_JIN_KITCHEN] = 6
	TR_SCORE[SCORE_TYPE_BAO_CHARGE_JIN_JIN_KITCHEN] = 12
	TR_SCORE[SCORE_TYPE_JIN_KITCHEN] = 3
	TR_SCORE[SCORE_TYPE_JIN_JIN_KITCHEN] = 6
	TR_SCORE[SCORE_TYPE_BAO_JIN_KITCHEN] = 3
	TR_SCORE[SCORE_TYPE_BAO_JIN_JIN_KITCHEN] = 6
	// 黔西麻将
	// 金沙麻将
	// 仁怀麻将
	RH_SCORE[SCORE_TYPE_JIN_KITCHEN] = 3
	RH_SCORE[SCORE_TYPE_JIN_JIN_KITCHEN] = 6
	RH_SCORE[SCORE_TYPE_WUGU_KITCHEN] = 4
	RH_SCORE[SCORE_TYPE_WUGU_JIN_KITCHEN] = 8
	RH_SCORE[SCORE_TYPE_WUGU_JIN_JIN_KITCHEN] = 16
	RH_SCORE[SCORE_TYPE_KONG_EXPOSED] = 2  // 明杠
	RH_SCORE[SCORE_TYPE_KONG_TURN] = 4     // 转弯杠
	RH_SCORE[SCORE_TYPE_KONG_DARK] = 4     // 暗杠
	RH_SCORE[SCORE_TYPE_BAO_KONG] = 2      // 明杠
	RH_SCORE[SCORE_TYPE_BAO_KONG_TURN] = 4 // 转弯杠
	RH_SCORE[SCORE_TYPE_BAO_KONG_DARK] = 4 // 暗杠
	RH_SCORE[SCORE_TYPE_KONG_QIANG] = 4    // 暗杠
	RH_SCORE[SCORE_TYPE_PINGHU] = 2
	RH_SCORE[SCORE_TYPE_ZIMO] = 2
	RH_SCORE[SCORE_TYPE_QIDUI] = 15
	RH_SCORE[SCORE_TYPE_LONGQIDUI] = 30
	RH_SCORE[SCORE_TYPE_QING] = 15
	RH_SCORE[SCORE_TYPE_KONG_DRAW] = 15
	RH_SCORE[SCORE_TYPE_BAOTING] = 15
	RH_SCORE[SCORE_TYPE_SHABAO] = 15
	RH_SCORE[SCORE_TYPE_SHABAO_LONG_7DUI] = 30
	RH_SCORE[SCORE_TYPE_SHABAO_LONG_7DUI_QING] = 45
	RH_SCORE[SCORE_TYPE_SHABAO_7DUI] = 15
	RH_SCORE[SCORE_TYPE_SHABAO_7DUI_QING] = 30
	RH_SCORE[SCORE_TYPE_SHABAO_QING] = 15
}
