package config

var (
	STT = map[int]string{
		SCORE_TYPE_KONG_EXPOSED:     "明杠",
		SCORE_TYPE_KONG_DARK:        "暗杠",
		SCORE_TYPE_KONG_TURN:        "拐弯杠",
		SCORE_TYPE_KONG_QIANG:       "抢杠",
		SCORE_TYPE_TIANHU:           "天胡",
		SCORE_TYPE_DIHU:             "地胡",
		SCORE_TYPE_BAOTING:          "报听",
		SCORE_TYPE_QING:             "清一色",
		SCORE_TYPE_SHUANGLONG_QIDUI: "双龙7对",
		SCORE_TYPE_LONGQIDUI:        "龙7对",
		SCORE_TYPE_QIDUI:            "7对",
		SCORE_TYPE_DIQIDUI:          "地7对",
		SCORE_TYPE_DANDIAO:          "单调",
		SCORE_TYPE_REPAO_EXPOSED:    "热炮(明杠)",
		SCORE_TYPE_REPAO_DARK:       "热炮(暗杠)",
		SCORE_TYPE_REPAO_TURN:       "热炮(转弯杠)",
		SCORE_TYPE_DADUI:            "大对",

		SCORE_TYPE_BAO_KONG:      "包杠(明杠)",
		SCORE_TYPE_BAO_KONG_TURN: "包杠(转弯杠)",
		SCORE_TYPE_BAO_KONG_DARK: "包杠(暗杠)",
		SCORE_TYPE_BAO_QUE:       "查缺",
		SCORE_TYPE_QING_EXTRA:    "清一色加3分",
		SCORE_TYPE_FULL_CHIKEN:   "满鸡",

		SCORE_TYPE_KONG_DRAW:            "杠上开花",
		SCORE_TYPE_DAKUANZHANG:          "大宽张",
		SCORE_TYPE_BIANKADIAO:           "边卡吊",
		SCORE_TYPE_PINGHU:               "平胡",
		SCORE_TYPE_PINGHU_ZIMO:          "自摸平胡",
		SCORE_TYPE_CONTINUE_DEALER:      "连庄",
		SCORE_TYPE_CONTINUE_DEALER_LOSE: "庄输",
		SCORE_TYPE_SHABAO:               "杀报",
		SCORE_TYPE_ZIMO:                 "自摸",
		SCORE_TYPE_ZIMO_EXTRA:           "自摸加一分",

		SCORE_TYPE_CHARGE_KITCHEN:             "冲锋鸡",
		SCORE_TYPE_CHARGE_JIN_KITCHEN:         "金冲锋鸡",
		SCORE_TYPE_CHARGE_JIN_JIN_KITCHEN:     "金金冲锋鸡",
		SCORE_TYPE_BAO_CHARGE_KITCHEN:         "包冲锋鸡",
		SCORE_TYPE_BAO_CHARGE_JIN_KITCHEN:     "包金冲锋鸡",
		SCORE_TYPE_BAO_CHARGE_JIN_JIN_KITCHEN: "包金金冲锋鸡",

		SCORE_TYPE_RB_KITCHEN:             "责任鸡",
		SCORE_TYPE_RB_JIN_KITCHEN:         "金责任鸡",
		SCORE_TYPE_RB_JIN_JIN_KITCHEN:     "金金责任鸡",
		SCORE_TYPE_BAO_RB_KITCHEN:         "包责任鸡",
		SCORE_TYPE_BAO_RB_JIN_KITCHEN:     "包金责任鸡",
		SCORE_TYPE_BAO_RB_JIN_JIN_KITCHEN: "包金金责任鸡",

		SCORE_TYPE_CHARGE_WUGU_KITCHEN:             "冲锋乌骨鸡",
		SCORE_TYPE_CHARGE_WUGU_JIN_KITCHEN:         "金冲锋乌骨鸡",
		SCORE_TYPE_CHARGE_WUGU_JIN_JIN_KITCHEN:     "金金冲锋乌骨鸡",
		SCORE_TYPE_BAO_CHARGE_WUGU_KITCHEN:         "包冲锋乌骨鸡",
		SCORE_TYPE_BAO_CHARGE_WUGU_JIN_KITCHEN:     "包金冲锋乌骨鸡",
		SCORE_TYPE_BAO_CHARGE_WUGU_JIN_JIN_KITCHEN: "包金金冲锋乌骨鸡",

		SCORE_TYPE_KITCHEN:             "幺鸡",
		SCORE_TYPE_JIN_KITCHEN:         "金幺鸡",
		SCORE_TYPE_JIN_JIN_KITCHEN:     "金金幺鸡",
		SCORE_TYPE_BAO_KITCHEN:         "包幺鸡",
		SCORE_TYPE_BAO_JIN_KITCHEN:     "包金幺鸡",
		SCORE_TYPE_BAO_JIN_JIN_KITCHEN: "包金金幺鸡",

		SCORE_TYPE_SILVER_CHIKEN:        "银鸡",
		SCORE_TYPE_SILVER_DOUBLE_CHIKEN: "银鸡（双倍）",
		SCORE_TYPE_SILVER_TRIPLE_CHIKEN: "银鸡（三倍）",

		SCORE_TYPE_WUGU_KITCHEN:             "乌骨鸡",
		SCORE_TYPE_WUGU_JIN_KITCHEN:         "金乌骨鸡",
		SCORE_TYPE_WUGU_JIN_JIN_KITCHEN:     "金金乌骨鸡",
		SCORE_TYPE_BAO_WUGU_KITCHEN:         "包乌骨鸡",
		SCORE_TYPE_BAO_WUGU_JIN_KITCHEN:     "包金乌骨鸡",
		SCORE_TYPE_BAO_WUGU_JIN_JIN_KITCHEN: "包金金乌骨鸡",

		SCORE_TYPE_DIAMOND_KITCHEN:        "钻石鸡",
		SCORE_TYPE_DIAMOND_DOUBLE_KITCHEN: "钻石鸡（双倍）",

		// 滚筒，翻牌
		SCORE_TYPE_FB_KITCHEN: "前后鸡",
		SCORE_TYPE_FP_KITCHEN: "翻牌鸡",
		SCORE_TYPE_UD_KITCHEN: "上下鸡",

		SCORE_TYPE_B_KITCHEN:  "本鸡",
		SCORE_TYPE_GT_KITCHEN: "滚筒鸡",
		SCORE_TYPE_XQ_KITCHEN: "星期鸡",

		SCORE_TYPE_STAND_KITCHEN:             "站鸡",
		SCORE_TYPE_STAND_JIN_KITCHEN:         "金站鸡",
		SCORE_TYPE_STAND_JIN_JIN_KITCHEN:     "金站鸡",
		SCORE_TYPE_BAO_STAND_KITCHEN:         "包站鸡",
		SCORE_TYPE_BAO_STAND_JIN_KITCHEN:     "包金站鸡",
		SCORE_TYPE_BAO_STAND_JIN_JIN_KITCHEN: "包金站鸡",

		SCORE_TYPE_FIRST_CYCLE_CHARGE_KITCHEN:             "首圈鸡",
		SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_KITCHEN:         "金首圈鸡",
		SCORE_TYPE_FIRST_CYCLE_CHARGE_JIN_JIN_KITCHEN:     "金金首圈鸡",
		SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_KITCHEN:         "包首圈鸡",
		SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_JIN_KITCHEN:     "包金首圈鸡",
		SCORE_TYPE_BAO_FIRST_CYCLE_CHARGE_JIN_JIN_KITCHEN: "包金金首圈鸡",

		SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN:             "首圈责任鸡",
		SCORE_TYPE_RB_FIRST_CYCLE_JIN_KITCHEN:         "金首圈责任鸡",
		SCORE_TYPE_RB_FIRST_CYCLE_JIN_JIN_KITCHEN:     "金金首圈责任鸡",
		SCORE_TYPE_BAO_RB_FIRST_CYCLE_KITCHEN:         "包首圈责任鸡",
		SCORE_TYPE_BAO_RB_FIRST_CYCLE_JIN_KITCHEN:     "包金首圈责任鸡",
		SCORE_TYPE_BAO_RB_FIRST_CYCLE_JIN_JIN_KITCHEN: "包金金首圈责任鸡",

		SCORE_TYPE_TONG_SAN: "通三",

		SCORE_TYPE_PP_KITCHEN: "爬坡鸡",

		SCORE_TYPE_FLOWER_RED_KITCHEN_TING:         "红中(听)",
		SCORE_TYPE_FLOWER_RED_KITCHEN_WIN:          "红中(胡)",
		SCORE_TYPE_FLOWER_RED_KITCHEN_TING_DIAMOND: "钻石鸡(补花+听)",
		SCORE_TYPE_FLOWER_RED_KITCHEN_WIN_DIAMOND:  "钻石鸡(补花+胡)",

		SCORE_TYPE_SHABAO_SHUANG_LONG_7DUI:      "双龙七对（杀报）",
		SCORE_TYPE_SHABAO_SHUANG_LONG_7DUI_QING: "清双龙七对（杀报）",
		SCORE_TYPE_SHABAO_LONG_7DUI:             "龙七对（杀报）",
		SCORE_TYPE_SHABAO_LONG_7DUI_QING:        "清龙七对（杀报）",
		SCORE_TYPE_SHABAO_7DUI:                  "七对（杀报）",
		SCORE_TYPE_SHABAO_7DUI_QING:             "清七对（杀报）",
		SCORE_TYPE_SHABAO_DIQIDUI:               "地七对（杀报）",
		SCORE_TYPE_SHABAO_DIQIDUI_QING:          "清地七对（杀报）",
		SCORE_TYPE_SHABAO_DANDIAO:               "单吊（杀报）",
		SCORE_TYPE_SHABAO_DANDIAO_QING:          "清单吊（杀报）",
		SCORE_TYPE_SHABAO_DADUI:                 "大对（杀报）",
		SCORE_TYPE_SHABAO_DADUI_QING:            "清大对（杀报）",
		SCORE_TYPE_SHABAO_BIANKADIAO:            "边卡吊（杀报）",
		SCORE_TYPE_SHABAO_BIANKADIAO_QING:       "清边卡吊（杀报）",
		SCORE_TYPE_SHABAO_DAKUANZHANG:           "大宽张（杀报）",
		SCORE_TYPE_SHABAO_DAKUANZHANG_QING:      "清大宽张（杀报）",
		SCORE_TYPE_SHABAO_QING:                  "清一色（杀报）",
		SCORE_TYPE_SHABAO_HEPU_7DUI:             "合浦七对（杀报）",
		SCORE_TYPE_SHABAO_HEPU_7DUI_QING:        "清合浦七对（杀报）",

		SCORE_TYPE_J7W:       "见7挖",
		SCORE_TYPE_GWD:       "高挖弹",
		SCORE_TYPE_INIT_LACK: "原缺",
		SCORE_TYPE_LE:        "龙七对+3分",
	}

	FSTT = map[int]string{
		FRONT_SCORE_TYPE_ZHUANG:            "连庄",
		FRONT_SCORE_TYPE_ZHUANG_CONTINUE:   "着连庄",
		FRONT_SCORE_TYPE_ZHUANG_XIAZHUANG:  "庄家下庄",
		FRONT_SCORE_TYPE_KONG_DRAW:         "杠上开花",
		FRONT_SCORE_TYPE_KONG_DRAW_LOSER:   "着杠上开花",
		FRONT_SCORE_TYPE_TIANHU:            "天胡",
		FRONT_SCORE_TYPE_TIANHU_LOSER:      "着天胡",
		FRONT_SCORE_TYPE_DIHU:              "地胡",
		FRONT_SCORE_TYPE_DIHU_LOSER:        "着地胡",
		FRONT_SCORE_TYPE_BAOTING:           "报听",
		FRONT_SCORE_TYPE_BAOTING_LOSER:     "着报听",
		FRONT_SCORE_TYPE_QING:              "清一色",
		FRONT_SCORE_TYPE_QING_LOSER:        "着清一色",
		FRONT_SCORE_TYPE_FULL_CHIKEN:       "满鸡",
		FRONT_SCORE_TYPE_FULL_CHIKEN_LOSER: "着满鸡",

		FRONT_SCORE_TYPE_SHUANGLONGQIDUI:       "双龙7对",
		FRONT_SCORE_TYPE_SHUANGLONGQIDUI_LOSER: "着双龙7对",
		FRONT_SCORE_TYPE_LONGQIDUI:             "龙7对",
		FRONT_SCORE_TYPE_LONGQIDUI_LOSER:       "着龙7对",
		FRONT_SCORE_TYPE_QIDUI:                 "7对",
		FRONT_SCORE_TYPE_QIDUI_LOSER:           "着7对",
		FRONT_SCORE_TYPE_DIQIDUI:               "地7对",
		FRONT_SCORE_TYPE_DIQIDUI_LOSER:         "着地7对",
		FRONT_SCORE_TYPE_DANDIAO:               "单调",
		FRONT_SCORE_TYPE_DANDIAO_LOSER:         "着单调",
		FRONT_SCORE_TYPE_DADUI:                 "大对",
		FRONT_SCORE_TYPE_DADUI_LOSER:           "着大对",
		FRONT_SCORE_TYPE_DAKUAN:                "大宽张",
		FRONT_SCORE_TYPE_DAKUAN_LOSER:          "着大宽张",
		FRONT_SCORE_TYPE_BIANKADIAO:            "边卡吊",
		FRONT_SCORE_TYPE_BIANKADIAO_LOSER:      "着边卡吊",
		FRONT_SCORE_TYPE_PINGHU:                "平胡",
		FRONT_SCORE_TYPE_PINGHU_LOSER:          "着平胡",
		FRONT_SCORE_TYPE_PINGHU_ZIMO:           "平胡自摸",
		FRONT_SCORE_TYPE_PINGHU_ZIMO_LOSER:     "着平胡自摸",
		FRONT_SCORE_TYPE_XIAZHUANG:             "下庄",
		FRONT_SCORE_TYPE_DIANPAO:               "点炮",

		FRONT_SCORE_TYPE_BAO_KONG:        "包杠",
		FRONT_SCORE_TYPE_BAO_KONG_SHOURU: "包杠收入",
		FRONT_SCORE_TYPE_KONG_EXPOSED:    "明杠",
		FRONT_SCORE_TYPE_KONG_TURN:       "转弯杠",
		FRONT_SCORE_TYPE_KONG_TURN_LOSER: "着转弯杠",
		FRONT_SCORE_TYPE_KONG_DARK:       "暗杠",
		FRONT_SCORE_TYPE_KONG_DARK_LOSER: "着暗杠",
		FRONT_SCORE_TYPE_DIAN_KONG:       "点杠",

		FRONT_SCORE_TYPE_JI:                    "幺鸡",
		FRONT_SCORE_TYPE_JI_LOSER:              "着幺鸡",
		FRONT_SCORE_TYPE_SILVER_CHIKEN:         "银鸡",
		FRONT_SCORE_TYPE_SILVER_CHIKEN_LOSER:   "着银鸡",
		FRONT_SCORE_TYPE_CHARGE_JI:             "冲锋鸡",
		FRONT_SCORE_TYPE_CHARGE_JI_LOSER:       "着冲锋鸡",
		FRONT_SCORE_TYPE_JIN_JI:                "金鸡",
		FRONT_SCORE_TYPE_JIN_JI_LOSER:          "着金鸡",
		FRONT_SCORE_TYPE_JIN_CHARGE_JI:         "金冲锋鸡",
		FRONT_SCORE_TYPE_JIN_CHARGE_JI_LOSER:   "着金冲锋鸡",
		FRONT_SCORE_TYPE_WUGU:                  "乌骨鸡",
		FRONT_SCORE_TYPE_WUGU_LOSER:            "着乌骨鸡",
		FRONT_SCORE_TYPE_CHARGE_WUGU:           "冲锋乌骨鸡",
		FRONT_SCORE_TYPE_CHARGE_WUGU_LOSER:     "着冲锋乌骨鸡",
		FRONT_SCORE_TYPE_JIN_WUGU:              "金乌骨鸡",
		FRONT_SCORE_TYPE_JIN_WUGU_LOSER:        "着金乌骨鸡",
		FRONT_SCORE_TYPE_JIN_CHARGE_WUGU:       "金冲锋乌骨鸡",
		FRONT_SCORE_TYPE_JIN_CHARGE_WUGU_LOSER: "着金冲锋乌骨鸡",
		FRONT_SCORE_TYPE_FANPAI:                "翻牌鸡",
		FRONT_SCORE_TYPE_FANPAI_LOSER:          "着翻牌鸡",
		FRONT_SCORE_TYPE_UD:                    "上下鸡",
		FRONT_SCORE_TYPE_UD_LOSER:              "着上下鸡",
		FRONT_SCORE_TYPE_FB:                    "前后鸡",
		FRONT_SCORE_TYPE_FB_LOSER:              "着前后鸡",
		FRONT_SCORE_TYPE_YIWAI:                 "意外鸡",
		FRONT_SCORE_TYPE_XQ:                    "星期鸡",
		FRONT_SCORE_TYPE_XQ_LOSER:              "着星期鸡",
		FRONT_SCORE_TYPE_BEN:                   "本鸡",
		FRONT_SCORE_TYPE_BEN_LOSER:             "着本鸡",
		FRONT_SCORE_TYPE_TUMBLING:              "滚筒鸡",
		FRONT_SCORE_TYPE_TUMBLING_LOSER:        "着滚筒鸡",

		FRONT_SCORE_TYPE_DIAMOND:       "钻石鸡",
		FRONT_SCORE_TYPE_DIAMOND_LOSER: "着钻石鸡",

		FRONT_SCORE_TYPE_BAOPAI:                 "包牌",
		FRONT_SCORE_TYPE_BAOPAI_SHOURU:          "包牌收入",
		FRONT_SCORE_TYPE_BAOJI:                  "包鸡",
		FRONT_SCORE_TYPE_BAOJI_SHOURU:           "包鸡收入",
		FRONT_SCORE_TYPE_ZEREN:                  "责任鸡",
		FRONT_SCORE_TYPE_ZEREN_SHOURU:           "责任鸡收入",
		FRONT_SCORE_TYPE_CHAQUE:                 "查缺",
		FRONT_SCORE_TYPE_CHAQUE_SHOURU:          "查缺收入",
		FRONT_SCORE_TYPE_BEI_SHABAO:             "被杀报",
		FRONT_SCORE_TYPE_SHABAO:                 "杀报",
		FRONT_SCORE_TYPE_REPAO_KONG_EXPOSED:     "热炮(明杠)",
		FRONT_SCORE_TYPE_JIE_REPAO_KONG_EXPOSED: "接热炮(明杠)",
		FRONT_SCORE_TYPE_REPAO:                  "热炮(暗杠，转弯杠)",
		FRONT_SCORE_TYPE_JIE_REPAO:              "接热炮(暗杠，转弯杠)",
		FRONT_SCORE_TYPE_QIANG:                  "抢",
		FRONT_SCORE_TYPE_BEI_QIANG:              "被抢",

		FRONT_SCORE_TYPE_QING_EXTRA:       "清一色奖3分",
		FRONT_SCORE_TYPE_QING_EXTRA_LOSER: "着清一色奖3分",

		FRONT_SCORE_TYPE_ZIMO:             "自摸",
		FRONT_SCORE_TYPE_ZIMO_LOSER:       "着自摸",
		FRONT_SCORE_TYPE_ZIMO_EXTRA:       "自摸加一分",
		FRONT_SCORE_TYPE_ZIMO_EXTRA_LOSER: "着自摸加一分",

		FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN:       "首圈责任鸡收入",
		FRONT_SCORE_TYPE_RB_FIRST_CYCLE_KITCHEN_LOSER: "首圈责任鸡",

		FRONT_SCORE_TYPE_TONG_SAN:       "通三",
		FRONT_SCORE_TYPE_TONG_SAN_LOSER: "着通三",

		FRONT_SCORE_TYPE_PP_KITCHEN:       "爬坡鸡",
		FRONT_SCORE_TYPE_PP_KITCHEN_LOSER: "着爬坡鸡",

		// 补花鸡（红中）
		FRONT_SCORE_TYPE_FLOWER_RED_KITCHEN:       "红中",
		FRONT_SCORE_TYPE_FLOWER_RED_KITCHEN_LOSER: "着红中",
		// 补花钻石鸡（红中）
		FRONT_SCORE_TYPE_FLOWER_RED_DIAMOND_KITCHEN:       "钻石鸡",
		FRONT_SCORE_TYPE_FLOWER_RED_DIAMOND_KITCHEN_LOSER: "着钻石鸡",

		// 杀报牌型
		FRONT_SCORE_TYPE_BEI_SHABAO_HU_TYPE: "着杀报牌型",
		FRONT_SCORE_TYPE_SHABAO_HU_TYPE:     "杀报牌型",

		FRONT_SCORE_TYPE_J7W:       "见7挖",
		FRONT_SCORE_TYPE_J7W_LOSER: "着见7挖",

		FRONT_SCORE_TYPE_GWD:       "高挖弹",
		FRONT_SCORE_TYPE_GWD_LOSER: "着高挖弹",

		FRONT_SCORE_TYPE_INIT_LACK:       "原缺",
		FRONT_SCORE_TYPE_INIT_LACK_LOSER: "着原缺",

		FRONT_SCORE_TYPE_LE:       "龙七对+3分",
		FRONT_SCORE_TYPE_LE_LOSER: "着龙七对+3分",
	}
)
