# 所属环境
env="qa"
# 服务器版本, latest表示最新
version="latest"
#是否支持自定义牌, 0|1
enable_define_tiles=1
#消息推送地址
push_url="http://client.maxpanda.cn/client/push"
# 是否允许用户加入随机房间, 0|1
# 如果不允许, 会为每一个用户创建一个随机房间, 随后填充机器人
enable_join_random_room=0
# 是否允许指定随机房间的配置
enable_random_room_setting=0
# 是否允许自动托管, 0|1
enable_auto_hosting=1
# 俱乐部的地址
club_remote="127.0.0.1:38438"
# 回放存储方式 redis|oss
playback_save_type="oss"
# oss 配置
oss_endpoint="oss-cn-hangzhou-internal.aliyuncs.com"
oss_bucket="xxooxxoo"
oss_access_key_id="xxooxxoo"
oss_access_key_secret="xxooxxoo"
# 用户头像地址
user_avatar_url="http://s2.51gzmj.cn/icon/wxicon/%v/%v/%v/94.jpg"
# 联赛服务器地址
league_remote="127.0.0.1:31212"
# 联赛服务器获取用户raceId地址
leage_get_user_race_url="http://0.0.0.0:31213/getUserRace"
# 网关地址列表
gateway_remotes = ["127.0.0.1:29000"]
# 排位赛连胜奖励推送地址
rank_win_streak_rewards_url = "http://127.0.0.1:8484/client/notifyWinStreak"
# 选牌服务token验证地址
selector_token_verify_url = "http://10.26.239.72:8484/client/notifyRecommend"
