FROM golang:alpine as builder
WORKDIR $GOPATH/src
COPY start.sh .
ENV LANG=zh_CN.UTF-8
# 设置时区为上海
RUN apk add tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata \
    && chmod +x start.sh
ENTRYPOINT [ "./start.sh" ]
CMD ["bash"]