// Code generated by protoc-gen-go. DO NOT EDIT.
// source: club/club.proto

package pbclub

import (
	common "cy/game/pb/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClubMemberInfo struct {
	UserID               uint64   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Profile              string   `protobuf:"bytes,3,opt,name=Profile,proto3" json:"Profile,omitempty"`
	Online               int32    `protobuf:"varint,4,opt,name=Online,proto3" json:"Online,omitempty"`
	Identity             int32    `protobuf:"varint,5,opt,name=Identity,proto3" json:"Identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClubMemberInfo) Reset()         { *m = ClubMemberInfo{} }
func (m *ClubMemberInfo) String() string { return proto.CompactTextString(m) }
func (*ClubMemberInfo) ProtoMessage()    {}
func (*ClubMemberInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{0}
}

func (m *ClubMemberInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubMemberInfo.Unmarshal(m, b)
}
func (m *ClubMemberInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubMemberInfo.Marshal(b, m, deterministic)
}
func (m *ClubMemberInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubMemberInfo.Merge(m, src)
}
func (m *ClubMemberInfo) XXX_Size() int {
	return xxx_messageInfo_ClubMemberInfo.Size(m)
}
func (m *ClubMemberInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubMemberInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClubMemberInfo proto.InternalMessageInfo

func (m *ClubMemberInfo) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *ClubMemberInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ClubMemberInfo) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *ClubMemberInfo) GetOnline() int32 {
	if m != nil {
		return m.Online
	}
	return 0
}

func (m *ClubMemberInfo) GetIdentity() int32 {
	if m != nil {
		return m.Identity
	}
	return 0
}

type ClubInfo struct {
	ID                   int64             `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	MasterUserID         uint64            `protobuf:"varint,3,opt,name=MasterUserID,proto3" json:"MasterUserID,omitempty"`
	Notice               string            `protobuf:"bytes,4,opt,name=Notice,proto3" json:"Notice,omitempty"`
	Arg                  string            `protobuf:"bytes,5,opt,name=Arg,proto3" json:"Arg,omitempty"`
	Members              []*ClubMemberInfo `protobuf:"bytes,6,rep,name=Members,proto3" json:"Members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClubInfo) Reset()         { *m = ClubInfo{} }
func (m *ClubInfo) String() string { return proto.CompactTextString(m) }
func (*ClubInfo) ProtoMessage()    {}
func (*ClubInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{1}
}

func (m *ClubInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubInfo.Unmarshal(m, b)
}
func (m *ClubInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubInfo.Marshal(b, m, deterministic)
}
func (m *ClubInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubInfo.Merge(m, src)
}
func (m *ClubInfo) XXX_Size() int {
	return xxx_messageInfo_ClubInfo.Size(m)
}
func (m *ClubInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClubInfo proto.InternalMessageInfo

func (m *ClubInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ClubInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClubInfo) GetMasterUserID() uint64 {
	if m != nil {
		return m.MasterUserID
	}
	return 0
}

func (m *ClubInfo) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

func (m *ClubInfo) GetArg() string {
	if m != nil {
		return m.Arg
	}
	return ""
}

func (m *ClubInfo) GetMembers() []*ClubMemberInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

// ID查询俱乐部信息 c -> s
type QueryClubByIDReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	ClubID               int64           `protobuf:"varint,2,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryClubByIDReq) Reset()         { *m = QueryClubByIDReq{} }
func (m *QueryClubByIDReq) String() string { return proto.CompactTextString(m) }
func (*QueryClubByIDReq) ProtoMessage()    {}
func (*QueryClubByIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{2}
}

func (m *QueryClubByIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClubByIDReq.Unmarshal(m, b)
}
func (m *QueryClubByIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClubByIDReq.Marshal(b, m, deterministic)
}
func (m *QueryClubByIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClubByIDReq.Merge(m, src)
}
func (m *QueryClubByIDReq) XXX_Size() int {
	return xxx_messageInfo_QueryClubByIDReq.Size(m)
}
func (m *QueryClubByIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClubByIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClubByIDReq proto.InternalMessageInfo

func (m *QueryClubByIDReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryClubByIDReq) GetClubID() int64 {
	if m != nil {
		return m.ClubID
	}
	return 0
}

type QueryClubByIDRsp struct {
	Head                 *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Info                 *ClubInfo       `protobuf:"bytes,2,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryClubByIDRsp) Reset()         { *m = QueryClubByIDRsp{} }
func (m *QueryClubByIDRsp) String() string { return proto.CompactTextString(m) }
func (*QueryClubByIDRsp) ProtoMessage()    {}
func (*QueryClubByIDRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{3}
}

func (m *QueryClubByIDRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClubByIDRsp.Unmarshal(m, b)
}
func (m *QueryClubByIDRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClubByIDRsp.Marshal(b, m, deterministic)
}
func (m *QueryClubByIDRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClubByIDRsp.Merge(m, src)
}
func (m *QueryClubByIDRsp) XXX_Size() int {
	return xxx_messageInfo_QueryClubByIDRsp.Size(m)
}
func (m *QueryClubByIDRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClubByIDRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClubByIDRsp proto.InternalMessageInfo

func (m *QueryClubByIDRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryClubByIDRsp) GetInfo() *ClubInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ClubList struct {
	List                 []*ClubInfo `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClubList) Reset()         { *m = ClubList{} }
func (m *ClubList) String() string { return proto.CompactTextString(m) }
func (*ClubList) ProtoMessage()    {}
func (*ClubList) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{4}
}

func (m *ClubList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubList.Unmarshal(m, b)
}
func (m *ClubList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubList.Marshal(b, m, deterministic)
}
func (m *ClubList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubList.Merge(m, src)
}
func (m *ClubList) XXX_Size() int {
	return xxx_messageInfo_ClubList.Size(m)
}
func (m *ClubList) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubList.DiscardUnknown(m)
}

var xxx_messageInfo_ClubList proto.InternalMessageInfo

func (m *ClubList) GetList() []*ClubInfo {
	if m != nil {
		return m.List
	}
	return nil
}

// c -> s
type QueryClubByMemberReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	UserID               uint64          `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryClubByMemberReq) Reset()         { *m = QueryClubByMemberReq{} }
func (m *QueryClubByMemberReq) String() string { return proto.CompactTextString(m) }
func (*QueryClubByMemberReq) ProtoMessage()    {}
func (*QueryClubByMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{5}
}

func (m *QueryClubByMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClubByMemberReq.Unmarshal(m, b)
}
func (m *QueryClubByMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClubByMemberReq.Marshal(b, m, deterministic)
}
func (m *QueryClubByMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClubByMemberReq.Merge(m, src)
}
func (m *QueryClubByMemberReq) XXX_Size() int {
	return xxx_messageInfo_QueryClubByMemberReq.Size(m)
}
func (m *QueryClubByMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClubByMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClubByMemberReq proto.InternalMessageInfo

func (m *QueryClubByMemberReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryClubByMemberReq) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type QueryClubByMemberRsp struct {
	Head                 *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Infos                *ClubList       `protobuf:"bytes,2,opt,name=Infos,proto3" json:"Infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryClubByMemberRsp) Reset()         { *m = QueryClubByMemberRsp{} }
func (m *QueryClubByMemberRsp) String() string { return proto.CompactTextString(m) }
func (*QueryClubByMemberRsp) ProtoMessage()    {}
func (*QueryClubByMemberRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{6}
}

func (m *QueryClubByMemberRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClubByMemberRsp.Unmarshal(m, b)
}
func (m *QueryClubByMemberRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClubByMemberRsp.Marshal(b, m, deterministic)
}
func (m *QueryClubByMemberRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClubByMemberRsp.Merge(m, src)
}
func (m *QueryClubByMemberRsp) XXX_Size() int {
	return xxx_messageInfo_QueryClubByMemberRsp.Size(m)
}
func (m *QueryClubByMemberRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClubByMemberRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClubByMemberRsp proto.InternalMessageInfo

func (m *QueryClubByMemberRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryClubByMemberRsp) GetInfos() *ClubList {
	if m != nil {
		return m.Infos
	}
	return nil
}

// c -> s
type CreateClubReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Notice               string          `protobuf:"bytes,3,opt,name=Notice,proto3" json:"Notice,omitempty"`
	Arg                  string          `protobuf:"bytes,4,opt,name=Arg,proto3" json:"Arg,omitempty"`
	IsAutoCreate         bool            `protobuf:"varint,5,opt,name=IsAutoCreate,proto3" json:"IsAutoCreate,omitempty"`
	IsCustomGameArg      bool            `protobuf:"varint,6,opt,name=IsCustomGameArg,proto3" json:"IsCustomGameArg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateClubReq) Reset()         { *m = CreateClubReq{} }
func (m *CreateClubReq) String() string { return proto.CompactTextString(m) }
func (*CreateClubReq) ProtoMessage()    {}
func (*CreateClubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{7}
}

func (m *CreateClubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClubReq.Unmarshal(m, b)
}
func (m *CreateClubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClubReq.Marshal(b, m, deterministic)
}
func (m *CreateClubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClubReq.Merge(m, src)
}
func (m *CreateClubReq) XXX_Size() int {
	return xxx_messageInfo_CreateClubReq.Size(m)
}
func (m *CreateClubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClubReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClubReq proto.InternalMessageInfo

func (m *CreateClubReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *CreateClubReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateClubReq) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

func (m *CreateClubReq) GetArg() string {
	if m != nil {
		return m.Arg
	}
	return ""
}

func (m *CreateClubReq) GetIsAutoCreate() bool {
	if m != nil {
		return m.IsAutoCreate
	}
	return false
}

func (m *CreateClubReq) GetIsCustomGameArg() bool {
	if m != nil {
		return m.IsCustomGameArg
	}
	return false
}

type CreateClubRsp struct {
	Head *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	// 1成功 2失败
	Code                 int32     `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Info                 *ClubInfo `protobuf:"bytes,3,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateClubRsp) Reset()         { *m = CreateClubRsp{} }
func (m *CreateClubRsp) String() string { return proto.CompactTextString(m) }
func (*CreateClubRsp) ProtoMessage()    {}
func (*CreateClubRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{8}
}

func (m *CreateClubRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClubRsp.Unmarshal(m, b)
}
func (m *CreateClubRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClubRsp.Marshal(b, m, deterministic)
}
func (m *CreateClubRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClubRsp.Merge(m, src)
}
func (m *CreateClubRsp) XXX_Size() int {
	return xxx_messageInfo_CreateClubRsp.Size(m)
}
func (m *CreateClubRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClubRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClubRsp proto.InternalMessageInfo

func (m *CreateClubRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *CreateClubRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateClubRsp) GetInfo() *ClubInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// c -> s
type RemoveClubReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	ClubID               int64           `protobuf:"varint,2,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RemoveClubReq) Reset()         { *m = RemoveClubReq{} }
func (m *RemoveClubReq) String() string { return proto.CompactTextString(m) }
func (*RemoveClubReq) ProtoMessage()    {}
func (*RemoveClubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{9}
}

func (m *RemoveClubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveClubReq.Unmarshal(m, b)
}
func (m *RemoveClubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveClubReq.Marshal(b, m, deterministic)
}
func (m *RemoveClubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveClubReq.Merge(m, src)
}
func (m *RemoveClubReq) XXX_Size() int {
	return xxx_messageInfo_RemoveClubReq.Size(m)
}
func (m *RemoveClubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveClubReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveClubReq proto.InternalMessageInfo

func (m *RemoveClubReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *RemoveClubReq) GetClubID() int64 {
	if m != nil {
		return m.ClubID
	}
	return 0
}

type RemoveClubRsp struct {
	Head *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	// 1成功 2失败
	Code                 int32    `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveClubRsp) Reset()         { *m = RemoveClubRsp{} }
func (m *RemoveClubRsp) String() string { return proto.CompactTextString(m) }
func (*RemoveClubRsp) ProtoMessage()    {}
func (*RemoveClubRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{10}
}

func (m *RemoveClubRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveClubRsp.Unmarshal(m, b)
}
func (m *RemoveClubRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveClubRsp.Marshal(b, m, deterministic)
}
func (m *RemoveClubRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveClubRsp.Merge(m, src)
}
func (m *RemoveClubRsp) XXX_Size() int {
	return xxx_messageInfo_RemoveClubRsp.Size(m)
}
func (m *RemoveClubRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveClubRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveClubRsp proto.InternalMessageInfo

func (m *RemoveClubRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *RemoveClubRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// c -> s
type UpdateClubReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	ClubID               int64           `protobuf:"varint,2,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	Notice               string          `protobuf:"bytes,3,opt,name=Notice,proto3" json:"Notice,omitempty"`
	Arg                  string          `protobuf:"bytes,4,opt,name=Arg,proto3" json:"Arg,omitempty"`
	IsAutoCreate         bool            `protobuf:"varint,5,opt,name=IsAutoCreate,proto3" json:"IsAutoCreate,omitempty"`
	IsCustomGameArg      bool            `protobuf:"varint,6,opt,name=IsCustomGameArg,proto3" json:"IsCustomGameArg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateClubReq) Reset()         { *m = UpdateClubReq{} }
func (m *UpdateClubReq) String() string { return proto.CompactTextString(m) }
func (*UpdateClubReq) ProtoMessage()    {}
func (*UpdateClubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{11}
}

func (m *UpdateClubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClubReq.Unmarshal(m, b)
}
func (m *UpdateClubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClubReq.Marshal(b, m, deterministic)
}
func (m *UpdateClubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClubReq.Merge(m, src)
}
func (m *UpdateClubReq) XXX_Size() int {
	return xxx_messageInfo_UpdateClubReq.Size(m)
}
func (m *UpdateClubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClubReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClubReq proto.InternalMessageInfo

func (m *UpdateClubReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *UpdateClubReq) GetClubID() int64 {
	if m != nil {
		return m.ClubID
	}
	return 0
}

func (m *UpdateClubReq) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

func (m *UpdateClubReq) GetArg() string {
	if m != nil {
		return m.Arg
	}
	return ""
}

func (m *UpdateClubReq) GetIsAutoCreate() bool {
	if m != nil {
		return m.IsAutoCreate
	}
	return false
}

func (m *UpdateClubReq) GetIsCustomGameArg() bool {
	if m != nil {
		return m.IsCustomGameArg
	}
	return false
}

type UpdateClubRsp struct {
	Head *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	// 1成功 2失败
	Code                 int32    `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateClubRsp) Reset()         { *m = UpdateClubRsp{} }
func (m *UpdateClubRsp) String() string { return proto.CompactTextString(m) }
func (*UpdateClubRsp) ProtoMessage()    {}
func (*UpdateClubRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{12}
}

func (m *UpdateClubRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClubRsp.Unmarshal(m, b)
}
func (m *UpdateClubRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClubRsp.Marshal(b, m, deterministic)
}
func (m *UpdateClubRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClubRsp.Merge(m, src)
}
func (m *UpdateClubRsp) XXX_Size() int {
	return xxx_messageInfo_UpdateClubRsp.Size(m)
}
func (m *UpdateClubRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClubRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClubRsp proto.InternalMessageInfo

func (m *UpdateClubRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *UpdateClubRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// c -> s
type JoinClubReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	ClubID               int64           `protobuf:"varint,2,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *JoinClubReq) Reset()         { *m = JoinClubReq{} }
func (m *JoinClubReq) String() string { return proto.CompactTextString(m) }
func (*JoinClubReq) ProtoMessage()    {}
func (*JoinClubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{13}
}

func (m *JoinClubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinClubReq.Unmarshal(m, b)
}
func (m *JoinClubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinClubReq.Marshal(b, m, deterministic)
}
func (m *JoinClubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinClubReq.Merge(m, src)
}
func (m *JoinClubReq) XXX_Size() int {
	return xxx_messageInfo_JoinClubReq.Size(m)
}
func (m *JoinClubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinClubReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinClubReq proto.InternalMessageInfo

func (m *JoinClubReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *JoinClubReq) GetClubID() int64 {
	if m != nil {
		return m.ClubID
	}
	return 0
}

type JoinClubRsp struct {
	Head *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	// 1成功 2失败
	Code                 int32    `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinClubRsp) Reset()         { *m = JoinClubRsp{} }
func (m *JoinClubRsp) String() string { return proto.CompactTextString(m) }
func (*JoinClubRsp) ProtoMessage()    {}
func (*JoinClubRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{14}
}

func (m *JoinClubRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinClubRsp.Unmarshal(m, b)
}
func (m *JoinClubRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinClubRsp.Marshal(b, m, deterministic)
}
func (m *JoinClubRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinClubRsp.Merge(m, src)
}
func (m *JoinClubRsp) XXX_Size() int {
	return xxx_messageInfo_JoinClubRsp.Size(m)
}
func (m *JoinClubRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinClubRsp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinClubRsp proto.InternalMessageInfo

func (m *JoinClubRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *JoinClubRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// 退出俱乐部 c -> s
type ExitClubReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	ClubID               int64           `protobuf:"varint,2,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ExitClubReq) Reset()         { *m = ExitClubReq{} }
func (m *ExitClubReq) String() string { return proto.CompactTextString(m) }
func (*ExitClubReq) ProtoMessage()    {}
func (*ExitClubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{15}
}

func (m *ExitClubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitClubReq.Unmarshal(m, b)
}
func (m *ExitClubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitClubReq.Marshal(b, m, deterministic)
}
func (m *ExitClubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitClubReq.Merge(m, src)
}
func (m *ExitClubReq) XXX_Size() int {
	return xxx_messageInfo_ExitClubReq.Size(m)
}
func (m *ExitClubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitClubReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExitClubReq proto.InternalMessageInfo

func (m *ExitClubReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *ExitClubReq) GetClubID() int64 {
	if m != nil {
		return m.ClubID
	}
	return 0
}

type ExitClubRsp struct {
	Head *common.RspHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	// 1成功 2失败
	Code                 int32    `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitClubRsp) Reset()         { *m = ExitClubRsp{} }
func (m *ExitClubRsp) String() string { return proto.CompactTextString(m) }
func (*ExitClubRsp) ProtoMessage()    {}
func (*ExitClubRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{16}
}

func (m *ExitClubRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitClubRsp.Unmarshal(m, b)
}
func (m *ExitClubRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitClubRsp.Marshal(b, m, deterministic)
}
func (m *ExitClubRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitClubRsp.Merge(m, src)
}
func (m *ExitClubRsp) XXX_Size() int {
	return xxx_messageInfo_ExitClubRsp.Size(m)
}
func (m *ExitClubRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitClubRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ExitClubRsp proto.InternalMessageInfo

func (m *ExitClubRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *ExitClubRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// c -> s
type QueryClubDeskReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	ClubID               int64           `protobuf:"varint,2,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	Option               int32           `protobuf:"varint,3,opt,name=Option,proto3" json:"Option,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryClubDeskReq) Reset()         { *m = QueryClubDeskReq{} }
func (m *QueryClubDeskReq) String() string { return proto.CompactTextString(m) }
func (*QueryClubDeskReq) ProtoMessage()    {}
func (*QueryClubDeskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{17}
}

func (m *QueryClubDeskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClubDeskReq.Unmarshal(m, b)
}
func (m *QueryClubDeskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClubDeskReq.Marshal(b, m, deterministic)
}
func (m *QueryClubDeskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClubDeskReq.Merge(m, src)
}
func (m *QueryClubDeskReq) XXX_Size() int {
	return xxx_messageInfo_QueryClubDeskReq.Size(m)
}
func (m *QueryClubDeskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClubDeskReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClubDeskReq proto.InternalMessageInfo

func (m *QueryClubDeskReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryClubDeskReq) GetClubID() int64 {
	if m != nil {
		return m.ClubID
	}
	return 0
}

func (m *QueryClubDeskReq) GetOption() int32 {
	if m != nil {
		return m.Option
	}
	return 0
}

type QueryClubDeskRsp struct {
	Head                 *common.RspHead    `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Desks                []*common.DeskInfo `protobuf:"bytes,2,rep,name=Desks,proto3" json:"Desks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryClubDeskRsp) Reset()         { *m = QueryClubDeskRsp{} }
func (m *QueryClubDeskRsp) String() string { return proto.CompactTextString(m) }
func (*QueryClubDeskRsp) ProtoMessage()    {}
func (*QueryClubDeskRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c5ad7bb8a580e2, []int{18}
}

func (m *QueryClubDeskRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClubDeskRsp.Unmarshal(m, b)
}
func (m *QueryClubDeskRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClubDeskRsp.Marshal(b, m, deterministic)
}
func (m *QueryClubDeskRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClubDeskRsp.Merge(m, src)
}
func (m *QueryClubDeskRsp) XXX_Size() int {
	return xxx_messageInfo_QueryClubDeskRsp.Size(m)
}
func (m *QueryClubDeskRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClubDeskRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClubDeskRsp proto.InternalMessageInfo

func (m *QueryClubDeskRsp) GetHead() *common.RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *QueryClubDeskRsp) GetDesks() []*common.DeskInfo {
	if m != nil {
		return m.Desks
	}
	return nil
}

func init() {
	proto.RegisterType((*ClubMemberInfo)(nil), "pbclub.ClubMemberInfo")
	proto.RegisterType((*ClubInfo)(nil), "pbclub.ClubInfo")
	proto.RegisterType((*QueryClubByIDReq)(nil), "pbclub.QueryClubByIDReq")
	proto.RegisterType((*QueryClubByIDRsp)(nil), "pbclub.QueryClubByIDRsp")
	proto.RegisterType((*ClubList)(nil), "pbclub.ClubList")
	proto.RegisterType((*QueryClubByMemberReq)(nil), "pbclub.QueryClubByMemberReq")
	proto.RegisterType((*QueryClubByMemberRsp)(nil), "pbclub.QueryClubByMemberRsp")
	proto.RegisterType((*CreateClubReq)(nil), "pbclub.CreateClubReq")
	proto.RegisterType((*CreateClubRsp)(nil), "pbclub.CreateClubRsp")
	proto.RegisterType((*RemoveClubReq)(nil), "pbclub.RemoveClubReq")
	proto.RegisterType((*RemoveClubRsp)(nil), "pbclub.RemoveClubRsp")
	proto.RegisterType((*UpdateClubReq)(nil), "pbclub.UpdateClubReq")
	proto.RegisterType((*UpdateClubRsp)(nil), "pbclub.UpdateClubRsp")
	proto.RegisterType((*JoinClubReq)(nil), "pbclub.JoinClubReq")
	proto.RegisterType((*JoinClubRsp)(nil), "pbclub.JoinClubRsp")
	proto.RegisterType((*ExitClubReq)(nil), "pbclub.ExitClubReq")
	proto.RegisterType((*ExitClubRsp)(nil), "pbclub.ExitClubRsp")
	proto.RegisterType((*QueryClubDeskReq)(nil), "pbclub.QueryClubDeskReq")
	proto.RegisterType((*QueryClubDeskRsp)(nil), "pbclub.QueryClubDeskRsp")
}

func init() { proto.RegisterFile("club/club.proto", fileDescriptor_47c5ad7bb8a580e2) }

var fileDescriptor_47c5ad7bb8a580e2 = []byte{
	// 597 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x95, 0xd1, 0x6e, 0xda, 0x30,
	0x14, 0x86, 0x15, 0x12, 0x28, 0x1c, 0x4a, 0xcb, 0xac, 0xa9, 0x8a, 0xd0, 0x34, 0x21, 0x6b, 0x9b,
	0x72, 0x05, 0x15, 0x7b, 0x82, 0x0e, 0xa6, 0x35, 0xa8, 0xa5, 0xab, 0x25, 0xae, 0xa7, 0x04, 0xdc,
	0x2e, 0x1a, 0x89, 0xd3, 0xc4, 0x4c, 0xe3, 0x35, 0xf6, 0x20, 0x7b, 0x88, 0x5d, 0xec, 0xb9, 0xa6,
	0x63, 0xa7, 0x90, 0x30, 0x5a, 0x81, 0x40, 0xda, 0x0d, 0xf1, 0xf1, 0xb1, 0xff, 0x7c, 0xe7, 0xf8,
	0xc7, 0x81, 0xd3, 0xc9, 0x6c, 0xee, 0x77, 0xf1, 0xa7, 0x13, 0x27, 0x42, 0x0a, 0x52, 0x89, 0x7d,
	0x8c, 0x5a, 0xaf, 0x26, 0x8b, 0xee, 0xbd, 0x17, 0xf2, 0x6e, 0xec, 0x77, 0x27, 0x22, 0x0c, 0x45,
	0xd4, 0xfd, 0xca, 0xbd, 0xa9, 0x5e, 0xd5, 0x7a, 0xfd, 0x6f, 0x56, 0x3f, 0x74, 0x9e, 0xfe, 0x34,
	0xe0, 0xa4, 0x3f, 0x9b, 0xfb, 0xd7, 0x3c, 0xf4, 0x79, 0xe2, 0x46, 0x77, 0x82, 0x9c, 0x41, 0x65,
	0x9c, 0xf2, 0xc4, 0x1d, 0xd8, 0x46, 0xdb, 0x70, 0x2c, 0x96, 0x45, 0xa4, 0x05, 0x55, 0x1c, 0x8d,
	0xbc, 0x90, 0xdb, 0xa5, 0xb6, 0xe1, 0xd4, 0xd8, 0x32, 0x26, 0x36, 0x1c, 0x7d, 0x4e, 0xc4, 0x5d,
	0x30, 0xe3, 0xb6, 0xa9, 0x52, 0x8f, 0x21, 0xaa, 0xdd, 0x44, 0xb3, 0x20, 0xe2, 0xb6, 0xd5, 0x36,
	0x9c, 0x32, 0xcb, 0x22, 0x54, 0x73, 0xa7, 0x3c, 0x92, 0x81, 0x5c, 0xd8, 0x65, 0x95, 0x59, 0xc6,
	0xf4, 0x97, 0x01, 0x55, 0x84, 0x52, 0x38, 0x27, 0x50, 0xca, 0x50, 0x4c, 0x56, 0x72, 0x07, 0x84,
	0x80, 0x95, 0x43, 0x50, 0x63, 0x42, 0xe1, 0xf8, 0xda, 0x4b, 0x25, 0x4f, 0x32, 0x70, 0x53, 0x81,
	0x17, 0xe6, 0x10, 0x64, 0x24, 0x64, 0x30, 0xd1, 0x20, 0x35, 0x96, 0x45, 0xa4, 0x09, 0xe6, 0x45,
	0x72, 0xaf, 0x18, 0x6a, 0x0c, 0x87, 0xe4, 0x1c, 0x8e, 0x74, 0x3b, 0x52, 0xbb, 0xd2, 0x36, 0x9d,
	0x7a, 0xef, 0xac, 0xa3, 0x7b, 0xdd, 0x29, 0x76, 0x8a, 0x3d, 0x2e, 0xa3, 0xb7, 0xd0, 0xbc, 0x9d,
	0xf3, 0x64, 0x81, 0xf9, 0x0f, 0x0b, 0x77, 0xc0, 0xf8, 0x03, 0x79, 0x0b, 0xd6, 0x25, 0xf7, 0xa6,
	0x8a, 0xbc, 0xde, 0x7b, 0x81, 0x12, 0xba, 0xf1, 0x8c, 0x3f, 0x60, 0x82, 0xa9, 0x34, 0x62, 0xa9,
	0x52, 0x07, 0xaa, 0x20, 0x93, 0x65, 0x11, 0xfd, 0xb2, 0x2e, 0x99, 0xc6, 0xcf, 0x48, 0xa6, 0x71,
	0x4e, 0xf2, 0x0d, 0x58, 0x88, 0xa7, 0x04, 0xeb, 0xbd, 0x66, 0x1e, 0x5e, 0x61, 0xab, 0x2c, 0x3d,
	0xd7, 0x3d, 0xbe, 0x0a, 0x52, 0x89, 0x3b, 0xf0, 0x69, 0x1b, 0xaa, 0xdc, 0x0d, 0x3b, 0x30, 0x4b,
	0xc7, 0xf0, 0x32, 0x87, 0xa4, 0x6b, 0xdf, 0xad, 0xd2, 0xec, 0x78, 0x4a, 0x79, 0x5f, 0x51, 0xbe,
	0x49, 0x76, 0xfb, 0x6a, 0xdf, 0x41, 0x19, 0x19, 0xd3, 0x4d, 0xe5, 0x22, 0x36, 0xd3, 0x69, 0xfa,
	0xdb, 0x80, 0x46, 0x3f, 0xe1, 0x9e, 0xe4, 0x98, 0xd9, 0x81, 0x7b, 0x93, 0xe1, 0x56, 0x66, 0x32,
	0x37, 0x99, 0xc9, 0x5a, 0x99, 0x89, 0xc2, 0xb1, 0x9b, 0x5e, 0xcc, 0xa5, 0xd0, 0xef, 0x56, 0x3e,
	0xab, 0xb2, 0xc2, 0x1c, 0x71, 0xe0, 0xd4, 0x4d, 0xfb, 0xf3, 0x54, 0x8a, 0xf0, 0x93, 0x17, 0x72,
	0x54, 0xa8, 0xa8, 0x65, 0xeb, 0xd3, 0x34, 0x2e, 0xd4, 0xb0, 0x7d, 0x93, 0x08, 0x58, 0x7d, 0x31,
	0xd5, 0x35, 0x94, 0x99, 0x1a, 0x2f, 0x6d, 0x62, 0x3e, 0x6b, 0x93, 0x11, 0x34, 0x18, 0x0f, 0xc5,
	0xf7, 0x5d, 0xbb, 0xf6, 0x94, 0xaf, 0x87, 0x05, 0xbd, 0xbd, 0x2a, 0xa0, 0x7f, 0x0c, 0x68, 0x8c,
	0xe3, 0xe9, 0xee, 0x47, 0xfa, 0x04, 0xdc, 0x7f, 0x3b, 0xd6, 0x61, 0xa1, 0x8e, 0xfd, 0x9a, 0x72,
	0x05, 0xf5, 0xa1, 0x08, 0xa2, 0x03, 0x1d, 0xd7, 0x65, 0x4e, 0x6d, 0x6f, 0xae, 0x8f, 0x3f, 0x02,
	0x79, 0x38, 0xae, 0xa5, 0xda, 0x7e, 0x5c, 0x41, 0xee, 0xa2, 0x1d, 0xf0, 0xf4, 0xdb, 0x61, 0x6c,
	0x74, 0x13, 0xcb, 0x40, 0x44, 0xca, 0x46, 0xf8, 0xcd, 0x53, 0x11, 0x9d, 0xac, 0xbf, 0x6a, 0x7b,
	0x72, 0x07, 0xca, 0xb8, 0x03, 0x6f, 0x39, 0xbc, 0xa2, 0xc9, 0x6a, 0x1d, 0x4e, 0xab, 0xff, 0xab,
	0x5e, 0xe0, 0x57, 0xd4, 0x87, 0xfd, 0xfd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x17, 0xa4,
	0x09, 0x31, 0x08, 0x00, 0x00,
}
