// automatically generated by the FlatBuffers compiler, do not modify

package Common

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GatewayS2CCloseGamePush struct {
	_tab flatbuffers.Table
}

func GetRootAsGatewayS2CCloseGamePush(buf []byte, offset flatbuffers.UOffsetT) *GatewayS2CCloseGamePush {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GatewayS2CCloseGamePush{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GatewayS2CCloseGamePush) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GatewayS2CCloseGamePush) S2cResult(obj *GameResult) *GameResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(GameResult)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func GatewayS2CCloseGamePushStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GatewayS2CCloseGamePushAddS2cResult(builder *flatbuffers.Builder, s2cResult flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(s2cResult), 0)
}
func GatewayS2CCloseGamePushEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
