// automatically generated by the FlatBuffers compiler, do not modify

package Common

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LeagueApplyRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsLeagueApplyRequest(buf []byte, offset flatbuffers.UOffsetT) *LeagueApplyRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LeagueApplyRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LeagueApplyRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LeagueApplyRequest) LeagueId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LeagueApplyRequest) MutateLeagueId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func LeagueApplyRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LeagueApplyRequestAddLeagueId(builder *flatbuffers.Builder, leagueId int32) {
	builder.PrependInt32Slot(0, leagueId, 0)
}
func LeagueApplyRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
