[node]
[node.appwriter]
host="127.0.0.1"
port=3306
user="root"
passwd="SuUsW58Y"
db="maxpandaclient"
charset="utf8"
[node.appreader]
host="127.0.0.1"
port=3306
user="root"
passwd="SuUsW58Y"
db="maxpandaclient"
charset="utf8"
[node.logger]
host="127.0.0.1"
port=3306
user="root"
passwd="SuUsW58Y"
db="maxpandaclient"
charset="utf8"
