# 所属环境
env="product"
# 选服地址
select_server_url="http://xxooxxoo/leagueRoomServer"
# 获取我的房间信息接口
get_my_server_url="http://xxooxxoo/client/getMyServerForLocal"
# 通知发奖接口
rewards_notify_url="http://xxooxxoo:8484/client/notifyLeagueReward"
# 网关地址列表
gateway_remotes = ["xxooxxoo:29000","xxooxxoo:29000"]
