#!/usr/bin/env bash

# 项目的上层目录
srcdir="$GOPATH/src"
#项目名称
project="mahjong.club"
projectMonitor="mahjong.club.monitor"
#项目路径
projectdir="$srcdir/$project"
projectMonitordir="$srcdir/$project/tools/monitor"
#nohup存放目录
nohupDir="/data/mahjong.nohup"

# 更新代码
pull () {
	cd $projectdir
	echo "git checkout [$1]..."

	# 检出分支
	git checkout master
	git pull
	git checkout $1
	git pull
	cd -
}

# 编译安装
install () {
	# 编译主程序
	cd $projectdir
	echo "编译主程序"
	echo "go build -o $GOBIN/$project.$1"
	go build -o "$GOBIN/$project.$1"
	echo "主程序编译完成"
	cd -

	# 编译监控程序
	cd $projectMonitordir
	echo "编译监控程序"
	echo "go build -o $GOBIN/$projectMonitor"
	go build -o "$GOBIN/$projectMonitor"
	echo "监控程序编译完成"
	cd -
}

# 启动进程
start() {
	echo "启动主进程"
	echo "nohup ../../bin/$project.$3 -env=$1 -port=$2 >> $nohupDir/$project.nohup.out.$3 2>&1 &"
	nohup ../../bin/$project.$3 -env=$1  -port=$2 >> $nohupDir/$project.nohup.out.$3 2>&1 &
	echo "服务启动完成..."

	echo "启动监控程序"
	echo "nohup ../../bin/$projectMonitor -v=$3 -env=$1 -p=$2 >> $nohupDir/$projectMonitor.nohup.out.$3 2>&1 &"
	nohup ../../bin/$projectMonitor -v=$3 -env=$1 -p=$2 >> $nohupDir/$projectMonitor.nohup.out.$3 2>&1 &
	echo "监控程序启动完成..."

}

# 关闭进程
stop() {
	echo "关闭服务器 $1"
	ps -ef | grep $project | grep $1 | grep -v grep |awk '{print $2}' |xargs kill
	echo "进程已关闭"

	echo "关闭监控程序"
	ps -ef | grep $projectMonitor | grep -v grep |awk '{print $2}' |xargs kill
	echo "监控程序已关闭"
}

# 部署
deploy() {
	# 更新代码 pull tag/branch
	pull $3
	# 编译安装 install version
	install $3
	# 关闭旧程序 stop server
	stop $2
	# 开启新服务 start server version
	start $1 $2 $3
}

# 帮助
help() {
	echo "Usage:"
	echo "1. ./deploy pull tag/branch, eg: ./deploy pull 1.0.0"
	echo "2. ./deploy install version, eg: ./deploy install 1.0.0"
	echo "3. ./deploy stop  port, eg: ./deploy stop 38438"
	echo "4. ./deploy start server version port, eg: ./deploy start product 38438 1.0.0 "

	echo "Usage:"
	echo "./deploy deploy server version tag/branch port, eg: ./deploy deploy product 38438 1.0.0"

	echo "Usage:"
	echo "./deploy all, show all running process, eg: ./deploy all"
}

all() {
	ps -ef | grep $project | grep -v grep
}

case "$1" in 
	help)
		$1
		;;
	all)
		$1
		;;
	start)
		$1 $2 $3 $4
		;;
	stop)
		$1 $2
		;;
	pull)
		$1 $2
		;;
	install)
		$1 $2
		;;
	deploy)
		$1 $2 $3 $4
		;;
	*)
	help
	exit 2
esac
