// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game/mj/mj_changshou.proto

package pbgame_mj_changshou

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Int32XX struct {
	T                    int32    `protobuf:"varint,1,opt,name=T,proto3" json:"T,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32XX) Reset()         { *m = Int32XX{} }
func (m *Int32XX) String() string { return proto.CompactTextString(m) }
func (*Int32XX) ProtoMessage()    {}
func (*Int32XX) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{0}
}

func (m *Int32XX) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32XX.Unmarshal(m, b)
}
func (m *Int32XX) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32XX.Marshal(b, m, deterministic)
}
func (m *Int32XX) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32XX.Merge(m, src)
}
func (m *Int32XX) XXX_Size() int {
	return xxx_messageInfo_Int32XX.Size(m)
}
func (m *Int32XX) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32XX.DiscardUnknown(m)
}

var xxx_messageInfo_Int32XX proto.InternalMessageInfo

func (m *Int32XX) GetT() int32 {
	if m != nil {
		return m.T
	}
	return 0
}

///////////////////////////c-s///////////////////////////
// 出牌
type C2SOutCard struct {
	Card                 int32    `protobuf:"varint,1,opt,name=card,proto3" json:"card,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SOutCard) Reset()         { *m = C2SOutCard{} }
func (m *C2SOutCard) String() string { return proto.CompactTextString(m) }
func (*C2SOutCard) ProtoMessage()    {}
func (*C2SOutCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{1}
}

func (m *C2SOutCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SOutCard.Unmarshal(m, b)
}
func (m *C2SOutCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SOutCard.Marshal(b, m, deterministic)
}
func (m *C2SOutCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SOutCard.Merge(m, src)
}
func (m *C2SOutCard) XXX_Size() int {
	return xxx_messageInfo_C2SOutCard.Size(m)
}
func (m *C2SOutCard) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SOutCard.DiscardUnknown(m)
}

var xxx_messageInfo_C2SOutCard proto.InternalMessageInfo

func (m *C2SOutCard) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

//碰牌
type C2SPengCard struct {
	Card                 int32    `protobuf:"varint,1,opt,name=card,proto3" json:"card,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SPengCard) Reset()         { *m = C2SPengCard{} }
func (m *C2SPengCard) String() string { return proto.CompactTextString(m) }
func (*C2SPengCard) ProtoMessage()    {}
func (*C2SPengCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{2}
}

func (m *C2SPengCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SPengCard.Unmarshal(m, b)
}
func (m *C2SPengCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SPengCard.Marshal(b, m, deterministic)
}
func (m *C2SPengCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SPengCard.Merge(m, src)
}
func (m *C2SPengCard) XXX_Size() int {
	return xxx_messageInfo_C2SPengCard.Size(m)
}
func (m *C2SPengCard) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SPengCard.DiscardUnknown(m)
}

var xxx_messageInfo_C2SPengCard proto.InternalMessageInfo

func (m *C2SPengCard) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

//杠牌
type C2SGangCard struct {
	Card                 int32    `protobuf:"varint,1,opt,name=card,proto3" json:"card,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SGangCard) Reset()         { *m = C2SGangCard{} }
func (m *C2SGangCard) String() string { return proto.CompactTextString(m) }
func (*C2SGangCard) ProtoMessage()    {}
func (*C2SGangCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{3}
}

func (m *C2SGangCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SGangCard.Unmarshal(m, b)
}
func (m *C2SGangCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SGangCard.Marshal(b, m, deterministic)
}
func (m *C2SGangCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SGangCard.Merge(m, src)
}
func (m *C2SGangCard) XXX_Size() int {
	return xxx_messageInfo_C2SGangCard.Size(m)
}
func (m *C2SGangCard) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SGangCard.DiscardUnknown(m)
}

var xxx_messageInfo_C2SGangCard proto.InternalMessageInfo

func (m *C2SGangCard) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

//吃牌
type C2SChiCard struct {
	Card                 int32      `protobuf:"varint,1,opt,name=card,proto3" json:"card,omitempty"`
	WillCard             []*Int32XX `protobuf:"bytes,2,rep,name=will_card,json=willCard,proto3" json:"will_card,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *C2SChiCard) Reset()         { *m = C2SChiCard{} }
func (m *C2SChiCard) String() string { return proto.CompactTextString(m) }
func (*C2SChiCard) ProtoMessage()    {}
func (*C2SChiCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{4}
}

func (m *C2SChiCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SChiCard.Unmarshal(m, b)
}
func (m *C2SChiCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SChiCard.Marshal(b, m, deterministic)
}
func (m *C2SChiCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SChiCard.Merge(m, src)
}
func (m *C2SChiCard) XXX_Size() int {
	return xxx_messageInfo_C2SChiCard.Size(m)
}
func (m *C2SChiCard) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SChiCard.DiscardUnknown(m)
}

var xxx_messageInfo_C2SChiCard proto.InternalMessageInfo

func (m *C2SChiCard) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

func (m *C2SChiCard) GetWillCard() []*Int32XX {
	if m != nil {
		return m.WillCard
	}
	return nil
}

//胡牌
type C2SHuCard struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SHuCard) Reset()         { *m = C2SHuCard{} }
func (m *C2SHuCard) String() string { return proto.CompactTextString(m) }
func (*C2SHuCard) ProtoMessage()    {}
func (*C2SHuCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{5}
}

func (m *C2SHuCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SHuCard.Unmarshal(m, b)
}
func (m *C2SHuCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SHuCard.Marshal(b, m, deterministic)
}
func (m *C2SHuCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SHuCard.Merge(m, src)
}
func (m *C2SHuCard) XXX_Size() int {
	return xxx_messageInfo_C2SHuCard.Size(m)
}
func (m *C2SHuCard) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SHuCard.DiscardUnknown(m)
}

var xxx_messageInfo_C2SHuCard proto.InternalMessageInfo

//取消操作
type C2SCancelAction struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SCancelAction) Reset()         { *m = C2SCancelAction{} }
func (m *C2SCancelAction) String() string { return proto.CompactTextString(m) }
func (*C2SCancelAction) ProtoMessage()    {}
func (*C2SCancelAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{6}
}

func (m *C2SCancelAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SCancelAction.Unmarshal(m, b)
}
func (m *C2SCancelAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SCancelAction.Marshal(b, m, deterministic)
}
func (m *C2SCancelAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SCancelAction.Merge(m, src)
}
func (m *C2SCancelAction) XXX_Size() int {
	return xxx_messageInfo_C2SCancelAction.Size(m)
}
func (m *C2SCancelAction) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SCancelAction.DiscardUnknown(m)
}

var xxx_messageInfo_C2SCancelAction proto.InternalMessageInfo

//重连获取牌局信息
type C2SReconnectGame struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SReconnectGame) Reset()         { *m = C2SReconnectGame{} }
func (m *C2SReconnectGame) String() string { return proto.CompactTextString(m) }
func (*C2SReconnectGame) ProtoMessage()    {}
func (*C2SReconnectGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{7}
}

func (m *C2SReconnectGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SReconnectGame.Unmarshal(m, b)
}
func (m *C2SReconnectGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SReconnectGame.Marshal(b, m, deterministic)
}
func (m *C2SReconnectGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SReconnectGame.Merge(m, src)
}
func (m *C2SReconnectGame) XXX_Size() int {
	return xxx_messageInfo_C2SReconnectGame.Size(m)
}
func (m *C2SReconnectGame) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SReconnectGame.DiscardUnknown(m)
}

var xxx_messageInfo_C2SReconnectGame proto.InternalMessageInfo

///////////////////////////s-c///////////////////////////
//游戏开始
type UserInfo struct {
	UserPos              int32    `protobuf:"varint,1,opt,name=user_pos,json=userPos,proto3" json:"user_pos,omitempty"`
	DiceValue            int32    `protobuf:"varint,2,opt,name=dice_value,json=diceValue,proto3" json:"dice_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{8}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserPos() int32 {
	if m != nil {
		return m.UserPos
	}
	return 0
}

func (m *UserInfo) GetDiceValue() int32 {
	if m != nil {
		return m.DiceValue
	}
	return 0
}

type S2CStartGame struct {
	BankerId             int32       `protobuf:"varint,1,opt,name=banker_id,json=bankerId,proto3" json:"banker_id,omitempty"`
	UserInfo             []*UserInfo `protobuf:"bytes,2,rep,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *S2CStartGame) Reset()         { *m = S2CStartGame{} }
func (m *S2CStartGame) String() string { return proto.CompactTextString(m) }
func (*S2CStartGame) ProtoMessage()    {}
func (*S2CStartGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{9}
}

func (m *S2CStartGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CStartGame.Unmarshal(m, b)
}
func (m *S2CStartGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CStartGame.Marshal(b, m, deterministic)
}
func (m *S2CStartGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CStartGame.Merge(m, src)
}
func (m *S2CStartGame) XXX_Size() int {
	return xxx_messageInfo_S2CStartGame.Size(m)
}
func (m *S2CStartGame) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CStartGame.DiscardUnknown(m)
}

var xxx_messageInfo_S2CStartGame proto.InternalMessageInfo

func (m *S2CStartGame) GetBankerId() int32 {
	if m != nil {
		return m.BankerId
	}
	return 0
}

func (m *S2CStartGame) GetUserInfo() []*UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

//发牌
type S2CDealCard struct {
	CardFirst            int32      `protobuf:"varint,1,opt,name=card_first,json=cardFirst,proto3" json:"card_first,omitempty"`
	Cards                []*Int32XX `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *S2CDealCard) Reset()         { *m = S2CDealCard{} }
func (m *S2CDealCard) String() string { return proto.CompactTextString(m) }
func (*S2CDealCard) ProtoMessage()    {}
func (*S2CDealCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{10}
}

func (m *S2CDealCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CDealCard.Unmarshal(m, b)
}
func (m *S2CDealCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CDealCard.Marshal(b, m, deterministic)
}
func (m *S2CDealCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CDealCard.Merge(m, src)
}
func (m *S2CDealCard) XXX_Size() int {
	return xxx_messageInfo_S2CDealCard.Size(m)
}
func (m *S2CDealCard) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CDealCard.DiscardUnknown(m)
}

var xxx_messageInfo_S2CDealCard proto.InternalMessageInfo

func (m *S2CDealCard) GetCardFirst() int32 {
	if m != nil {
		return m.CardFirst
	}
	return 0
}

func (m *S2CDealCard) GetCards() []*Int32XX {
	if m != nil {
		return m.Cards
	}
	return nil
}

//玩家摸牌
type S2CDrawCard struct {
	ChairId              int32    `protobuf:"varint,1,opt,name=chair_id,json=chairId,proto3" json:"chair_id,omitempty"`
	Card                 int32    `protobuf:"varint,2,opt,name=card,proto3" json:"card,omitempty"`
	LeftNum              int32    `protobuf:"varint,3,opt,name=left_num,json=leftNum,proto3" json:"left_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CDrawCard) Reset()         { *m = S2CDrawCard{} }
func (m *S2CDrawCard) String() string { return proto.CompactTextString(m) }
func (*S2CDrawCard) ProtoMessage()    {}
func (*S2CDrawCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{11}
}

func (m *S2CDrawCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CDrawCard.Unmarshal(m, b)
}
func (m *S2CDrawCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CDrawCard.Marshal(b, m, deterministic)
}
func (m *S2CDrawCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CDrawCard.Merge(m, src)
}
func (m *S2CDrawCard) XXX_Size() int {
	return xxx_messageInfo_S2CDrawCard.Size(m)
}
func (m *S2CDrawCard) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CDrawCard.DiscardUnknown(m)
}

var xxx_messageInfo_S2CDrawCard proto.InternalMessageInfo

func (m *S2CDrawCard) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *S2CDrawCard) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

func (m *S2CDrawCard) GetLeftNum() int32 {
	if m != nil {
		return m.LeftNum
	}
	return 0
}

//玩家出牌
type S2COutCard struct {
	ChairId              int32    `protobuf:"varint,1,opt,name=chair_id,json=chairId,proto3" json:"chair_id,omitempty"`
	Card                 int32    `protobuf:"varint,2,opt,name=card,proto3" json:"card,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2COutCard) Reset()         { *m = S2COutCard{} }
func (m *S2COutCard) String() string { return proto.CompactTextString(m) }
func (*S2COutCard) ProtoMessage()    {}
func (*S2COutCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{12}
}

func (m *S2COutCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2COutCard.Unmarshal(m, b)
}
func (m *S2COutCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2COutCard.Marshal(b, m, deterministic)
}
func (m *S2COutCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2COutCard.Merge(m, src)
}
func (m *S2COutCard) XXX_Size() int {
	return xxx_messageInfo_S2COutCard.Size(m)
}
func (m *S2COutCard) XXX_DiscardUnknown() {
	xxx_messageInfo_S2COutCard.DiscardUnknown(m)
}

var xxx_messageInfo_S2COutCard proto.InternalMessageInfo

func (m *S2COutCard) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *S2COutCard) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

//玩家该轮的操作
type S2CHaveOperation struct {
	Operation            string   `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CHaveOperation) Reset()         { *m = S2CHaveOperation{} }
func (m *S2CHaveOperation) String() string { return proto.CompactTextString(m) }
func (*S2CHaveOperation) ProtoMessage()    {}
func (*S2CHaveOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{13}
}

func (m *S2CHaveOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CHaveOperation.Unmarshal(m, b)
}
func (m *S2CHaveOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CHaveOperation.Marshal(b, m, deterministic)
}
func (m *S2CHaveOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CHaveOperation.Merge(m, src)
}
func (m *S2CHaveOperation) XXX_Size() int {
	return xxx_messageInfo_S2CHaveOperation.Size(m)
}
func (m *S2CHaveOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CHaveOperation.DiscardUnknown(m)
}

var xxx_messageInfo_S2CHaveOperation proto.InternalMessageInfo

func (m *S2CHaveOperation) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

//玩家碰牌
type S2CPengCard struct {
	ChairId              int32    `protobuf:"varint,1,opt,name=chair_id,json=chairId,proto3" json:"chair_id,omitempty"`
	Card                 int32    `protobuf:"varint,2,opt,name=card,proto3" json:"card,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CPengCard) Reset()         { *m = S2CPengCard{} }
func (m *S2CPengCard) String() string { return proto.CompactTextString(m) }
func (*S2CPengCard) ProtoMessage()    {}
func (*S2CPengCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{14}
}

func (m *S2CPengCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CPengCard.Unmarshal(m, b)
}
func (m *S2CPengCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CPengCard.Marshal(b, m, deterministic)
}
func (m *S2CPengCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CPengCard.Merge(m, src)
}
func (m *S2CPengCard) XXX_Size() int {
	return xxx_messageInfo_S2CPengCard.Size(m)
}
func (m *S2CPengCard) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CPengCard.DiscardUnknown(m)
}

var xxx_messageInfo_S2CPengCard proto.InternalMessageInfo

func (m *S2CPengCard) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *S2CPengCard) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

//玩家杠牌
type S2CGangCard struct {
	ChairId              int32    `protobuf:"varint,1,opt,name=chair_id,json=chairId,proto3" json:"chair_id,omitempty"`
	Card                 int32    `protobuf:"varint,2,opt,name=card,proto3" json:"card,omitempty"`
	GangType             int32    `protobuf:"varint,3,opt,name=gang_type,json=gangType,proto3" json:"gang_type,omitempty"`
	LoseChair            int32    `protobuf:"varint,4,opt,name=lose_chair,json=loseChair,proto3" json:"lose_chair,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CGangCard) Reset()         { *m = S2CGangCard{} }
func (m *S2CGangCard) String() string { return proto.CompactTextString(m) }
func (*S2CGangCard) ProtoMessage()    {}
func (*S2CGangCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{15}
}

func (m *S2CGangCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CGangCard.Unmarshal(m, b)
}
func (m *S2CGangCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CGangCard.Marshal(b, m, deterministic)
}
func (m *S2CGangCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CGangCard.Merge(m, src)
}
func (m *S2CGangCard) XXX_Size() int {
	return xxx_messageInfo_S2CGangCard.Size(m)
}
func (m *S2CGangCard) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CGangCard.DiscardUnknown(m)
}

var xxx_messageInfo_S2CGangCard proto.InternalMessageInfo

func (m *S2CGangCard) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *S2CGangCard) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

func (m *S2CGangCard) GetGangType() int32 {
	if m != nil {
		return m.GangType
	}
	return 0
}

func (m *S2CGangCard) GetLoseChair() int32 {
	if m != nil {
		return m.LoseChair
	}
	return 0
}

//玩家吃牌
type S2CChiCard struct {
	ChairId              int32      `protobuf:"varint,1,opt,name=chair_id,json=chairId,proto3" json:"chair_id,omitempty"`
	Card                 int32      `protobuf:"varint,2,opt,name=card,proto3" json:"card,omitempty"`
	CardTable            []*Int32XX `protobuf:"bytes,3,rep,name=card_table,json=cardTable,proto3" json:"card_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *S2CChiCard) Reset()         { *m = S2CChiCard{} }
func (m *S2CChiCard) String() string { return proto.CompactTextString(m) }
func (*S2CChiCard) ProtoMessage()    {}
func (*S2CChiCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{16}
}

func (m *S2CChiCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CChiCard.Unmarshal(m, b)
}
func (m *S2CChiCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CChiCard.Marshal(b, m, deterministic)
}
func (m *S2CChiCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CChiCard.Merge(m, src)
}
func (m *S2CChiCard) XXX_Size() int {
	return xxx_messageInfo_S2CChiCard.Size(m)
}
func (m *S2CChiCard) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CChiCard.DiscardUnknown(m)
}

var xxx_messageInfo_S2CChiCard proto.InternalMessageInfo

func (m *S2CChiCard) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *S2CChiCard) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

func (m *S2CChiCard) GetCardTable() []*Int32XX {
	if m != nil {
		return m.CardTable
	}
	return nil
}

//玩家胡牌
type S2CHuCard struct {
	ChairId              int32      `protobuf:"varint,1,opt,name=chair_id,json=chairId,proto3" json:"chair_id,omitempty"`
	CardTable            []*Int32XX `protobuf:"bytes,2,rep,name=card_table,json=cardTable,proto3" json:"card_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *S2CHuCard) Reset()         { *m = S2CHuCard{} }
func (m *S2CHuCard) String() string { return proto.CompactTextString(m) }
func (*S2CHuCard) ProtoMessage()    {}
func (*S2CHuCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{17}
}

func (m *S2CHuCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CHuCard.Unmarshal(m, b)
}
func (m *S2CHuCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CHuCard.Marshal(b, m, deterministic)
}
func (m *S2CHuCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CHuCard.Merge(m, src)
}
func (m *S2CHuCard) XXX_Size() int {
	return xxx_messageInfo_S2CHuCard.Size(m)
}
func (m *S2CHuCard) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CHuCard.DiscardUnknown(m)
}

var xxx_messageInfo_S2CHuCard proto.InternalMessageInfo

func (m *S2CHuCard) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *S2CHuCard) GetCardTable() []*Int32XX {
	if m != nil {
		return m.CardTable
	}
	return nil
}

//倒计时显示在谁头上
type S2CTimeoutChair struct {
	ChairId              int32    `protobuf:"varint,1,opt,name=chair_id,json=chairId,proto3" json:"chair_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CTimeoutChair) Reset()         { *m = S2CTimeoutChair{} }
func (m *S2CTimeoutChair) String() string { return proto.CompactTextString(m) }
func (*S2CTimeoutChair) ProtoMessage()    {}
func (*S2CTimeoutChair) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{18}
}

func (m *S2CTimeoutChair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CTimeoutChair.Unmarshal(m, b)
}
func (m *S2CTimeoutChair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CTimeoutChair.Marshal(b, m, deterministic)
}
func (m *S2CTimeoutChair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CTimeoutChair.Merge(m, src)
}
func (m *S2CTimeoutChair) XXX_Size() int {
	return xxx_messageInfo_S2CTimeoutChair.Size(m)
}
func (m *S2CTimeoutChair) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CTimeoutChair.DiscardUnknown(m)
}

var xxx_messageInfo_S2CTimeoutChair proto.InternalMessageInfo

func (m *S2CTimeoutChair) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

type PlayerBalanceInfo struct {
	HuType   string `protobuf:"bytes,1,opt,name=hu_type,json=huType,proto3" json:"hu_type,omitempty"`
	GangType string `protobuf:"bytes,2,opt,name=gang_type,json=gangType,proto3" json:"gang_type,omitempty"`
	//暗杠数,接杠数,放杠数,明杠数
	HuCard               int32      `protobuf:"varint,3,opt,name=hu_card,json=huCard,proto3" json:"hu_card,omitempty"`
	HandCard             []*Int32XX `protobuf:"bytes,4,rep,name=hand_card,json=handCard,proto3" json:"hand_card,omitempty"`
	Point                int32      `protobuf:"varint,5,opt,name=point,proto3" json:"point,omitempty"`
	TotalPoint           int32      `protobuf:"varint,6,opt,name=total_point,json=totalPoint,proto3" json:"total_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PlayerBalanceInfo) Reset()         { *m = PlayerBalanceInfo{} }
func (m *PlayerBalanceInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerBalanceInfo) ProtoMessage()    {}
func (*PlayerBalanceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{19}
}

func (m *PlayerBalanceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerBalanceInfo.Unmarshal(m, b)
}
func (m *PlayerBalanceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerBalanceInfo.Marshal(b, m, deterministic)
}
func (m *PlayerBalanceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerBalanceInfo.Merge(m, src)
}
func (m *PlayerBalanceInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerBalanceInfo.Size(m)
}
func (m *PlayerBalanceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerBalanceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerBalanceInfo proto.InternalMessageInfo

func (m *PlayerBalanceInfo) GetHuType() string {
	if m != nil {
		return m.HuType
	}
	return ""
}

func (m *PlayerBalanceInfo) GetGangType() string {
	if m != nil {
		return m.GangType
	}
	return ""
}

func (m *PlayerBalanceInfo) GetHuCard() int32 {
	if m != nil {
		return m.HuCard
	}
	return 0
}

func (m *PlayerBalanceInfo) GetHandCard() []*Int32XX {
	if m != nil {
		return m.HandCard
	}
	return nil
}

func (m *PlayerBalanceInfo) GetPoint() int32 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *PlayerBalanceInfo) GetTotalPoint() int32 {
	if m != nil {
		return m.TotalPoint
	}
	return 0
}

//单局游戏结束
type S2CGameEnd struct {
	GameIndex            int32                `protobuf:"varint,1,opt,name=game_index,json=gameIndex,proto3" json:"game_index,omitempty"`
	HuChair              int32                `protobuf:"varint,2,opt,name=hu_chair,json=huChair,proto3" json:"hu_chair,omitempty"`
	Banker               int32                `protobuf:"varint,3,opt,name=banker,proto3" json:"banker,omitempty"`
	PlayerBalance        []*PlayerBalanceInfo `protobuf:"bytes,4,rep,name=player_balance,json=playerBalance,proto3" json:"player_balance,omitempty"`
	Isdeuce              bool                 `protobuf:"varint,5,opt,name=isdeuce,proto3" json:"isdeuce,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *S2CGameEnd) Reset()         { *m = S2CGameEnd{} }
func (m *S2CGameEnd) String() string { return proto.CompactTextString(m) }
func (*S2CGameEnd) ProtoMessage()    {}
func (*S2CGameEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{20}
}

func (m *S2CGameEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CGameEnd.Unmarshal(m, b)
}
func (m *S2CGameEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CGameEnd.Marshal(b, m, deterministic)
}
func (m *S2CGameEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CGameEnd.Merge(m, src)
}
func (m *S2CGameEnd) XXX_Size() int {
	return xxx_messageInfo_S2CGameEnd.Size(m)
}
func (m *S2CGameEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CGameEnd.DiscardUnknown(m)
}

var xxx_messageInfo_S2CGameEnd proto.InternalMessageInfo

func (m *S2CGameEnd) GetGameIndex() int32 {
	if m != nil {
		return m.GameIndex
	}
	return 0
}

func (m *S2CGameEnd) GetHuChair() int32 {
	if m != nil {
		return m.HuChair
	}
	return 0
}

func (m *S2CGameEnd) GetBanker() int32 {
	if m != nil {
		return m.Banker
	}
	return 0
}

func (m *S2CGameEnd) GetPlayerBalance() []*PlayerBalanceInfo {
	if m != nil {
		return m.PlayerBalance
	}
	return nil
}

func (m *S2CGameEnd) GetIsdeuce() bool {
	if m != nil {
		return m.Isdeuce
	}
	return false
}

type PlayerBalanceResult struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Point                int32    `protobuf:"varint,2,opt,name=point,proto3" json:"point,omitempty"`
	HuPai                int32    `protobuf:"varint,3,opt,name=huPai,proto3" json:"huPai,omitempty"`
	DianPao              int32    `protobuf:"varint,4,opt,name=dianPao,proto3" json:"dianPao,omitempty"`
	AnGang               int32    `protobuf:"varint,5,opt,name=anGang,proto3" json:"anGang,omitempty"`
	MingGang             int32    `protobuf:"varint,6,opt,name=mingGang,proto3" json:"mingGang,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerBalanceResult) Reset()         { *m = PlayerBalanceResult{} }
func (m *PlayerBalanceResult) String() string { return proto.CompactTextString(m) }
func (*PlayerBalanceResult) ProtoMessage()    {}
func (*PlayerBalanceResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{21}
}

func (m *PlayerBalanceResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerBalanceResult.Unmarshal(m, b)
}
func (m *PlayerBalanceResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerBalanceResult.Marshal(b, m, deterministic)
}
func (m *PlayerBalanceResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerBalanceResult.Merge(m, src)
}
func (m *PlayerBalanceResult) XXX_Size() int {
	return xxx_messageInfo_PlayerBalanceResult.Size(m)
}
func (m *PlayerBalanceResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerBalanceResult.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerBalanceResult proto.InternalMessageInfo

func (m *PlayerBalanceResult) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PlayerBalanceResult) GetPoint() int32 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *PlayerBalanceResult) GetHuPai() int32 {
	if m != nil {
		return m.HuPai
	}
	return 0
}

func (m *PlayerBalanceResult) GetDianPao() int32 {
	if m != nil {
		return m.DianPao
	}
	return 0
}

func (m *PlayerBalanceResult) GetAnGang() int32 {
	if m != nil {
		return m.AnGang
	}
	return 0
}

func (m *PlayerBalanceResult) GetMingGang() int32 {
	if m != nil {
		return m.MingGang
	}
	return 0
}

//大局结算
type S2CBalanceResult struct {
	RoomName             string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	PlayerResult         []*PlayerBalanceResult `protobuf:"bytes,2,rep,name=player_result,json=playerResult,proto3" json:"player_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *S2CBalanceResult) Reset()         { *m = S2CBalanceResult{} }
func (m *S2CBalanceResult) String() string { return proto.CompactTextString(m) }
func (*S2CBalanceResult) ProtoMessage()    {}
func (*S2CBalanceResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{22}
}

func (m *S2CBalanceResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CBalanceResult.Unmarshal(m, b)
}
func (m *S2CBalanceResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CBalanceResult.Marshal(b, m, deterministic)
}
func (m *S2CBalanceResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CBalanceResult.Merge(m, src)
}
func (m *S2CBalanceResult) XXX_Size() int {
	return xxx_messageInfo_S2CBalanceResult.Size(m)
}
func (m *S2CBalanceResult) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CBalanceResult.DiscardUnknown(m)
}

var xxx_messageInfo_S2CBalanceResult proto.InternalMessageInfo

func (m *S2CBalanceResult) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *S2CBalanceResult) GetPlayerResult() []*PlayerBalanceResult {
	if m != nil {
		return m.PlayerResult
	}
	return nil
}

type CardInfo struct {
	ChairId  int32 `protobuf:"varint,1,opt,name=chair_id,json=chairId,proto3" json:"chair_id,omitempty"`
	OutCards int32 `protobuf:"varint,2,opt,name=out_cards,json=outCards,proto3" json:"out_cards,omitempty"`
	//玩家碰的牌 json {"12":1,"13":1}->碰了2萬 3萬
	PengCards string `protobuf:"bytes,3,opt,name=peng_cards,json=pengCards,proto3" json:"peng_cards,omitempty"`
	//玩家杠的牌 json {"16":2}-> 杠了6萬（1:明杠(碰牌后再杠)，2:暗杠，3:接杠)
	GangCards string `protobuf:"bytes,4,opt,name=gang_cards,json=gangCards,proto3" json:"gang_cards,omitempty"`
	//玩家吃的牌[11,12,13;22,23,24],3个连续的组成吃
	ChiCards             []*Int32XX `protobuf:"bytes,5,rep,name=chi_cards,json=chiCards,proto3" json:"chi_cards,omitempty"`
	HandCards            []*Int32XX `protobuf:"bytes,6,rep,name=hand_cards,json=handCards,proto3" json:"hand_cards,omitempty"`
	CardNum              int32      `protobuf:"varint,7,opt,name=card_num,json=cardNum,proto3" json:"card_num,omitempty"`
	Point                int32      `protobuf:"varint,8,opt,name=point,proto3" json:"point,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CardInfo) Reset()         { *m = CardInfo{} }
func (m *CardInfo) String() string { return proto.CompactTextString(m) }
func (*CardInfo) ProtoMessage()    {}
func (*CardInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{23}
}

func (m *CardInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardInfo.Unmarshal(m, b)
}
func (m *CardInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardInfo.Marshal(b, m, deterministic)
}
func (m *CardInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardInfo.Merge(m, src)
}
func (m *CardInfo) XXX_Size() int {
	return xxx_messageInfo_CardInfo.Size(m)
}
func (m *CardInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CardInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CardInfo proto.InternalMessageInfo

func (m *CardInfo) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *CardInfo) GetOutCards() int32 {
	if m != nil {
		return m.OutCards
	}
	return 0
}

func (m *CardInfo) GetPengCards() string {
	if m != nil {
		return m.PengCards
	}
	return ""
}

func (m *CardInfo) GetGangCards() string {
	if m != nil {
		return m.GangCards
	}
	return ""
}

func (m *CardInfo) GetChiCards() []*Int32XX {
	if m != nil {
		return m.ChiCards
	}
	return nil
}

func (m *CardInfo) GetHandCards() []*Int32XX {
	if m != nil {
		return m.HandCards
	}
	return nil
}

func (m *CardInfo) GetCardNum() int32 {
	if m != nil {
		return m.CardNum
	}
	return 0
}

func (m *CardInfo) GetPoint() int32 {
	if m != nil {
		return m.Point
	}
	return 0
}

//重连获取牌局信息
type S2CReconnectGame struct {
	PlayerCard *CardInfo `protobuf:"bytes,1,opt,name=player_card,json=playerCard,proto3" json:"player_card,omitempty"`
	//玩家可執行的操作 json  [{"canPeng":true}] [{"canGang":[42]}]
	CanOperation         string   `protobuf:"bytes,2,opt,name=can_operation,json=canOperation,proto3" json:"can_operation,omitempty"`
	CurOutChair          int32    `protobuf:"varint,3,opt,name=cur_out_chair,json=curOutChair,proto3" json:"cur_out_chair,omitempty"`
	LastOutChair         int32    `protobuf:"varint,4,opt,name=last_out_chair,json=lastOutChair,proto3" json:"last_out_chair,omitempty"`
	LastOutCard          int32    `protobuf:"varint,5,opt,name=last_out_card,json=lastOutCard,proto3" json:"last_out_card,omitempty"`
	Banker               int32    `protobuf:"varint,6,opt,name=banker,proto3" json:"banker,omitempty"`
	LeftNum              int32    `protobuf:"varint,7,opt,name=left_num,json=leftNum,proto3" json:"left_num,omitempty"`
	GameIndex            int32    `protobuf:"varint,8,opt,name=game_index,json=gameIndex,proto3" json:"game_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CReconnectGame) Reset()         { *m = S2CReconnectGame{} }
func (m *S2CReconnectGame) String() string { return proto.CompactTextString(m) }
func (*S2CReconnectGame) ProtoMessage()    {}
func (*S2CReconnectGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ff6895602b8062, []int{24}
}

func (m *S2CReconnectGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CReconnectGame.Unmarshal(m, b)
}
func (m *S2CReconnectGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CReconnectGame.Marshal(b, m, deterministic)
}
func (m *S2CReconnectGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CReconnectGame.Merge(m, src)
}
func (m *S2CReconnectGame) XXX_Size() int {
	return xxx_messageInfo_S2CReconnectGame.Size(m)
}
func (m *S2CReconnectGame) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CReconnectGame.DiscardUnknown(m)
}

var xxx_messageInfo_S2CReconnectGame proto.InternalMessageInfo

func (m *S2CReconnectGame) GetPlayerCard() *CardInfo {
	if m != nil {
		return m.PlayerCard
	}
	return nil
}

func (m *S2CReconnectGame) GetCanOperation() string {
	if m != nil {
		return m.CanOperation
	}
	return ""
}

func (m *S2CReconnectGame) GetCurOutChair() int32 {
	if m != nil {
		return m.CurOutChair
	}
	return 0
}

func (m *S2CReconnectGame) GetLastOutChair() int32 {
	if m != nil {
		return m.LastOutChair
	}
	return 0
}

func (m *S2CReconnectGame) GetLastOutCard() int32 {
	if m != nil {
		return m.LastOutCard
	}
	return 0
}

func (m *S2CReconnectGame) GetBanker() int32 {
	if m != nil {
		return m.Banker
	}
	return 0
}

func (m *S2CReconnectGame) GetLeftNum() int32 {
	if m != nil {
		return m.LeftNum
	}
	return 0
}

func (m *S2CReconnectGame) GetGameIndex() int32 {
	if m != nil {
		return m.GameIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*Int32XX)(nil), "pbgame_mj_changshou.int32XX")
	proto.RegisterType((*C2SOutCard)(nil), "pbgame_mj_changshou.C2SOutCard")
	proto.RegisterType((*C2SPengCard)(nil), "pbgame_mj_changshou.C2SPengCard")
	proto.RegisterType((*C2SGangCard)(nil), "pbgame_mj_changshou.C2SGangCard")
	proto.RegisterType((*C2SChiCard)(nil), "pbgame_mj_changshou.C2SChiCard")
	proto.RegisterType((*C2SHuCard)(nil), "pbgame_mj_changshou.C2SHuCard")
	proto.RegisterType((*C2SCancelAction)(nil), "pbgame_mj_changshou.C2SCancelAction")
	proto.RegisterType((*C2SReconnectGame)(nil), "pbgame_mj_changshou.C2SReconnectGame")
	proto.RegisterType((*UserInfo)(nil), "pbgame_mj_changshou.UserInfo")
	proto.RegisterType((*S2CStartGame)(nil), "pbgame_mj_changshou.S2CStartGame")
	proto.RegisterType((*S2CDealCard)(nil), "pbgame_mj_changshou.S2CDealCard")
	proto.RegisterType((*S2CDrawCard)(nil), "pbgame_mj_changshou.S2CDrawCard")
	proto.RegisterType((*S2COutCard)(nil), "pbgame_mj_changshou.S2COutCard")
	proto.RegisterType((*S2CHaveOperation)(nil), "pbgame_mj_changshou.S2CHaveOperation")
	proto.RegisterType((*S2CPengCard)(nil), "pbgame_mj_changshou.S2CPengCard")
	proto.RegisterType((*S2CGangCard)(nil), "pbgame_mj_changshou.S2CGangCard")
	proto.RegisterType((*S2CChiCard)(nil), "pbgame_mj_changshou.S2CChiCard")
	proto.RegisterType((*S2CHuCard)(nil), "pbgame_mj_changshou.S2CHuCard")
	proto.RegisterType((*S2CTimeoutChair)(nil), "pbgame_mj_changshou.S2CTimeoutChair")
	proto.RegisterType((*PlayerBalanceInfo)(nil), "pbgame_mj_changshou.PlayerBalanceInfo")
	proto.RegisterType((*S2CGameEnd)(nil), "pbgame_mj_changshou.S2CGameEnd")
	proto.RegisterType((*PlayerBalanceResult)(nil), "pbgame_mj_changshou.PlayerBalanceResult")
	proto.RegisterType((*S2CBalanceResult)(nil), "pbgame_mj_changshou.S2CBalanceResult")
	proto.RegisterType((*CardInfo)(nil), "pbgame_mj_changshou.CardInfo")
	proto.RegisterType((*S2CReconnectGame)(nil), "pbgame_mj_changshou.S2CReconnectGame")
}

func init() { proto.RegisterFile("game/mj/mj_changshou.proto", fileDescriptor_09ff6895602b8062) }

var fileDescriptor_09ff6895602b8062 = []byte{
	// 1012 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x6e, 0xdc, 0xc4,
	0x17, 0xd7, 0x6e, 0xb2, 0xbb, 0xf6, 0xd9, 0xa4, 0x4d, 0xdd, 0xea, 0xdf, 0x4d, 0xd3, 0xea, 0x1f,
	0x06, 0x84, 0x72, 0x81, 0x52, 0xe4, 0x5e, 0x85, 0x22, 0x24, 0x70, 0xa1, 0xcd, 0x45, 0x93, 0x95,
	0x1d, 0xa0, 0x12, 0x17, 0x66, 0xd6, 0x3b, 0x59, 0xbb, 0xd8, 0x33, 0x96, 0xed, 0x69, 0x93, 0x1b,
	0xde, 0x85, 0x4b, 0x9e, 0x80, 0x47, 0xe0, 0x05, 0x78, 0x20, 0x74, 0xce, 0x8c, 0xf7, 0xa3, 0x24,
	0x4d, 0xf6, 0xce, 0xe7, 0x63, 0xe6, 0xcc, 0xef, 0x77, 0xbe, 0x0c, 0x8f, 0x66, 0xbc, 0x10, 0x4f,
	0x8b, 0xb7, 0x4f, 0x8b, 0xb7, 0x71, 0x92, 0x72, 0x39, 0xab, 0x53, 0xa5, 0x0f, 0xcb, 0x4a, 0x35,
	0xca, 0xbb, 0x5f, 0x4e, 0xd0, 0x1a, 0x2f, 0x9b, 0xd8, 0x43, 0x18, 0x64, 0xb2, 0x79, 0xe6, 0xbf,
	0x79, 0xe3, 0x6d, 0x41, 0xe7, 0x6c, 0xd4, 0xd9, 0xef, 0x1c, 0xf4, 0xc2, 0xce, 0x19, 0xdb, 0x07,
	0x08, 0xfc, 0xe8, 0x54, 0x37, 0x01, 0xaf, 0xa6, 0x9e, 0x07, 0x9b, 0x09, 0xaf, 0xa6, 0xd6, 0x4c,
	0xdf, 0xec, 0x13, 0x18, 0x06, 0x7e, 0x34, 0x16, 0x72, 0x76, 0x83, 0xcb, 0x4b, 0xfe, 0x11, 0x97,
	0x5f, 0x28, 0x4e, 0x90, 0x66, 0xd7, 0x79, 0x78, 0x47, 0xe0, 0xbe, 0xcf, 0xf2, 0x3c, 0x26, 0x43,
	0x77, 0x7f, 0xe3, 0x60, 0xe8, 0x3f, 0x3e, 0xbc, 0x02, 0xcb, 0xa1, 0x05, 0x12, 0x3a, 0xe8, 0x8e,
	0xd7, 0xb1, 0x21, 0xb8, 0x81, 0x1f, 0xbd, 0xd2, 0x24, 0xdc, 0x83, 0xbb, 0x18, 0x89, 0xcb, 0x44,
	0xe4, 0xdf, 0x26, 0x4d, 0xa6, 0x24, 0xf3, 0x60, 0x27, 0xf0, 0xa3, 0x50, 0x24, 0x4a, 0x4a, 0x91,
	0x34, 0x2f, 0x79, 0x21, 0xd8, 0x0b, 0x70, 0x7e, 0xac, 0x45, 0x75, 0x2c, 0xcf, 0x95, 0xb7, 0x0b,
	0x8e, 0xae, 0x45, 0x15, 0x97, 0xaa, 0xb6, 0x4f, 0x1a, 0xa0, 0x3c, 0x56, 0xb5, 0xf7, 0x04, 0x60,
	0x9a, 0x25, 0x22, 0x7e, 0xc7, 0x73, 0x2d, 0x46, 0x5d, 0x32, 0xba, 0xa8, 0xf9, 0x09, 0x15, 0x6c,
	0x06, 0x5b, 0x91, 0x1f, 0x44, 0x0d, 0xaf, 0xe8, 0x56, 0x6f, 0x0f, 0xdc, 0x09, 0x97, 0xbf, 0x89,
	0x2a, 0xce, 0x5a, 0x74, 0x8e, 0x51, 0x1c, 0x4f, 0xbd, 0xaf, 0xc0, 0xa5, 0x30, 0x99, 0x3c, 0x57,
	0x16, 0xe1, 0x93, 0x2b, 0x11, 0xb6, 0x0f, 0x0b, 0xe9, 0x59, 0xf8, 0xc5, 0x7e, 0x85, 0x61, 0xe4,
	0x07, 0x2f, 0x04, 0x27, 0xc4, 0xf8, 0x2c, 0xe4, 0x29, 0x3e, 0xcf, 0xaa, 0xba, 0xb1, 0x81, 0x5c,
	0xd4, 0xfc, 0x80, 0x0a, 0xcf, 0x87, 0x1e, 0x0a, 0xf5, 0xad, 0x78, 0x34, 0xae, 0xec, 0x67, 0x13,
	0xa1, 0xe2, 0xef, 0x29, 0xc2, 0x2e, 0x38, 0x49, 0xca, 0xb3, 0x25, 0x20, 0x03, 0x92, 0x8f, 0x17,
	0xd9, 0xeb, 0x2e, 0x65, 0x6f, 0x17, 0x9c, 0x5c, 0x9c, 0x37, 0xb1, 0xd4, 0xc5, 0x68, 0xc3, 0xb8,
	0xa3, 0x7c, 0xa2, 0x0b, 0xf6, 0x1c, 0x20, 0xf2, 0x83, 0xb6, 0xc4, 0xd6, 0xbb, 0x97, 0x7d, 0x09,
	0x3b, 0x91, 0x1f, 0xbc, 0xe2, 0xef, 0xc4, 0x69, 0x29, 0x2a, 0x8e, 0xe9, 0xf4, 0x1e, 0x83, 0xab,
	0x5a, 0x81, 0xee, 0x70, 0xc3, 0x85, 0x82, 0x7d, 0x4d, 0x38, 0xe6, 0xf5, 0xba, 0x66, 0xbc, 0x0b,
	0x3a, 0x3d, 0x2f, 0xe5, 0x35, 0x59, 0xd8, 0x03, 0x77, 0xc6, 0xe5, 0x2c, 0x6e, 0x2e, 0x4b, 0x61,
	0x69, 0x70, 0x50, 0x71, 0x76, 0x59, 0x0a, 0xcc, 0x59, 0xae, 0x6a, 0x11, 0xd3, 0x05, 0xa3, 0x4d,
	0x93, 0x33, 0xd4, 0x04, 0xa8, 0x60, 0x17, 0x44, 0x53, 0xdb, 0x21, 0x6b, 0x06, 0x7e, 0x6e, 0xeb,
	0xa1, 0xe1, 0x93, 0x1c, 0x23, 0xdf, 0x9c, 0x75, 0xaa, 0x96, 0x33, 0x74, 0x67, 0x09, 0xb8, 0xc8,
	0xb1, 0xbe, 0x29, 0xf0, 0x6a, 0x90, 0xee, 0x7a, 0x41, 0xbe, 0x80, 0xbb, 0x91, 0x1f, 0x9c, 0x65,
	0x85, 0x50, 0xba, 0x21, 0xc4, 0x1f, 0x09, 0xc5, 0xfe, 0xe9, 0xc0, 0xbd, 0x71, 0xce, 0x2f, 0x45,
	0xf5, 0x1d, 0xcf, 0xb1, 0x95, 0xa9, 0x4f, 0x1f, 0xc2, 0x20, 0xd5, 0x86, 0x5c, 0x93, 0xf6, 0x7e,
	0xaa, 0x89, 0xda, 0x15, 0xde, 0xbb, 0x64, 0x5a, 0xf0, 0x6e, 0x4e, 0x11, 0x65, 0x26, 0x25, 0xfd,
	0xd4, 0x40, 0x3d, 0x02, 0x37, 0xe5, 0x72, 0x6a, 0x4c, 0x9b, 0xb7, 0x99, 0x38, 0xe8, 0x4e, 0x47,
	0x1f, 0x40, 0xaf, 0x54, 0x99, 0x6c, 0x46, 0x3d, 0xba, 0xd1, 0x08, 0xde, 0xff, 0x61, 0xd8, 0xa8,
	0x86, 0xe7, 0xb1, 0xb1, 0xf5, 0xc9, 0x06, 0xa4, 0x1a, 0xa3, 0x86, 0xfd, 0xdd, 0xa1, 0x24, 0xe3,
	0xa8, 0xf8, 0x5e, 0x52, 0x17, 0x53, 0xb0, 0x4c, 0x4e, 0xc5, 0x45, 0xdb, 0xc5, 0xa8, 0x39, 0x46,
	0x05, 0xf2, 0x83, 0x0f, 0xa7, 0x72, 0x31, 0xc9, 0x1e, 0xa4, 0xda, 0x50, 0xf7, 0x3f, 0xe8, 0x9b,
	0xb1, 0xd2, 0x42, 0x32, 0x92, 0xf7, 0x1a, 0xee, 0x94, 0x44, 0x5b, 0x3c, 0x31, 0xbc, 0x59, 0x5c,
	0x9f, 0x5f, 0x89, 0xeb, 0x3f, 0x0c, 0x87, 0xdb, 0xe5, 0xb2, 0xca, 0x1b, 0xc1, 0x20, 0xab, 0xa7,
	0x42, 0x27, 0x82, 0x80, 0x3a, 0x61, 0x2b, 0xb2, 0x3f, 0x3a, 0x70, 0x7f, 0xe5, 0x78, 0x28, 0x6a,
	0x9d, 0x37, 0xde, 0x0e, 0x6c, 0xe8, 0x79, 0x3a, 0xf1, 0x73, 0x41, 0x55, 0x77, 0x99, 0xaa, 0x07,
	0xd0, 0x4b, 0xf5, 0x98, 0x67, 0xf6, 0xfd, 0x46, 0xc0, 0x78, 0xd3, 0x8c, 0xcb, 0x31, 0x57, 0xb6,
	0x3f, 0x5a, 0x11, 0x01, 0x73, 0x89, 0x6d, 0x69, 0x19, 0xb7, 0x92, 0xf7, 0x08, 0x9c, 0x22, 0x93,
	0x33, 0xb2, 0x18, 0xbe, 0xe7, 0x32, 0xfb, 0x9d, 0x66, 0xc7, 0xea, 0xfb, 0xf6, 0xc0, 0xad, 0x94,
	0x2a, 0x62, 0xc9, 0x8b, 0xb6, 0x88, 0x1c, 0x54, 0x9c, 0xe0, 0xf4, 0x7e, 0x0d, 0x16, 0x7f, 0x5c,
	0x91, 0xb7, 0xad, 0xf1, 0x83, 0x9b, 0xc9, 0x33, 0xb7, 0x87, 0x5b, 0xe6, 0xb8, 0x91, 0xd8, 0x9f,
	0x5d, 0x70, 0xb0, 0x5a, 0xda, 0x1d, 0x73, 0x5d, 0x5f, 0xed, 0x81, 0xab, 0x74, 0x13, 0xb7, 0x13,
	0x9b, 0x40, 0x28, 0x33, 0x2e, 0x69, 0x01, 0x95, 0x42, 0xce, 0xac, 0x75, 0xc3, 0x4c, 0xbb, 0xd2,
	0x4e, 0xb7, 0xda, 0x94, 0xd0, 0xdc, 0xbc, 0x69, 0xcc, 0x33, 0xde, 0x9a, 0x8f, 0xc0, 0x4d, 0xd2,
	0xcc, 0x5a, 0x7b, 0xb7, 0x29, 0xf1, 0xc4, 0x0c, 0xa0, 0x1a, 0xbb, 0x7d, 0xde, 0x1d, 0xf5, 0xa8,
	0x7f, 0x9b, 0x6e, 0x6f, 0xdb, 0xa3, 0x26, 0xb4, 0x38, 0x2a, 0x70, 0x1d, 0x0c, 0x2c, 0x5a, 0x5e,
	0x4d, 0x4f, 0x74, 0xb1, 0xa8, 0x07, 0x67, 0xa9, 0x1e, 0xd8, 0x5f, 0x5d, 0x4a, 0xd6, 0xca, 0x8e,
	0xf6, 0xbe, 0x81, 0xa1, 0xcd, 0xc7, 0xfc, 0x6f, 0xe1, 0xba, 0x95, 0xd9, 0xf2, 0x1c, 0x82, 0x39,
	0x41, 0x5d, 0xfa, 0x29, 0x6c, 0x27, 0x5c, 0xc6, 0x8b, 0x65, 0x61, 0x46, 0xc3, 0x56, 0xc2, 0xe5,
	0x62, 0x9b, 0x30, 0xd8, 0x4e, 0x74, 0x15, 0x53, 0x06, 0xa8, 0xd5, 0x4c, 0x45, 0x0e, 0x13, 0x5d,
	0x9d, 0xb6, 0x93, 0xea, 0x33, 0xb8, 0x93, 0xf3, 0xba, 0x59, 0x72, 0x32, 0xe5, 0xb9, 0x85, 0xda,
	0xb9, 0x17, 0x83, 0xed, 0x85, 0x17, 0x3e, 0xd8, 0x94, 0xea, 0xb0, 0x75, 0xc2, 0x27, 0x2d, 0x1a,
	0xb7, 0xbf, 0xd2, 0xb8, 0xcb, 0xfb, 0x73, 0xb0, 0xb2, 0x3f, 0x3f, 0x98, 0x12, 0xce, 0x07, 0x53,
	0x62, 0xd2, 0xa7, 0xdf, 0xbe, 0x67, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x34, 0x1b, 0xcb, 0xed,
	0x14, 0x0a, 0x00, 0x00,
}
