// automatically generated by the FlatBuffers compiler, do not modify

package Common

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MatchRoomRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsMatchRoomRequest(buf []byte, offset flatbuffers.UOffsetT) *MatchRoomRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MatchRoomRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *MatchRoomRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MatchRoomRequest) GameType() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MatchRoomRequest) MutateGameType(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func MatchRoomRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MatchRoomRequestAddGameType(builder *flatbuffers.Builder, gameType uint16) {
	builder.PrependUint16Slot(0, gameType, 0)
}
func MatchRoomRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
