// automatically generated by the FlatBuffers compiler, do not modify

package Common

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClubG2CRoomActiveRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsClubG2CRoomActiveRequest(buf []byte, offset flatbuffers.UOffsetT) *ClubG2CRoomActiveRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClubG2CRoomActiveRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ClubG2CRoomActiveRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClubG2CRoomActiveRequest) ClubId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClubG2CRoomActiveRequest) MutateClubId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *ClubG2CRoomActiveRequest) RoomId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClubG2CRoomActiveRequest) MutateRoomId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func ClubG2CRoomActiveRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ClubG2CRoomActiveRequestAddClubId(builder *flatbuffers.Builder, clubId int32) {
	builder.PrependInt32Slot(0, clubId, 0)
}
func ClubG2CRoomActiveRequestAddRoomId(builder *flatbuffers.Builder, roomId uint64) {
	builder.PrependUint64Slot(1, roomId, 0)
}
func ClubG2CRoomActiveRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
