// automatically generated by the FlatBuffers compiler, do not modify

package Common

const (
	GameTypeGameType_NONE = 0
	GameTypeMAHJONG_GY = 1
	GameTypeMAHJONG_BJ = 2
	GameTypeMAHJONG_ZY = 3
	GameTypeMAHJONG_SD = 4
	GameTypeMAHJONG_LD = 5
	GameTypeMAHJONG_STT = 6
	GameTypeMAHJONG_XY = 7
	GameTypeMAHJONG_LPS = 8
	GameTypeMAHJONG_KL = 9
	GameTypeMAHJONG_DY = 10
	GameTypeMAHJONG_AS = 11
	GameTypeMAHJONG_TR = 12
	GameTypeMAHJONG_GYA = 13
	GameTypeMAHJONG_QX = 14
	GameTypeMAHJONG_JS = 15
	GameTypeMAHJONG_ZYA = 16
	GameTypeMAHJONG_RH = 17
	GameTypeMAHJONG_GFT = 18
	GameTypeMAHJONG_GYE3 = 19
	GameTypeMAHJONG_GYE4 = 20
	GameTypeExtra1 = 81
	GameTypeExtra2 = 82
	GameTypeExtra3 = 83
	GameTypeExtra4 = 84
	GameTypeExtra5 = 85
	GameTypeExtra6 = 86
	GameTypeExtra7 = 87
	GameTypeExtra8 = 88
	GameTypeExtra9 = 89
	GameTypeExtra10 = 90
	GameTypeExtra11 = 91
	GameTypeExtra12 = 92
	GameTypeExtra13 = 93
	GameTypeExtra14 = 94
	GameTypeExtra15 = 95
	GameTypeExtra16 = 96
	GameTypeExtra17 = 97
	GameTypeExtra18 = 98
	GameTypeExtra19 = 99
	GameTypeMAHJONG_MATCH_GZ_1 = 100
	GameTypeMAHJONG_MATCH_GZ_2 = 101
	GameTypeMAHJONG_MATCH_GZ_3 = 102
	GameTypeMAHJONG_MATCH_GZ_4 = 103
)

var EnumNamesGameType = map[int]string{
	GameTypeGameType_NONE:"GameType_NONE",
	GameTypeMAHJONG_GY:"MAHJONG_GY",
	GameTypeMAHJONG_BJ:"MAHJONG_BJ",
	GameTypeMAHJONG_ZY:"MAHJONG_ZY",
	GameTypeMAHJONG_SD:"MAHJONG_SD",
	GameTypeMAHJONG_LD:"MAHJONG_LD",
	GameTypeMAHJONG_STT:"MAHJONG_STT",
	GameTypeMAHJONG_XY:"MAHJONG_XY",
	GameTypeMAHJONG_LPS:"MAHJONG_LPS",
	GameTypeMAHJONG_KL:"MAHJONG_KL",
	GameTypeMAHJONG_DY:"MAHJONG_DY",
	GameTypeMAHJONG_AS:"MAHJONG_AS",
	GameTypeMAHJONG_TR:"MAHJONG_TR",
	GameTypeMAHJONG_GYA:"MAHJONG_GYA",
	GameTypeMAHJONG_QX:"MAHJONG_QX",
	GameTypeMAHJONG_JS:"MAHJONG_JS",
	GameTypeMAHJONG_ZYA:"MAHJONG_ZYA",
	GameTypeMAHJONG_RH:"MAHJONG_RH",
	GameTypeMAHJONG_GFT:"MAHJONG_GFT",
	GameTypeMAHJONG_GYE3:"MAHJONG_GYE3",
	GameTypeMAHJONG_GYE4:"MAHJONG_GYE4",
	GameTypeExtra1:"Extra1",
	GameTypeExtra2:"Extra2",
	GameTypeExtra3:"Extra3",
	GameTypeExtra4:"Extra4",
	GameTypeExtra5:"Extra5",
	GameTypeExtra6:"Extra6",
	GameTypeExtra7:"Extra7",
	GameTypeExtra8:"Extra8",
	GameTypeExtra9:"Extra9",
	GameTypeExtra10:"Extra10",
	GameTypeExtra11:"Extra11",
	GameTypeExtra12:"Extra12",
	GameTypeExtra13:"Extra13",
	GameTypeExtra14:"Extra14",
	GameTypeExtra15:"Extra15",
	GameTypeExtra16:"Extra16",
	GameTypeExtra17:"Extra17",
	GameTypeExtra18:"Extra18",
	GameTypeExtra19:"Extra19",
	GameTypeMAHJONG_MATCH_GZ_1:"MAHJONG_MATCH_GZ_1",
	GameTypeMAHJONG_MATCH_GZ_2:"MAHJONG_MATCH_GZ_2",
	GameTypeMAHJONG_MATCH_GZ_3:"MAHJONG_MATCH_GZ_3",
	GameTypeMAHJONG_MATCH_GZ_4:"MAHJONG_MATCH_GZ_4",
}

