// automatically generated by the FlatBuffers compiler, do not modify

package Common

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClubReloadRoomPush struct {
	_tab flatbuffers.Table
}

func GetRootAsClubReloadRoomPush(buf []byte, offset flatbuffers.UOffsetT) *ClubReloadRoomPush {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClubReloadRoomPush{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ClubReloadRoomPush) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClubReloadRoomPush) ClubId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClubReloadRoomPush) MutateClubId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *ClubReloadRoomPush) Room(obj *Room) *Room {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Room)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ClubReloadRoomPushStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ClubReloadRoomPushAddClubId(builder *flatbuffers.Builder, clubId int32) {
	builder.PrependInt32Slot(0, clubId, 0)
}
func ClubReloadRoomPushAddRoom(builder *flatbuffers.Builder, room flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(room), 0)
}
func ClubReloadRoomPushEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
