// automatically generated by the FlatBuffers compiler, do not modify

package Common

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SettlementInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsSettlementInfo(buf []byte, offset flatbuffers.UOffsetT) *SettlementInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SettlementInfo{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SettlementInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SettlementInfo) UserId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SettlementInfo) MutateUserId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *SettlementInfo) WinWay() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SettlementInfo) MutateWinWay(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *SettlementInfo) WinStatus() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SettlementInfo) MutateWinStatus(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *SettlementInfo) BaoTing() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SettlementInfo) MutateBaoTing(n byte) bool {
	return rcv._tab.MutateByteSlot(10, n)
}

func (rcv *SettlementInfo) TotalScore() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SettlementInfo) MutateTotalScore(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *SettlementInfo) GameScore() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SettlementInfo) MutateGameScore(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func (rcv *SettlementInfo) ScoreItems(obj *ScoreItem, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(ScoreItem)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SettlementInfo) ScoreItemsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SettlementInfo) TingStatus() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SettlementInfo) MutateTingStatus(n byte) bool {
	return rcv._tab.MutateByteSlot(18, n)
}

func (rcv *SettlementInfo) HuStatus() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SettlementInfo) MutateHuStatus(n byte) bool {
	return rcv._tab.MutateByteSlot(20, n)
}

func (rcv *SettlementInfo) PaoStatus() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SettlementInfo) MutatePaoStatus(n byte) bool {
	return rcv._tab.MutateByteSlot(22, n)
}

func SettlementInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func SettlementInfoAddUserId(builder *flatbuffers.Builder, userId uint32) {
	builder.PrependUint32Slot(0, userId, 0)
}
func SettlementInfoAddWinWay(builder *flatbuffers.Builder, winWay byte) {
	builder.PrependByteSlot(1, winWay, 0)
}
func SettlementInfoAddWinStatus(builder *flatbuffers.Builder, winStatus byte) {
	builder.PrependByteSlot(2, winStatus, 0)
}
func SettlementInfoAddBaoTing(builder *flatbuffers.Builder, baoTing byte) {
	builder.PrependByteSlot(3, baoTing, 0)
}
func SettlementInfoAddTotalScore(builder *flatbuffers.Builder, totalScore int32) {
	builder.PrependInt32Slot(4, totalScore, 0)
}
func SettlementInfoAddGameScore(builder *flatbuffers.Builder, gameScore int32) {
	builder.PrependInt32Slot(5, gameScore, 0)
}
func SettlementInfoAddScoreItems(builder *flatbuffers.Builder, scoreItems flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(scoreItems), 0)
}
func SettlementInfoStartScoreItemsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SettlementInfoAddTingStatus(builder *flatbuffers.Builder, tingStatus byte) {
	builder.PrependByteSlot(7, tingStatus, 0)
}
func SettlementInfoAddHuStatus(builder *flatbuffers.Builder, huStatus byte) {
	builder.PrependByteSlot(8, huStatus, 0)
}
func SettlementInfoAddPaoStatus(builder *flatbuffers.Builder, paoStatus byte) {
	builder.PrependByteSlot(9, paoStatus, 0)
}
func SettlementInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
