[node]
[node.appwriter]
host="xxooxxoo"
port=3306
user="xxooxxoo"
passwd="xxooxxoo"
db="xxooxxoo"
charset="utf8"
[node.appreader]
host="xxooxxoo"
port=3306
user="xxooxxoo"
passwd="xxooxxoo"
db="xxooxxoo"
charset="utf8"
[node.logger]
host="xxooxxoo"
port=3306
user="xxooxxoo"
passwd="xxooxxoo"
db="xxooxxoo"
charset="utf8"
