# 所属环境
env="qa"
# 心跳间隔(秒)
heartbeat_interval=3
# 屏蔽词过滤
sensitive_url="http://10.26.239.72:53782/replace"
# 报警设置
# 发件服务器地址
alarm_host="http://10.26.239.72:13579/alarm/mail"
# 报警标题
alarm_subject="[测试服]俱乐部服务重启警报"
