// automatically generated by the FlatBuffers compiler, do not modify

package Common

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LeagueCancelResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsLeagueCancelResponse(buf []byte, offset flatbuffers.UOffsetT) *LeagueCancelResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LeagueCancelResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LeagueCancelResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LeagueCancelResponse) S2cResult(obj *GameResult) *GameResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(GameResult)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func LeagueCancelResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LeagueCancelResponseAddS2cResult(builder *flatbuffers.Builder, s2cResult flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(s2cResult), 0)
}
func LeagueCancelResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
